### ISSUE TITLE
Code formatting.... - question not issue.

### ISSUE THREAD

**Issue by iisfaq** [RickStrahl/MarkdownMonster#1004]
I only started to use your tool a day or so ago.

I found quite quickly that I would like to press CTRL + click on the format code toolbar icon to format a block without the dialog coming up.

Maybe if you have not selected a formatter yet (at all or for the session) the dialog will show.

If CTRL (or some other key) is held down and you click on the format code icon (or the ALT+C shortcut) it would not display the dialog and just choose the last chosen formatter and format the code right away.

Your thoguhts?

**Comment by RickStrahl** [comment]
No - I don't think that's a good.idea because of the non-discovery of the mechanism. Using the last format is too unpredictable IMHO.

You can use accept dialog very quickly with just:

* Enter  

nearly instantly if a syntax selection has been made. Alternately you can type a letter or two for the syntax and then press Enter to select something else. It's very keyboard friendly and fast - basically 1 extra key (Enter).

I tend to use Alt-C from clipboard or selection then immediately press Enter or type letter(s) for syntax then ENTER.

**Comment by iisfaq** [comment]
That is fine, it is your app and as you say Enter is very quick.

chris
