### ISSUE TITLE
Viewing preview in web browser now has broken TOCs

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#1012]
Not sure what has changed nor when, but the TOC when viewed within a Web Browser is now broken. The preview page appears at:

file:///C:/Users/SMT/AppData/Local/Temp/_MarkdownMonster_Preview.html

And links within the preview page appear as:

file:///D:/Project/#filter-system

Please fix, this has completely broken viewing all but the simplest pages in a web browser.

**Comment by RickStrahl** [comment]
You're going to have to be more specific about what you're doing...

**Comment by SMTStuck** [comment]
Thought that was clear enough but no worries...

1) Create a standard markdown file with headers (#, ## etc.).
2) Generate a TOC (aka Document Outline).
3) View -> View In Web Browser.
4) The TOC links no longer point to the current preview document, but now point to the directory of the actual markdown file.

Thanks.

**Comment by RickStrahl** [comment]
Hmmm... I see. I don't think there's anything that can be done about that in the View in Web Browser view as that simply opens the rendered file in an external browser without any special fixup. The failure is due to the `base` path in the page and the browser prefixing the base path to the local hash navigation. We can't remove the base path as that's required in order for other resources like images to display properly with relative paths when the actual file is not in the temp location.

View in Web Browser is just a raw preview of what was rendered - it's not and never was meant to be something that you use for anything that a quick preview.

The internal preview browser works fine (because we're internally handling link navigation).

If you want a usable file that works correctly with adjusted resources etc. you should be using the HTML export, not View in External Web Browser.

**Comment by RickStrahl** [comment]
That said - I just took a look to see why the internal browser is working but not the View in Web Browser view. The internal browser intercepts navigation and manually navigates to the specified location. Turns out for the non-internal version this can work too but I short circuited the exit if the host isn't detected.

I've changed that logic so the hash navigation now can happen even if the host is not present which makes the external navigation work. 

It'll be in 2.8.8.2 or later.

**Comment by SMTStuck** [comment]
> I've changed that logic so the hash navigation now can happen even if the host is not present which makes the external navigation work.

Thank you, it's a feature heavily relied upon for the larger MD doccs, so I knew it was definitely working not too long ago.
