### ISSUE TITLE
[Feature Request] - Keep the italics and bold in the table of content

### ISSUE THREAD

**Issue by oscaretu** [RickStrahl/MarkdownMonster#1016]
The generated index entries do not retain the italics and boldface that appear in the original headers. I'd like that the rendering in the TOC would be the same than in the headers.

**Comment by RickStrahl** [comment]
My first thought was to not support this, but it turns out it's actually not that difficult to do. 

I ended up retrieving the InnerHtml of the header and then applying ReverseMarkdown against it:

```csharp
var text = header.Text;
if (!string.IsNullOrEmpty(header.InnerHtml))
    text = reverseMarkdown.Convert(header.InnerHtml);
```

![image](https://user-images.githubusercontent.com/1374013/225780659-87f83335-797c-4089-ae75-c700f28eff82.png)

**Comment by RickStrahl** [comment]
Well that's just going to have to be that way. It gets too complicated to dig into multi-nested tags in this scenario.

Honestly it's an edge case to put complex markup into headers.
