### ISSUE TITLE
Bug: Navigation keys do not work in presentation mode

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1020]
The navigation keys `PgDn`, `PgUp`, `Down`, `Up`, `Home` and `End` do not work in the presentation mode (`F11`) of MM v2.8.9.15.
This is also true for combinations such as `Ctrl+Pgdn`.
See also #1019.

**Comment by RickStrahl** [comment]
Not sure if that was fixed by the changes in #1019, but it works for me. One caveat: You have to focus into the browser either via scrollbar activation or clicking into the text in order for the navigation of the document to start firing.

`Ctrl-Pgdn` is not a browser navigation command. It doesn't nothing in edge either.

**Comment by RickStrahl** [comment]
Fixed the initial focus when changing into presentation mode to force focus into the previewer.
