### ISSUE TITLE
[Feature Request] Allow multiple instances of MM

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#1021]
Prior versions of MM allowed the launching of multiple instances, either using the start menu or **Run > mm**

This seems to have been removed at some point.

My use case is I work on 3 different Jekyll blogs and often I can be working on them simultaneously, so I would launch multiple instances of MM for each blog.

Was there any particular reason for this deprecation?

MM v 2.8.9
Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)

**Comment by RickStrahl** [comment]
Therer are a couple of ways to do this:

* Turn of `Use Single Window` (Settings)
* Open in new Window

The former will open shell accessed documents in a new window rather than in a single shared window.

Open in new Window lets you open an existing tab in a new window which you can then keep separate.

**Comment by conradakunga** [comment]
Works perfectly. Thanks!
