### ISSUE TITLE
Search using Regexp Unable To find literal Dash 

### ISSUE THREAD

**Issue by CheetahChrome** [RickStrahl/MarkdownMonster#1026]
If I search for an escaped `\-` dash, it is not found. Ultimately, I would like to use `\-{2,}` so I could replace all extraneous dashes with a single dash. Note that `\s{2,}` works as expected, but that is a keyword and not a literal.

![image](https://user-images.githubusercontent.com/1110966/231262600-c59de746-a89a-4cb3-96f1-117203ce6176.png)

**Comment by RickStrahl** [comment]
I'm not sure what you're trying to do here, so I can't really help. You need to provide an example of what you're searching and trying to accomplish.

In my quick tests using `\-` to search for dashes and repacing with something else works. I think the problem is the space you're using above. If you want literal spaces you'll need the regEx operator for space (`\s` if I recall - my regEx is rusty).

However, before we even get into this the editor's search functionality is built into the ACE Editor that drives the main editor surface, so most likely this is something that has to be pushed up to the [ACE repository](https://github.com/ajaxorg/ace/issues).

**Comment by CheetahChrome** [comment]
Upon retesting this issue, I found I can search for

| Search | Result |
| - | - |
| \- | works |
|\-{2,} | fails |
| \-+ | works |

So what I am trying to do is take say this `| ---- | ---------- |` and change it to this `| - | - |` because the markdown table doesn't need multiple dashes, only one.

It looks like the editor's regex parser is wonky and usage may vary.

Thanks for time. Closing the issue.
