### ISSUE TITLE
Crash with "writing at protected memory"

### ISSUE THREAD

**Issue by warbe-maker** [RickStrahl/MarkdownMonster#1028]
I've lost all my changes now three times consequtively. Before the third crash I saved my changed very frequently but even the saved changes got lost. It may be caused by the fact that I copied a file, removed 90% of the content and started to write something different. I would very much apreaciate a hint how a crashing MarkdownMonster can be made less likely.

**Comment by RickStrahl** [comment]
Yes we know about this issue which was introduced about a month ago by a bug in the WebView2 (Microsoft) control.

Please install the latest version (2.8.16 or later) which has a fix for this issue. It's a workaround for now until Microsoft fixes the underlying control issue, but it avoids the failure path.

**Comment by RickStrahl** [comment]
As a related note, make sure you have `Auto Save Backups` enabled. That option should automatically save your files every few seconds after you make changes.

![image](https://user-images.githubusercontent.com/1374013/233811222-f98363fd-7653-41ab-b559-447bf2b7d890.png)

FWIW, auto-save had recently introduced regression bug, that made it not work, but has been fixed in 2.8.17. If enabled MM should prompt you if a backup file exists and offer to use that instead of the main source file to allow recovering content.
