### ISSUE TITLE
Editor font too small since release 2.9.6

### ISSUE THREAD

**Issue by hermanslagman** [RickStrahl/MarkdownMonster#1039]
Since release 2.9.6 editor font has become ridiculously small.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/6782343/5a65f797-330e-48ff-9d9c-07e84bb9008f)

**Comment by RickStrahl** [comment]
Can you install 2.9.7? 

We had to step back from multi-monitor DPI support in 2.9.6 due to a bug that was introduced by the per monitor DPI settings. We've since fixed that issue and reverted back to the pre-2.9.6 settings.

But also:

* You can change the font size in the configuration
* You can set the zoom level and it will be remembered (scroll wheel or manual on the status bar)

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/753486c6-5f97-4ba9-bf5f-0611298a7241)

**Comment by hermanslagman** [comment]
2.9.8.1 didn't do the trick.
But I needed to set the Zoom level to 100%. (was 56%), 
Did the 2.9.6 install change the zoom level? I don't think I ever had to do that.

**Comment by RickStrahl** [comment]
I think the bug in 2.9.6 might have caused the Zoom level to change. 

But it's also easy to accidentally change the zoom level with `Ctrl-Mousewheel` which incidentally is also the easiest way to quickly change the value.
