### ISSUE TITLE
Disable image preview option

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#1065]
While writing articles, we often drag images from the file manager into the MD editor to generate image links. However, the image preview will open when we click on an image. We can only drag the image link after the image preview is opened, and the same goes for changing to another image. 

We hope there could be an option that allows us to turn on or off the image preview function ourselves.

**Comment by RickStrahl** [comment]
Well, not correct actually. You most certainly can drag without first previewing the image and moving focus to the preview document.

![DragandDrop](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/5c33e9f9-1ac3-4ffd-bebd-2b28febf20bd)

The key is not to release the mouse button (ie. don't navigate to the image first, but immediately drag).

* Grab the image with mouse down and don't release the mouse button until you drop the file

Preview Navigation doesn't occur until the UpClick occurs and then only if a drag operation hasn't been initiated. So if you grab the file and drag there's no preview.

To be fair I've done this myself - I accidentally click into the image instead of dragging, but with a little discipline it's pretty easy to grab and drop and not preview and it's the expected behavior if you have multi-use operations assigned to an item in a list.

**Comment by kkbruce** [comment]
You're right. The issue lies in the clicking action. Thank you for your patience in answering.
