### ISSUE TITLE
Image preview not working when # in path 

### ISSUE THREAD

**Issue by mi-molette** [RickStrahl/MarkdownMonster#1068]
I use Markdown 3.0.1.1
When the md and image files are store in a folder with "#" in the path preview does not work.
The image is correctly printed or embeded. But does not display in preview as show under

![Image](https://i.imgur.com/xMVQmLL.png) 

![Image](https://i.imgur.com/tlLiWqy.png)

**Comment by RickStrahl** [comment]
Thanks for the report - I've fixed this issue which is due to the hash being invalid in a URL unless it's encoded. The base url is the problem but the same thing also applies for the other links in the page to script files and other resources.

Here's what this looks like now:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/d2fd927d-0273-48df-826a-563777c88ee0)

In this case the Markdown file lives in a folder like this:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/89bac25c-1339-4df9-b2d7-29d98560cb28)


where the folder includes a hash and a couple of other characters that can cause problems in a url. 

Ironically full URL encoding for these paths doesn't work (ie. `HttpUtility.UrlEncde()`) as the encoded slashes do not work in the base and link urls, so I had create a custom encoder that only encodes the extended characters that break the file references.

It'll be in 3.1.6 in a few days.
