### ISSUE TITLE
Drop the image to insert the link error

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#1070]
![2023-11-19_15-39-13](https://github.com/RickStrahl/MarkdownMonster/assets/2024682/95773f85-4a4c-4161-a957-10dcae02a98f)

Log:

```
2023/11/19 下午 03:42:06 - App: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v3.1.3.0
10.0.22621.1.amd64fre.ni_release.220506-1250 - zh-TW - NET .NET 8.0.0 - 64 bit
Microsoft Corporation Surface Pro 9, Intel(R) Iris(R) Xe Graphics, hw-acc: True
zh-TW - zh-TW
C:\Users\kingk\AppData\Local\Markdown Monster
Portable: False
---
System.Private.CoreLib
   at System.Object.GetType()
   at Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.<>c__DisplayClass10_0.<SetAsyncMethodContinuation>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------



2023/11/19 下午 03:42:30 - App: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Markdown Monster v3.1.3.0
10.0.22621.1.amd64fre.ni_release.220506-1250 - zh-TW - NET .NET 8.0.0 - 64 bit
Microsoft Corporation Surface Pro 9, Intel(R) Iris(R) Xe Graphics, hw-acc: True
zh-TW - zh-TW
C:\Users\kingk\AppData\Local\Markdown Monster
Portable: False
---
System.Private.CoreLib
   at System.Object.GetType()
   at Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.<>c__DisplayClass10_0.<SetAsyncMethodContinuation>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException
---------------------------
```

**Comment by kkbruce** [comment]
I found that the behavior is that when I use Snagit to capture and save images to the file directory, it will fail if I immediately pull the image into the editor. If I click on "Refresh folder" in File Explorer after saving the image and then retrieve the image into the editor, there will be no errors.

**Comment by RickStrahl** [comment]
The error unfortunately is generated internally in the WebView, meaning it looks it happens during the drop operation. Based on the call stack it looks it never makes it into the MM code base which intercepts the drop operation higher up in the stack.

Not sure what could be causing that - drag operations out of the folder browser are text based so it captures a file path, which MM then uses to try and resolve the path. 

I doubt that the issue has anything to do with SnagIt or a file that was just created since we're not seeing a file related failure - this is caused by the drop (or perhaps by the link insertion after the drop).

What are you doing exactly to capture the image? Are you using SnagIt natively to capture and save, or are you using the screen capture addin?

If you use SnagIt, there might be a better workflow. Here's what I typically use:

* Take your capture
* Copy to clipboard (or enable auto-clipboard)
* Move your cursor into the document
* Paste
* Save the file where you want it to go

If you use the Addin this also works - it will basically automate the copy to clipboard and paste operation but personally I end up just using SnagIt directly most of the time because I'm so used to using it for other things as well - always copying rather than saving.

That said - this shouldn't be failing. But I don't think this is related to snagit.

**Comment by RickStrahl** [comment]
So I took a few minutes to try and duplicate this in a few ways.

![ScreenCaptureBug](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/f62eed03-6e9a-41c6-8613-4ac3685cc2e8)

I tried using the addin and SnagIt alone - both saving and pasting (or Finish in the Addin) and in none of the cases can I make the app crash, but I'm not exactly quick about getting the image dragged in from the folder browser either.

If you are using snagit I definitely think the faster way to do all of this is to either use the addin and its Finish operation (which copies to clipboard and **then** saves, or to copy to clipboard and then paste which will save at that point.

However, I did try to use SnagIt on its own to save and then quickly drag the file from the FB to the editor and that too appeared to work.

So if you have exact steps of what you're doing that might be helpful.

**Comment by kkbruce** [comment]
I use Snagit to capture and save files directly, then drag and drop them from MM’s file manager. 

I have two laptops with the same operation; one usually works, but the other does not work correctly (as described above), and I can’t find the reason. But the several methods you provided can effectively solve this error. I think I will change my operating habits, whether direct copy and paste or add-in. 

I appreciate your patience in testing and answering.
