### ISSUE TITLE
Feature Request: Support for `[[_TOC_]]`

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#1084]
GitLab, Azure DevOps and Typora support `[[_TOC_]]` to generate a table of contents dynamically. It would be nice if MarkdownMonster joined this league.

**Comment by RickStrahl** [comment]
Can you find a me a reference to this in the GitHub docs somewhere? I can't seem to dig anything up on this.

**Comment by jbridgy** [comment]
Here is the reference to the [TOC feature of GitLab Flavored Markdown (GLFM)](https://docs.gitlab.com/ee/user/markdown.html#table-of-contents). GitHub does not support `[[_TOC_]]`.

**Comment by RickStrahl** [comment]
Ok, I've added this feature:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/b11f526b-6340-408f-ac3a-b16fe93f4afe)

TOC gets rendered into the document on every re-render so it's dynamic and updates with the document changes.

The document outline now also has a new button that inserts this tag into the page in addition to the existing behavior of embedding a static TOC.

**Comment by jbridgy** [comment]
Looks good!
Is TOC also rendered in the following cases?

1. Document is exported to a HTML file using the ![image](https://github.com/RickStrahl/MarkdownMonster/assets/98041047/b8c7d805-3e2f-4979-bd1d-a2a7ac573d20) button.
2. Document is exported to a PDF file using the ![image](https://github.com/RickStrahl/MarkdownMonster/assets/98041047/63d19546-9e54-4583-8d94-3f35bcebf19c) button.
    In this case MM already offers the option "Generate Table of Contents" (which actually means "Generate Bookmarks").
    So rendering the TOC (hyperlinked) in addition to or instead of the bookmarks may be another option.
4. Document is printed (I guess after conversion to HTML).

**Comment by RickStrahl** [comment]
It'll work with anything that generates full HTML output which includes PDF and print output which just 'prints' the html content.

**Comment by jbridgy** [comment]
Thank you for the prompt implementation! It works as I expected except for headings containing inline code with a single `\`.
EXAMPLE:
```markdown
### Directories in `SomeProjectRoot\`
```

MM v3.2.8 generates the following invalid TOC entry for the heading above:
```markdown
[Directories in SomeProjectRoot\](#directories-in-someprojectroot)
```
**`\]` makes the link invalid.**

Expected TOC entry:
```markdown
[Directories in SomeProjectRoot\\](#directories-in-someprojectroot)
```

The rendering is correct in MM's Document Outline, GitLab, Azure DevOps and Typora.

BTW: It would be nice if MM's Document Outline allowed headings to be **collapsed** and expanded.

**Comment by jbridgy** [comment]
I encountered two other issues with the `[[_TOC_]]` tag using MM v3.2.8.2:

1. The tag is not expanded correctly if the heading structure is not normalized, that is, if there is a heading that is more than one level lower than its context (parent).
2. Furthermore headings on levels 5 and 6 are ignored.

EXAMPLE:
The following heading structure is normalized:
```markdown
# H1
## H2
### H3
#### H4
##### H5 (ignored by `[[_TOC_]]`)
###### H6 (ignored by `[[_TOC_]]`)
## H2
## H2
# H1
```

The following heading structure is **not** normalized because it starts with a heading of level 2 (instead of 1)
and because a heading of level 4 occurs in a context of level 2 (instead of 3):
```markdown
Disable heading # H1
## H2
Disable heading ### H3
#### H4
##### H5 (ignored by `[[_TOC_]]`)
###### H6 (ignored by `[[_TOC_]]`)
## H2
## H2
# H1
```

**Comment by jbridgy** [comment]
I encountered another issue with the TOC tag using MM v3.2.9.3.

The tag is not expanded correctly if the heading contains pairs of `\++`, `+\+` or `\+\+`.
MM renders text between pairs of `++` with underline, like text between `<u>` and `</u>`.
To prevent the headings from being rendered wrongly at least one `+` of each `++` needs to be escaped.
However, the TOC uses the unescaped headings.

EXAMPLE:

```
# Features of C\++17, C+\+20 and C\+\+23
```

MM generates the following **invalid** TOC entry for the heading above:

```
[Features of C++17, C++20 and C++23](#features-of-c17-c20-and-c23)
```
The rendered TOC entry reads "Features of C17, C20 and C++23", where "17, C" is underlined.

Expected TOC entry:

```
[Features of C\++17, C\++20 and C\++23](#features-of-c17-c20-and-c23)
```

**Comment by RickStrahl** [comment]
Thanks...

Fixed.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/393b6b75-7ccc-4084-91f7-7a54178bab39)

The fix was a bit tricky - reason it didn't work is because I was using HTML document to parse (reusing what's used for the Doc outline). That doesn't work though because we need to make sure we can retrieve the raw Markdown including the `\` escape character. 

So code now uses the Markdown parser to parse the Markdown document to get headers and then explicitly checks each subblock for escape characters which are injected into the generated output.

This fixes the `[[_TOC_]]` as well as the manually injected Toc from the bookmarks sidebar.

**Comment by RickStrahl** [comment]
One thing that I noticed and forgot about:

The manual TOC generates a TOC that shows only headings that occur after the injected TOC, while the new `[[_TOC_]]` command injects everything....

**Comment by jbridgy** [comment]
Does the new implementation also fix the following issue with inline code ?

![image](https://github.com/RickStrahl/MarkdownMonster/assets/98041047/4ae59558-7f2d-4d45-be78-a41c3cd952af)

The static TOC is correct while the dynamic TOC loses the inline code formatting and even generates rubbish when the inline code ends with `\\`. 
See also [old comment one same issue](https://github.com/RickStrahl/MarkdownMonster/issues/1084#issuecomment-2009564053) and [updated comment on related issues](https://github.com/RickStrahl/MarkdownMonster/issues/1084#issuecomment-2013747271).

**Comment by RickStrahl** [comment]
Yeah looks like it:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/eb1d8374-b414-48f5-b3f3-d7812e718688)

I think the inlines were fixed for the document outline (which now uses the same mechanism). 

The new code uses the Markdown document to find headers and then based on the type of text fixes it up.

There may still be edge cases I would think where this doesn't work. Markdown is not a perfect 2-way markup language - things can easily get lost in the back and forth. But I think most of the more common scenarios are addressed.

**Comment by RickStrahl** [comment]
Ok I was too quick on that - no that doesn't work if the code inside of the inline is 'escaped' text.

The only way this works if the inline code is kept intact. Slashes would be easy to fix, but there are million things that could be inside of the an inline that don't render right as markdown. 

So now:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/74182f54-d997-474a-8850-7d70d27e5c5a)

I don't really like the way that looks but there's really no reliable way to make that work without the inlines. Slashes are only one thing - it could be many, many other escaped characters, but the parser doesn't know about that because the text is an inline code block that's treated as well an linline code block.

For the Document outline this is simpler because there's no escaping happening there, so using the plain text in the actual outline works (and that's what it's been doing).
