### ISSUE TITLE
Double click opens file twice

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1092]
Double clicking a file opens it twice (seems to only happen when it's the very first file opened); ask (prompt) before opening the same file twice. Also: sometimes the second copy is empty after closing one of them... I have never lost anything, but it's a little worrying nonetheless

RickStrahl: Double-click - by design: First click opens in display-only mode, second click enters edit mode. Read mode is non-sticky, full edit mode is sticky. There's also Markdown Preview Mode in config which determines how preview is displayed (editor or full page previewer)

Me: Double clicking: what does sticky mean in this context? Also: if second click enters edit mode, then it should be edit mode in the same tab

**Comment by RickStrahl** [comment]
Single click: Preview mode. When you navigate somewhere else the file closes and the new file is displayed.

Double click: Full editor mode. File is opened and stays open in the editor. Navigating off leaves the file open and a new tab is opened for the next file navigated.

This is by design. You can change the preview behavior to have Markdown files show the Html preview optionally but that only applies to markdown files.

**Comment by RickStrahl** [comment]
Might have to rethink this in light of #1088 and change to show all 'known editor formats' as preview. Previous behavior was to only show certain files not every supported editor files in preview during navigation.

**Comment by RickStrahl** [comment]
Updated default editors for certain executable file types like cmd, sh, bat - previously these would do nothing for preview and open in Explorer for double click. 

All of the text based formats have been removed from the 'special' executable list, and now are treated as text documents that preview and edit in the editor for single click and double click respectively.
