### ISSUE TITLE
Opening nested folder levels often only works with arrows

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1093]
When browsing down a file tree and opening nested folders, one level works with a double click on the folder name, but subsequent levels only work with a click on the arrow. 
What's strange is that when "click-spamming" the folder (clicking 10 times or so), sometimes it will fold open (and closed again on the next click)

**Comment by RickStrahl** [comment]
Fixed.

Another weird timing issue related to double click operations firing more than once resulting in race conditions.

Fixed with a debouncing mechanism that prevents multiple double clicks.

This fixes a couple of issues:

* Cleaner Double Click to edit-open
* Folder expansion that works reliably and more quickly (before on large folders it could take a long time due to dual processing)
* .. navigation now works properly
