### ISSUE TITLE
Ctrl-B bolding behavior inconsistent

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1096]
- write some text
- select part of it
- hit Ctrl-B to Bold it and it will get **text moretext** around it
- continue to hit B and the cursor jumps backwards two characters at a time
- Expectation: whould unbold if in the middle of a bolded block

...same probably for italics?

**Comment by RickStrahl** [comment]
There's no unbolding support.

It's an editor, not a word processor :smile:

**Comment by RickStrahl** [comment]
I did change the cursor movement behavior. I believe that was a regression from older behavior where Ctrl-B would create an empty bold block and place the cursor inside (like GitHub does).

That was removed it looks like, but heck I can't remember the details. For now I've removed the cursor movement because without the empty embedding behavior that is wrong.
