### ISSUE TITLE
Problems with HTML preview

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1120]
clicking on an HTML file (saved from https://jlzych.com/2018/06/27/notes-from-good-strategy-bad-strategy/ )
- first shows a preview of the previous file
- then goes blank and shows nothing for a while
- then shows the preview
- the preview of dark text on a dark background (using a dark theme) is not optimal : )

For the background, I'm not sure a color is specified in the HTML. If you want me to attach the file, let me know.

![image](https://github.com/RickStrahl/MarkdownMonster/assets/14021625/41cd8b5b-aa22-45f4-b5f7-f29cf4cb9930)

**Comment by RickStrahl** [comment]
Hmmm... when I save from the Web browse it looks like this:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/7d4faefa-2a31-4db2-876d-389a44d83d89)

But that's because that actually saves the HTML plus all the support files.

If I rename the resource folder then I see what you do.

MM doesn't render a background for the browser, primarily to avoid flashes when the browser is made visible and before content is loaded (long story). So the background chrome basically bleeds through if the host page doesn't set a background color.

I don't really want to change the default for this, but I've added an override property that allows you to change the preview default background color in:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/3e1bdf3e-5920-4722-8452-73273a6e763f)

You can set this towhatever  HTML color you like, but you may see more flashing of the white background, especially when using dark preview themes.

With that here's what this looks like:

![image](https://github.com/RickStrahl/MarkdownMonster/assets/1374013/0bd0e50e-4d96-475f-b793-6bc47f0a4039)

**Comment by RickStrahl** [comment]
3.2.19.1
