### ISSUE TITLE
AI Feature: AI Request Failed invalid uri

### ISSUE THREAD

**Issue by EdCharbeneau** [RickStrahl/MarkdownMonster#1126]
When using Azure Open AI, I'm getting an error message when trying to use the summarize feature. It seems like the app isn't agreeing with the URI for some reason, however I have copied it directly from the Azure Portal. I've tried multiple deployments and keep getting the URI error. Is there something missing from the endpoint format? My settings are below:

Endpoint 
`https://aisamplesinstance.openai.azure.com/openai/deployments/demo4o/chat/completions?api-version=2023-03-15-preview`

Settings
![image](https://github.com/user-attachments/assets/9f0cf739-9f5b-4a48-b26a-e6d45c277aa8)

Summarize doc error
![image](https://github.com/user-attachments/assets/d205d18d-ce20-48a2-a40a-048a6d28f4f7)

**Comment by RickStrahl** [comment]
Azure OpenAI configuration is a pain because it doesn't use the standard OpenAI endpoint/apikey, but rather relies on endpoint deployment and apikey. 

It works like this for you:

```
Endpoint: https://aisampleinstance.openai.azure.com/
ModelD: demo4o
```

I believe this is the same that Semantic Kernel uses. 

[Documented here](https://markdownmonster.west-wind.com/docs/_6y41clpfe.htm#azure-openai-provider-configuration)

**Comment by EdCharbeneau** [comment]
It's working now thank you.

I had to apply the changes and restart. 👍
