### ISSUE TITLE
Renaming file in tree view does not rename file loaded in the tab

### ISSUE THREAD

**Issue by internationils** [RickStrahl/MarkdownMonster#1141]
I renamed a file on the left side in the tree view, and the name in the tab did not change. When saving the tab a duplicate was created with the old name.
![image](https://github.com/user-attachments/assets/dfc7e32f-1a9b-45d5-af9b-0a2542230829)

**Comment by RickStrahl** [comment]
Took a look and found this to be highly inconsistent. This is a weird timing where shutdown of the old tab is not quite complete when the new tab is created and cause an odd cyclical redundancy. 

I think this is fixed with some optimizations and some extra wait time before opening the new tab to ensure the tab headers have a time to normalize. 

Also updated the actual 'rename' code which previously had a path through that would not delete the original file. We moved to `File.Move()` now that .NET 8+ has an `overwrite` parameter which makes this a single atomic OS operation.

Updated in the preview release 3.5.0.11

**Comment by RickStrahl** [comment]
Fixed:

![EmptyTagMarkup](https://github.com/user-attachments/assets/7db3b2d9-6946-4320-b3dd-dd80950da92e)

Yup a regresssion to a helper function (`WrapText()`)  that by default ignores empty text. Added explicit override to the method to allow empty values to expand. The logic to move the cursor into the empty tag was still there :smile: 

Updated in preview release 3.5.0.12 and later

**Comment by RJS32** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
