### ISSUE TITLE
Find and Replace not working as expected using regex pattern

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1148]
Specifically, I've noticed that when running a search that includes a newline character (`\n`), the Find box displays the number of found results (> 0), but the controls turn red and are disabled (see before and after pictures below):

### Before newline character is included in search:

![image](https://github.com/user-attachments/assets/f876fde7-03c4-4fc7-8e77-ff4ab47d10c0)

### After inputting newline character:

![image](https://github.com/user-attachments/assets/4e02fa40-58da-4018-96b9-f61ad2e440da)

**Comment by RickStrahl** [comment]
Hmmm... looks like a bug in ACE editor. Will take a look and see if I can fix this on my end.

**Comment by RickStrahl** [comment]
Hmmm... interesting: Happening in the stock ACE implementation as well:

https://ace.c9.io/build/kitchen-sink.html

**Comment by RickStrahl** [comment]
Did a little more research on this and it looks like ACE does not support multi-line RegEx parsing. So anything that deals with \n is not going to work without major workarounds.

Since MM uses ACE there's not really a workaround. 

Best I can offer here is to jump into VS Code and try to do the S&R there (right click Open -> Open In VS Code (if installed)) or you can configure another text editor if you're using something else.

**Comment by pa-0** [comment]
Maybe a context menu option for grepWin[^1] (open source and much muuuch lighter than Vs Code -- native win32 app)?

[^1]: https://github.com/stefankueng/grepWin/

**Comment by RickStrahl** [comment]
You can add any external program you want to Markdown Monster and it'll show up on the Open.. menu.

[Configure and Run External Programs via Open With...](https://markdownmonster.west-wind.com/docs/_6if1ephjm.htm)

**Comment by pa-0** [comment]
Sweet! I will have to play with that - I missed it when skimming the documentation.  Thanks.
