### ISSUE TITLE
BUG: New OpenAI Features

### ISSUE THREAD

**Issue by SyntaxDreamer** [RickStrahl/MarkdownMonster#1161]
Is this just me, or it's not possible to add any OpenAI provider? Every time I paste the API key, the application just crashes without an error.

Select a new provider, example Generic OpenAI, start to complete data, paste the key, it hangs and then closes after a few seconds. Nothing in the error logs either.

As a side comment, can the icon for AI features in the toolbar be replaced? It does not look or consistent with the rest of the UI. It seems like a pixelated icon that has nothing to do in terms of style with the rest of the icons. Not a big deal but does not look good at all.

**Comment by RickStrahl** [comment]
Hmmm... I see it. That looks like a regression bug. 

Fixed. Checking into a couple of other related issues in that dialog but will have an update up shortly.

**Comment by RickStrahl** [comment]
The fix for this is in `3.5.7.5` and later. Issue was an extra null check and update that was causing a recursive stack overflow. 

I also made a few enhancements:

* different icon since we're now not doing just images
* dropdown next to icon shows the AI options on the menu
* AI editor menu now has Image Generation as an option too


Here's the new drop down menu:
![image](https://github.com/user-attachments/assets/68a9495d-1df4-445b-9e7f-0baadcccc9ac)
