### ISSUE TITLE
Feature Request: Keyboard Shortcut for Fenced Codeblocks (triple backticks above and below selected text)

### ISSUE THREAD

**Issue by pa-0** [RickStrahl/MarkdownMonster#1162]
If it's not too much of a hassle to implement, a keyboard shortcut/menu option to add three backticks above and below selected text would be swell! Better even if, once the backticks are added, the cursor would relocate to the immediate right of the third backtick at the top (so that the language identifier could then be added next.  

I realize there is the dialog for inserting a formatted code block, but sometimes it's more convenient (especially if the code block already exists in the document) to be able to simply hit a keyboard combination to add the backticks.

**Comment by RickStrahl** [comment]
Not going to add this.

You can use Alt-c, Enter or alt-c - type language prefix - Enter to quickly jam through the paste code dialog. No need for taking your hand off the keyboard.

**Comment by RickStrahl** [comment]
Hmmm... I suppose we could allow for empty code in that dialog to put up an empty code block. I'm making that change.

**Comment by RickStrahl** [comment]
Ok so made a few changes that should make this easier:

![CodePastingEmpty](https://github.com/user-attachments/assets/c5cfe364-f55c-4429-b472-3db95a3cda04)

In the code above I use Alt-C to trigger the dialog and ENTER to accept plus the language if I need to change.

The changes are:

* Empty now behaves the same as pre-selected code - selects the language drop down  
(this is for focus reasons. The editor doesn't allow easy navigation out because it supports ENTER and Tab, so focus is now always on the drop down - 99% of the time you won't want to edit code here, just see it most likely).

* Added **None** as a 'language' - no language is added to the ticks

* **None** moves the cursor in between the code ticks to allow editing in Markdown

**Comment by pa-0** [comment]
What about if there is text selected in the editor when the shortcut is pressed?

**Comment by RickStrahl** [comment]
Maybe you should try it?

Same behavior but text is prefilled and cursor is not placed in the code but after.
