### ISSUE TITLE
Embedding Tweet causes MM to lockup every refresh.

### ISSUE THREAD

**Issue by shawnwildermuth** [RickStrahl/MarkdownMonster#117]
Any way to enable embeds that include JavaScript not to be executed in the preview window? For example, I was trying to embed a tweet:

```
<blockquote class="twitter-tweet" data-lang="en" cards="hidden" conversation="true"><p lang="en" dir="ltr">Are all <a href="https://twitter.com/hashtag/aspnetcore?src=hash">#aspnetcore</a> apps in Azure webapps taking 15 minutes to deploy (using GitHub build integration)?</p>&mdash; Shawn Wildermuth (@ShawnWildermuth) <a href="https://twitter.com/ShawnWildermuth/status/819281676115345409">January 11, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

I'm happy if the preview window just disallows all JS execution, but maybe there is a way to wrap it so that it only gets emitted when I publish?

**Comment by RickStrahl** [comment]
Hi Shawn,

There's a setting that controls rendering of script tags: 

![image](https://cloud.githubusercontent.com/assets/1374013/21958333/24593bac-da50-11e6-9851-04c3b7cb985f.png)

It's off by default for cross site scripting reasons, but you can manually enable it.

There was also a change in 1.1.14 that automatically refreshes the preview completely rather than just embedding the updated content into the previewer when `<script>` tags are included in the content. But the `AllowRenderScriptTags` has to be enabled in order for any of that to work.

**Comment by RickStrahl** [comment]
BTW, what are you doing with Tweets that requires script?

**Comment by RickStrahl** [comment]
So the problem with your particular embedding of the twitter block is that you're using the indeterminate protocol prefix:

**//platform.twitter.com/widgets.js**

If you use:

**https://platform.twitter.com/widgets.js**

it works and the tweet injects properly for the preview. The problem is when we preview we use the **file://** prefix and the **//** doesn't mean the right thing in that context. I suspect it's looking for a domain :-)

So - if you want to embed script - you have to use the explicit protocol. With Twitter this shouldn't be an issue - it should always be `https://`

**Comment by shawnwildermuth** [comment]
Great, that's easy for me to use!
