### ISSUE TITLE
Wyam addin

### ISSUE THREAD

**Issue by M-Zuber** [RickStrahl/MarkdownMonster#119]
[Wyam.io](wyam.io) is a static site generator useful for docs, blogs, e-commerce, you name it.

The proposed add in would let you run + open in browser the preview server of `wyam` while writing.
There are two ways to accomplish this: Make the user install `wyam` and run the exe with `Process.Start`, or use the embedded engine.

The advantage to using the exe is not having to deal with most of the wyam configuration, as that will be supplied by the user in a `wyam.config` file.
On the other hand the embedded engine gives some finer control, and does not require the user to install any additional programs.

Configuration:
- Recipe
- Theme
- Path to executable?
- Port to run preview server on

**Comment by RickStrahl** [comment]
Wyam looks pretty interesting but I guess I'm not sure how an integration with MM would work or be beneficial. 

To move this discussion forward I think we'd need to come up with some concise use cases of what you want to accomplish.

On a side note I was thinking that it might be nice to have a more generic addin for MM that can execute external commands easily. So you could create a batch file or POSH script or even run an EXE from a master Commands addin.

Actually this is already possible in a hacky way via the Snippets addin and the Razor scripting support. A snippet could actually execute code to launch a new process and fire external stuff quite easily. But having a dedicated Exceute Commands adding might be useful for a number of things.

**Comment by JonDouglas** [comment]
I think this is a good idea. It would be nice to have a base class include a method of providing an exe/command path to execute. Perhaps this can go inside `MarkdownMonsterAddin`? Or perhaps it would require a more custom addin class. 

I think the idea of integrating with wyam would be a killer feature for MarkdownMonster. Whether it's wyam, jekyll, or another static site generator, there's lots of potential here to help others start blogging in this fashion and use the editor.

Perhaps the spec of this feature can be added to:

- Path of command/executable
- Link to download (On failure to detect location)

**Comment by RickStrahl** [comment]
I'm all for that but I would still like to see a concrete workflow and how it relates to Markdown Monster and an Addin. If I understand the use case correctly you'll be doing editing and at some point run the generator to re-gen your site or documentation output etc. Wouldn't this be a fairly infrequent operation that is already configured in some external fashion? I guess I'm not quite sure what benefit an addin would provide over launching something from the command line or explorer (short of having some way to trigger that process).

**Comment by M-Zuber** [comment]
Example workflow:

1. Open blog/documentation/whatever collection of documents
2. Click addin icon which launches preview server and opens browser
3. do some work
4. see changes in browser

**Comment by M-Zuber** [comment]
A generic addin that launches a commandline executable with specified arguments would be very useful, but the argument for a more specific addin could be made that it would allow arguments to be set through a comfortable UI.
In addition it can provide a mechanism for installing/downloading the wanted tool

**Comment by wekempf** [comment]
Just want to mention, [PoshWyam](https://github.com/Wyamio/PoshWyam) (still under development) allows Wyam to be bootstrapped and run without an explicit need to install Wyam somewhere. It does this via NuGet following the same tools conventions used by Cake. When PoshWyam nears completion it will be available via the PowerShell Gallery. Alternatively, a plugin here could do the same bootstrapping behavior itself, rather than rely on PoshWyam directly. So long as all tools bootstrap the same way this is the most minimally invasive strategy that doesn't embed the engine.

Another thought, the PoshWyam scripts give you other commands as well, such as the generation of a blog post, which would be nice to add to any editor's extensions. I intend to do something similar for Visual Studio Code via the Tasks mechanism it exposes (a concept worthy of MM, as it lets you define tasks externally in a text file rather than having to add plugins).

**Comment by RickStrahl** [comment]
@wekempf Have you looked at the Commander Addin for Markdown Monster that has been added since this discussion was started? It allows C# scripting (and by extension shelling via Process.Start()) to access just about anything.

Wyam sounds like a great idea, I just don't have a clear vision of what an Addin should actually do in terms of behavior UI etc. I'm happy to help set up an addin but I'm not sure I know exactly where to go from there so I'll need some help from those of you that are requesting this feature.

**Comment by RickStrahl** [comment]
Since nobody wants to take point on defining what should happen with this I'm closing this issue. Please feel free to re-open if there's something more concrete to work with or if you want take a stab at implementing an add-in. I'll be happy to help get started...
