### ISSUE TITLE
When opening files, selecting multiple files only opens first one

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#123]
I only know this because after my recent crash (issue posted), I have to re-open the multiple files I had open before. (MM came up with just the sample open and not my last ones open)

**Comment by RickStrahl** [comment]
yes - MM saves settings on exit, so when you crash changes haven't saved yet and because of the crash of course the settings are never written as the exit code never fires.

Might be a good idea to save more frequently or at least after opening a new file - saves are pretty efficient so no harm done saving more frequently what's in loaded in memory.

**Comment by RickStrahl** [comment]
Added configuration saving after a new file is loaded. 

3149b361ace264f950c3bb0f8973af52ad540598
