### ISSUE TITLE
MM Crashes Shortly After Start, I'm on Ver 1.1.20

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#124]
I have MM crashing while I am editing a new file:
![mm exploded suddenly 2017-01-26_10-28-50](https://cloud.githubusercontent.com/assets/701808/22340811/b7437408-e3bc-11e6-8ba7-f4d8c65cc2d8.png)
Dump text:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	MarkdownMonster.exe
  Application Version:	1.1.20.1
  Application Timestamp:	5887cb28
  Fault Module Name:	mshtml.dll
  Fault Module Version:	11.0.9600.18538
  Fault Module Timestamp:	58275c38
  Exception Code:	c0000005
  Exception Offset:	0013a4ee
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
```

**Comment by RickStrahl** [comment]
Any more info? Does this page crash repeatedly? If so send me the markdown and I can take a look and see if it's happening here as well. 

It's crashing from within the Web browser control's HTML parser  (mshtml) so it's not something I have really any control over unfortunately. The most common issues I see where MSHTML blows up has to do with external script code executing in the browser when the externally loaded content is not responding in a timely manner. This could be script but also external images sometimes. Part of this is because MM updates the Webbrowser control so frequently.

**Comment by ArthurZ** [comment]
It crashed once. I lost the original markdown but I wanted to preserve in the image what it was.
There were no external scripts, nor images.
But I was typing in a rapid succession.

**Comment by RickStrahl** [comment]
Closing this issue since this seems to be a one off - nothing actionable on this.
