### ISSUE TITLE
Please add document autorecovery 

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#125]
In light of the recent repeated crashes please add a document auto-recovery feature.
Thank you Rick!

**Comment by RickStrahl** [comment]
Auto-backup should be enabled by default and when you have a backup file that isn't cleaned up it should open along side your normal document.

More info here:
* [Auto-Save and Auto-Backup of Topics](https://markdownmonster.west-wind.com/docs/_4sv0nob04.htm)

**Comment by ArthurZ** [comment]
Unfortunately it was `setting is false by default.` And it's be too late for me, due to 
"Untitled documents are not saved until you save them to a permanent location on disk."
But thank you!

**Comment by ArthurZ** [comment]
I wish it could be auto-on and irrespective to a file saved

**Comment by RickStrahl** [comment]
The auto-backup is on by default. Auto-Save is off by default (because that can have potential unintended consequences like not being able to abort). 

Both might be off for you because you had versions running before the setting was instituted and that makes it default to false.

And yes for both you need to have a dedicated filename before they kick in. Untiltled files are not saved.
