### ISSUE TITLE
It takes a long time to bring up the Add-on Manager

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#128]
Hi,

I'm on Win 7, it takes really a very long time to bring the Add-on Manager.
I have the mouse cursor icon spinning minutes.

It is a productivity deterrent IMHO. Shouldn't be taking time at all.

**Comment by RickStrahl** [comment]
Well, the addin list is downloaded and each individual addin pulls information from the respective Github repository (for now). I'll be changing that to a static list that pre-populates the list in a service in the future but for right now all of the data is pulled in real-time. 

It's not much data since the addin list is small, but it pulls off GitHub and if there's a problem with Github or a very slow connection I suppose it can take time.

Was this just once or is it repeatably slow? For me the addin list pulls up in about 1 second here. 

How about for others?

**Comment by ArthurZ** [comment]
Yeah, perhaps it depends on the time of day one tries. Right now it loaded really fast, like in < 2 sec.

**Comment by RickStrahl** [comment]
There must have been some issue with either the connection or github at the time. While we may be able to fix addin list via caching, any installs will require a download so the internet connection has to be good.

As mentioned well eventually have a more efficient addin list that gets all the addin data in a single request but as long as we have only a handful of admins this isn't going to make things better.

Closing for now.
