### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by tjrobinson** [RickStrahl/MarkdownMonster#136]
When I open Markdown Monster I get the splash screen, then a black box with no UI. It appears to be partly functional though as if I click in the right place I can close the app, or get a menu to appear. See below (interestingly the screenshot shows it as a white box):

![image](https://cloud.githubusercontent.com/assets/925311/22828269/393fb420-ef94-11e6-9d3c-28c77c9e7063.png)

However, if I then move it onto another screen (the laptop itself), it's fine. And then if I move it back onto a monitor, it's fine.

![image](https://cloud.githubusercontent.com/assets/925311/22828298/6094a76a-ef94-11e6-9cd0-a73b0b05c0b3.png)

My display settings - all screens are scaled to 100%.

![image](https://cloud.githubusercontent.com/assets/925311/22828358/b7389194-ef94-11e6-987a-c472058b55dc.png)

**Comment by RickStrahl** [comment]
Thanks for posting this detail. 

We had a previous issue on that, but unfortunately no resolution as it appears to be a WPF rendering bug that occurs very rarely (I think) and presumably only on certain monitors/video card combos. So far I've heard of 2 people running into this - so it happens, but rarely.

I've tried to dupe with a variety of monitors and TVs (thought it might be low-res displays especially susceptible), but haven't had any way to duplicate. We've also tried to different ways to force the window to refresh itself (and do a raw render). One thing MM does is render off screen then flic in because of the Web browser controls. But even without that in the previous case the rendering didn't work.

Can you try:

* Shut down MM on different screens
* Restart MM

MM should remember the screen location. Is the behavior the same on all monitors?

**Comment by tjrobinson** [comment]
Shutting down and restarting MM on different screens:

* On external monitors it opens black, on the laptop screen it opens fine
* Re-opening after closing doesn't make any difference, it still opens black as above, even if I move it to the laptop screen to get the rendering working then move it back.

Interestingly I get a similar issue with Google Chrome - on the external monitors F11 for full screen causes a black screen, whereas on the laptop screen it works fine.

I suspect this may be graphics card driver related.

Rough specs:
- Lenovo P50
- Windows 10 Pro
- Intel HD Graphics 530
- NVidia Quadro M200M
- Screens connected using separate DisplayPort cables via a dock

Leave it with me - I'll see if I can get full-screen working properly in Chrome and then retry MM if I do.

**Comment by tjrobinson** [comment]
Updating the graphics drivers to the latest (from Lenovo at least) didn't help but following these steps did, for Chrome: http://superuser.com/questions/1098204/chrome-html5-videos-in-fullscreen-are-black-when-intel-graphics-are-enabled-or-h

**Comment by RickStrahl** [comment]
Thanks for checking into this and checking back here.

Cross referencing a couple of other issues here so maybe we can find common ground:

#94 #21

**Comment by RickStrahl** [comment]
Certainly looks like this is a hardware/gpu rendering issue to WPF.

This post has a few suggestions:
https://blogs.msdn.microsoft.com/dsui_team/2013/11/18/wpf-render-thread-failures/ 

I wonder if you could try the Registry hack temporarily to see if that gets rid of the issue.

If so I can probably try setting the rendermode flag in code as an option if things fail.

**Comment by RickStrahl** [comment]
Another thing to try is: See if you can force your MM to run on the Intel Video card. The nVidia driver options should have an app that let you specify whether you want accellerate specific apps. WPF apps automatically end up getting pushed onto the nvidia card most likely. Maybe running on the intel driver will produce better results.

**Comment by tjrobinson** [comment]
The registry hack works.

The system was configured to run everything using Integrated Graphics by default. I tried switching the configuration for MM between the two options but it made no difference, still black (with the registry hack reverted temporarily).

If something could be put in code that would be useful, though it sounds like it's not affecting many.

**Comment by RickStrahl** [comment]
Ok - I added:

```csharp
if (mmApp.Configuration.DisableHardwareAcceleration)
    RenderOptions.ProcessRenderMode = System.Windows.Interop.RenderMode.SoftwareOnly;
```

in 1.1.28 (just updated - I didn't rev the version number).

Undo the registry hack, then start MM and edit the configuration and set that key in the configuration file to true:

```json
  "DisableHardwareAcceleration": true
```

which should do it for just Markdown Monster. You might have to start, stop then restart to see the key show up in the configuration file (as it gets written when MM exists).

**Comment by tjrobinson** [comment]
Thanks Rick, that works perfectly. I'm happy to consider this issue closed as it doesn't seem to be an MM issue and your workaround seems like the only solution for now.

**Comment by RickStrahl** [comment]
Thanks for helping track this down Tom. While it sucks this happens at all, at least this workaround hack provides a solution I can point people at. I don't see any significant performance difference in MM operation due to this even though there are some animations due to our usage of MahApps. 

Thanks again!

**Comment by afewell** [comment]
I have this issue, I did change the value in the config file to disable hardware acceleration and that did not fix the issue. That being said, if I open it, drag it to my laptop screen and then back to my main external monitor (sometimes 2 or 3 times) it seems to work fine. I am new to using this editor, but if it works well this bug is not really a big issue for me.

**Comment by RickStrahl** [comment]
Hmmm... that should definitely work. Did you double check to make sure the key was set when you started up? It sure sounds like exactly the same issue described here.
