### ISSUE TITLE
Relative path in image URLs

### ISSUE THREAD

**Issue by tjrobinson** [RickStrahl/MarkdownMonster#137]
I'm using Markdown Monster to edit a GitHub wiki, and really liking the image pasting feature.

It's all working fine except to get the images to display on GitHub itself I'm having to change the image path to use forward slashes instead of backslashes. The preview within Markdown Monster itself works fine though.

What I get:

`![](images\image.png)`

What I need:

`![](images/image1.png)`

I'd be happy to try and submit a PR but want to check this isn't by design first.

**Comment by RickStrahl** [comment]
This looks like a bug.

**Comment by RickStrahl** [comment]
Should be fixed in 1.1.27.  Took a few tries to get this in a few different places. There might be a few more especially in addins.

Also, paths now are always embedded as relative paths all the way down to the root which can be ugly for hardcoded paths (although MM will prompt to save non-relative paths).

95563e09c5ba0bc4bceaf74dd788a0fe46b47e2a
559b3d129ea8fcd073c58dd961fa76476f306b0b
7fe535165073c52a1d7a72ea0a715db6c07bcb26

**Comment by tjrobinson** [comment]
Looks good to me, thanks @RickStrahl
