### ISSUE TITLE
Integration with Pandoc

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#142]
I recently needed to convert some documents from RTF to Markdown. I was able to do that via Pandoc. 
Pandoc turned out to be the Swiss Knife of a conversion utility overall which would be an omission not to include / integrate with MM.
It'd be just awesome to have it done IMHO.

**Comment by RickStrahl** [comment]
Licensing doesn't allow for it in commercial software.

**Comment by ArthurZ** [comment]
Bummer. may be to create a web service that can convert from within MM?

**Comment by RickStrahl** [comment]
I think an add-on could get around the licensing issues because it wouldn't be part of the main commercial distribution. 

The other issue is that it's very large. The minimum zipped PanDoc exe is 11megs. And then you need the support exe plus latex to really do anything useful. It'll be a big thing that comes down to support this.

Also I took a look last night for a few conversions. Tried to convert md file to html  and it did a few odd things like treat HTML text as a code block rather than rendering. Also tried converting HTML to  RTF and it just produced jibberish. So I think before any of this gets done we need to examine what actual use cases there are for this in terms of conversions.

An add-in would work for this though - addin could just pop up a form with a host of conversions you can perform and then just perfom those actions by shelling out.

But not something I'm going to tackle right now. If somebody can put together a few useful samples or better yet create an addin that would be a good way to start. Again I think the Snippets addin would make a good starting point for the UI aspect of this.

**Comment by RickStrahl** [comment]
This should be a lot easier with post 1.2 versions which now have an easy way to create addins that provide custom Markdown parser implementations or forwarding.

* ![Creating a custom Markdown Parser in an Addin](https://markdownmonster.west-wind.com/docs/_4ut0j7xoe.htm)

**Comment by RickStrahl** [comment]
Some progress on this: I've set up an Addin project that provide Pandoc integration and uses Pandoc for generating Markdown as an optional markdown parser. There's also a UI component that lets you run Pandoc commands agains the active markdown document although that functionality is still in flux. The idea will be that you can set up custom commandlines that can be executed to generate output. For example you can specify a .pdf file and it will generate pdf output, or a .docx file and it will generate a Word document.

Anyway for those of you interested the add-in lives here:
https://github.com/RickStrahl/Pandoc-MarkdownMonster-Addin

Please take a look and if this is important to you please provide feedback and possibly PRs for helping out on this as I'm not sure what features are actually desired for this.
