### ISSUE TITLE
Preview fails with user account path with international character

### ISSUE THREAD

**Issue by sondreb** [RickStrahl/MarkdownMonster#144]
![image](https://cloud.githubusercontent.com/assets/309938/22924452/7697446e-f2a5-11e6-9e3d-91739f054f04.png)

**Comment by RickStrahl** [comment]
In this case what's the actual path name? It looks like the path is UTF-8 encoded? 

Not quite sure where the UTF-8 encoding comes from.

**Comment by RickStrahl** [comment]
Apparently the WebBrowser control doesn't like strings and standard encoding doesn't work (due to some sort of double encoding bug).

But using Uri's appears to do the trick.

Fix here:
4f0555dc8e638e5690f2bd34ddca1ff812f30acd

Can you check this in the next update post 1.1.28.

Thanks for your help!
