### ISSUE TITLE
Create a facility for registering and using custom markdown parsers

### ISSUE THREAD

**Issue by MissaouiChedy** [RickStrahl/MarkdownMonster#148]
## Issue
It seems that it is not possible to create and use a custom markdown parser in Markdown Monster.

The [MarkdownParserFactory](https://github.com/RickStrahl/MarkdownMonster/blob/master/MarkdownMonster/_Classes/MarkdownParser/MarkdownParserFactory.cs) class is always returning a `MarkdownParserMarkdig` instance.

## Proposal
We can create a facility for registering custom markdown parsers implementing `IMarkdownParser`, in the settings we can then add the possibility to choose which `IMarkdownParser` should be used.

The `MarkdownParserFactory` can then instantiate the specific `IMarkdownParser` specified in the settings.

The custom `IMarkdownParser` can be provided as a AddIn.

## Use cases
- I need this capability in order to generate preview for markdown files that includes [liquid template engine](https://jekyllrb.com/docs/templates/) statements that needs to be generated by [Jekyll](https://jekyllrb.com/). 
- Some users may need to support custom markdown language extensions.

I will be glad to contribute if the proposed feature is relevant.

**Comment by RickStrahl** [comment]
The question is how to implement this.

I just added an `OnCreateMarkdownParser()` handler in the Addin interface to allow overriding the `IMarkdownParser` instance creation. You can basically implement a non-visual addin that just implements this method and returns whatever you want as long as it implements `IMarkdownParser` which really just means a Parse method.

Would this work?

**Comment by MissaouiChedy** [comment]
Adding the `OnCreateMarkdownParser` on the `MarkdownMonsterAddin` is a good start but several interrogations remain:

- How to select which parser to use when multiple Parser addins are loaded ?
- How to differentiate between a "regular" addin and a Parser Addin ?

Regarding the first question I suggest we let the user choose the parser used to render the preview in the same way she uses the editor and preview themes.
Regarding the second question I suggest we create a subclass of the `MarkdownMonsterAddin` that looks like this:

```
public abstract class MarkdownMonsterParserAddin : MarkdownMonsterAddin, IMarkdownMonsterAddin
    {
        public abstract IMarkdownParser GetParser();
        public abstract string Name { get; }
}
```

I actually fiddled a little bit and came up with a prototype available [here](https://github.com/MissaouiChedy/MarkdownMonster/tree/MarkdownParserAddin) under the *MarkdownParserAddin* branch.

From the user standpoint, it is possible to select the parser from alist of available parsers:
![capt](https://cloud.githubusercontent.com/assets/2974316/23218684/254a8584-f91d-11e6-9079-a2efefee7ea4.png)

From the addin developer standpoint, it is possible to create a `MarkdownMonsterParserAddin` subclass that return an instance of a developer defined class implementing `IMarkdownParser`. The *CustomParserAddin* project available under the solution is an example.

Here are the changes that I made:
- Created a Parser selection Combo box in the status bar
- Introduced the `MarkdownMonsterParserAddin` class
- Created an Addin "wrapper" for the Default MarkDig parser
- Changed the MarkdownParserFactory to return an instance of the currently selected parser
- Created the `CustomParserAddin` which returns the very basic `CustomParser` 

Do you think that this is a viable solution?

**Comment by RickStrahl** [comment]
Yup in overall view this looks pretty good.
A few things:

* We don't want an abstract method because that requires implementing. The `OnGetMarkdownParser()` method already handles that basically and is less intrusive but maybe it's better to make that an explicit virtual `GetMarkdownParser()` method that by default returns null.

* The name is an obvious omission although that comes from the menu caption typically. Thanks.

* The selection drop down is good but I don't think I'd want that quite so prominent. Most people wouldn't know what to do with that, so we probably have to find a new home for that. At the very least it'd be on the right of the lists and then maybe show up only if there are multiple parsers available.

**Comment by RickStrahl** [comment]
Took a look at your code and it's heading in the right direction. 

I  want to avoid type lookups - there are all sorts of issues with performance there especially for addins loaded out of a separate folders so we need to avoid that, especially since this has to happen during startup.

Rather I think it'd be better to just query all the addins for GetParser() to get the list of addins and identify them by Addin Id (or name perhaps since that will be cleaner in code). 

So I was thinking along these lines:

```csharp
public static class MarkdownParserFactory
{
    public static IMarkdownParser GetParser(bool renderLinksAsExternal = false, bool usePragmaLines = false, bool forceLoad = false, string addinId = null)
    {
        IMarkdownParser parser = null;

        if (!string.IsNullOrEmpty(addinId) && addinId != "MarkDig")
        {
            var addin = AddinManager.Current.AddIns.FirstOrDefault(a => a.Name == addinId || a.Id == addinId);
            if (addin != null)
                parser = addin.GetMarkdownParser();
        }

        return parser ?? (parser = new MarkdownParserMarkdig(usePragmaLines: usePragmaLines, force: forceLoad));
    }


    public static List<string> GetParserNames()
    {
        var parserStrings = new List<string>()
        {
            {"MarkDig"}
        };
        foreach (var addin in AddinManager.Current.AddIns)
        {
            var parser = addin.GetMarkdownParser();
            if (parser != null)
                parserStrings.Add(addin.Name ?? addin.Id);
        }

        return parserStrings;
    }
    
}
```

This avoids having to scan all addins for parsers - rather they just can provide them for you when requested. If you want multiple parsers - just create multiple addins in the same project.

**Comment by RickStrahl** [comment]
So I've added some of these changes in:

a95977ed8351bf9f773a193dfe7c0525a650ac22

**Comment by MissaouiChedy** [comment]
@Rick the plumbing you added for handling the Parser addins is solid, but selecting another parser from the markdown parser combo box does not refresh the preview.

I fixed this by modifying the `MainWindow.MarkdownParserName_SelectionChanged.
Here is a [pull request](https://github.com/RickStrahl/MarkdownMonster/pull/149) containing the previous change along with some other improvements:
- Parser selection combo box is only visible when multiple parsers are loaded
- Created a test case for the `MarkdownParserFactory` class

I have a question: Why not passing the `renderLinksAsExternal` and `usePragmaLines` arguments to `MarkdownMonsterAddin.GetMarkdownParser`?

**Comment by rick** [comment]
![](http://akns-images.eonline.com/eol_images/Entire_Site/201524/rs_500x281-150304100041-8db66e815038eb28_Bound3b.gif)

**Comment by RickStrahl** [comment]
> I have a question: Why not passing the renderLinksAsExternal and usePragmaLines arguments to MarkdownMonsterAddin.GetMarkdownParser?

Because the parser instance is cached and those two settings have to be changed potentially for each render operation.

**Comment by RickStrahl** [comment]
So that last comment was wrong :smile:. 

UsePragmaLines - at least on MarkDig - has to be set when the parser pipeline is initialized, so this has to be done each time. I suppose it's not a heavy operation, but still a bummer that this works that way.

So I probably just broke your custom Markdown Parser :-)  as I changed the interface to just have:

    public interface IMarkdownParser
    {
        string Parse(string markdown);
    }

I figure better now than later when people start implementing custom parsers 😨

**Comment by MissaouiChedy** [comment]
I think it is OK to get rid of the `bool renderLinksExternal` argument if it is MarkDig specific.

Regarding my custom Markdown Parser, I'll just update it  ;-)

**Comment by RickStrahl** [comment]
Phew, all sorts of cleanup to get this all working properly.

d5e562cfa7ed59591fd021a7e348a4870809886d

Nasty timing issue for loading parsers before addins are loaded (async load) that took while to track down.

**Comment by MissaouiChedy** [comment]
Tried it, it works 👍

**Comment by RickStrahl** [comment]
Now to create some custom parsers :-)
