### ISSUE TITLE
Add the ability to insert a line seperator

### ISSUE THREAD

**Issue by LDARBY** [RickStrahl/MarkdownMonster#151]
The markdown code for this is  "----------" without the "

**Comment by RickStrahl** [comment]
I don't think that `---` (or more) is supposed to be doing that. 

Go to BabelMark and see what various Markdown parsers are rendering for the following:

```markdown
This is a test
------

this is another test
******
```

Check it out at:
https://babelmark.github.io/?text=This+is+a+test%0A------%0A%0Athis+is+another+test%0A******

Note both have lines but the first is due to styling on the H2 tag, not to an actual line separator.

The official line separator is `***` (or more) it looks like. Three dashes or more render an `<h2>` tag in all parsers that are tested there.
