### ISSUE TITLE
It'd be nice to have flowcharts and diagramming support in MM 

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#155]
I wish MM could support flow charting and diagramming

**Comment by RickStrahl** [comment]
I don't know what to tell you. You want an ice cream dispenser too perhaps? :-)

If you're not willing to provide some input in all of these requests you're making for features that are outside of the base scope of the editor, then I would prerfer you don't make them. 

I have no idea what to do with requests like this other than close them.

**Comment by thomaslevesque** [comment]
I assume @ArthurZ is referring to [Mermaid](https://knsv.github.io/mermaid/). It's a diagram definition language that can be embedded in Markdown.

**Comment by RickStrahl** [comment]
Yeah I looked at it a while back. Unfortunately it doesn't work very well in IE 11 or even Edge so we can't preview it in the editor 😢

**Comment by conspacer** [comment]
I use this feature (Mermaid diagramming) quite a bit in [haroopad](https://github.com/rhiokim/haroopad), but so many bugs and lack of any development in the last 4 years has me hunting for a replacement MD editor... MM is looking good so far in many ways

**Comment by RickStrahl** [comment]
Closing since there is no real resolution with this issue given that Mermaid rendering won't work properly in the preview editor unfortunately.  

All that said it is possible to make Mermaid work:

* Create a template that adds the Mermaid scripts and css to the Preview HTML page
* Preview in External Browser that's not IE/Edge (alt-v-p)
