### ISSUE TITLE
triple backtics code does not render in color

### ISSUE THREAD

**Issue by zodiacon** [RickStrahl/MarkdownMonster#187]
Hi,
I'm using the triple backtick to show some C# code (as an example). The preview shows it nicely, but when the blog is posted, it's just plain text with no syntax highlighting and different formatting. Look here: https://blogs.microsoft.co.il/pavely/2017/05/08/packinging-apps-into-single-files/

Also, couldn't find a way to configure tab size in the editor.

Thanks for a cool tool!

**Comment by RickStrahl** [comment]
Markdown doesn't provide the physical formatting - it just generates HTML and your application running on the server is responsible for styling the HTML in the way you like it. 

Source code formatting uses standard Markdown formatting of:

```html
<pre><code lang="language-html">
<!-- HTML encoded code block goes here -->
</code></pre>
```

 to output code blocks. Generally you use a Javascript library to format the code in the HTML. MM uses [highlightJs](https://github.com/isagalaev/highlight.js/) for this purpose in the previewer and the self-contained HTML output it creates.

There's more info in the help file on how you can hook this up in your HTML (your blog template most likely):

* [Source Code Highlighting](https://markdownmonster.west-wind.com/docs/_4sf0may9m.htm)

**Comment by zodiacon** [comment]
My blog is hosted on a server I don't control. It would have been nice to have syntax highlighting for code out of the box.

**Comment by RickStrahl** [comment]
Anyway you implement syntax coloring - even if fully pre-generated into the HTML instead of using JS to highlight -  will require some level of customization as you'd still need to add appropriate stylesheets. So no matter what you need to have some control over your server.

I realize this is an issue with places like Medium that don't let you customize html at all, but most other providers do have some basic template manipulation that should allow you to add script and styles to the page.

It's also possible to embed the above scripts directly into the post - since Markdown is just an extension of HTML (unless your service filters it). 

So you could add this to the bottom of a post:

```html 
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/highlight.min.js"></script>
<script>
document.querySelectorAll("pre code")
           .forEach(function(item) { hljs.highlightBlock(item); });
</script>
```

**Comment by zodiacon** [comment]
Thanks, I'll give this a try.
Appreciated!
