### ISSUE TITLE
Suggestion: Auto Close spell window on outside click

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#188]
Sorry to bundle but a few related suggestions:

1. Rather than clicking the 'close' button, is it possible to auto-close this window if I click on anywhere else on the app please? Or make that an option please? 

![image](https://cloud.githubusercontent.com/assets/174004/25818258/e68a8d60-33de-11e7-9670-6780307c3d4e.png)

2. On mouse-over (with delay) show suggested correctly spelled words.

3. Also, is possible to style that popup suggestion window differently so it stands out a little more with suggestions please?

Thanks and keep up the great work. :)

**Comment by RickStrahl** [comment]
Hmmm... the popup should close when you move out of it. If you drag your mouse across it then out it should go away. But I see the issue is partially that the mouse cursor is not really inside the popup to start with, so it's not super obvious that this works that way until you're actually inside of the popup and move out. It's easy to miss.

So I took a closer look and implemented outside click handling with a temporary click handler.

6bc5c45ad3f8613cb9cbea8d09f2bf45bb3d211c

It'll be in 1.3.10

**Comment by RickStrahl** [comment]
As to #2, that's a lot more tricky. There's not a really good API around the 'marker' interface so don't see a good way to trap a hover event (especially with a delay). 

I agree this would be a cool feature or even a keyboard shortcut to drop down the list just to avoid the mouse usage.

**Comment by Mehul** [comment]
@RickStrahl 
I like the changes, thank you!

**Comment by RickStrahl** [comment]
I'm going to close this issue. If you want you can repost No. 2 as a separate issue, but I'm not sure that I'll be able to make that happen.

**Comment by Mehul** [comment]
No Worries. It'll stew in your brain for days/weeks then you'll wake up one day with the answer. :)
