### ISSUE TITLE
Suggestion: Move temporary HTML files to a different directory than source file

### ISSUE THREAD

**Issue by daughtkom** [RickStrahl/MarkdownMonster#19]
When writing a readme.md for GitHub, if I "git add ." while the document is open, it adds the temporary __readme.htm.  It would be nice to have the temporary files be somewhere else that wouldn't get included by mistake (e.g., Temp).

A less desirable workaround would be to use a unique file extension I could add to gitignore.

**Comment by RickStrahl** [comment]
Yes I know about this and it's not optimal, but having the document in the current folder is the only reliable way to find referenced resources like images or related documents short of copying the entire folder structure. Otherwise you won't know what resources may be referenced from various locations.

Originally we deleted the files immediately after rendering (and I may look at this again as I've changed the way the refresh operation works by updating the HTML directly vs. actually refreshing), but there are a few issues with this as well - mainly if you explicitly refresh (f5 in the preview) or navigate back - that the navigation may not work also breaking further refreshes.

For now the easiest solution is to add a __*.htm reference into GitHub projects which will exclude all files.

Note the files are deleted when the documents are closed or you shutdown.

**Comment by daughtkom** [comment]
I get that, and don't have any good idea to get around it.  Would you be willing to make the naming convention more unique?  Maybe something like __*.mm.htm?

Though not often, I can imagine running into real files named __something.htm at some point.

**Comment by daughtkom** [comment]
Actually, here's a thought for consideration: use the `base` tag in your preview document.  Example:

```html
<head>
    <meta charset="utf-8" />    
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link href="C:\Program Files\Markdown Monster\PreviewThemes\Blackout\..\scripts\bootstrap\css\bootstrap.min.css" rel="stylesheet"/>
    <link href="C:\Program Files\Markdown Monster\PreviewThemes\Blackout\..\scripts\fontawesome\css\font-awesome.min.css" rel="stylesheet" />
    <link href="C:\Program Files\Markdown Monster\PreviewThemes\Blackout\Theme.css" rel="stylesheet" />
	<base href="file:///C:/Users/username/Desktop/" />
<body>
```

Then the preview document can live anywhere.

**Comment by RickStrahl** [comment]
Thanks for the suggestion. I had thought about that as well but there are problems with this also - duplicate filenames for example (unless generating unique names which might also be OK).

However, I think the easier solution is to use hidden files. This seems to bypass all the issues - Git ignores them and the browser can still see them to render. Experimenting now - seems to work so far.

Thanks for the suggestion. We might end up revisiting to that if other problems crop up.

**Comment by RickStrahl** [comment]
Thanks for the suggestion. I had considered that before as well, but then there are potential file name issues - if maintaining the file.

Since there have been changes to the way rendering is handled in recent versions with refreshes updating the existing document rather than refreshing, I've gone back to deleting the temp file after a couple of seconds after rendering. There are a few edge cases where you can end up with a missing document in the browser (navigate, back then refresh in Preview), but any typing or saving will restore the preview then. If that still causes issues I'll look into the `base` path in the preview.

Fixed in 9597920a5623a9230b4ebf121f1cb864R1139
