### ISSUE TITLE
Cursor alignment off with some Unicode characters

### ISSUE THREAD

**Issue by tjrobinson** [RickStrahl/MarkdownMonster#195]
When editing the following markdown, the cursor alignment isn't correct making typing/selection difficult:

`t❌✔t D123456❌✔5 `

![image](http://i.imgur.com/bVZkxv3.gif)

![image](https://cloud.githubusercontent.com/assets/925311/26098075/7bcda958-3a1e-11e7-89df-2682da6ba1a6.png)

Windows is scaled at 100% on a 2560x1440 resolution, running Windows 10 Creators Update.

**Comment by tjrobinson** [comment]
Ah, that's a shame. It's not a problem most of the time but we've got one page on our wiki with a lot of emojis on it :)

And yes, I really should get round to registering my copy soon.

**Comment by RickStrahl** [comment]
I'll forward this to the Ace repro and see what they have to say - I'm pretty sure this is not doable as they rely on fixed width characters, but worth the question. I'll forward whatever comes back here.

**Comment by RickStrahl** [comment]
Looks like there are several issues out on this, but it hasn't really made any progress. There are patches that have been in process for a couple of years. This may get fixed in the future but not likely any time soon. :-(

**Comment by RickStrahl** [comment]
As mentioned there are several threads open on this on the Ace Forum and it looks like this unfortunately won't get fixed any time soon since it requires some major reworking of the editor internals.

Here's one of the discussions:
https://github.com/ajaxorg/ace/issues/1153

Closing issue for now since this is not likely to get resolved.
