### ISSUE TITLE
Add support for Blogger API

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/MarkdownMonster#197]
Unfortunately, Google doesn't support MetaWeblogAPI for Blogger.com but has its own API: https://developers.google.com/blogger/. Please add support for this API.

**Comment by RickStrahl** [comment]
Thanks Doug. Let's put that on the list of Todo items, but this is the first request I've heard for this. Let's see what kind of feedback this issue brings.

Do you know what version of Blogger your Blog is using? There are a number of versions, but then the newer versions are likely lightly used since Google no longer has a blogging site. New blogger sites are rare

Here's the link for the NuGet package
https://www.nuget.org/packages/Google.Apis.Blogger.v3/

And the documentation lives here:
https://developers.google.com/blogger/docs/2.0/developers_guide_dotnet

Looks like the .NET docs are only for version 2 though - sigh.

**Comment by DougHennig** [comment]
I don't think this is worth doing after all -- a bunch of work for little payback. I'll let you decide if you want to keep it open or close it.

**Comment by RickStrahl** [comment]
I'll leave this open here in case somebody wants to tackle this. I will probably add this when I have a little more time.
