### ISSUE TITLE
Word highlighting issues with themes

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#198]
1. Using monokai and I try to highlight a word that is a heading, it gets clipped:

![image](https://cloud.githubusercontent.com/assets/174004/26506268/c2d9ec5a-4200-11e7-9be8-03404432eddc.png)

2. Using cobalt, the word is not even highlighted (or doesn't appear highlighted):

![image](https://cloud.githubusercontent.com/assets/174004/26506315/e72e5b22-4200-11e7-9070-e99ddef6fc9d.png)

I'm using the ['Hack' font](https://github.com/chrissimpkins/Hack) at 17pt, and the clipping doesn't occur with 'Consolas' but I'd rather use Hack font. Also, the highlight in cobalt is an issue regardless of the font.

Actually, try using any other font than consolas and MM cursor and highlight go out of sync. [Or is it only me :) ]

Thanks.

**Comment by RickStrahl** [comment]
Where are you setting hte font? The font can't be set in the styles it has to be set in the editor options because ACE needs to calculate the actual screen width of each character for cursor, marker and selection positionioning. 

FWIW, I set my font to Fira Code which is pretty different in width from Consolas and tried Monkai and Cobalt and the alignment for selections and caret are correct for me. Note that you **have to** use a fixed width font - proportional fonts will throw off the caret and alignment.

As to the cobalt theme - and back color - this is the standard cobalt theme for Ace Editor. Looks like a bug to not highlight.

As to fixing the specific error, you can adjust the following in the `theme-cobalt`:

```css
.ace-cobalt .ace_heading,\
.ace-cobalt .ace_markup.ace_heading {\
color: #C8E4FD;\
}\
```

Note: removes the background color for this style. I've made that change here.

**Comment by RickStrahl** [comment]
Any word on this?

**Comment by Mehul** [comment]
Yes, I set the font in the styles. I think I was using the wrong name for the fonts. In VSCode, you use the font file name and in MM, you use the name that's displayed in the info screen. So that seems to be a non-issue.

As for highlight, thanks, I've got that set up now.

**Comment by RickStrahl** [comment]
Yeah, you can't change the styles - always change the font name and size in settings only. As to font names these should be the same that'd be used in CSS. AFAIK, it's always the name of the font from the font-settings, not the filename (which could be anything and can be confusing because there are usually multiple files for each font-weight combo and style).

**Comment by Mehul** [comment]
That was meant to say Settings. I set the font in settings, not styles. :)

**Comment by RickStrahl** [comment]
Hmmm... so it wasn't working until you fixed the font name?

I'd think that if the font name is wrong that it would universally fall back to some default font ('cause CSS). 
IAC with the proper font name it appears to be working, right?

**Comment by Mehul** [comment]
Ok, I spoke too soon. And this is about the font issue so I don't know if you want another ticket but I'll post it here. This video should highlight the frustrating oddity with any other font than Consolas for me:


[MMFontIssues.zip](https://github.com/RickStrahl/MarkdownMonster/files/1059163/MMFontIssues.zip)

**Comment by RickStrahl** [comment]
Hmmm... I'm not sure - I can't duplicate that. I set up my config same as in the video (monokai, fira code, 19px) and I don't see any cursor offsets. There must be something else that's causing this perhaps.

Two things:
* Scaling level in Windows?
* .NET Version? (about screen should show)

I have seen this behavior before, **but only if CSS font-sizes/font** was changed in some way. ie. the theme-monokai.js template or editor.css with specific font sizing.

**Comment by Mehul** [comment]
I'm running .net 4.7 from about. I'll check this on my home laptop as well.

**Comment by Mehul** [comment]
Ok, tested on home laptop but same issue with clipping. I notice that it does the highlight clipping on Headings but regular paragraphs are fine (when using different font).

![image](https://user-images.githubusercontent.com/174004/26960441-0e7f4552-4c8c-11e7-9ea6-6cefe28afb47.png)

In that screenshot, I'm using Fira Mono at 19.
---
Then, I tried getting a fresh portable copy and clearing appdata/roaming but same issue. Then I tried installed version, same issue. I had version from December 2016 and that had the same issue.
Are you not seeing the same issue? Btw, at home laptop, the scaling is at 100%.

**Comment by RickStrahl** [comment]
What happens when you use `Courier New`?

No I'm not seeing this. I use Fira Code as my main font. I'm running at 19 as well and 100% scaled on a 4k monitor, but on a scaled smaller screen I also have no issues.

The portable install is a bit dated but it should have the changes that were made to properly update the font info - you are seeing the font. Maybe try the full install. I'll update the portable install shortly when 1.4 goes out the door... 

It all sounds **exactly** like when the CSS font sizes or font names have changed (in the theme-xxxxx.js) file or in editor.css.

**Comment by Mehul** [comment]
Courier New is ok. I'm running the latest Fira Code font (19 size) on my external 24" running at 1920x1080 (same issues though). No scaling that I know of. I tried it on my main laptop screen w/o the screens attached and still the same issue. Now, I did a test on a coworker's laptop that has never had MM installed. He installed Fira Code first then MM (non-portable) installer. And it had the same issue. Could you zip up your install so I could try it on my end please? Again, I'm not doing anything to the CSS. Or could ACE be detecting some CSS from elsewhere? Thanks.

**Comment by RickStrahl** [comment]
The install I use is the current downloaded version from the Web site (or Chocolatey which is the same build). I'm not doing anything different than anybody else for my installed copy.

Really not sure what the difference is here -  I can't duplicate it here or on 2 other RDP and 2 Azure VMs. I see this working on all of them.

![firacode](https://user-images.githubusercontent.com/1374013/26997900-5f3fd6cc-4d32-11e7-9402-a3ec7ee5d5cc.gif)

The fact that it works with `Courier New` and `Consolas` which both are native, but not with `Fira Code`  (for you) which is not, I'm wondering if there's a problem with the font somehow. Are you getting the font from Github here: https://github.com/tonsky/FiraCode and installing the TTF file?

**Comment by Mehul** [comment]
Hi, Yes, I get the TTF from github. I'll try it again tomorrow and let you know

**Comment by Mehul** [comment]
Ok, I figured out and solved the issue. It was on my end, I had not installed ALL the fonts so likely when I was highlighting the heading, it was looking for Bold and didn't find it. Anyways, it's fine and sorry for the trouble. Keep up the good work.

**Comment by RickStrahl** [comment]
Ah, good to know. Thanks!

That makes sense I suppose - although I would expect it to screw up the font completely as you type as an invalid font falls back to  whatever the system default is.
