### ISSUE TITLE
Publish window can be opened more than once

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#199]
Clicking publish brings up the window but clicking it again, brings the window up again. Should it be modal? Or simply restrict it to once instance?

![image](https://cloud.githubusercontent.com/assets/174004/26511487/16b5e1ce-4217-11e7-8a78-934aed59c74d.png)

**Comment by RickStrahl** [comment]
The window isn't modal and not meant to be since you can in fact go back and edit the post before posting to blog. And in theory you can open multiple blogs at the same time although that's probably an unlikely use case :-)

Not sure if we should make this a single instance window - but it definitely shouldn't be modal.

**Comment by Mehul** [comment]
Doesn't it seem unusual to create two of those publish windows on the same post? I click publish button with the intent that I will publish or close that window and go back editing, right? Anyways, it's not a big deal either way so go ahead close this. :-)

**Comment by RickStrahl** [comment]
I've made it so that there's only a single instance of the window. 

If a window is open the old one is close and a new one opened with the new content only.
