### ISSUE TITLE
Search/replace window is very small on high definition screens.

### ISSUE THREAD

**Issue by aidanw** [RickStrahl/MarkdownMonster#202]
On my laptop the find and find/replace window is small and crushed. The screen is 3200 x1800 and I expect that this is the problem.

![image](https://cloud.githubusercontent.com/assets/1986524/26636131/aea00a6e-4613-11e7-89dd-4f8333096021.png)

If I alter the compatibility settings of the application, then I get a normal proportioned window, however the whole ui is then fuzzy!

![image](https://cloud.githubusercontent.com/assets/1986524/26636328/5096c326-4614-11e7-9c88-2c2a5762cdf1.png)

**Comment by RickStrahl** [comment]
Thanks for reporting.

What scaling level are you using? And what version of .NET?


It might help running .NET 4.6.2 or later - likely you're on 4.6.1. MM uses the new High DPI features to allow for per monitor scaling and that was introduced in 4.6.2.

What was the default showing for the Override drop down?

**Comment by RickStrahl** [comment]
On further investigation it looks like it's not the scaling that's the problem but the overall font-size. 

I've made some tweaks to at least keep the size of the find box fixed so it doesn't get smooshed as your per screen shot, but that still won't size up properly.

Unfortunately it's very tricky controlling that find window via CSS and I'm having no luck finding a good way to get the window to scale up. I'll keep looking but for now the window is fixed in size.

Maybe you need to scale your screen a little more :-)
