### ISSUE TITLE
Error when loading app

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#204]
I get a popup window when starting the app.
It doesn't stay open long enough to see the message.
There is a Do you want to continue button, and I was able to click it.
The  following is a screenshot.  The toolbar and menu is missing.

![mmerror](https://user-images.githubusercontent.com/19954905/26837330-d1c4f458-4aa2-11e7-9f3d-c0772a629e30.png)

**Comment by RickStrahl** [comment]
Can you double check with 1.3.22. There was a versioning bug, that had me shipping a non-release version rather than the final release build. 1.3.22 addresses that. The issue had to do with reading command line arguments.

That explains the crash, but not sure about the missing menu, unless somehow that's caused by the form not properly initializing during startup. Give 1.3.22 a try and let me know if that fixes it.

Thank you.

**Comment by HowardEdidin** [comment]
The issue is resolved.
