### ISSUE TITLE
Copy operation is not a change to a document

### ISSUE THREAD

**Issue by Xansky** [RickStrahl/MarkdownMonster#206]
When I open a document just to copy some text out of it, I see that the document is marked as changed when I press Ctrl+C. When I go to close the document, I am asked if I want to save it. A simple copy operation does not change the document and should therefore not mark the document as dirty.

**Comment by RickStrahl** [comment]
@Xansky - Hmmm, I can't duplicate that. 

Are you sure you're not getting a character? 

* Open document
* Select some text
* Press Ctrl-C
* Observed: no change in file status

MM checks the content against a cached copy of the last loaded/saved document so it shouldn't flag unless the content is actually different. In fact, if you type some text, then remove that same text, the flag should disappear.

This used to be a problem a long while back because we didn't actually look at the content, but just figured based on keystrokes. Are you on 1.4 or at least 1.3.+?

**Comment by Xansky** [comment]
I'm on version 1.4. Now I can't replicate it either. It was definitely happening last week. Glad it resolved itself!

**Comment by RickStrahl** [comment]
LOL - I hate those!!!! :smile:
