### ISSUE TITLE
Feature request: please integrate with Pastebin

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#238]
Feature request: please integrate with www.pastebin.com. 
Super useful for writing blogs.
Pastebin APIs are easy to use https://pastebin.com/api

**Comment by RickStrahl** [comment]
Have you looked at the Gist addin? It basically provides the ability to load and save documents from Gists.

https://github.com/RickStrahl/GistIntegration-MarkdownMonster-Addin#usage-for-open-and-saving-documents-from-gists

Something like this can be built as an addin if needed for PasteBin as well and you could probably use the Gist Addin as a base and just replace the API for the load and save features.

Down the line, MM probably needs some sort of provider interface to allow loading of documents (and images) from various locations. The big issue for a generic interface is how to handle the authentication part generically which is why I haven't gone down this path yet. This is on the todo list but relatively low priority for the moment. 

In the meantime the best solution is to create an addin...
