### ISSUE TITLE
MarkdownMonsterAddin.Model not initialized

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#241]
Hate to be a pain.

Markdown Monster version 1.6.4

I have an issue, during startup mm initiates a preview of the document before an addin has had it's Model member set `(MarkdownMonster.AddIns.MarkdownMonsterAddin.Model)`.

My problem with that is that I'm writing a markdown parser addin that places a macro processor between the markdown document that's being edited and the markdown interpreter (markdig). While processing the markdown file I need access to the directory where the document is located so that any #.include() macros can be processed. I need to grab `Filename` out of `Model.ActiveDocument` to get the directory; it's okay if there is no path part to the filename (new file) because any errors encountered by the macro parser will be the fault of the user, not because an include file can't be found (when it should be found). 

I'm not calling this a bug, but it seems that an addin's base class should be fully initialized before it's markdown `Parse()` member is called.

**Comment by RickStrahl** [comment]
Addins are loaded out of band in the background so that they don't slow down MM's startup if you have a lot of - or slow addins.  

So no, there's no guarantee that the addin is loaded by the time the document needs to be rendered for the first time - if there's an active document and a new Parser has not registered itself yet, the original renderer will be used.

I've gone back and forth on this, but in the end I think the load perf is important enough to warrant this behavior.

As a workaround you can install your parser as needed and you can explicitly refresh the preview after loading. This is likely to happen even before MM becomes visible (but still after the initial rendering).
Call Addin.RefreshPreview() after you've set you markdown parser.

**Comment by jmclain** [comment]
The parser is loaded but Addin.Model is null which means I can't access Model.ActiveDocument. Not a killer problem, I'm just putting a message in the preview window that the addin/parser is still loading and the user should wait a few moments and then refresh. Note I'm binding F12 as a refresh hotkey because I could not locate one in the mm UI.

**Comment by RickStrahl** [comment]
You can implement `OnWindowLoaded()` which is fired once everything is initialized. IOW, load the parser in GetMarkdownParser, then do whatever UI related things (like refreshing the Preview) in `OnWindowLoaded()`.

https://markdownmonster.west-wind.com/docs/_50m0t2enu.htm

**Comment by jmclain** [comment]
I just noticed the OnBeforeOpenDocument() and OnAfterOpenDocument() which will allow me to grab the path of the documents as they are loaded.

One question. As mm loads I assume (as the debugger shows) that the last document loaded is the document that will be in the editor?

**Comment by RickStrahl** [comment]
Depends on configuration settings based on `RememberLastDocumentsLength`. If that value is 0 or `UseSingleWindow=false` then no recent documents are remembered.

I don't think you need to handle those events you mention - once you set the parser it'll do its thing automatically, you just have force a re-render once initially. The OnLoad() fires in the Window's Onload but before the window is actually shown.

Maybe what we need is an `OnModelLoaded()` method that fires earlier in the load cycle after the model initializes in the Window. UI won't be active yet, but at least the model data would be available.

**Comment by RickStrahl** [comment]
Added:

4f1213629a92ef4301654a54e0ce447e90d3b343
