### ISSUE TITLE
File Menu ctrl-s

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#245]
Hello Rick,

I don't know if this is intentional or not but doing a file save using Ctrl-S always executes, even when the file is not dirty and File->Save is disabled. I discovered this when hooking OnAfterSaveDocument() to do the save of a secondary file that contains the results of macro expansion on the markdown in the editor.

**Comment by RickStrahl** [comment]
Not intentional. I suspect the logic here is short circuited directly from editbox (certain key combos don't forward to the host application) and Ctrl-s is one of those. It probably needs a gate to check whether it should save.

Added this tweak and which should keep any of the save commands from firing when the document isn't dirty.
348313a73eb1af43eb777bc10a013879789f516e

Note there may still be other places that force save operations.
