### ISSUE TITLE
Saving overwriting a file without any warnings

### ISSUE THREAD

**Issue by tucaz** [RickStrahl/MarkdownMonster#250]
Hi!

I had a file named `foo.xmind` with the outline of a book I'm writing using Markdown Monster. While saving the `.md` file I accidentally overwrote the `.xmind` file. I was able to recover a previous old version of my outline, so not all is lost. It was my fault and I understand that.

However, I believe a few steps could be taken to prevent another accident such as this one.

I wanted to save my `.md` file as `foo.md` so I went to the same folder as my `.xmind` file and started typing `foo`. The window auto-complete showed me `foo.xmind` and without any extra thought I pressed `enter` and then the override happened. I wish Markdown Monster would:

1. Ask me if I really wanted to overwrite the file
2. Double check if I'm using `.md` as the extension instead of some non-markdown related extension

Thanks!

**Comment by RickStrahl** [comment]
Are we talking about the Save dialog here? Or the folder browser? 

The Save dialog behavior is standard Windows behavior for saving documents. I believe if you are overwriting a file it **will** ask if you want to replace the existing file...  Ok I take that back, looks like those prompts are not there. 

Fixed: edf557e9d835f50f271ca9e1d830681de292750f

As to checking for non-.md files - not sure if we want that since there might be legit reasons to store markdown files with other extensions. MM supports extension mapping so possibility of other file types exists.
