### ISSUE TITLE
Saving new file folder location

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#252]
When saving a new file and the folder browser is open shouldn't the save file dialog default to the current folder browser directory?

**Comment by RickStrahl** [comment]
Currently last save location is remembered from previous save location and stored in the settings.

Using the folder browser location might be Ok - only if it's open of course.

**Comment by jmclain** [comment]
"Save file to the current folder browser directory."

This was a knee jerk reaction on my part because the folder browser is where I wanted to save a file. On further thought I'm not so sure I'm right, or wrong!

Maybe the folder browser needs a button to "Create a new file here." File is created with that path.

**Comment by RickStrahl** [comment]
You can press `N` in the folder browser to create a new file there or right click **New File**. Adding a button adds a bit of clutter and kind of a pain because you'd have to decide where to put the file exactly. The N operation is context sensitive so creates files inside of folders etc. based on selection.

Maybe we need like VS Code's file browser toolbar?
