### ISSUE TITLE
Broken bookmarks on page

### ISSUE THREAD

**Issue by jmclain** [RickStrahl/MarkdownMonster#258]
Just as a note. 
```
<base href="{$docPath}" />
```
In the theme.html file breaks the usage of bookmarks on the page. I know ${docPath} is substituted.

**Comment by RickStrahl** [comment]
Yeah I know this is a problem I haven't been able to solve. Browsers don't render # links when there's a file:// base path (some security issue I can't really sense of). 

But I don't know how to fix this. MM maps the theme file into the document folder so that it can use relative links to images and other assets. One way or another the page needs to render in that folder context in order to display pages correctly.

The alternative is to render the HTML file in the actual folder (which MM originally did) but it caused a number of other issues. File pollution with HTML files floating around, issues around untitled files, and the fact that the only way the rendering works is out of that folder which is problematic for some other things like PDF generation.

If anybody has ideas on how to get local basepaths to render with # links that would be great, but I don't think that's possible.

**Comment by RickStrahl** [comment]
FWIW, I just tried actually moving a preview file into the folder of the document and removing the the `base` tag and `#` navigation still fails. I think it just doesn't work at all with file based operations.

So unless I'm missing something it seems to me this is unfixable for local content unless running a local web server.

**Comment by jmclain** [comment]
Well, now I have to think about this. I discovered this when creating a page that does not have any images or other linked items so I wasn't even thinking about why `base` was there. Thinking cap on ...

**Comment by RickStrahl** [comment]
Idea: Should have thought of this earlier - but the client page is rendering script so we can intercept navigation to # tags and maybe do something like this:

```js
$("document").on("click","a",function() {
   if (this.href.substr(0,1) == "#") {
         // scroll to element
   }
});
```

**Comment by RickStrahl** [comment]
Ok, the following works:

```js
    $(document).on("click","a",
        function(e) {
            var url = this.href;
            var hash = this.hash;
            
            if (url.substr(0, 4) === "http" &&
                te.mmEditor.NavigateExternalUrl(url)) {
                    e.preventDefault();
                    return false;                
            }
            if (hash) {                
                var sel = hash + ",name=[" + hash.substr(1) + "]";
                var $el = $(sel);                
                $("html").scrollTop($el.offset().top - 100); 
                return false;
            }
        });
```

Nice! That solves this problem in a hacky sort of way for the preview and also for copied files.

**Comment by jmclain** [comment]
Bravo! Of course browser history is not updated :-)
