### ISSUE TITLE
Download MarkdownMonsterSetup.exe will have Anti-Virus alert !

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#26]
Hi

I download MarkdownMonsterSetup.exe,
but **Anti-Virus** software will alert me.

http://imgur.com/4kz624C

I use virustotal to scan again, then have 7 alert.
what's happen?

**Comment by RickStrahl** [comment]
It's a false positive. The code for everything is in this repository so you can see what is there.

I believe the issue is HUNSPELL.dll which is being flagged falsely. Doing a quick read it looks like there's been some hijacked versions of hunspell around that have had trojans in it, but the official library is widely used and certainly seems legit (from the official source).

https://hunspell.github.io/

So not sure what to do about this as it's a fairly vital component.

Anybody have any more information I wonder?

**Comment by kkbruce** [comment]
I have no idea.

I'm use Virustotal to re-scan version 0.49, 
from 7 down 4, is good news.
;-)

**Comment by RickStrahl** [comment]
I've switched to different installer software and now I see no AV hits.

Last analysis from v0.50:
https://www.virustotal.com/en/file/b06245e0f1b0bd4cbf51e901edc6771df27b7f927970899bd8d20c29ec4ddba1/analysis/

**Comment by kkbruce** [comment]
Nice job. (y)

**Comment by RickStrahl** [comment]
The exe and installer are now also signed so that might further help in the future.
