### ISSUE TITLE
Images with Spaces won't embed properly

### ISSUE THREAD

**Issue by tbleken** [RickStrahl/MarkdownMonster#265]
Images with spaces in their names does not show in the preview window for new, untitled documents. If I replace the spaces with %20 the images shows up.

**Comment by RickStrahl** [comment]
Images with spaces are not supported by Markdig as brought up in this thread on the Markdig Repo:

https://github.com/lunet-io/markdig/issues/167

Browsers do support images with spaces in them without urlencoding, but since Markdig (following CommonMark specs) won't render it with spaces the point is moot. 

Fix is needed to add the space encoding when images are saved and embedded.

**Comment by tbleken** [comment]
A workaround, at least for me, would be that MM asked for a file name when I select Open From Html. Default should be the same name but with md as extension. Pressing Escape could mean no name, showing up as Untitled.

**Comment by RickStrahl** [comment]
Fixed b3ef6b36946cee57d74edf109ed8e1c9ac361255

**Comment by tbleken** [comment]
Please forgive my ignorance, but how can I implement this fix?

**Comment by RickStrahl** [comment]
It'll be updated in the next update.

Otherwise you have to build the code yourself.
