### ISSUE TITLE
Coloring Bug in Editor 

### ISSUE THREAD

**Issue by Andis59** [RickStrahl/MarkdownMonster#285]
I have found an annoying bug in the coloring of text in the Editor.

# Coloring bug
An annoying coloring bug occurs when using characters outside of ASCII in text within <- -> or <. .> or <_ _>

I don't know what the <- -> (or its variants) are used for, but the miscoloring is annoying! I noticed it when I was using <---- as an arrow and the rest of the text was colored red, except for the Swedish letters ÅÄÖ åäö ->

The bug only occurs in the Markdown window.

I'm using Windows 10, Markdown Monster 1.8.4, Light Application Theme, VisualStudio Editor Theme and Github Preview rendering Theme

I attached a sample file that visualize the bug.
NB! github will not let me upload a file with the extention .md so I changed it to .txt

[Coloring bug.txt](https://github.com/RickStrahl/MarkdownMonster/files/1578481/Coloring.bug.txt)

**Comment by RickStrahl** [comment]
Markdown supports HTML tags and anything that starts with a `<` is colored as an HTML element in the editor - because of the way HTML allows any characters as content anything inside is treated as tag text.  

But even so I don't see what you're describing in the message above. Here's what I see with default theming enabled:

![image](https://user-images.githubusercontent.com/1374013/34276175-53df9f0a-e644-11e7-8204-3a303d2fad0f.png)


That all looks reasonable to me.

**Comment by Andis59** [comment]
OK, Depending on the Editor Theme the coloring will be "bad" or "good"...
I will try and see if I find one that I can live with!

Is there someway to know what css class (guessing here) is used for the coloring of HTML elements?

**Comment by RickStrahl** [comment]
I'm using Twilight in the above which is one that I've tweaked a bit to be optimal. 

Easiest way to see tags used is render the document then open in external browser like Chrome and use the F12 developer tools to see the tags that are applied then customize.

**Comment by RickStrahl** [comment]
I'm going to close this since there's no real actionable task here. I agree that this isn't optimal, but after spending some time in the markdown renderer and seeing this logic buried in the HTML renderer I'm not going to try mess with this because for the most part this is an edge case.

Feel free to re-open this issue if there's more information.
