### ISSUE TITLE
Change default code language

### ISSUE THREAD

**Issue by kkbruce** [RickStrahl/MarkdownMonster#289]
like img https://imgur.com/a/J5Gkg

Sometime write c# post, js post, diff language post, 
I need to change "code language" everyone by post in code area,
Have easy way to set **default code language** by post(or add to MarkdownMonster.json)?

**Comment by RickStrahl** [comment]
I added a default code language, that is synced to whatever your last language used was. So if you use the dailog and set to html it stays at html until you change it.

Tracking per post is a bit of a pain because MM knows nothing about a post as the Weblog component is an Add in.

d2394281e4808cd3a94035b6fc1283058099c9ed

and

05a36969fcc1368cda5d3398b3ab093f2e771066

**Comment by kkbruce** [comment]
💯

**Comment by RickStrahl** [comment]
It's live here now (pre-release):
https://west-wind.com/files/MarkdownMonsterSetup_Latest.exe
