### ISSUE TITLE
Please consider enhancing file tabs

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#304]
If I work with many .md files open I can't see or jump easily to the one I may need. Presently I need to click on the arrows to cycle through the files.

Please allow the following configs:

1. positioning tabs onto two rows (or more than two, my monitor will fit)
2. position tabs stacked (vertically on the right)
3. make the tab width shrinkable (long file name/paths take the whole real estate) thereby hiding the others

Lastly, it looks like **MM** does not remember last used/open files between upgrades.

**Comment by RickStrahl** [comment]
There will most definitely **not** be any tab stacking in any way. Woe those horrible interfaces... :-)

But I did add the abillity to more easily see all the files that are open with a drop down instead of the scroller at the end of the tabbar.

Here's what this looks like:

![image](https://user-images.githubusercontent.com/1374013/34902182-5b189100-f7ba-11e7-8af0-b4a9f1b62a63.png)

You can also cycle through tabs with Ctrl-tab and Shift-Ctrl-Tab.

**Comment by ArthurZ** [comment]
That's exactly indeed what I referred to, but was not eloquent enough to express it.
However, to what version was it added? I am on the latest right now 1.8.4 and it does not show up:
![image](https://user-images.githubusercontent.com/701808/34902346-aaa61698-f7e7-11e7-805c-31dc19ec0e3a.png)

**Comment by RickStrahl** [comment]
I just added it. You can download **Latest** from the download page to get these changes.

**Comment by ArthurZ** [comment]
This is five * service.
But what is the URL to the 

> Latest

**Comment by ArthurZ** [comment]
Got it from https://west-wind.com/files/MarkdownMonsterSetup_Latest.exe

**Comment by ArthurZ** [comment]
Thank you this is awesome!

**Comment by RickStrahl** [comment]
Also added: Window menu to show open windows and manage open documents:

![image](https://user-images.githubusercontent.com/1374013/34903758-861a93c2-f7dc-11e7-96dc-9ec2b60dab35.png)

**Comment by ArthurZ** [comment]
Makes total sense, much appreciate you taking prompt care of these improvements.
