### ISSUE TITLE
End of Line changed somewhere between 1.9.4 and 1.9.10

### ISSUE THREAD

**Issue by Andis59** [RickStrahl/MarkdownMonster#332]
When I upgraded from 1.9.4 to 1.9.10 the adding TocGenerator stopped working!
The problem was that TocGenerator splits the text into lines using this code:

`string[] lines = markdown.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);`

 Environment.NewLine is **"\r\n"** but the text in 1.9.10 and above uses **\n** as end of line! Which leads to that the whole text is treated as one line and TocGenerator can't create a Table of Content.

The easy fix is to change the above line in TocGenerator, but a real solution must be to use  Environment.NewLine as End of Line in MarkdownMonster!

It used to be, so why has it changed?

**Comment by RickStrahl** [comment]
Yes we switched to /n line endings for the editor primarily because there are a boat load of places where line endings are checked and that code has become exceedingly erratic (the TOC editor being one of them).  Natively, the editor internally uses /n and converts on the way out which has other issues (such as when text is passed from selections and things. ACE supports different line ending modes and that switch is what changed and that's what is what's actually causing the problem with the addin.

I have to give this some more thought. There are other related issues with not using \r\n such as files opened in a base editor (like Notepad not being able to recognize the new lines).

**Comment by Andis59** [comment]
I can just add that Daniel Vaughan has updated the TocGenerator adding so it works now with the /n line endings!

**Comment by RickStrahl** [comment]
Oh crap :-) I moved back to CRLF because I can see that causing a bunch of other issues. Ideally the generator needs to work with either. But I just checked and I think it must be working with either as it works on my current build now.

**Comment by RickStrahl** [comment]
Going to close this since I moved back to CRLF/Windows format. If you get a chance please double check and re-open if you still have a problem.  1.9.14 and later have the change.
