### ISSUE TITLE
Skipping cursor in v1.9.12

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#334]
## Description
Since upgrading to v1.9.12 (and also on a clean installation), I've noticed a behavior that's causing serious problems with using MM. When at the end of the document, the cursor will skip to the top of the editor window.

## Steps to Reproduce
1. Install MM
2. Open, the SampleMarkdown will display
3. Ensure editor window does _not_ display the entire document.
4. CTRL-HOME to ensure cursor is at top of page
5. CTRL-END briefly sends the cursor to the document bottom, then the cursor goes to the top of the editor window.

## More Information
This probably relates to the new behavior that the cursor moves when scrolling. *This is an unconventional and, I believe, incorrect behavior*. In other text editors and word processors, scrolling leaves the cursor where it is. Page-Down/Up moves the cursor.

I don't know the reproduction steps for when I'm typing, but this happens so frequently I'm going to have to revert to a previous version, as I don't have time right now to dig into the code (sorry). 

Thanks, Rick. I hope it's not some breaking change with the underlying text engine.

**EDIT**  

I see that the cursor tracks scrolling at least back to version 1.9.4, which I just compiled and am using. However, the bugs I've reported don't occur. (I still believe that tying cursor to scrolling is an incorrect and unexpected behavior.)

**Comment by RickStrahl** [comment]
Yes this is a nasty side effect of the fact that ACE doesn't allow mapping the mouse to a row/line pair **without a selection**. So right now in order to do this I have to select the line to get the appropriate position to sync the preview (and now the document outline) to.

However, in the recent work done I found another way to capture the visible viewport and I think I might be able to work with that. That'll require some changes to the way the preview sync works as I have to pass in the line number. I'll noodle with this. 

If this works I think it'll address both of the points you raise here (cursor position that's tracking and jumpiness at the end of the doc).

**Comment by bladewolf55** [comment]
Thanks, Rick. It's no fun working around these kinds of unexpected
behaviors. I don't imagine the ACE developers imagined people wanting to
sync browser output to their text editor!


--
Charles L Flatt
513-535-0764 (m)

"I believe in those whom I love and trust. All else is foolishness."
--Roland, The Book of Lost Things

**Comment by RickStrahl** [comment]
Ok so I think this is going to work. 

* I've hooked the browser sync to the active view port so the top of the view port determines the syncing. 

* The Selection is no longer changed - it stays fixed where ever it was (Yay!)

* Top and bottom jumping or scrolling seems to work without any jumpiness

The fix is here: 7e0cd6aacb9ebe3e77e78b14183996429161832d

**Comment by bladewolf55** [comment]
Wow, rocking! I'll test tomorrow (Colorado time).


--
Charles L Flatt
513-535-0764 (m)

"I believe in those whom I love and trust. All else is foolishness."
--Roland, The Book of Lost Things

**Comment by RickStrahl** [comment]
Looks like this is fixed, right?

**Comment by bladewolf55** [comment]
Yes. With the recent changes, the app feels much smoother.


--
Charles L Flatt
513-535-0764 (m)

"I believe in those whom I love and trust. All else is foolishness."
--Roland, The Book of Lost Things
