### ISSUE TITLE
The new TOC creator and Save to PDF

### ISSUE THREAD

**Issue by Andis59** [RickStrahl/MarkdownMonster#342]
The new document outline is really nice! So also the _Generate document outline into Markdown document at cursor position_

There is one thing that you need to document (I have not found it documented) and that is when you use this new function and use _Save as PDF_ then you need to change the Theme.html for the theme you are using. You have to remove this line

`<base href="{$docPath}" />`

Otherwise the links in the PDF will point to a file:///<path to the .md file/#headerID> and that will not work....

Thanks for all the work you put into this excellent program!

// Anders

**Comment by RickStrahl** [comment]
Hmmm... I think this is fixed in 1.9.18. If you're running an earlier version can you please retry?

I added the  `--enable-internal-links`  and `--keep-relative-links` flags to the command line that processes the PDF generation which should respect the internal links - it works for me here.

After generation click on Copy Command Line and paste that here and see if those parameters are in the command line. If not try pasting that line into a command window and running from there with those flags added.

**Comment by RickStrahl** [comment]
Ok so I took another look and I do now see the behavior you describe. I was using a custom template and additional logic that removes the Base tag.

I added a fix to render the file into the same folder as the source file and then removing the Base tag from the template and that seems to work.

a1a0bfb472796178c5709d26a7bb7b77ab134779

**Comment by Andis59** [comment]
Works perfectly!
Thank you very much!
