### ISSUE TITLE
Spell Checker - Wishlist

### ISSUE THREAD

**Issue by anders-eriksson** [RickStrahl/MarkdownMonster#358]
My wish list for the Spell Checker.

1. Change Language for the selected words/sentences/paragraphs. This would mean that I can have the document default in one language (Swedish) and part of it, e.g. quotes, in another (English).

2. Make None a language. So I can select a part of the text and set language to None and no spell checking is done. I use MM for creating documentation for my program and it will contain C# named words, e.g. ThisIsMySpecialProperty.

**Comment by RickStrahl** [comment]
Hey @anders-eriksson,

Not to sound dismissive, but:

I don't think this is going to happen at least not from my end :-)

It seems like this would be used by almost nobody because it's not what I would consider expected behavior. If you have to explicitly select text, then switch to a different different language on a block of highlighted text would you really expect to see spelling highlights on a highlighted block of text? That seems unintuitive and also probably visually difficult to discern (depending on the editor theme I suppose).

Not to mention very difficult to manage the different text sections and keeping straight what's managed by what language.

On a side note, I deal with lots of code documentation as well, so I can relate to having things highlighted as errors that really aren't, but that's kind of expected in any text editor you use. If you write an article in Word you wouldn't expect to have it ignore non-language keywords either :-)

What I do that helps with getting too much error overload is to explicitly add custom/code words I use into the custom dictionary using **Add to Dictionary** on the context menu, which helps a lot with the error clutter.

**Comment by anders-eriksson** [comment]
Well, this is how it's done in Word, or any other word processing software. You can select a word or paragraph and specify which language it has. The document has a default language, but you can enter other languages and set the language for the spell checker.

I Word *None* is a valid "language" which tells the spell checker not to check this word or paragraph.

But this might be an edge wish, so ...

Thank you very much for a splendid program!
