### ISSUE TITLE
Toggle Spellchecking

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#359]
The toggle off the spell checker is not working.

Also is there a way to not check code blocks?

**Comment by RickStrahl** [comment]
Hmmm.... can't duplicate the toggle. Works for me. Note that you **single** click to toggle. The highlighting of the toggle is a bit subtle, but it seems to work jsut fine.

**Fenced** code blocks shouldn't be spell checked. Indented code blocks however will be.

**Comment by RickStrahl** [comment]
Image is not shown.

Don't know it works for me - you're using the check in the right Window box to toggle, right? What version?

+++ Rick ---

**Comment by HowardEdidin** [comment]
Version 1.10.16

**Comment by HowardEdidin** [comment]
![spell](https://user-images.githubusercontent.com/19954905/39654857-6b6452b0-4fbc-11e8-9e33-9b3738e43313.png)

The code block shows spelling errors

**Comment by RickStrahl** [comment]
Ah yes... that's because the code spans the entire screen and probably a bunch more above. MM doesn't spellcheck the entire document all at once so it takes the screen plus some padding before and after and if the code block doesn't start in that area it doesn't recognize it as a code block. 

Smaller code blocks will not show highlighting.

There's a trade off here - we're doing this for performance trying to keep the spell check area small - the larger it is the slower the editor ultimately becomes so I'm going to call this an edge case and say this particular scenarios isn't going to get fixed. 

Most code blocks hopefully won't be excessively long.

**Comment by RickStrahl** [comment]
I've bumped the number of lines before the first screen row to 50 - so if there's less than 50 lines of code before the top of the screen, you shouldn't see code syntax checked. More than 50 lines **before the top** and it will end up highlighted.
