### ISSUE TITLE
ER - Embed CSS styles into exported HTML

### ISSUE THREAD

**Issue by paulmrozowski** [RickStrahl/MarkdownMonster#368]
It would be nice if the HTML export embedded the standard CSS stylesheet used by the document into the HTML file. The standard export w/o styling is pretty ugly.

**Comment by RickStrahl** [comment]
The export is a raw export of the HTML text generated.

If you want a high fidelity print of the document with all related resources I recommend you do:

* Go to the Preview Window
* **Right Click -> Show In External Browser**
* Save As... save with related resources

This works in most browsers to export a folder with the raw document plus all resources stored locally.

Putting that functionality directly into MM is on the ToDo list but not high priority since you can do it easily within a browser.

**Comment by RickStrahl** [comment]
Added to latest build:

![image](https://user-images.githubusercontent.com/1374013/40356731-d3fdcf12-5d6e-11e8-8a3a-2a23ec7c793a.png)

You can get it with **Latest Build** from the download page...

**Comment by paulmrozowski** [comment]
That works great. Yeah, this was mostly so I end up with just 1 file.  No/very minimal images in most cases. I see that Font Awesome gets embedded which is also nice. Thanks.
