### ISSUE TITLE
Upon startup on first install, Script Error: "0" is null or not an object

### ISSUE THREAD

**Issue by tomzx** [RickStrahl/MarkdownMonster#37]
I downloaded v1.0 from https://markdownmonster.west-wind.com/download.aspx and started it up. This is the first thing I see.

![markdownmonster_2016-11-04_10-00-53](https://cloud.githubusercontent.com/assets/188960/20008118/aae022b6-a275-11e6-9df8-fa607d4eb6f5.png)

Furthermore, if I select yes/no, it keeps displaying this same error over and over. I had to force quit the application to close it. At this point the application cannot be used since if I restart it, I face the same issue.

**Comment by RickStrahl** [comment]
Hmmm... that's odd. It looks like this might be a IE browser issue.

Can you try a couple of things for me?

* Turn off Spell checking in the Title bar (the check mark toggle) 
then close and reopen the preview (World icon)

I wonder if this problem is caused by some IE  setting or not properly getting the right version. What version of IE is installed on your machine? 

The failure is on a **range** selection which makes me think the browser is running in a non-HTML5 mode for you and the browser mode setting might be failing. MM sets the browser into IE 11 mode during installation and I wonder if you don't have IE11 installed it might revert to IE old. IE11 is a requirement, but it should actually work with IE 10.

Can you check and see if you have the following in the registry:

![image](https://cloud.githubusercontent.com/assets/1374013/20020068/6767c00e-a273-11e6-92fe-7ec428ffb39b.png)

The key would be set to **11001** by default. If you have IE 10 try changing it to **10001** - that might help.

**Comment by tomzx** [comment]
I do not use IE on this computer, but it is a Win7 SP1 machine (with the default IE8 that was left untouched).

![iexplore_2016-11-04_16-14-48](https://cloud.githubusercontent.com/assets/188960/20020894/e32fcdfe-a2a9-11e6-94a7-2c9514fcbef8.png)

**Comment by RickStrahl** [comment]
Yeah that is the problem. Requirements call for IE 10/11. Windows 7 can install IE 11 (which is a good idea anyway as a number of applications use the WB control internally).
