### ISSUE TITLE
SUGGESTION: Show full path to active file in the title bar

### ISSUE THREAD

**Issue by BIOSMonkey** [RickStrahl/MarkdownMonster#371]
I use MM extensively to generate the help contents for large web applications.   These .md files exist in different "plugin" folders under /strings, but are all named the same thing :)

It would be helpful to be able to see the full path in the title bar at a glance rather than hovering over the tab.

I looked in the settings JSON file and didn't immediately see an option for this ... hope I didn't miss it.

**Comment by RickStrahl** [comment]
Sorry, but that's not going to happen. I understand what the issue is but we can't have long file paths on a tab even as an option.

The compromise MM has is showing the last folder path token when duplicate file names are open. Now in your case that doesn't work due to the fact your multi-document structure is identical, but full path names are way too long to display on a tab. You wouldn't be able to see even two tabs at the top and that's just not an option.

Hovering over to get the full filename is as good as this is going to get.

**Comment by RickStrahl** [comment]
Ok... added.

![image](https://user-images.githubusercontent.com/1374013/40139640-621f37fe-5905-11e8-98f9-07c2302f6262.png)

**Comment by BIOSMonkey** [comment]
Awesome - thank you Rick!

Has the portable zip download been updated? Looks like its still 1.10.23.

FYI I tried installing the latest pre-release and that one is even older (1.9.13.5)

**Comment by BIOSMonkey** [comment]
What version will this be in?

**Comment by RickStrahl** [comment]
Whatever the next release is. 1.11 released just before this went in.
Anything post 1.11.

+++ Rick ---

--

+++ Rick ---

Rick Strahl
West Wind Technologies
Making Waves on the Web

weblog.west-wind.com
markdownmonster.west-wind.com

**Comment by BIOSMonkey** [comment]
OK thanks, I wasn't sure and just wanted to make sure I wasn't doing something wrong

**Comment by RickStrahl** [comment]
Don't worry update releases come fast :-)

--

+++ Rick ---

Rick Strahl
West Wind Technologies
Making Waves on the Web

weblog.west-wind.com
markdownmonster.west-wind.com

**Comment by RickStrahl** [comment]
The preview release is up on the download site. (Latest).

**Comment by BIOSMonkey** [comment]
Installed and verified.   Thanks again.  This small change is really helpful when I have ten tabs open all with the same "helpContents-EN.md".
