### ISSUE TITLE
SUGGESTION: Batch processing for open files

### ISSUE THREAD

**Issue by BIOSMonkey** [RickStrahl/MarkdownMonster#373]
This suggestion might be a little specific to my need, but maybe as a food-for-thought kind of thing....

I use MM to generate the help contents for large web applications. These .md files exist in different "plugin" folders under /strings, and there are quite a lot of them.

Ultimately, for production, these .md files are saved as HTML (same name, same folder, just as HTML) for contextual help content.   It would be nice to be able to perform this action as a batch on all open files (and would work nicely with the other suggestion for Project support).

Obviously, others might want to save as pdf but I am sure the batch process would be helpful here too.   In this case it would also be nice to have an option to concatenate pdf output to a single pdf as well (I do this when giving ALL the help to QA).

**Comment by RickStrahl** [comment]
Yeah that is very specific and really you're looking for a documentation tool rather than an editor.

We're working on a documentation solution that will integrate with Markdown Monster (KavaDocs) but it's not quite ready yet. It'll include support for projects that have a concept of files that are related to each other along with an index of topics. From that you will then be able to generate output like PDF or a static Web site.

But it's not ready - it's a side project for MarkusEgger and myself and the core is working but the tooling is very rough at the moment.
