### ISSUE TITLE
Editor Preview Displays Cached Image

### ISSUE THREAD

**Issue by sportflier** [RickStrahl/MarkdownMonster#387]
MM 1.11.16

1. In MM, open an existing MD document with an embedded image (PNG)
2. In Windows Explorer, replace the image file with a different image file (same name)
3. In MM, editor pane, delete the embedded image
4. Insert the new image (same name) using the insert image toolbar button. Insert image dialog shows the new image. Click the button to embed the image.
5. MM preview pane still shows the old image

**Comment by RickStrahl** [comment]
Yes aware of that :-)

The problem is that it's a browser preview so the browser will cache images which generally is a good thing as it makes the preview fast when you're not updating images.

You can press F5/Ctrl-Shift-R in the preview to force a refresh of the page.

I'm making a couple of adjustments for the various image update mechanisms to EXPLICITLY force the browser to refresh which should help. It doesn't seem to work all the time but at least most of the time in the most common cases.

**Comment by RickStrahl** [comment]
This 62c7952e59240ff4502bce3a86814c67dae95142 should address most of the issues.
