### ISSUE TITLE
Convert .md links to .html links when saving as HTML

### ISSUE THREAD

**Issue by CatoAntonsen** [RickStrahl/MarkdownMonster#39]
Sometimes I need to make an html alternative to a set of documentation in .md format. I would be helpful if links to other .md documents are converted to .html so I don't have to do this manually.

**Comment by RickStrahl** [comment]
Not sure I understand what you're asking? You want to auto-convert any href links that are to .md files to html instead?

If so you can create a plug-in that does that, but I don't think that's a core feature that should be built-in?

**Comment by CatoAntonsen** [comment]
I guess the reason you would convert to HTML in the first place is that the "recipient" is unable to view .md files. If that's the reason, then it doesn't make sence to link from the converted html file to other .md files that the "recipient" is unable to read too... (?)

But yes, I agree it's probably not a core feature.

**Comment by RickStrahl** [comment]
I don't really understand your use case. Why would you link to an md file in your scenario? Just link to the HTML file then even if it doesn't exist?

The reason we couldn't do this as part of the core product is because there's no way to know the intent you have. In a lot of documentation systems it's perfectly fine to link to an .md file that is server rendered into HTML.

**Comment by CatoAntonsen** [comment]
The use case is that I have some documentation stored in VSTS maintained as multiple .MD formatted files. Technical personnel uses this version.

Occasionally I want to export these to a document library in SharePoint for a non-technical audience. It's not an option to set up a web server for this limited use.

But I agree with you that this is probably a bad solution anyway.
