### ISSUE TITLE
Feature Request: Update HTML preview more frequently

### ISSUE THREAD

**Issue by daughtkom** [RickStrahl/MarkdownMonster#4]
Something to consider for the backlog some day...

It seems that the preview only updates after hitting Enter.  If I delete or change a word or line of text, the preview does not reflect this until hitting Enter.

Suggest updating after each key press with a short throttle (~200ms), or perhaps triggering on some additional keys (arrows, backspace, delete, space bar, punctuation, etc.).

**Comment by RickStrahl** [comment]
Unfortunately refreshing on a timer is not a good option and 200ms would be way, way too much. I've tried it and even with a 2 second delay it's annoying.

The problem is that the WebBrowser control is not updating completely asynchronously (even when running the refresh off an async task) so it blocks the main UI thread very briefly and flashes a working cursor which is incredibly annoying if it happens too often.

I've experimented with a lot of stuff actually and currently I use any punctuation keys, enter and a few others and have a debounce operation on the refresh so that it's not triggered to rapid fire (I think the debounce is ~200ms).

More info here:
http://markdownmonster.west-wind.com/docs/_4ni0v22ad.htm#PreviewRefresh

What I'm trying to avoid is rapid refreshes so at this point I'm using keys that are triggered often but not constantly. Backspace and del would be ok too but they are often used.

Open to other ideas...

**Comment by daughtkom** [comment]
Makes sense.  I'll be honest that when I was trying to confirm this I didn't actually try punctuation.  That's my bad and I should have caught that.  

When I noticed, though, was when:
* I corrected a ~~tpyo~~ typo
* I deleted a paragraph
* I cut/pasted (moved) a paragraph.

In trying to think of things that would be triggered when someone does those things, but maybe not as frequently as I originally suggested, I thought of two possible events to handle:
* mouse click (in editor, menu or toolbar)
  * similar to arrow keys (which I am more likely to use personally), but probably less chatty and more deliberate
* CTRL key -- to catch CTRL+C, CTRL+X, CTRL+V, CTRL+S, etc.
  * alternately, intercept cut and paste specifically and leave copy/save (and everything else) as is

Just an idea...

**Comment by daughtkom** [comment]
Thanks.  Seems like a good compromise/start...

**Comment by RickStrahl** [comment]
So I've also added the Ctrl key so any Ctrl-<key> combo will refresh which should work to update it.And as a bonus you can press Ctrl any time to refresh if for some reason the update isn't quick enough.

**Comment by RickStrahl** [comment]
I've updated the download - you can Check for new Version and update that way.

**Comment by daughtkom** [comment]
Nice.  Thanks.

**Comment by ButchersBoy** [comment]
"Open to other ideas..."

How about using RX to subscribe to key presses, throttle them, and then refresh...normally works pretty well.  Something along these lines: http://kasperholdum.dk/2013/04/throttling-search-queries-on-textchanged-with-cancellation-support/

**Comment by RickStrahl** [comment]
The problem with RX is that the editor is JavaScript so it's crossing platform boundaries. I suppose I could use RX inside of the JS editor code (which is what actually triggers the updates), but there are other concerns.

As I mentioned above as well, the other problem is that the Web browser control blocks the main thread briefly (you can see the bloody work icon pop up briefly) even when you refresh asynchronously. I haven't found a way around this.

So updating on any sort of timer/non-triggered update is going to be a problem regardless of how long or short that timeout is and it's probably better to do the update on a few known triggers.

Give 0.28 a try - I think the Ctrl- trigger will catch a lot more things (ie.copy paste, undo etc.) as well as having an explicit key that can refresh (ctrl anytime).
