### ISSUE TITLE
File marked dirty on Ctrl+C copy

### ISSUE THREAD

**Issue by kfrancis** [RickStrahl/MarkdownMonster#40]
Why does the editor show files as unsaved (or that save is pending) when content in the saved/unedited file is copied?

**Comment by RickStrahl** [comment]
It's a bug - currently we're checking for keys pressed and that key combo is triggering the saved state update. There needs to be an additional check to compare against the original markdown before it was saved.

**Comment by RickStrahl** [comment]
I've changed the way the change tracking works by checking on keyup and comparing against original text. Initial code failed because the original text wasn't updating properly. Should work much better now.

632a9ad09f4ed8334568eb87eff1147d869281b6

Still testing behavior, but you can build from source to try out now. I'll update when I post a new release post 1.0.2

**Comment by RickStrahl** [comment]
Please check this out in 1.0.3.

**Comment by kfrancis** [comment]
That worked, thanks!
