### ISSUE TITLE
MM unusable with large files

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#400]
Independently from the long opening time, which is understandable, once the file is displayed, nothing can
be done, and MM can crash after some time. I tested with this popular document:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md

**Comment by RickStrahl** [comment]
Hmmm... yeah I can see that. The issue actually isn't the editor - it's the preview. If you turn the preview off the file can be edited fairly quickly.

The issue here is that the Web Browser control rendering the content is taking very long to render the document and ties up the main thread of the application. It's made worse by the doc synching that occurs. This is a limitation of the IE WebBrowser control in use - it blocks while rendering and there's no way that I've been able to find around this using this control.

I have a prototype addin that uses Chrome for rendering and that control (CefSharp) renders in the background so I suspect that should fare much better.

I'm not really sure why the load time is that slow in the browser honestly - the document is large, but not that large. I also tried turning of the doc syncing mode which should leave the browser just sitting once loaded but even with that I see really slow perf.

For now I don't have a good answer other than turning off the preview and doing external previews (alt-v-b) to see the content. That'll allow editing at least.

**Comment by pethopal** [comment]
(as I suppose you are using MarkDig for converting markdown to html...
If I am right, you could maybe consider using MarkDig.Extension.Wpf)

**Comment by RickStrahl** [comment]
While that may fix the speed problem, it causes some other issues - there's all sorts of additional processing happening and I want to allow for user customization with simple HTML.

It's a solvable problem, and something that is already on my radar (not for perf but for IE deprecation) so the browser will have to be switched out. I'm waiting to see what will happen with the WebView once that's a little further along which may solve some of these issues. Both CefSharp and WebView do async rendering so they don't tie up the UI thread which may solve these issues.

I'm going to close this for now. May reopen when the time comes to look at the new browser engines.

**Comment by RickStrahl** [comment]
There have been some improvements in recent versions (1.20.3+) related to how the preview refresh works that improve the performance of very large documents. 

The document in question above now works reasonably well for intial load and for document navigation. Editing is also improved as the preview is not refreshed frequently with large documents. 

However, when an actual refresh occurs - it is slow because of the size of the document is simply time consuming and while the refresh of this massive document occurs for 1-2 seconds the editor won't respond.

The ultimate solution as before is to hide the preview or disable automatic preview refresh and only explicitly refresh the preview when ready. Without refresh document editing of this massive document is quite decent.

**Comment by RickStrahl** [comment]
So with a number of recent updates and enabling the Chromium addin it looks like it's now possible to use Markdown Monster with much larger documents more comfortably. The changes above help, but even more so using the Chromium addin which renders on a separate UI thread, doesn't interfere with editor operation while the preview is being updated. 

This means you now get decent editor performance even for this massive document.

Caveats: Preview refreshes on large documents are delayed quite a bit to avoid recursive refresh operations.
