### ISSUE TITLE
Could the caret be a little bit wider?

### ISSUE THREAD

**Issue by hwkmueller** [RickStrahl/MarkdownMonster#402]
Is it possible to make the caret in the main editor a little bit wider, maybe 3 or 4 pixel, like that in the searchbox? I'm on a highresolution screen ...

**Comment by RickStrahl** [comment]
The caret is controlled via CSS and you can customize that but it's a bit sketchy because the CSS gets replaced on updates. 

In editor.css you can do:

```css
.ace_cursor { 
    border-left: 4px solid !important;
}
```

to effect the cursor.

I think what we probably need to make this more palatable is an extension like `editor-user.css` that can get loaded if it exists.

**Comment by hwkmueller** [comment]
Ah, yes, thank you. For the meantime the standard-css will do.

Am 7. Juli 2018 19:13:39 schrieb Rick Strahl <notifications@github.com>:

**Comment by RickStrahl** [comment]
So I added support for  the `editor-user.css` file that is not installed and which won't be updated, so you can add customizations to the editor styling including the above cursor tweak.

**Comment by hwkmueller** [comment]
Works fine, thank you

2018-07-07 20:19 GMT+02:00 Rick Strahl <notifications@github.com>:
