### ISSUE TITLE
Please add a "Save All" option

### ISSUE THREAD

**Issue by skleanthous** [RickStrahl/MarkdownMonster#409]
Very often I find myself with mutliple open md files and I want to save them all. _Ideally_ I would like to be able to re-map that to Ctrl+Shift+s. I don't need `Save as` to have a shortcut, but I find myself needing a "save all" very frequently.

**Comment by skleanthous** [comment]
Hey @RickStrahl,

Thanks for the quick turnaround! Is there any configuration to re-map these keys?

In any case, feel free to close this issue, my main problem got solved. Thank you.

**Comment by RickStrahl** [comment]
Key remapping is on the wish list, but unfortunately this is not so easy to handle because key mappings are necessarily made in multiple places (in the WPF app interface and in the editor's JS interface). I have some ideas but it'll require some fairly major reworking of the JS handling especially since some functionality it handled in JS code.

Anyway closing this.

**Comment by RickStrahl** [comment]
Key remapping will be part of 1.12.10 and later version so you should be able to remap `Ctrl-Shift-S` to **Save All**. 

See #139 for more info on what that looks like.
