### ISSUE TITLE
Multiple Keybindings for Same Command Are Replaced on Open

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#412]
If a command, such as CloseActiveDocument, has multiple keybindings, the bindings are not preserved when MM is opened.

## Steps to Reproduce
1.   Perform clean MM installation, and launch (so that Roaming profile folder is created)
2.   Open MarkdownMonster-KeyBindings.json. Note bindings for CloseActiveDocument and ReloadEditor.

![keybindings on clean install first open](https://user-images.githubusercontent.com/2903411/43967342-64413432-9c81-11e8-8780-40ddab8aa9cf.png)

3.   Close MM
4.   Open MM. Keybindings have changed

![keybindings on clean install second open](https://user-images.githubusercontent.com/2903411/43967424-9690d348-9c81-11e8-912c-af39e98bbe0e.png)

## Support!
I'm pretty excited about being able to change keybindings, since I'd really like to use CTRL-W for toggling word wrap, and ultimately F12 for toggling the preview window. But I understand this is a challenging feature, considering how you have to integrate with the ACE editor.

**Comment by RickStrahl** [comment]
FWIW, I've added a shortcut mapping for `TogglePreviewBrowser` that's mapped to F12 by default.

Wordwrap is mapped to `alt-z` by default which is the same as Visual Studio/VS Code. You should be able to change that.

I'll see what's happening with the double mapping.

**Comment by bladewolf55** [comment]
Thanks, Rick. The problem in my use case is that even if I change WordWrap
to CTRL-W (the default for Notepad, after MS finally assigned a shortcut,
so maybe I need to rethink my standard!), MM will, upon restart, change
CloseWindow back to CTRL-W. So, my change can't work.

I agree, VS Code's default is ALT-Z. However, Visual Studio's default is
CTRL-E,W, at least when using the default C# mappings. (I set the same
keymappings in VS Code using the plugin, same result.)

[image: image.png]

Now I'm curious what other editors use for WordWrap's shortcut!

**Comment by RickStrahl** [comment]
Yes the multiple key mappings issue is a bug. The problem is that I'm looking up the command in the collection and it always finds the same one and overwrites that one. The result is that there's only one mapping. I'm going to need a unique key in the collection to identify each item for this to work properly and that key will have to be exposed in the saved config file (even though it shouldn't be changed).

Once that fixed any re-mapping to dupe keys should work. 

For now the solution for you is to set the keymapping for **CloseWindow** to something else, then remap the **WordWrap** command to `Ctrl-W`. It's a pain but that should work as a temporary workaround.

I'll get the multi-bindings fixed but I have to play around to see what works for ids. Probably just incremental numeric ids or a short random string of a few characters. I won't get to this until later in the week probably.

**Comment by bladewolf55** [comment]
Thanks, Rick. Mapping WordWrap is definitely not urgent for me, but the bug
may be affecting others. Your workaround is what I did, and doesn't work
exactly because CloseWindow gets reset to CTRL-W. I didn't try changing
both CloseWindow entries, but, again, it's just not that urgent for me.

I appreciate your efforts. A client of mine said he's installing MM because
of how I've used it in meetings.

**Comment by RickStrahl** [comment]
I think the following fixes should address this issue. 135bf65b5dcee32da2430efa5c0621594aee2ea0

This fix:

* Adds an Id to the each command
* Ids default to the command name
* If there are multiple mappings to the same command a custom `Id` can be assigned

With this in place I can now map `ctrl-w` to WordWrap. To do this:

* Edit `MarkdownMonster-KeyBindings.json`
* Set WordWrap to `ctrl-w`
* Set CloseDocument's `ctrl-w` to `null`
* Save `MarkdownMonster-KeyBindings.json` 

You may have to nuke your existing `MarkdownMonster-KeyBindings.json` file to get the ids in there correctly.

**Comment by bladewolf55** [comment]
That takes care of my request. Thanks, Rick!

--
Charles L Flatt
513-535-0764 (m)
"Home is not a place. It is living among those who love and honor you."
--M'yrnn J'onzz, from Supergirl
