### ISSUE TITLE
MM doesn't remember that Favorites were visible on startup

### ISSUE THREAD

**Issue by paulmrozowski** [RickStrahl/MarkdownMonster#413]
If I toggle on the Favorites view, then exit MM, then go back in, I kind of expected the Favorites to become visible again automatically.

**Comment by RickStrahl** [comment]
Yes that's kind of by design to minimize clutter and startup speed. First view brings up the favorites tab and then it's around from then on but until then it's not visible unless you click the toolbar icon or add a new one from the Folder Browser or Tab menu.

Some work has to be done with the way the tab view is handled soon as it's slowing down the load time of MM - there are a few issues there as the components are loaded onto the tabs. Once that gets addressed I probably change the way the tabs are loaded by lazy loading. But at the moment that doesn't work yet.
