### ISSUE TITLE
Save as HTML action defaults to single file, won't remember my setting

### ISSUE THREAD

**Issue by BIOSMonkey** [RickStrahl/MarkdownMonster#427]
I use MM to create html help files, and as such I export to raw HTML.

1) Using 1.12.12 I found that the dialog is defaulting to a large single file.   It didn't do this before.   Even worse, it doesn't remember my setting and I have to change it back every single time  - even when saving the same file again!

Is there a settings config key to set the default save as HTML form as raw?

2) After saving the raw file, Explorer is popping open the folder location ... ?

**Comment by RickStrahl** [comment]
1. Well there are choices now on how you want to save the file - so yes that involves making a selection. I agree though that the first choice probably should be the raw HTML output, with the other options a selectable option rather than the other way around. Remembering the setting? Maybe - if others ask for it but this seems to me like an edge case.  

2. That's pretty much expected behavior when you create a new file that you open it or show it in explorer so it may be opened.

If you want something more custom (ie. generate output and display it
