### ISSUE TITLE
Automatic Document Outline indents inappropriately

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#445]
Start with this:

    # One
    # Two 
    # Three

Then insert a generated document outline. Doing so results in this:

    
    * [One](#one)
    * [Two](#two)
    * [Three](#three)
    

And this is good, because the result looks essentially like you'd expect in the preview window.

However, if you start with this instead:

    ## One
    ## Two 
    ## Three

&hellip; then the generated document outline is indented like this:

    
    	* [One](#one)
    	* [Two](#two)
    	* [Three](#three)
    

This is not particularly ideal, because that indenting style results in the preview window as if it were preformatted code, and doesn't look like an outline the way you'd expect.

I don't always want to use H1's (that is, headings with single #'s), since the size of an H1 in the preview window is sometimes overpowering. It would be ideal if the outline generator recognized the case where H2's don't live beneath parent H1's, meaning in other words that H2's are the top-level heading style, and in that case, MM shouldn't assume that those H2's should be indented in the generated outline.

**Comment by RickStrahl** [comment]
Hmmm... yes. I recently change this behavior to properly reflect the indentation level which previously was expecting just relative paths. That turned out the be a bad idea, so the new way just uses the header level as the indentation size.

Should be able to fix this though by looking what the lowest indentation level is and if it's 2 we should start level 2 as the base line.

**Comment by RickStrahl** [comment]
Fixed: ce8b6d5430e30c7404caf5c7c1a142c0f4ab8cf0
