### ISSUE TITLE
Mermaid diagram rendering not correct in preview

### ISSUE THREAD

**Issue by bently0602** [RickStrahl/MarkdownMonster#451]
Mermaid diagrams do not preview render correctly. If I had guess it would be because of IE 11 issues with the embedded mode. Opening in external browser like Chrome works correctly.

This markdown snippet:

![capture](https://user-images.githubusercontent.com/2075170/46482840-fcddb480-c7bb-11e8-819b-1e05e9934d3f.PNG)

Renders like this in preview mode:
![capture2](https://user-images.githubusercontent.com/2075170/46482866-0c5cfd80-c7bc-11e8-98af-55ab7462bba3.PNG)

Also some text on the arrows do not render:
![capture3](https://user-images.githubusercontent.com/2075170/46483038-6067e200-c7bc-11e8-9ba6-948bf5f94c4d.PNG)

**Comment by RickStrahl** [comment]
Yes IE 11 unfortunately doesn't support Mermaid properly. The only way to properly preview at the moment is to use an external browser view (alt-v-b).

In the not to distant future I'm going to switch off the WebBrowser control and switch either to CefSharp or integrating the WebView control, both are currently adding features that will make things a bit easier that I'm waiting for.

I have a Chromium Preview add-in, but it's very  rough and requires some manual setup. It works but it's but not complete. If you're really despearte you can play around with that.

Closing this issue since it's well known and on the list to be addressed with a new browser engine in the future.
