### ISSUE TITLE
Save doesn't work

### ISSUE THREAD

**Issue by KenAGreen** [RickStrahl/MarkdownMonster#454]
I lost data twice (I'm a slow learner) in MM as neither Ctrl-S, Save or the Save icon work even though I bought but hadn't yet received the registration code. If this is because of the unregistered version, I think I should have received a warning notice. Continued Save As finally worked.
Now that I've loaded my registration key, it seems to work OK.

**Comment by RickStrahl** [comment]
It's not because of the registration code. The registered behavior does not affect how the program saves data...

You can always tell the status of the document when there's a `*` next to the filename which means the document has changes that haven't been saved. If you press Ctrl-S and the * sticks around then the document has not been saved. This shouldn't happen though, so if you are seeing this that's a bug, although I'm not sure what since that's working for me and most other people - otherwise I'd get a lot more complaints :-)

Ctrl-s should always work as do any of the other commands (they are all tied to the same operation). If you have not saved the document before (ie. Untitled) then the Save operation should prompt you to save.

So if that's not working, please provide  a repro to the exact steps that are not working and then I can take a look. 

FWIW there were problems with this a long while back (~1.0 release) , so just to be sure make sure you have a recent version (1.13+).

ps. you should have also gotten your registration code earlier today...

**Comment by KenAGreen** [comment]
Aw nuts, I can't reproduce it any more. The only oddity I've found is 
that if I make a change to a doc, the tab correctly shows an asterisk 
but the Save icon is still disabled. However, clicking it enables the 
icon and clicking it again actually does the save. File | Save works as 
it's supposed to.

Thanks,
Ken


------ Original Message ------

**Comment by RickStrahl** [comment]
So I took a closer look at the save operation and I see there is a minor bug in the UI bits, but saving always seems to work for me.

* The Save Toolbar Option doesn't always show as enabled after an edit
* It seems to take multiple changed characters for the Save button to not be disabled

This is a databinding issue and I'll look into it. The menu should always work because it refreshes the list when its activated.

So that leaves the issue you mentioned where saving wasn't actually saving which honestly I can't duplicate unless you can give me a better use case to duplicate. 

Note too that there are options for auto-saving as you type and creating backup files. Backups always are created in case MM crashes and when you re-open your original document the save file is show with it side by side.

More info in this topic:

* [ Auto-Save and Auto-Backup of Topics](https://markdownmonster.west-wind.com/docs/_4sv0nob04.htm)

If you find more info on when saving doesn't work I definitely want to hear about it, but as it stands I can't duplicate that behavior.
