### ISSUE TITLE
Scrolling Editor <-> Preview

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#456]
Scrolling Editor to Preview, and Preview to Editor work file.
But the mode "Editor and Preview" has an annoying problem.
Let's say I scroll the preview (with the scroll bar of the preview), then the editor scrolls too. But there is some kind of "feedback" taking place: the new editor's scrolled position "tries" to modify the preview position I am acting on. The result is that sometimes it's just impossible to scroll and stop where I would like.
This is not a new issue, but this starts to get on my nerves :(

**Comment by RickStrahl** [comment]
It's a known issue but unfortunately I've not been able to resolve this - two way scrolling necessarily has some recursiveness to it. It works in most scenarios but there are a few cases (top of the doc) and large single block elements (large images or code blocks) that can cause quite a bit of jumpiness.

The problem is there's no way to tell in the browser whether a scroll action was initiated by the editor or by the user. There are some mitigations in there with a timer flag but it just doesn't work all the time.

My recommendation: use editor to preview syncing and scroll the editor to move through the document.

I'll take another look to review but I'm pretty sure I exhausted what I could do about this.

**Comment by RickStrahl** [comment]
Ok so took another look at this and there are definitely a few optimizations I was able to make. It looks like this is working much better now - the jumpiness is gone (except for large blocks that fill the entire page since the editor and preview can't figure out what to sync to in those cases).

eaf12e83851163c6bf7db51b62b3893a5e790677

I've updated the latest pre-release build if you want to check it out before the next update.
