### ISSUE TITLE
An Enhancements Request: Export to PDF, Insert Table, Synchronized Scrolling

### ISSUE THREAD

**Issue by ArthurZ** [RickStrahl/MarkdownMonster#46]
Enhancements Request: 

1. An ability to export to PDF;
2. An Insert Table Wizard a-la [http://www.tablesgenerator.com/markdown_tables](http://www.tablesgenerator.com/markdown_tables);
3. Synchronized Scrolling between the code and preview pane.

Thank You!

**Comment by RickStrahl** [comment]
Please post feature requests or bugs one at a time. It doesn't make for a good discussion to have these bunched together.

1.  PDF
You can preview your HTML in your browser of choice and create a PDF from there. I don't think this is something that MM should handle. Markdown is meant to go to HTML and the last thing we want to do is support funky PDF rendering issues because the PDF doesn't render quite the same as the markdown text.   
Both Chrome and Firefox have built-in support for PDF creation via the Print option and save as PDF.

2. Table Wizard
Something to consider but not high in priority. If you really want this please repost as a separate topic.

3. Synced scrolling
We already have synced scrolling between code and preview: When you scroll in code the preview scrolls to sync. Not the other way though, but I'm also not sure that this is a good idea - it can be annoying to lose your current cursor location when you're looking through the preview text for proof reading or editing.  
The base syncing was introduced in 1.0.6 - if you have an older version you have to update.

**Comment by ArthurZ** [comment]
Thanks Rick,
Re .1 Too many hops to my liking, plus at work any other browser than IE is prohibited;
     .2 Will do
     .3 Does not work. Upgraded to 1.0.7 put in ```"SyncPreviewToEditor": true``` Have either vertical scroll bars not working in sync
