### ISSUE TITLE
Clicking twice on panel border doesn't resize it correctly

### ISSUE THREAD

**Issue by jonathanlinat** [RickStrahl/MarkdownMonster#461]
![2018-11-28_12-15-42](https://user-images.githubusercontent.com/14064112/49161314-5ddec000-f307-11e8-9d56-b59861d2fc43.gif)

Version 1.13.12, 32 bit, Windows 10, Unregistered

**Comment by RickStrahl** [comment]
I'm not sure exactly what you're referring to here...

I think you mean these steps (which are not quite right for me either):

* double click separator to zoom 
* then resize back to panel size
* then double click separator again

The last double click just resizes the panel to the old position, rather than the re-zooming.

Is that it?

**Comment by RickStrahl** [comment]
This should do the trick: ec293516041307651ac7abf9cad4efad0e7f21da

**Comment by jonathanlinat** [comment]
I was talking about something like in VSCode when you double click on panel separator, the panel is resized to its original size.

![2018-12-03_09-10-40](https://user-images.githubusercontent.com/14064112/49373030-5d657100-f6db-11e8-9243-07b8d3ed3cae.gif)

**Comment by RickStrahl** [comment]
Well that's not the behavior of the double click in MM. The double click zooms the preview, the second click should restore the previously saved position before zooming. 

That behavior won't change.
