### ISSUE TITLE
Focus stealing every file reload / 10 seconds

### ISSUE THREAD

**Issue by mwanchap** [RickStrahl/MarkdownMonster#476]
Every 10 seconds or so, MarkdownMonster appears to be re-reading open files (probably to check for updates), and whenever this happens it steals focus, which can make it pretty frustrating to have open while doing anything else.  Strangely, this behaviour still occurs even if no files are open.  I've been using MM for about 6 months now and this hasn't been an issue on other computers or previous installs on this computer, which is a real bummer because now I miss using it! Visual Studio's MD editing just isn't the same...

I've tried an uninstall/reinstall but the strange behaviour persists.  Any ideas or anything I can do to help investigate?

**Comment by RickStrahl** [comment]
Hmmm... can you give a repro scenario?

MM doesn't re-read files, but there's a file watcher on the folder browser folder that is open and its children  and it will scan for file changes. However, it doesn't notify you if a file changes nor does focus or show a dialog.

MM does have a changed file dialog but that should only show up if you navigate away from MM then come back and the file has changed on disk since you left (and the file is dirty - otherwise it will silently update it).

I'm not seeing this so a repro scenario would be good. Is it possible something else is making changes to the underlying file? AV software perhaps, but even then there's nothing that should cause app focus to change.

**Comment by mwanchap** [comment]
Almost certainly an issue on my end.  Now that I'm home from work, I can't repro on my other computer, and procmon shows me that the file-reading activity I was seeing is not the cause of the focus changing but is probably occurring _because_ of it as a side-effect (as you said, happens on window activation).  Must be something else that is messing around with the focused window...

Thanks for the quick response + suggestions, and apologies for the red herring. I'll have another crack at tracking down the culprit on Monday when I'm back at work.

**Comment by RickStrahl** [comment]
Going to close this for now. If you have more info and it turns out this is related to MM's handling feel free to reopen this issue.
