### ISSUE TITLE
Suggestion: Reorganize in Outline View

### ISSUE THREAD

**Issue by Randy-Buchholz** [RickStrahl/MarkdownMonster#481]
It would be nice to be able to drag-and-drop the order of text blocks in the outline view.

This could also incorporate some level features. Dropping a heading on another heading would make it a child (last). Dropping between children would move it there with the correct indent/heading level. Maybe hold shift to keep the current heading level. (Or something like that).

**Comment by RickStrahl** [comment]
Yeah that would be nice but that'll be pretty tricky to do, because you have to read through the document and figure out ending sections which can be tricky based on nested outline levels. Even what you describe is pretty ambiguous. Dropping on a heading would you drop it before, after or below?  Do you take just the section or all of its children with it etc.

IOW, interesting idea but I think problematic in terms of implementation and usability since this isn't a fixed structure.
