### ISSUE TITLE
Line spacing anomaly

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#487]
I'm going to admit up front that this is almost too minor to mention, but it bothers me just enough that I want to get it on the table.

If your document looks like this:

```text
    1. One
        a. Alpha 
        a. Beta
    1. Two
        a. Delta
        a. Gamma
```

then the rendering in the Preview window looks perfectly fine.

![image](https://user-images.githubusercontent.com/42981101/52811451-fa347b00-3049-11e9-9c60-959f62964e68.png)

If you then space the rows out, it also looks fine:

```text
    1. One

        a. Alpha 

        a. Beta

    1. Two

        a. Delta

        a. Gamma
```

![image](https://user-images.githubusercontent.com/42981101/52811418-e6891480-3049-11e9-83c8-dec7bf2d252d.png)

However, if you remove the `Beta` row, then the Preview window looks like the spacing is off:

```text
    1. One

        a. Alpha 

    1. Two

        a. Delta

        a. Gamma
```

![image](https://user-images.githubusercontent.com/42981101/52811017-e9373a00-3048-11e9-8406-86dfb1495bfb.png)

Do you see what I mean? It's not my imagination. There's a bit less space before the `Two` line now than there is after it.

![image](https://user-images.githubusercontent.com/42981101/52810990-d7ee2d80-3048-11e9-95e6-6233873c3ab7.png)

This is almost certainly a consequence of the Hipster Preview Theme that I'm using. It's less noticeable with other themes. I don't notice it at all with the Medium theme. I imagine I can see it with the Dharkan and Westwind themes, but it's certainly not as apparent with those themes.

**Comment by RickStrahl** [comment]
That's just a styling issue - most likely the padding for `ul` or perhaps margins for `ul/ol` in the Hipster theme. 

The problem is that both the ul/ol and li have margins and it looks like the li is taking priority in the nested configuration. I tried moving around the ul/ol **after** the li declaration but that's not working either.

The only solution I see here is to make the margins of the list and the item the same or close which will make the display more even.

```css
ul, ol {
    margin: 0.6em 0;
}

li {
    margin: 0.6em 0.2em 0.6em 1em;
}
```

Which gives me:

![image](https://user-images.githubusercontent.com/1374013/52936857-9d62ea00-3301-11e9-927b-3b6fd5bed55b.png)

which is more balanced.
