### ISSUE TITLE
Unexpected paragraph line break

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#490]
Paste a long string of text, then append, "For more on this subject see (some long string that starts with a forward slash)."

To my surprise, the preview window renders this with a line break before the word "see" rather than after it.

Here's what in my edit window:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. For more on this subject, see /aaaa/bbbb/cccc/dddd/eeee/ffff/gggg/hhhh/iiii/.
```

Here's my preview window:

![image](https://user-images.githubusercontent.com/42981101/53364544-def02800-38f3-11e9-93ed-63c7b8010857.png)

It surprises me that "see" shows up at the start of the last line, even though there's room for it at the end of the line before it.

I notice that if I remove the forward slash before "aaaa", or if I enclose the very long string in quotation marks, "see" shows up on the previous line like I expect.

**Comment by RickStrahl** [comment]
That's a browser rendering issue in the IE control - nothing I can really do about that as that's the browser interpreting the line breaks on its content.

If you `Ctrl-F12` to preview in an external browser the behavior is different. Chrome renders it correctly as does FireFox and Edge. I can see the same behavior in full IE on the desktop. It depends on the amount of space left at the end of the line - if there's less space it wraps properly.

IAC, nothing I can do to fix this since the HTML output is correct.
