### ISSUE TITLE
postDate changed to time of download when downloading Blog Post from WordPress

### ISSUE THREAD

**Issue by priyadarshan** [RickStrahl/MarkdownMonster#492]
I have just found out about Markdwon Moster, and I am thrilled about it.

I would like to start managing my WordPress blog with it, and I started downloading some posts.

I noticed that postDate is changed to actual time of download instead of being preserved, ie. if I right now would download a post written in 2002, it would have yaml field `postDate: 2019-03-03T18:35:48.2429634+01:00`

Is that by design?

Thank you for Markdown Monster!

**Comment by RickStrahl** [comment]
Right now I don't pick up the post date from the server - it creates a new post and dates it today because - new post. I probably should check the original date and set it. 

FWIW, there's no official way to push a post date to the server on updates unless you use custom variables, so even if the date says something else, that date is not actually going to be used by WordPress so the original date will stay intact.

However, that should probably be fixed - I'll take a look.

**Comment by RickStrahl** [comment]
Should be fixed in:
0be1696a95915d0b3d9dd04dcfe28e8866cc86c0

I've posted a new preview release (1.15.5.3)

**Comment by priyadarshan** [comment]
Thank you so much!

I do not have enouth expertise to compile it myself, I shall wait for next release to test it.

If I may, I am adding two feature requests as separate tickets, feel free of course to close them if they are not appropriate.

Markdown Monster has become the cornerstone of my blogging now.

**Comment by RickStrahl** [comment]
You can download **latest prerelease** from the download page for the change. New update should be out in day or two.

**Comment by priyadarshan** [comment]
Thank you.
