### ISSUE TITLE
Feature Request: Allow setting of slug field on WordPress

### ISSUE THREAD

**Issue by priyadarshan** [RickStrahl/MarkdownMonster#494]
Would it be possible to allow setting of `slug` field on WordPress?

The `slug` field is quiteuseful for custom permalinks, and it is not a field one can manage with a custom field, so right now it is out of reach.

Thank you again!

**Comment by RickStrahl** [comment]
AFAIK, you can't change slugs - they are not even exposed to the blog API - they are generated by Wordpress and returned, but once set you can't change that at least not through the old metaweblog/wordpress api MM uses..

**Comment by priyadarshan** [comment]
I know [org2blog](https://github.com/org2blog/org2blog)  is able to set and modify slug (and even creation date) at will. I am not sure how it does it though.

**Comment by RickStrahl** [comment]
I've added support for receiving and pushing the permalink, but as far as I can tell Wordpress is ignoring that if changes are made to that. 

I think it depends on the backend that is processing the incoming requests. Raw Word press may not let you change the slug (they are permalinks after all that in theory should never be changed as they break the Web).

Note that MM uses the old Wordpress MetaWeblog based API since we're doing mostly simple things - post/update cycles and not full blog management. Changing slugs should be a rare thing to do and on the few occasions you do doing it manually **and very explictly** is probably a good thing since it's not a good idea to muck around with URLs once they've been published IMHO.

**Comment by priyadarshan** [comment]
This is wonderful, thank you!

**Comment by RickStrahl** [comment]
You better try it before you thank me :-) I think this isn't going to let you change the slug - I know it doesn't work with the actual WordPress site, but it might work with other custom installations. Please do reply back with feedback on whether this works or not in your case.

**Comment by priyadarshan** [comment]
I was just looking at the [latest tag](https://github.com/RickStrahl/MarkdownMonster/releases/tag/1.15.8), it is source code, but I can't find the .exe. I will test as soon as I figure it out how to compile it.

But, even if one cannot push back, just having the whole blog, including current permalinks (I spend a lot of time on those) is actually very useful to me, even as backup value.

I really treasure the capability MarkdownMonster offers to create a **text** backup of a site. I know, one needs to go trhough and make sure, but MarkdownMonster does 90% of the legwork, and that is priceless help.

Thank you!

**Comment by RickStrahl** [comment]
You can grab the latest release from here:
https://markdownmonster.west-wind.com/download.aspx 

Use the *Latest Pre-Release* link which has these changes in it.

**Comment by priyadarshan** [comment]
I am testing it now, and it definitely works as you described. Thank you, MarkdownMonster
is such a joy to use.
