### ISSUE TITLE
Feature Request: Images in Markdown as base64 should be collapsable

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#495]
Including images in markdown as base64 is in some cases a nice feature. 
But it takes A LOT of space in the editor with no interesting information. 

It would be nice if these image texts (data:image/jpeg;base64,/9j/4AAQSkZJR..... ) would be collapsed by default

**Comment by RickStrahl** [comment]
Yes that sounds like a good addition. Not quite sure how to do this though - this will require some custom tweaking of the markdown processing and I don't know if it would work for inline images.

**Comment by RickStrahl** [comment]
So I took a look at the base64 embedding logic in MM and there are some serious problems there. The images aren't getting embedded properly due to some timing issues which are causing the image reference and content to get embedded into the middle of the document which is not correct. The way this is supposed to work is that the image reference get embedded in place (a small link) and the image content goes on the bottom.

I went ahead and fixed those issues and now this appears to be working properly so that the actual image content ends up on the very bottom of the document - more or less out of the way.

```markdown
Some content above...

![KavaDocs][image_ref_sq74v6u0]

More content below here...

and yet more.

more...


[image_ref_sq74v6u0]: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyM... more here
```

Is this sufficient rather than collapsing the image content?

**Comment by weggetor** [comment]
Yes Rick, this is absolutely a solution I could live with 👍 
I only had the problem that editing the document is really annoying because of the endless scrolling. If the base64 code is at the end of the document thats absolutely fine for me!

**Comment by RickStrahl** [comment]
Cool.

Also fixed another bug that caused spell checking to fail with the base64 content - that should now work properly too. Check out the preview release from the download page (1.15.8.1) which has these fixes in it.

GOing to leave this open for now - I do want to look into seeing what it would take to collapse certain items in the editor.
