### ISSUE TITLE
Unsaved changes of a document get lost when jump to the document by a local link

### ISSUE THREAD

**Issue by tsvx** [RickStrahl/MarkdownMonster#503]
Suppose I have two files, A.md and B.md with the following contents:

`A.md`:

    [Link to file B](B.md)

`B.md`:

    [Link to file A](A.md)

and the both are opened in the Markdown Monster window.

Then I make a change to the file A (making it 'dirty'), switch to the file B and click on the "Link to file A". Then I have the file A focused and clean, loosing all of its changes.

I think, there should be no losing of changes of a file when one switches to it by a local link.

**Comment by RickStrahl** [comment]
Yes that's a bug. Not quite sure why that's happening I'll have to take a look. It doesn't happen if you navigate via the tabs. 

If you look closely you can see that the changes are there initially and then get wiped out as the doc is apparently reloaded.

Looks like the activation from the link needs check and see if the file is already open and just activate the tab rather than explicitly open it.
