### ISSUE TITLE
Add support for .editorconfig file

### ISSUE THREAD

**Issue by marin-bratanov** [RickStrahl/MarkdownMonster#509]
In my organization there is an [.editorconfig](https://editorconfig.org/) file at the root of the repo that I write in. It would be great if MM could use that to ensure **consistent line endings** and whitespace.

If this could be extended to code blocks (for example, if a code block starts like ```C# or ````JavaScript, then typing inside should use the convention for whitespace from the .editorconfig). That's a stretch goal, though.

**Comment by RickStrahl** [comment]
I'm not sure this is a good idea for whitespace as Markdown has significant whitespace. Trailing spaces are legal (for line breaks) as are leading spaces for code blocks and indentation of list and a few other things.

In most .editorconfig files (in visual Studio/Code) markdown is explicitly **excluded** for processing.

Line endings - I have to review that again sometime. I went down the path to allow configurable line endings but ran into some trouble with some of the parsing routines and I had to basically roll that back out at the time. 

Internally MM normalizes all line endings to `/n` for processing but then the documents are written out with Windows endings for consistency. 

There have been some changes (the normalization for processing) since then that probably will make that work much better now, but it'll add some processing overhead.

**Comment by marin-bratanov** [comment]
Thanks for the response. I agree with everything you say, and I added this so it stays as a backlog, in case you believe it makes sense for the product.

MD is often excluded from .editorconfig, but it may be included in case the organization writes documentation, or in case someone decided all files must have specific line endings for all files (that's my case, I simply had to conform to line ending requirements, then I started thinking about things that may help).
