### ISSUE TITLE
Dark\vscode dark is way off

### ISSUE THREAD

**Issue by hypercube33** [RickStrahl/MarkdownMonster#512]
Status bar is blue, dark colors are off and off-putting. Font isnt the same or same weight. Makes it harder to separate UI components as-is.  If there is a file I can go edit with the values for all of these I'd be happy to make a pull.

VS Code uses the following fonts (14 pt) in descending order:

Monaco
Menlo
Consolas
"Droid Sans Mono"
"Inconsolata"
"Courier New"
monospace (fallback)

**Comment by RickStrahl** [comment]
What are you referering to specifically? There are a number of different themes involved. 

The outer shell theme is not really meant to be changed - there's Dark and Light and they are handled in WPF styles which is a royal pain to style. MM basically uses a stock MahApps theme with a few minor changes for borders and shadows that are off in the default theme. This is not really open to change though.

The Editor theme is the main editor and that is determined by ACE Editor themes. I created [ a custom VS Code dark theme](https://github.com/RickStrahl/MarkdownMonster/blob/master/MarkdownMonster/Editor/scripts/Ace/theme-vscodedark.js) roughly based on the VS Code defaults. I didn't meticulously duplicate the theme so this certainly can take some tweaking to match closer to the actual VS Code dark them. 

Then there's the Preview theme and specificlaly the HighlightJs theme. I'm using the [stock HighlightJs visualstudio dark theme.](https://github.com/highlightjs/highlight.js/blob/master/src/styles/vs2015.css). The fonts are determined by the preview theme which come from the specific preview theme- for example:

[Dharkan Theme pre/code tags](https://github.com/RickStrahl/MarkdownMonster/blob/master/MarkdownMonster/PreviewThemes/Dharkan/Theme.css#L201)

If you make changes I suggest to copy the existing style(s) and create new ones.

As to the actual fonts - the first two are Mac fonts which will never apply on Windows since they are not installed and MM only runs on Windows. The style fonts are pretty much ignored anyway as the font is set based on the configuration setting in the MM configuration as is the line spacing. These things are set at the editor level rather than through (which is what ACE requires in order to get the right font metrics).
