### ISSUE TITLE
No favorites button 

### ISSUE THREAD

**Issue by robcxyz** [RickStrahl/MarkdownMonster#513]
I can't find the favorites button on the toolbar or any simple way to add an active tab to the favorites bar without copying the path and typing the name of the doc. 

What am I missing?

Thanks and great tool.

**Comment by RickStrahl** [comment]
Start here:

https://markdownmonster.west-wind.com/docs/_58u0u6bnh.htm

**Comment by RickStrahl** [comment]
You can also get to the Favorites Tab with Alt-V-V

**Comment by robcxyz** [comment]
Thank you for quick reply and tip.  Am I going crazy though and is there no favorites button in the toolbar though or is there something I need to do to activate it?

**Comment by RickStrahl** [comment]
Also added support for drag and drop from Explorer into the Favorites tab just now. It's 1.16.15.3 and later.

**Comment by RickStrahl** [comment]
No there's no favorites bar on the toolbar because the tab on the left serves that purpose. Just click on the tab.

![image](https://user-images.githubusercontent.com/1374013/57051720-805e6780-6c1e-11e9-98dd-b159c596f349.png)

Also the tab context menu option was missing - but that's also been added back.

**Comment by robcxyz** [comment]
Yeah I the Alt+v+v is what I needed. In fact the whole Alt+<...> thing is becoming a theme I see and should end dumb questions going forward. 

These subtle details really add up when you write markdown all day.... 
Thanks again and much appreciated.

**Comment by robcxyz** [comment]
@RickStrahl 

The update you just pushed with the add to favorites is great (and was super fast thanks) but could use two minor improvements.  First is when you `add to favorites` that you populate the name of the document into the favorites tab which should basically be the default.  Also what would the keyboard shortcut for that be?  

Thanks again...

**Comment by RickStrahl** [comment]
There's no keyboard shortcut for those operations because they don't live on the main menu. I'm not planning on adding custom keyboard shortcuts for these either because they are unlikely to be highly travelled paths and permaennt keybings are hard to map at this point as there are so many already.

I think one thing that might be useful though is to make the right click menu inside of the editor include all the options from the tab drop down because it actually applies in that same context and that at least would give you the opportunity to use the drop down key and navigate or hotkey inside of the tab menu.
