### ISSUE TITLE
Custom syntax highlighting like TODO: 

### ISSUE THREAD

**Issue by robcxyz** [RickStrahl/MarkdownMonster#515]
Minor suggestion:

In vscode you can install an extension to do custom syntax highlighting on key words like TODO:

Would be nice to have the same capability in vscode on the editor side, not the rendering of the markdown as that is a whole other bag of worms.

**Comment by RickStrahl** [comment]
Yeah I've been thinking about that for a number of things. Unfortunately the Markdown formatting in the editor is really difficult to change due to the ACE editor Markdown syntax implementation. The markdown syntax is extremely complex (it's the most complex syntax of all editors as it combines a bunch of syntaxes together) and it's very difficult to hook.

I haven't found any decent examples to hook into that short of creating a custom syntax and adding explicit custom overrides. I've tried a few times to do this but not had any luck.

I don't see this happening unless someone wants to take a crack at that.

**Comment by RickStrahl** [comment]
Takign another look at this there's actually some documentation on how to do this for ACE. Still not trivial but actually much easier than modifying the actual sytnax:

https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode

Not sure whether it's possible to completely override an existing syntax and then serve the same extensions.

**Comment by timunie** [comment]
Hi @RickStrahl 

Just as a suggestion: I like the way [Notepad++](https://notepad-plus-plus.org) supports userdefined languages. Attached is an example and here is the result:
![image](https://user-images.githubusercontent.com/47110241/66900070-619d3300-effc-11e9-8416-8f9fac800a5c.png)

That way one would need to edit the text-file and MarkdownMonster will load this at runtime. I don't know if this is possible with ACE or not. 

Happy coding 
Tim

[Test.txt](https://github.com/RickStrahl/MarkdownMonster/files/3733119/Test.txt)
