### ISSUE TITLE
Significant snippet/command slowdown due to Roslyn

### ISSUE THREAD

**Issue by bladewolf55** [RickStrahl/MarkdownMonster#519]
**Description**  
Roslyn was enabled for the Snippet AddIn on Jan 30. Since then, there's a delay of five seconds on activating snippets.

**Steps**  
1. Close MM
2. Open MM
3. Try a snippet

**More Information**  
I spent several hours tracking this down. Below is a specific snippet I'm experiencing the behavior on on. To use the snippet, select a few lines of text and press Ctrl+Shirt+8. The selected lines will be prepended by Markdown checkboxes.

It seems that, after that first delay, the snippet will then open quickly. So maybe there's an initialization time coming into play? But it happens frequently enough that it bugs me. (I was too busy to devote time to it before today.)

In addition, I'm noticing problems using C# commands via the Command AddIn. I haven't experiment, yet, with setting them to not use Roslyn.

The specific Git Reference object ID is 04d182b.

Here's the line of code:

`AddIns/Snippets-MarkdownMonster-Addin/SnippetsAddin/_classes/ScriptParser.cs`

```csharp
//Line 103
  _razorHost.CodeProvider = new Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider();
```

When I comment out this line, the behavior is as expected (snippet activates almost immediately).

I don't have a suggestion, and I'm surprised others haven't reported this. This is on a very clean 
 development machine, as I did a Win10 reinstall a few weeks ago.

Let me know how else I can help.

**Snippet**  
C# Razor Template
Shortcut CTRL-SHIFT-8

```csharp
@{
    string sel = Model.ActiveEditor.GetSelection().Replace("\r","");
    if (String.IsNullOrWhiteSpace(sel))
    {
        return;
    }
    List<string> newLines = new List<string>();
    string[] lines = sel.Split('\n');
    foreach (string line in lines)
    {
        if (!String.IsNullOrWhiteSpace(line))
        {
            newLines.Add("- [ ] " + line.Trim());
        }
    }
    Model.ActiveEditor.SetSelection(String.Join("\r\n", newLines));
}
```

**Comment by RickStrahl** [comment]
Yes I'm aware of that problem - unfortunately there's not much I can do about this. Roslyn is required because it provides the new C# language features - otherwise you're stuck in C# 5 and you don't get any of the new language features which is going to be unexpected. 

The overhead is the Roslyn startup time. Once it's up, it's still slower than the old compiler but not as drastically. Basically the first hit loading the compiler is what all the overhead is about. 

One thing that I can maybe think about is firing up a compile cycle after startup on a background thread - that'll get the compiler warmed up so then subsequent requests will be faster. However, this will increase memory if you don't use so maybe this is not a good trade off.

I don't know what the solution is for this one but not supporting newer C# features I think is not one of them.

**Comment by bladewolf55** [comment]
I figured "warmup time" was at issue, and I agree with you about moving
forward on C#, as well as the long-term benefits of .Net Core.

I suspect the extra memory wouldn't be a problem for anyone. MM takes a
measly 25MB of memory on my machine. I'd happily double that in order to
not have my writing flow interrupted by freezes, and I doubt people who
don't use C# mods would even notice or care. After all, MS Word uses 50MB
of memory on start up. Smooth Markdown Monster is just as important to me!

Thanks Rick.



--
Charles L Flatt
513-535-0764 (m)
"All of humanity’s problems stem from man’s inability to sit quietly in a
room alone." -- Blaise Pascal

**Comment by RickStrahl** [comment]
Can you confirm that if you run more than one script that only the first one is slow? Re-running the same one wouldn't be fair since that will be cached, but running another script should be considerably faster.

**Comment by RickStrahl** [comment]
Added the pre-load to the Snippet Addin's startup: eceea46cabc0a9474b6f012f081cf040af268032

Give 1.16.16.2 (pre-release) a try and see whether that helps.

**Comment by bladewolf55** [comment]
I'm not able to successfully build. The MarkdownMonster reference errors
shown below also exist for ScreenCaptureAddin.

[image: image.png]

--
Charles L Flatt
513-535-0764 (m)
"All of humanity’s problems stem from man’s inability to sit quietly in a
room alone." -- Blaise Pascal

**Comment by RickStrahl** [comment]
Make sure you build the Markdown Monster project first, then build the addins (or a full build). Build order is not working in for SDK projects and if the addins build first they are not finding the required EXE reference (long story on why this is set up as it is). Alternately you can just build Markdown Monster and not the addins.

**Comment by bladewolf55** [comment]
Thanks, Rick. The problem may also have been not having preview 5 of Core 3
installed. Regardless, I'm building successfully, now, and the latest
release resolves my Snippets issue. Thank you!

However, keyboard shortcuts don't seem to work for the Commander AddIn. I
have v0.5.3 Feb 25 installed. It doesn't matter whether I set the
compilation to use Classic or Roslyn. Running via the Run Command button
works.

When set to Roslyn, there is the five second warmup time. I think you're
right to put this warmup into MM so it's available to all AddIns.

Do you want me to submit a separate issue for Commander? If I can make
time, I'll look into it myself and submit a pull request.

--
Charles L Flatt
513-535-0764 (m)
"All of humanity’s problems stem from man’s inability to sit quietly in a
room alone." -- Blaise Pascal

**Comment by RickStrahl** [comment]
Hmmm... that is really strange, but I see the same. 

* First invocation is fast (even if not immediate)
* Immediate re-invocation is fast
* Wait 10 seconds or more and it's slow
* Immediate re-invocation is fast

That makes no sense to me... 

Once Roslyn is loaded it should just be there in memory and be ready. And clearly it **can** stick around because first invocation doesn't have to be within in the timeout window. I'll have to take a look and see what could possibly be causing this slowness.

**Comment by bladewolf55** [comment]
I think this SO article may provide some clues.

https://stackoverflow.com/questions/15365376/roslyn-slow-startup-time

The GitHub repo also mentions the idle time for VBCSCompiler.exe.

https://github.com/aspnet/RoslynCodeDomProvider

I doubt I'll find an answer tonight--this is my first foray into using
Roslyn directly. There's no issue when running in debug, probably because
VS is keeping the compiler alive in order *to* debug. :-)

--
Charles L Flatt
513-535-0764 (m)
"All of humanity’s problems stem from man’s inability to sit quietly in a
room alone." -- Blaise Pascal

**Comment by RickStrahl** [comment]
I've made another change that keeps the compiler active and that seems to work actually. Still loads for the snippets addin (not commander) but if you got both loaded that should work for both of them. 

Basically I made the wrapper static so it stays alive and it looks like htat's working - Startup is much faster now actually non-initial compilations are in the 2ms range. That'll solve it but effectively that keeps the compiler in memory which definitely is a memory hit.

**Comment by RickStrahl** [comment]
Ok so that last bit was not really working, but I took the private reflection code and added it to MM to run the compiler and keep it running for 20 minutes. This seems to work well.

Now this may end up causing other problems - with updates because the compiler will be loaded in mermory and won't be able to uninstall so that's a problem.

**Comment by bladewolf55** [comment]
Since the installer shuts down the running MM instance, how about unloading
the compiler when that event occurs? I don't know what it is in WPF forms.
Back in my VB6 days there was an event that fired for external close
requests.

--
Charles L Flatt
513-535-0764 (m)
"All of humanity’s problems stem from man’s inability to sit quietly in a
room alone." -- Blaise Pascal

**Comment by RickStrahl** [comment]
Done and added. Refactored the ScriptRunner a bit, added the warmup and shut down code - it'll run for 20 minutes now and gets shutdown when MM shuts down. Not sure if the timeout is incremental since last access or total. Guess we'll find out but 20 minutes is quite a stretch.

The last thing left to do is move this code into the main project and make it fire there, rather than in the snippet addin since it won't pre-load unless there's a snippet with code in it.

**Comment by bladewolf55** [comment]
Thanks for putting such quick effort into this. I'll test when the next
release is ready.

--
Charles L Flatt
513-535-0764 (m)
"All of humanity’s problems stem from man’s inability to sit quietly in a
room alone." -- Blaise Pascal

**Comment by bladewolf55** [comment]
1.16.17.9 seems to take care of the Snippets issue. I'll check in a week or so whether Command keyboard shortcuts are working. If not, I'll try to take a look myself before opening an issue.

Thanks again, Rick. Closing this issue.

**Comment by bladewolf55** [comment]
Oh! One more thing. MM is taking 13 to 60MB of memory on my machine depending on activity, which isn't a problem at all.
