### ISSUE TITLE
Drag and drop doesn't drop everything

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#528]
Open Markdown Monster. Make sure it has no open files.

From File Explorer, select several markdown text files (A.md, B.md, etc.), grab them with the mouse, and drop them onto the MM window. All of the files are added as tabs. So far, so good.

However, now start MM with one or more open markdown file open, and do the same drag and drop operation. The intent is to add new files to the set of tabbed files, but now, only one of the dropped files is added to the set of tabs that MM displays. The others are ignored.

So, for example, if A.md and B.md are open in MM, and you try to drop C.md , D.md, and E.md into the MM workspace window, only one of those three new files (and, as it turns out, it's the one your mouse was pointing to when you selected the group for dragging) is added to the MM workspace, so now there are only three files there instead of the expected five.

Again this issue doesn't occur if you start this exercise without any open files in MM. In that case, dragging and dropping adds all five of them.

**Comment by RickStrahl** [comment]
There are two types of drag and drop operations and those are what you're seeing for the differences. Dropping **on the window** will properly drop multiple files. This works when no tabs are open, or if tabs are open, if you drop on the anywhere **except the editor pane** (ie. in the toolbar area for example).

For content area/editor drops a different drop handler is uses which uses the browser to detect the drop, and I have to check if that can possibly capture multiple drop sources - I believe that comes in as a single document link and that's why that doesn't work. I'll have to check.

**Comment by bcmadsen** [comment]
Thanks for looking into this. I'm fine if you want to close this out.
