### ISSUE TITLE
Feature request: Toolbar icons for break and highlight

### ISSUE THREAD

**Issue by akordowski** [RickStrahl/MarkdownMonster#539]
Writing markdown documents I regularly use one line breaks (`<br/>`) and also like to highlight (`<mark></mark>`) some text passages. Currently I have to write these html tags all the time. It would be very convenient if I could add a break or highlight a text using a toolbar icon. I would like to contribute this feature.

Highlight icon: https://fontawesome.com/icons/highlighter?style=solid

**Comment by RickStrahl** [comment]
We’re trying to minimize the amount of items on the toolbar. There are lots of things that could be on the toolbar, but they’re not all going to be there. So these two Are not going to be there.

The shortcut for `<br/>` actually is two spaces plus ENTER, and you can press `Shift-Enter` to enter that key combo into a document. This is preferable to using the line breaks to avoid the visual noise of HTML in the Markdown.

**Comment by RickStrahl** [comment]
I've added some additional functionality that allows you to add toolbar buttons with additional functionality via configuration.

![image](https://user-images.githubusercontent.com/1374013/60224686-60bb7800-9838-11e9-97e6-c54888ca880b.png)

These key/value pairs are a FontAwesome icon id plus a markdown 'command' of which a number that aren't on the toolbar are available. I've added `mark` just now so that's now available. You can also add an arbitrary HTML markup tag, which will wrap the selected text using `html|tagname`.

More info in the documentation:

[https://markdownmonster.west-wind.com/docs/_5im10bjpw.htm](https://markdownmonster.west-wind.com/docs/_5im10bjpw.htm)

**Comment by akordowski** [comment]
That's awesome! Thank you very much! @RickStrahl you rock!!

What do you think about to change the value to an object and provide additionally a description for the tooltip?

`"Pencil": { Command: "mark", Description: "Highlights a text" }`

**Comment by RickStrahl** [comment]
Not inclined to add this as this is pretty much and advanced addition feature. You'll know what those additional icons are since you added them :-)

There are a other things that might be important here, but I've decided against putting them in here. If you really want more control or are looking for something more permanent I would suggest creating an addin that provides this.

**Comment by akordowski** [comment]
Regardless the new feature is very helpfull. Thank you very much!
