### ISSUE TITLE
Feature request: Extended search and replace

### ISSUE THREAD

**Issue by akordowski** [RickStrahl/MarkdownMonster#540]
I would like to propose to extend the search and replace feature for 'All Open Documents' and 'Current Project' like in Visual Studio. I would like to contribute this feature.

**Comment by RickStrahl** [comment]
So this is a good idea, but before jumping into this we should take some time to discuss how this should work.

Most likely we either need a new dialog for this or a sidebar tab list that can show search results files. From there you jump to the file and find the matches.

I think doing in editor searches (like Visual Studio) is not going to be possible due to the way ACE editor manages the search box - overriding that box is difficult and even more difficult to keep in sync with ACE editor updates, so I'm pretty much opposed to that approach.

In order to do this we'll need a few things:

* Search Helper that can find instances of text in text files and return locations in the documents
* We'll probably need some new routines in the editor to automate search text operation (ie. fill the search box and search).
* Sidebar implementation that list files and starts searching an individual file.
* Possibly some sort of mini preview of the search text with surrounding lines of code (or perhaps just the effected line of code a la Resharper)

This is not a small feature which is why I haven't tackled that one yet.

Another alternative today is to open the folder in VS Code (or another editor and search from there :-))

**Comment by matthewdw** [comment]
I'd like to vote for this enhancement too.  It would help turn MM into a searchable notes library rather than focusing entirely on the current file being edited.   HTML Help Builder is already a closer product to this but it's a bit over the top in terms of functionality and price if you just want a notes library like Evernote.

**Comment by RickStrahl** [comment]
@matthewdw  FWIW, you can use the file browser today to search for file names including subfolders. It doesn't search content though.

As I mentioned I started building some of this infrastructure starting with the search component. The harder part of this process is going to be how to flesh out the UI in a good way.

Actually it's interesting you mention Help Builder for notes etc. - that's what I currently use as well. I've been building another tool that will eventually replace Help Builder that works as an add-in in MM that basically provides the project management that's currently missing in MM as a plain editor.

IAC stay tuned - I'll have something for searching soon.

**Comment by RickStrahl** [comment]
I've added an initial implementation of Search in Files:

![image](https://user-images.githubusercontent.com/1374013/60648312-ff9b3200-9e3f-11e9-8b09-58e08adb9659.png)

It's in the latest pre-release builds from the download site.

**Comment by matthewdw** [comment]
Very nice!  The functionality is definitely functional already and serves the purpose nicely.  My only suggestion is that when activating "find in files" my expectation was that it would search in the currently selected parent folder (pictured) by default.  I had to browse to the folder manually instead but no big deal once you know that is how it works.

![image](https://user-images.githubusercontent.com/52383197/60766168-826cf880-a09d-11e9-894c-1eb51b269cb5.png)

**Comment by RickStrahl** [comment]
If you use the search icon in the browser that’s the behavior you get...

**Comment by matthewdw** [comment]
Yes, great!

**Comment by RickStrahl** [comment]
Yeah so what folder is active is still something that I'm tinkering with. 

Here's what we currently have:

First Activation from Find in Files on Menu:   
Folder of active project or active document if no project is open

Activation from Folder Browser Search Icon:  
Folder that's active in the Folder Browser (behavior you were asking for)

Otherwise:  
Whatever was used last stays active (ie. sticky search pane content)
