### ISSUE TITLE
Hiding images from file and folder browser

### ISSUE THREAD

**Issue by matthewdw** [RickStrahl/MarkdownMonster#548]
I am storing my documentation images in the same folder as the Markdown document itself, but I would like the _file and folder browser_ to only show the .md files and not all of the images.  For a document with a lot of images it can start looking messy.

![image](https://user-images.githubusercontent.com/52383197/60493731-5f110a80-9ca5-11e9-81be-d363f882598b.png)

Can we have some way to hide certain file extensions or only show certain file extensions in the file browser?

**Comment by matthewdw** [comment]
Oh I just found the `IgnoredFileExtensions` option in `MarkdownMonster.json` which does the job nicely.
```
    "IgnoredFileExtensions": ".saved.bak,kavadocstopic.md,.saved.bak.md,.png",
```

By the way, it is a bug that the default version of this configuration has a semi colon at the end of the string?  It seems to work fine without that.

**Comment by RickStrahl** [comment]
I don't foresee adding an explicit filter other than the global ignore filter. That's more meant to keep out files that are just noise of temporary files, but if it works for you to do other filtering then great.

The folder browser is very useful but I don't want to turn it into a full explorer replacement :-) A lot of things in the folder browser are complicated to implement and don't add that much value to MM overall since the file browsing is just a support feature.
