### ISSUE TITLE
Closing documents with Ctrl-F4 prevents keyboard menu access

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#549]
Open a document, close it with the mouse, and all is well.

Open a document and close it with ctrl-F4 from the keyboard, then use the mouse to open another document, and all is well.

But if you open a document, then close it with ctrl-F4, and then try to use the keyboard to access a menu (such as, say, File | Exit or File | Open), you can't. The menu bar is unresponsive to keyboard action.

Ordinarily, Windows users expect to be able to press Alt-F at this point to bring up the File menu, but the menu doesn't respond.

To get it to respond again, you can move focus away from Markdown Monster (such as by Alt-Tabbing to another window and back again), or else by interacting with MM's menu using the mouse -- but until the user does any of those things, the Alt-button doesn't generate any response from the menu.

**Comment by RickStrahl** [comment]
It's only an issue if you close the **last** window that's open in the editor. Otherwise Ctrl-F4 behaves properly.

This relates back to another issue that you raised a while back (can't recalll or find it because it was not directly related to closing). There's some oddity that happens when the last tab is closed that messes with the focus of the application. 

If you use the mouse to access the menu after it doesn't work, then retry with Alt-F (or whatever) it woks again.

I'll take another look but I think this is enough of an edge case as to not be a critical failure.
