### ISSUE TITLE
Multi-monitor oddity when MM starts maximized

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#557]
Open MM, with or without open documents. Move it to a secondary monitor, that is, not the one that has the taskbar and start menu. *Do not maximize it.* Shut it down. Open it back up again. The MM window reopens where it was when it was closed down. As long as MM remains not-maximized, all of this is expected behavior.

Now, with MM on that secondary monitor, maximize it and then shut it down. Now restart it. This time, to my surprise, it opens, maximized, on the primary monitor (the one with the start menu), rather than on the monitor where it was when it closed. When it opens maximized, in other words, it always shows up on the primary monitor, no matter where it had been when it shut down.

**Comment by RickStrahl** [comment]
Unfortunately, that's something that I don't have a quick solution for. The problem is that MM stores the location of the window only when it's not maximized. If the window is maximized when shutting down no new Window location settings are saved on shutdown at all, so next time the window opens at the last non-maximized location that was saved at a previous shutdown.

The reason for this is that there's no easy way to detect which monitor the Window is maximized on. I have the location, but mapping that location to a particular monitor is not easily done without all sorts of gymnastics related to mapping monitor DPI to relative pixels etc. I've looked into that some time ago and couldn't find a solution that didn't involve a ton of API code that I'm not even sure would still work (given recent changes in how .NET deals with DPI settings now).

The only simple thing that could be done is to capture the maximized location and display the window at that same location **non-maximized** but sized to full screen - which is what used to happen. But I think that's also very unexpected and IMHO much more difficult to unset to a 'normal'
working setting if you end up not wanting the window maximized next time you launch.

Given that I don't think capturing the screen to maximize on is not an option - what would you like to see?

**Comment by RickStrahl** [comment]
So after some experimenting I was able to make this work - courtesy of an odd behavior in the WPF `StateChanged` event behavior. Looks like when you maximize a window `StateChanged` still reports the original window size. This means I can capture the window location prior to and so display the window at the non-maximized location first, and then maximize it from there which puts it onto the right screen.
