### ISSUE TITLE
External preview window is brought to the front when the main window is active

### ISSUE THREAD

**Issue by NoahAndrews** [RickStrahl/MarkdownMonster#558]
It would be great to have the option to choose whether or not the external preview window comes to the front when the main window becomes active.

**Comment by RickStrahl** [comment]
This should be the default behavior.

In what scenario do you not see the preview window come to the front when you re-assert focus? When I do, both windows activate.

**Comment by NoahAndrews** [comment]
Sorry I was unclear. I actually wanted to disable that behavior.

**Comment by RickStrahl** [comment]
I don't think that's a good idea. Why would you want that? What's the use case?

I played around with this a little just to see of the effect. A number of things:

* Adding this as an explicit option would be confusing in terms of options IMHO. Docked, OnTop, Activated - it feels like too many options that to the uninitiated sound very similar.

* Tied Window Activation to Docked status  
Using this approach the window is only activated automatically when docked, but not when external. The problem with this is that the preview also doesn't show when the Preview changes if the window is not active which is probably not the desired behavior. In reality while typing this will likely cause the window to be always visible anyway. To make this work I'd have to add a forced show operation (which is not trivial since we wouldn't want to focus the window) on every preview operation.

So - honestly I think the current behavior seems appropriate. If you're in MM both windows are active seems like the right thing to do to me. If anything I think we'd need the second approach, which again is perhaps more confusing of why the Window pops up.

**Comment by NoahAndrews** [comment]
I've come up with two real-world use cases where I'd like to have the preview not come up when I switch to the main window.

1. Having both windows maximized and alt-tabbing between previewing and editing. I tried to do this just now, when proofreading a document I had just written.
2. Having the editor window visible to one side, and alt-tabbing between the preview and some reference material on the other side. I want to be able to edit the document while looking at the reference material in this configuration. Not being able to do this is what prompted me to make the issue in the first place.

I don't really understand everything you go through when explaining why tying the window activation to the docked status doesn't work well, starting with "the preview also doesn't show when the Preview changes if the window is not active which is probably not the desired behavior".

**Comment by RickStrahl** [comment]
Hmmm... I sort of see what you mean :-)

Just not sure if that's common enough of a use case to warrant complicating the options to the point that it won't be super obvious what items to tick off. 

[ ] Docked [ ] Always on Top [x] Linked

the last option wouldn't make sense when docked and also not when Always On Top...

I have to see what's actually involved in this. I think the only way to control the behavior is by setting the owner of the window which means a change to the setting requires that the window is completely unloaded/reloaded too.

**Comment by RickStrahl** [comment]
So consolidated various settings into a single option that now is a drop down:

![image](https://user-images.githubusercontent.com/1374013/63542952-81214f00-c4d6-11e9-8be9-8e018365fcc0.png)

This should address your scenario while keeping the UI reasonably simple enough as to not be confusing.

**Comment by NoahAndrews** [comment]
That looks fantastic! Thanks for being so responsive.
