### ISSUE TITLE
`Save All` behaves like `Save As`

### ISSUE THREAD

**Issue by breki** [RickStrahl/MarkdownMonster#564]
I have remapped the `Save All` keyboard shortcut to `Ctrl+Alt+S` (to correspond to Visual Studio mapping), but when I run it (either through the keyboard shortcut or by clicking on the menu item), it runs the `Save As` action - it opens the `Save As` dialog. 

The relevant `KeyBindings.json` section:
```json
  {
    "Id": "SaveAs",
    "Key": "Alt+Shift+S",
    "CommandName": "SaveAs"
  },
  {
    "Id": "SaveAll",
    "Key": "Ctrl+Shift+S",
    "CommandName": "SaveAll"
  },
```

And the screenshot of the `File` menu:
![2019-09-06 06_36_15-MarkdownMonster-KeyBindings json  - Markdown Monster](https://user-images.githubusercontent.com/226863/64401331-bb5f2480-d070-11e9-9f9a-eda412d5f81b.png)

BTW I have now remapped the shortcuts back to the defaults, but `Save All` still doesn't work.

**Comment by RickStrahl** [comment]
Took a look at this. Caused by a side effect of changes a while back where tabs are completely delay loaded. Basically there was a check for support editor bits that haven't been loaded yet and if they aren't it would report that the Save failed.

Changed so that the save operation goes and if the missing pieces are not loaded the Save Operation is all that runs.
