### ISSUE TITLE
Two bugs since 1.19

### ISSUE THREAD

**Issue by jovibor** [RickStrahl/MarkdownMonster#568]
Hi.
In 1.18 all was working fine.

Since 1.19:
**First issue:**
The preview sync doesn't work anymore in "Edit to Preview" on any document, no matter what i tried. No settings were touched after 1.18->1.19 upgrade. In fact i did never change any defaults.
**Second issue:**
All internal #anchors `[](#)` stopped to work as well. If i press the link inside preview window it doesn't follow it, but worked nicely in 1.18. And if the link is external `[](http://...)` it opens it in the preview window within the MM, but in 1.18 used to do it in external Chrome (as it suppose to).

**Windows 10 (1809)**
Thanks.

**Comment by RickStrahl** [comment]
1. I can't duplicate this. Still works fine for me. Can you make sure that you have the right scheme configured which is:

![image](https://user-images.githubusercontent.com/1374013/64495232-1a2cc580-d24c-11e9-9849-8c7abaa429cd.png)

or you can use the statusbar drop down.

2. Also can't duplicate 

Here's a screen capture of both issues in a short clip.

![NavigationBugs](https://user-images.githubusercontent.com/1374013/64495285-fc139500-d24c-11e9-8ba7-ab792f947a3d.gif)

Can you download the latest current build (1.19.2.x) just to be sure we're looking at the same thing.

**Comment by RickStrahl** [comment]
Also in the future, could you please post multiple issues separately? It's better to have each issue isolated.

In this case it looks like the issues you're seeing are related (perhaps due to some configuration problem) but generally separate is much cleaner to follow up on.

Thank you.

**Comment by jovibor** [comment]
Yes, i'm running the latest. (v1.19.2.2)
Yes, i have right scheme, and absolutely the same worked fine in 1.18 :)

**Comment by RickStrahl** [comment]
Hmmm... not sure as I can't duplicate this on two machines.

Can you try resetting your configuration file just to make sure it's not some odd combination of settings that's causing this.

**Comment by jovibor** [comment]
Ok, see what i did:
I totally removed `C:\Users\[username]\AppData\Local\Markdown Monster` 
I totally removed `C:\Users\[username]\AppData\Roaming\Markdown Monster`

I made fresh install 1.19.2.2 and this problem still persist. 
So, i can guess it's exactly some 1.19... version issue, because there was no such in 1.18.
What else can i possibly do?
It's worth mention that "Preview to Editor" works, but not "Editor to Preview".

Sorry for inconvenience.

**Comment by RickStrahl** [comment]
What happens if you switch to `Both` for the syncing?

Honestly I don't know what could be causing this and since I can't duplicate it it's hard for me to address. The only thing I can think of is perhaps some odd hardware issue that's causing the scroll events to not fire properly in the editor, but I find that hard to accept since that would break lots of other stuff.

**Comment by jovibor** [comment]
> What happens if you switch to `Both` for the syncing?
In this case it works as well only in one direction "Preview to Editor".
I even used "Reset settings to Default".

One more:
When i change "Preview rendering theme" in any order, say from Github to Dharkan, it synchronizes "Edit to Preview" position, but just one time, any next scrolls don't sync.

Well, can you at least point me to the link with latest 1.18... stable installer release, if no workaround atm?

**Comment by RickStrahl** [comment]
You can download old versions from here:

https://github.com/RickStrahl/MarkdownMonsterReleases/

Note I think the 1.8 revs ended up in the 1.7 tree.

**Comment by RickStrahl** [comment]
Still not sure why that's happening - there's nothing that has changed in the preview and editor behaviors that should affect this and not just with a specific document? There are situations where the preview may not behave properly due to large blocks of text/images that span more than a page.

Can you verify that this is with all documents? If you open the sample document do you see the same behavior?

Thanks for you patience - I know this is frustrating but if I can't duplicate I can't address it unfortunately.

**Comment by RickStrahl** [comment]
Ok I was able to duplicate after all on one machine and fix.

1.19.4 is up and I believe that should work for you now. Let me know.

**Comment by jovibor** [comment]
> Ok I was able to duplicate after all on one machine and fix.
> 
> 1.19.4 is up and I believe that should work for you now. Let me know.

Just woke up and here a neat surprise.
Yes. It's now working perfectly, and even faster (preview update latency) than previously.
Thank you for not being indifferent. :)

**Comment by RickStrahl** [comment]
Hey no thank you - you helped me fix a bug that I totally missed.

**Comment by RickStrahl** [comment]
Can you also re-check your anchor issue please and if that still doesn't work please create a new issue. Thanks.

I think though that this fix also fixes the anchor problem - the problem was that there was an invalid reference in the script code and that blew up the initialization code for the preview - anything that followed didn't get run and the anchor mapping is probably another one that followed. 

Again thanks for your help.

**Comment by jovibor** [comment]
Anchors work perfectly now!
