### ISSUE TITLE
Code Highlighting in Jekyll using Liquid

### ISSUE THREAD

**Issue by pkellner** [RickStrahl/MarkdownMonster#569]
I don't know the details of how this all works, but when publishing on docs.microsoft.com, I get syntax highlighting by typing

```HTML
<html>...</html>
```

Doing that in my Jekyll markdown and publishing to github pages does not seem to work.  However, when I add the plugin highlight to the ruby gem space and publishing to github pages, I get what I want.  I'm not a ruby guy so not really sure what's really happening.

Attached is a picture of what I see in MM when I use this highlight plugin.  Notice the following:

The HTML code does not show up on the preview (just what would be rendered by the HTML itself which is kind of confusing)

The liquid syntax does show up in the markdown

The HTML is highlighted reasonably well in the editor itself

Any way I can improve this experience?

**Comment by pkellner** [comment]
BTW, this is the URL for the published blog with HTML highlighted.

https://peterkellner.net/2019/09/07/integrating-jekyll-and-smartforms-with-recaptcha-free/

**Comment by RickStrahl** [comment]
Hmmm... doesn't docs.Microsoft.com support standard Markdown syntax highlighting with fenced code blocks? Last I looked that worked fine. Are you saying in the docs you just type the Html and gets syntax coloring? Because in Markdown down `<html>` will be evaluated as HTML and processed as raw HTML.

**Comment by RickStrahl** [comment]
Honestly I have no idea what you're asking in this.

MM displays fenced code blocks without issue. What happens on your published site may be something completely different and that depends on the Markdown processor there and what addons are running etc.

You can embed HTML into a page using standard HTML and script tags and that will work, but scripts have to be explicitly enabled in the options and even then that may not work well because the scripts have to be reloaded when the page is refreshed via DOM replacement.

Closing unless you have a better explanation what you actually trying to accomplish.
