### ISSUE TITLE
When should LastFolder setting update?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#571]
In the MarkdownMonster.json file, my LastFolder setting never changes. Maybe not a bug? Maybe I'm expecting something I shouldn't?

Is LastFolder supposed to change whenever I open a *.md file? Whenever I close one? Some other time?

All I know is, it's not changing, even when I open files in other locations -- at least, not unless I open Settings to change it manually. I feel like I shouldn't need to do that ... should I?

**Comment by RickStrahl** [comment]
I took a look and the LastFolder definitely is a bit funky. I adjusted the code so now the folder gets updated:

* When a file is opened (open or recent/fav lists)
* When a file is saved
* When a project is opened/saved
* When you pick a file to embed for a URL

This is a bit more consistent I think, but originally my plan had to be more selective about when the folder changes, but it turns out whatever the logic was there is lost in the mists of time because I don't remember ;-)

It's in 1.19.7+.
