### ISSUE TITLE
Heading not highlighted when expected

### ISSUE THREAD

**Issue by thnk2wn** [RickStrahl/MarkdownMonster#585]
Markdown Monster Version 1.19.9

In some cases, syntax highlighting is not showing headings styled as headings (blue text). The preview and end result is correct but the editor appears as if it is plain text.

In this case there is some trailing whitespace between the last bullet and the heading. Wiping out the spaces on the line before seems to correct it.

<img width="276" alt="2019-10-09_15-31-34" src="https://user-images.githubusercontent.com/120529/66513848-f9a19680-eaa9-11e9-83ad-820bd71412ac.png">

**Comment by RickStrahl** [comment]
I think that's actually the correct behavior because white space at the end of a line (or an empty line) is significant in a list. 2 spaces or more are considered a line continuation and so the heading is treated as if it was part of the previous line.

ie. this:

```markdown
This is a #NotAHeader
```

won't render a header.

FWIW, MM's markdown formatting in the editor is part of [ACE Editor](https://github.com/ajaxorg/ace). So if this looks like something you want to see changed it might be better to raise this issue on the Ace repo.

**Comment by thnk2wn** [comment]
Thanks. I guess it's a gray area as the whitespace isn't on the end of the list item lines but the empty line below and the markdown that way does in fact render correctly. My interpretation was this should result in line break not continuation (https://markdown-guide.readthedocs.io/en/latest/basics.html#line-return).

I do see some other editors like https://dillinger.io/ behaving the same though VS Code seems to be correct:

![image](https://user-images.githubusercontent.com/120529/66532675-28396480-eade-11e9-8ced-386addc6f976.png)

At any rate, not a big deal on my end just seemed odd. I can consider raising an issue for this or similar with the ACE repo. Thanks.
