### ISSUE TITLE
[Feature Request] Editable Dropdownlist with available Editors in Settings

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#587]
At the moment one has to type in the style by hand. It would be comfortable to have a short list of common editor styles to select with to option to type in any other editor like today.

I will have a look if I can make a PR for this. If you don't want this feature, just close this issue.

Happy coding
Tim

**Comment by RickStrahl** [comment]
The problem is the settings page is auto-generated from the type information. The various theme lists are not based on type information but are dynamically read at runtime based on file/folders on disk. Currently that's not supported - it'll require some sort of attribute or value converter that can generate the custom type which is not trivial to build and hook in generically.

Maybe some day, but not high on the priority list.
