### ISSUE TITLE
App restarts after switching theme

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#588]
Is there a reason why the App restarts after switching from dark to light theme or vise versa? If not I may have a look if I can do it without restart. 

Happy coding
Tim

**Comment by RickStrahl** [comment]
The theming has to be applied when the form is initialized so the main form has to restart. Since that's pretty much the entire app we might as well restart. I've looked at dynamically updating the theming but there are issues and artifacts that make this less than ideal.

I don't really see this as a problem since it's not very likely people will switch themes very often.

**Comment by timunie** [comment]
No it is not a problem, it is more or less an idea for a tiny improvement. In my program it works very fine and my few users like to toggle the theme at runtime. 

If you want me to I will have a look if I am able to do this in your program too. If you don't want me to, just close this issue :+1: 

Happy coding
Tim

**Comment by RickStrahl** [comment]
Sure, if you want to take a look and see if you can make this work reliably without a restart and without changing the way the theming is handled altogether, that's fine.

**Comment by timunie** [comment]
I will have a look and if I don't find a way I will close this issue.  I am using MahApps too and it works really well in my case.

**Comment by timunie** [comment]
Hi Rick,
I had a try and got it done the half way. Changing the `Brushes` is not the problem and the `Window` gets themed as well. The main problem is that there are tow diffrerent Controltemplates for the `TabItems`. 

What we need to do to get this done from my point of view:

- Define all `Brushes` that should change as `DynamicResource` instead of `StaticResource`
- Move all `Styles` into one or more `ResourceDictionaries` and just change the parts that differ (`Brushes`, `Sizes`, `Margins` ...). This is the main issue why it does not work yet. 
- Adjust the way the `Theme` is applied a little bit.

I don't know if you plan to update MahApps to v2.0.0 if it is released. There are many breaking changes. Maybe this would be a good time to have a look at this topic as well - What do you think?

Again a big thank for this good program. 👍 

Happy coding
Tim

**Comment by timunie** [comment]
ADDITION to the post above: I created a short gif to show the differences in `Light` and `Dark` Theme. Are the differences wanted or by accident?
![MM_Compareison_DarkLight](https://user-images.githubusercontent.com/47110241/67184775-c84b9380-f3e4-11e9-92c4-0b23b08c710a.gif)

Happy coding
Tim

**Comment by RickStrahl** [comment]
No not intentional :-) looks like an extra margin in the menu bar...

As to MahApps 2.0 - Jan helped me a long while back in early beta to get it running, but at the time it was too far off to release. I definitely would like to move onto MahApps 2.0 I think there a few things like the Window border and window movement at minimum that would be helped greatly by the new version. 

When I have more time I'd like to revisit that for sure and consolidation definitely would be good at that time - WPF styling in general is definitely not my forte - I'm just stumbling through that mostly especially when it comes to the global styles which were mostly lifted out of MahApps directly and slightly modified.

**Comment by timunie** [comment]
So let's wait until MahApps 2.0 is released (will be in a few weeks as Jan told me). I will try to get v2.0.0 implemented and raise a PR when I'm done, if you want me to. But please keep in mind that there are many breaking changes, so there might be some bugs in first weeks after upgrading.

I can also start updating now with the latest prerelease, if you want me to. 

Happy coding
Tim

**Comment by RickStrahl** [comment]
Before you start on this:

* Take a look at the old branch that has the changes - I think Jan did a bunch of the work already
* Lets make sure we do this when I have a little time to work on this because the last thing I want is to have a huge chunk of code coming that I don't have time to review. This is something that 

The old branch is here:
https://github.com/RickStrahl/MarkdownMonster/commits/MahApps_v20

Thanks Tim!

**Comment by timunie** [comment]
Hi Rick, /cc @punker76 

I will wait for your "go" bevore I start anything. As Jan is already working on that, we also have to ask him which part I should do to avoid more work than needed. 

Happy coding
Tim

**Comment by RickStrahl** [comment]
Closing as this is not a requirement.
