### ISSUE TITLE
[Feature Request] implement Autoupdater

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#589]
I like to stay up to date with my programs. In my own App I use [AutoUpdater](https://github.com/ravibpatel/AutoUpdater.NET) to provide a comfortable way to update the App on user side. 

Happy coding
Tim

**Comment by RickStrahl** [comment]
I don't want to go down this path. Originally MM had auto-updating features, but it just a source of hassles with permissions and flags for Anti-Virus and so on. 

Rather than deal with that we show a notice that a new version is available and let people download and install from the Web site (or using Chocolatey) which is only mildly more involved than a built in updater.
