### ISSUE TITLE
links in the generated toc fail if a header contains german umlauts

### ISSUE THREAD

**Issue by foxdancer** [RickStrahl/MarkdownMonster#591]
define a header in MD like this
`## Namenskonventionen für Forms`
the generated html for this is 
`<h2 id="namenskonventionen-für-forms">Namenskonventionen für Forms</h2>`

in the generated document outline this looks like
MD: `* [Namenskonventionen für Forms](#namenskonventionen-für-forms)`
HTML:  `<li id="pragma-line-14"><a href="#namenskonventionen-f%C3%BCr-forms">Namenskonventionen für Forms</a></li>`

best
Joachim

**Comment by RickStrahl** [comment]
Hmmm... I don't this this is specific to the Bookmarking - this is more focused on the Markdown output rendering of hashes, and the impact of URL Encoding on it.

Took a look and plugged this

```markdown
* [Namenskonventionen für Forms](#namenskonventionen-für-forms)
```

into Babelmark here:

https://johnmacfarlane.net/babelmark2/?text=*+%5BNamenskonventionen+f%C3%BCr+Forms%5D(%23namenskonventionen-f%C3%BCr-forms)

and the results are rather interesting. Looks like most Markdown parsers in fact parse this the same way as MarkDig (what MM uses) does. Yet it seems this produces HTML that can't be navigated.


Not really sure how this can be fixed. It looks like even plain HTML fails for either extended characters  or urlencoded text in the hash.

Try putting this into an empty document:

```markdown
* [Namenskonventionen für Forms](#namenskonventionen-für-forms)
  
The above produces a UrlEncoded hash:

```html
<li><a href="#namenskonventionen-f%C3%BCr-forms">Namenskonventionen für Forms</a></li>
```

We can also try:

```html
<li><a href="#namenskonventionen-für-forms">Namenskonventionen für Forms</a></li>
```

Finally another without any extended characters:

```html
<li><a href="#namenskonventionen-ohne-umlaut">Namenskonventionen Ohne Umlaut</a></li>
```

But both of those fail as well:

<ul>
    <li><a href="#namenskonventionen-f%C3%BCr-forms">Namenskonventionen für Forms (encoded)</a></li>
    <li><a href="#namenskonventionen-für-forms">Namenskonventionen für Forms (unencoded)</a></li>
    <li><a href="#namenskonventionen-ohne-umlaut">Namenskonventionen ohne Umlaut</a></li>
</ul>

## Namenskonventionen für Forms
More text here...

## Namenskonventionen Ohne Umlaut
More text here...
```

Running the first two hashes will fail no matter what I try - encoded or unencoded when I open the page in Chrome it'll open a file listing. The last link (without umlaut) works as expected.

@xoofx

**Comment by foxdancer** [comment]
Did another test (local files, Chrome, Firefox, Brave + Edge)...

It looks like this is caused by the embedded  ` <base href="file:/// ...   `

Navigation works as soon as I remove this

**Comment by foxdancer** [comment]
sorry - didn't want to close this

**Comment by RickStrahl** [comment]
Yeah sure there are issues with the local file link (it does work for non extended chars which is weird) but I can't remove that for preview rendering because that base ensures that related images etc. can be found since the document doesn't render out of the folder where the actual file is stored.

What happens if you publish the content or use it on a Web page for final HTML output (which doesn't include the header)? I'm guessing that it'll work fine in a proper browser view - it's only the local preview that's a problem.

**Comment by foxdancer** [comment]
Don't want you and me to spent too much time on this...
Will try to avoid these international characters inside of headers/titles ;-) 

thx for your efforts!
Viele Grüße

**Comment by xoofx** [comment]
Note that https://babelmark.github.io/?text=%23%23+Namenskonventionen+f%C3%BCr+Forms the output is somewhat expected

You can also configure markdig to use GitHub like auto-generated link (which is not the default)

**Comment by timunie** [comment]
Hi all,
it works for me if I edit these headers manually. I don't know if this can be done automatically. What i did is to give any header a unique `ID`. Can't this be done while processing the document? 

e.g.: This is the first subheader of the first header `1-1`.
```
<h2 id="1-1">Änderungen</h2>
```
and here is the outline entry:
```
* [Änderungen](#1-1)
```

I can provide a sample *.md-File if you need it.

Happy coding
Tim

**Comment by timunie** [comment]
Hi all,

i found an even better workaround :smile:, see image below:
![image](https://user-images.githubusercontent.com/47110241/67362484-6f5a3780-f56b-11e9-96e5-560934523156.png)

Here is the Markdown code i used:

```
# How to handle special chars (e.g. German "Umlaut" like äöüß) in Headers {#heading-link}
If you have any special character in your Markdown the links in the auto generated table of content will not work for those headings. 

But there is a workaround:
1. Go to Tools --> Settings
2. Set `Generic Attributes` to true (for more information visit https://github.com/lunet-io/markdig/blob/master/src/Markdig.Tests/Specs/GenericAttributesSpecs.md)
3. Give a custom id by instert `#` followed by your id into curly braces (`{#your-header-id}`) for the problematic headings

The id is not rendered in the resulting text:
 .``` markdown
# Your header with special char (ä,ö,ü,ß) {#your-header-id}
 .```
# Your header with special char (ä,ö,ü,ß) {#your-header-id}
```
## build in solution
I think a build in solution is possible, if we change the way the id is generated (for example implement an option to use numbered references. There are three ways I can think about:
1. Get the `html` from `Markdig`, loop through all nodes and change the `node.id`
2. Implement a second method to generate the `id` inside `Markdig`. (create a feature request at `Markdig`)
3. Creade a custom provider for `Markdig`

I myself would prefere the second method. What do you think @RickStrahl 

Happy coding
Tim

**Comment by RickStrahl** [comment]
No... this is not an option.

The way the IDs are generated is using a specific format that is part of the Markdown parsing engine. There are specific rules that are applied there. So the problem is formatting which seems to me might be a bug in the Markdig parser, but again according to the Markdown 'specifications' the parser is actually generating the proper value - it's the client side browsing that's at issue and as far as I'm concerned that's not really a big a concern because it's just meant as a preview. It works fine for hashes that don't have special characters so this is some odd browser quirk, although all browsers seem to be failing on this in the same way.

**Comment by timunie** [comment]
Yes, the value is ok but it does not help if the result don't work at the end useres side (in my opinion). 

In my opinion we should move this issue / feature request to the Markdown parser itself. But if you don't want, I will not do :+1: 

I am quite happy with the workaround discribed above.

Thank you for the quick response.
Tim

**Comment by RickStrahl** [comment]
So I finally took a closer look at this.

The problem here isn't the encoding either in Markdig or in Markdown Monster. That's fine.

The problem is the relative filepath via the `base` header in the `<head>` tag of the document. The problem is that this resolves to a `file:///` link in preview pages, and from what I can gleam `file:///` links don't navigate hash tags - at all, unless they are intercepted.



You can see this if you try the following:

* Create your headers and links that link them
* Now go File -> Save To -> Html -> Self Contained HTML Document
* Open that HTML document

Notice that the hash links work.

This is because the generated HTML page doesn't include a base tag. Even if it did it would contain document relative base tag likely and so links work just fine.

By comparison if you try the same thing with the preview generated HTML:

* Open your page for Preview
* Shift-F12 to open in browser 
* Note the URL
* Open the URL in an editor

Notice the base tag and file: links inside. None of the hash links will navigate in file mode.

Now, MM already does some interception of hash links in the Preview browser, so **there is a bug there** somewhere in that the URL isn't properly translated, but if you just dump the file to disk from a preview that will never work with hash links because of the file links.


Note the problem has nothing to do with the German Umlaut encoding!

**Comment by RickStrahl** [comment]
So I took a closer look at this and while this is mostly related to browsers not properly identifying UrlEncoded links properly after some experimentation I ended up posting an issue over on the Markdig repository:

https://github.com/lunet-io/markdig/issues/380

The issue is basically that the link generation for links uses a different encoding scheme than the ID generation used for auto-id generation. Although the Document View retrieves the link IDs using the same algorithm as the auto-links do, the issue here is in the link encoding. There are a few problems, but in this particular case it's that the umlauts are encoded by Markdig in links, but not in generated auto-links.

I'm not sure if there's a solution to fix this behavior short of your explicit link creation work around here because it looks to me that the link creation uses URL encoding while the ID generation uses some other mechanism, although **it definitely encodes as well** just differently.

**Comment by timunie** [comment]
Hi Rick,
thank you for your feedback and the deeper look into this issue. :+1: From my side this can be closed. I'm quite happy with my workaround.  

Nevertheless I want to show you one thing that I found in a different software. They escape the german umlauts by replacing them with the base char:
```
## Präambel
<h2 id="praambel">Präambel</h2>
```
link: https://github.com/madskristensen/MarkdownEditor

Happy coding
Tim

**Comment by RickStrahl** [comment]
So I think the solution here is simply to UrlDecode the hash before trying to locate the ID. This may not work for everything but it should most definitely work for the umlauts.
