### ISSUE TITLE
Adding favorites: are the added spaces in the name intentional?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#596]
When adding a file to the list of favorites that has consecutive capital letters, MM adds spaces between them. Is this by design? I find it surprising, but I don't want to insist that it's a bug since it might be something you intend. In case it is a bug, I wanted to at least mention it.

![image](https://user-images.githubusercontent.com/42981101/67604330-2d2e2300-f730-11e9-8fe4-3ebadc8a95e8.png)

**Comment by RickStrahl** [comment]
Sort of :-) The default code de-camelizes text so if you have camel case text or snake case text it'll try to turn it into readable text. Doesn't work so well if you have a bunch of upper case letters strung together.

**Comment by RickStrahl** [comment]
So, not really seeing a good way around this for reverse camel conversion. Reverse camel conversion just can't be reliable because there are scenarios where you have to account for names or single letter words like `A`.

Since this is just a pre-generated value that you can change, I'm not going to do anything about this and just leave this as is.
