### ISSUE TITLE
Enable Spellcheck feature

### ISSUE THREAD

**Issue by PrimeJoker** [RickStrahl/MarkdownMonster#597]
Enabling the Spellcheck feature in **Toots** > **Settings**. Trying to use this for editing it some times/randomly gets disabled. Also, right-clicking removes the correct word to replace it with.

**Comment by RickStrahl** [comment]
Spell check gets disabled if there are too many spell checking errors in the active page you're viewing. I can't remember the threshold, but it's pretty large. Usually this happens when you have the wrong language selected. 

The reason for this is with a huge number of errors the page becomes difficult to read/parse and things start slowing down, so MM disables spell checking and you have to manually re-enable it.

Are you sure you have the right language selected for spell checking?

**Comment by PrimeJoker** [comment]
I have the "**en-GB**" language selected. I have updated my installed version to the latest MM release. I don't seem to have a lot of spell check errors on my markdown document. 

Thanks for the information. I will keep you posted if any issues arise.

**Comment by RickStrahl** [comment]
So, does it work with the correct language?

**Comment by PrimeJoker** [comment]
Still the same @RickStrahl. It keeps deactivating every so often. I know have it disabled for now. Is it something you can look into? Or just leave it as a feature? If it's an intentional feature then you can clone this ticket.

**Comment by RickStrahl** [comment]
I need a repro scenario. I don't see any issues with spellchecking either in en-US or de-DE which I both use. 

Can you send me a document that you're working on where it fails along with the language you're using. Any other steps if any would be helpful.
