### ISSUE TITLE
Document Outline remains after documents are closed

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#599]
Open a document. Open its document outline. So far, so good.

![image](https://user-images.githubusercontent.com/42981101/69450221-867a7980-0d11-11ea-9b31-50f7e5952d6b.png)

Close the document. The document's outline stays in the left-hand pane, and probably shouldn't.

![image](https://user-images.githubusercontent.com/42981101/69450263-9b570d00-0d11-11ea-9d1f-9461a58f5c35.png)

As you can see, the left-hand-gutter icon is missing, but the left-hand pane still shows an outline for a document that isn't loaded.

**Comment by bcmadsen** [comment]
Can we reopen this issue? I'm not sure it's fixed quite right. Either that, or there's now a new issue that needs some attention.

If you close a document, the "Is Document Outline Visible" setting gets set to false, but then never gets set back to true again once any document is open again. After that point, in order to see the document outline, I have to turn on the "Is Document Outline Visible" setting manually.

Can you please take another look at this?

**Comment by RickStrahl** [comment]
Hmmm I think I see what the issue is here. Because the configuration value is set it permanently toggles the Document Outline Visible flag and so it has to be enabled again. I think it needs to be left at just hiding the outline explicitly as the code did before with the addition of activating another panel when the last tab is closed.
