### ISSUE TITLE
"This page can’t be displayed"

### ISSUE THREAD

**Issue by ButchersBoy** [RickStrahl/MarkdownMonster#6]
Getting this in the browser component quite a lot.  Strangely seems to happen quite a bit after I hit CTRL+S.  I know the document is valid, often I hit SPACE > BACKSPACE and the preview comes back.

ver .27

**Comment by RickStrahl** [comment]
Hmmm... I am a habitual Ctrl-s'er and I haven't seen that myself.

I'm guessing what's happening is that there might be multiple refreshes overlapping. The way the preview works is that it renders a temporary HTML file in the same folder as the markdown file which is rendered and then immediately deleted. If there are overlapped updates it's possible that a secondary render gets its HTML file deleted.

I just played around with this here though and I can't make that happen. Even rapid fire Ctrl-s on a very large MD file works.

Any more hints on what's happening when it doesn't work? Very slow machine by any chance?

**Comment by RickStrahl** [comment]
I've made a change so that the rendered HTML file isn't deleted until the document is closed. This should avoid any issues with the file not being there and also allowing you to navigate back and forth.

The downside of this fix is that if MM crashes there will be left over html files (which do get cleaned up next time you open and properly close the file).

**Comment by ButchersBoy** [comment]
.29 looks much better

**Comment by RickStrahl** [comment]
Cool.

IAC, leaving the file around is probably a better idea anyway so you can navigate links and come back with back button - that wasn't working before because the file wasn't there anymore.

Thanks.
