### ISSUE TITLE
Incorrect handling of the underscore character in the editor

### ISSUE THREAD

**Issue by sanychsamara** [RickStrahl/MarkdownMonster#600]
It appears that markdown editor window incorrectly highlights and italicizes any string between underscore characters. Even if underscore is part of the word and not preceded/followed by a whitespace.

Internal preview renders underscore correctly.

Steps to reproduce
Paste following inside the editor window
```
aaa_aaa bbb_bbb
ccc _eeee dddd_ fff
```

Editor will incorrectly highlight and italicize "aaa", "bbb", "eeee" and "dddd".
Preview will correctly highlight only "eeee" and "dddd"

Tested with v1.20

**Comment by RickStrahl** [comment]
Yes so this is an issue in the ACE Editor component which provides the Markdown syntax coloring logic in MM.

Now, whether that's correct or incorrect is unfortunately up for debate. Check out what Babelmark shows for this:

https://johnmacfarlane.net/babelmark2/?text=this+this+test_value+is+different+than+this_testvalue1.

Split between how various renderers implement tihs. MarkDig (which is what I use for the preview)  uses one way and many others including Pandoc (which arguably is the most popular across platforms) uses what the editor uses.

So while this can be raised as an issue on ACE Editor I see low probability of this actually getting fixed because it's based on interpretation of the spec and from the looks of it they're following what Pandoc produces.

I agree with your preference however as this causes much less conflict especially in the editor.
