### ISSUE TITLE
Add option to insert pagebreak

### ISSUE THREAD

**Issue by rockfordlhotka** [RickStrahl/MarkdownMonster#603]
I am writing book content using MM, and there are cases, especially at the end/start of a chapter, where there must be a pagebreak.

In searching the web I originally found that if you are using pandoc/latex to generate your PDF output that you can leave latex statements in the text, such as `\newpage` (??). The problem I've encountered is that it is _super hard_ to get professional looking PDF output using pandoc.

Of course MM generates beautiful PDF with its Send To option, so that'd be so much easier. In further searching the web I recently found that you can leave HTML in the markdown. This triggers a page break:

```html
<div style="page-break-after: always;"></div>
```

Today I tested, and this does work in MM with its PDF generation. Very nice!

But this is very obscure and undiscoverable. The pandoc answers are much higher in the google results - I'm not entirely sure how I found this HTML solution actually.

I think it would be quite ideal if MM had a built-in formal solution to this problem. Whether that be a toolbar option to insert this HTML, a custom tag in markdown (why doesn't markdown do this??), or something.

**Comment by RickStrahl** [comment]
You already found the solution of adding the page-break through styling.

FWIW there's a stock snippet for this:

Type `pagebreak` in the editor on an empty line and it will insert that `<div>`

![image](https://user-images.githubusercontent.com/1374013/70600912-09feec00-1b95-11ea-850c-33aa084c3850.png)

so that should make the process a little easier. 

It's also possible to add custom buttons to the toolbar using Configuration via `Editor.AdditionalToolbarIcons`.

[Adding Custom Icons to the Toolbar](https://markdownmonster.west-wind.com/docs/_5im10bjpw.htm)

I've just added 'pagebreak' as a command so you can now do:

```json
 "Editor": {
    "AdditionalToolbarIcons": {
      "Paragraph": "pagebreak"
    },
```

which gives you an icon on the toolbar.

![image](https://user-images.githubusercontent.com/1374013/70605539-cdd08900-1b9e-11ea-8570-f884a3542a21.png)

> Note you need to install the latest preview version (post 15.0 which is not quite up yet, check back).

Finally there's one more option that might be easier for you. Perhaps you can assocaite the line break with a specific HTML tag like `<h1>` or `<h2>`and have  a page break before in which case you can define the `page-break-before: always` on the style in `theme.css`:

```css
h1 {  page-break-before: always }
h1:first-child { page-break-before: auto }
```

To do this:

* Right click on the preview
* Edit Preview Theme
* Make a copy of the active theme you're using (if not a custom theme already)
* Change `theme.css` with the styles above

Save, and change your active preview theme (on the status bar) to the new/updated theme.
Now when you type `# Heading for chapter` you get a page break.

As to discoverability - I hear you, but I think this doesn't warrant a default icon on the toolbar or edit menu, just because printing and PDF isn't a primary operation.  I think adding a topic in the help file as a recipe (with most of what I have here) might be a good idea though.

**Comment by rockfordlhotka** [comment]
Thank you, this is helpful.

Is there not a way to switch themes without renaming the files (like the original and this new one I'm creating)?

**Comment by RickStrahl** [comment]
Sorry I didn't say that right. You create a new theme with whatever customizations you want to make. If you already did that and have a custom theme, then you just update that theme with these changes. 

Once you have a new theme (which is just a new folder in the `PreviewThemes` folder, you can select that from the preview theme selection drop down and you can make as many changes as you need to for that theme.

The reason for the separate theme and folder is that the original themes get overwritten during updates - so if you make your changes in those your changes would be lost.

**Comment by RickStrahl** [comment]
FWIW I also just added an additional sub-dropdown to the toolbar with a few additional items that available but don't warrant real estate on the main toolbar :-)

![image](https://user-images.githubusercontent.com/1374013/70661489-7ff06b00-1c08-11ea-8446-314815f90122.png)

**Comment by rockfordlhotka** [comment]
I've created a new theme folder. I don't see this dropdown to pick the theme though? What am I looking for?

**Comment by RickStrahl** [comment]
Bottom right on the status bar:

![image](https://user-images.githubusercontent.com/1374013/70677271-cb1f7380-1c32-11ea-86e7-8846c28c485d.png)
