### ISSUE TITLE
Preview Split Displayed below?

### ISSUE THREAD

**Issue by mlevison** [RickStrahl/MarkdownMonster#604]
I'm using markdown in general for notetaking from papers and other sources I read online. Even on a 13" Display - I place by browser or PDF on the left. The editor on the right. If display the preview pane it fights with the editor for limited space side to side. Better would be displaying the preview at the bottom so I can see briefly how things look.

Is this a feature you would consider adding?

**Comment by Smurf-IV** [comment]
Also the ability to add a frame to the bottom, so that enhanced parsers can report "Real-time" Logging in a "Wide" window

**Comment by RickStrahl** [comment]
I'm looking into this, but the short answer is: Probably not. 

The editor/preview have a ton of configuration associated with positioning and I don't see  a good away to translate that into a vertical layout without breaking all the existing configuration. While I see the utility I think vertical stacking tends to be rare giving monitor sizes (ie. wide rather than the tall aspect ratios). Then there's the whole thing about how synching works in a stacked layiout. side by side we can try to be consistent with matching up cursor with preview text.

**Comment by RickStrahl** [comment]
@Smurf-IV Smurf - if you need to do this from an addin you can probably insert your own frame just above the status bar. 

Please file a separate issue for separate feature suggestions.

Thanks.

**Comment by RickStrahl** [comment]
I've looked this over some more and this would introduce a lot of changes, related to keeping window sizing and saving intact and honestly I don't see this as something that a lot of people would need. '

Given the pain to utility factor I'm going to say no to this - if others think this is something they really need they should add their voice to this issue. In the meantime I'm going to close this issue.
