### ISSUE TITLE
Bug: View Html Source goes wild.

### ISSUE THREAD

**Issue by jovibor** [RickStrahl/MarkdownMonster#608]
It's been here for a while, few versions at the very least.
When clicking subj menu, on arbitrary document, cursor starts blinking very frequently, and the preview pane (*_MarkdownMonster_Preview.html*) starts scrolling by itself up and down.
winver: *18363.535*
![image](https://user-images.githubusercontent.com/5625787/71386015-92ba6500-2636-11ea-80ca-533670723b1e.png)

**Comment by RickStrahl** [comment]
Yes I can duplicate that. Looks like the preview sync is not working correctly for HTML documents. 

If you toggle off the Preview (F12) the HTML can be edited with no issues. It also works better with the preview on and only editor -> preview formatting, but it's still not right.

There's been a ton of work that was done to get the Markdown two-way sync to work, and that probably has a few regressions for the HTML preview. 

This will take a bit to review and get fixed.

**Comment by RickStrahl** [comment]
So this issue has been addressed as well as a related issue.

The first issue is the preview jitter which was caused by the addition of a file watcher some time ago to monitor a document's updates. The file monitor also sees changes to the preview markdown file, which previously was being edited as is in the editor. The problem is editing that file updates the preview, which updates the editor, which updates the preview - you get the idea... The first fix was to edit the source file with a different name and also disable file change events to fire on the preview html file (which triggered the initial chain of change events).

The second issue was that the preview syncing was no longer working for HTML documents meaning that if you made changes to the editor document the changes weren't showing up in the preview editor. This was due to a number of changes in the preview sync logic that is specific to markdown processing which includes line numbers in the generated HTML source that are then synced up with the editor. These don't exist in the HTML Source view... To fix this there's now a separate preview sync path used for HTML documents that attempt to sync the document based on line contents. This isn't going to work 100% of the time (especially if you have empty or tag only lines), but it should work reasonably well for text content and scrolling through an HTML document.
