### ISSUE TITLE
Code blocks that carry over two line introduce space when saved to PDF

### ISSUE THREAD

**Issue by adilio** [RickStrahl/MarkdownMonster#609]
Hi Rick,

Detailing the issue discussed over Twitter here, along with steps to reproduce. Again, this may just be a limitaiton of PDF format by nature, so perhaps not something solveable here. Still wanted to show you what @gep13 and I are seeing.

## Steps to repoduce

Take the following PowerShell code and save it as a PowerShell code block in a markdown file:

```powershell
choco install package-with-a-really-really-long-name --source . -y --params "'/LicenseFile:<FULL_PATH_TO_LICENSE_FILE>'"
```

Then, open that MD file in Markdown Monster, and select `Save to > Save to PDF`. Use the default values.

You should see the PDF generated a code block that carries over 2 lines. Now, highlight and copy that code, and paste it into a PowerShell Terminal.

## Expected behavior

The parameter should paste into the terminal as follows:
```
--params "'/LicenseFile:<FULL_PATH_TO_LICENSE_FILE>'"
```

## Actual behavior
The parameter pastes into the terminal with a space between `/LicenseFile:` and `<FULL_PATH_TO_LICENSE_FILE>`, as follows:
```
--params "'/LicenseFile: <FULL_PATH_TO_LICENSE_FILE>'"
```

## Environment data

```
Windows 10 Enterprise 1909
Markdown Monster v1.20.6
Portable mode
[default settings]
```

## Additional Note

Just thought I'd ask, since I can't find this setting. When code blocks are generated in Markdown Monster, each block is labeled in the top right corner with the language, like so:
 
![image](https://user-images.githubusercontent.com/21287462/71386595-d1eba600-25a3-11ea-8695-0750958712d0.png)

Is there any way to turn this off, as it blocks the code text in PDF?

Thanks for such a wonderful product, very customizeable and well worth the registration cost!

**Comment by RickStrahl** [comment]
So I think the issue here is that when the document gets created, the lines are split and the code block is wrapped. Since there's no scrolled content inside of a PDF document, I think that's probably the behavior you would expect in a PDF document and the break is more or less appropriate.

You say you see a space - I actually see a line break. If I copy the text from the code into notepad I get:

![image](https://user-images.githubusercontent.com/1374013/71405778-7ab4f800-25da-11ea-939e-937930e25bda.png)

which honestly seems reasonable to me, even if it's not the intent here.

However there are some other related issues that are more troublesome. For example, it looks like paste operations often remove extra blank lines from code snippets (presumably because Chromium fixes up the empty space via styling rather than blank lines). Here's an example:

![image](https://user-images.githubusercontent.com/1374013/71405883-bf409380-25da-11ea-9498-a15bb56a3f04.png)


Unfortunately, I don't think there's a solution to this because we depend entirely on the conversion provided by `wkhtmltopdf` which uses the Chromium engine to perform the conversions. It'll do whatever it does and there's no control. I did muck around a bit with the way the print styling is handled, but I can't find a way to make the code not wrap (nor do I really think we'd want that because it would just be cut off which is not an option for 'print' which is what PDF is intended for.

I've moved your **Additional Note** to a new issue in #610.








the text actually splits onto multiple lines in the PDF document and the PDF treats the line breaks as breaks. So

**Comment by adilio** [comment]
Appreciate the feedback, @RickStrahl. I had a feeling it would be something along these lines.

As for copying and pasting from PDF's, the use case here is to a PowerShell console. It's the same with some other terminals as well. I feel that copying and pasting of code blocks into terminals by users is a real and valid use case, and separate from copying and pasting into an editor. And users that do that are often less technical, and may not understand the code well enough to troubleshoot. Just wanted to make that distinction clear.

I have proposed another solution internally to not convert to PDF, and have an HTML version of doc to point folks to. Hopefully that works.

Sincerely appreciate your efforts and explanation!

**Comment by RickStrahl** [comment]
Sure cutting and pasting is a valid use case. But a PDF is meant to be more of a print document than an interactive document, so text fidelity has always been a questionable issue in general. Heck in some cases PDF is just a set of generated JPEGs :smile:

I understand that it would be nice if it worked, but there's likely no solution. Even if a bug was filed with wkhtmltopdf I doubt they would consider this a worthwhile use case to fix because the focus of the PDF is for display rather than text spacing accuracy. Looking at PDF output from a printed HTML page in Chrome produces a similar result, so this 'behavior' is inherent to the Chromium engine processing the document for 'print'.

As to presentation - HTML content is better if you need to capture text for sure. But not as portable.

**Comment by adilio** [comment]
Yeah, sounds good @RickStrahl, and thanks for checking!

Not sure what your procedure is for these types of issues, but I'm ok with you closing this one. Thanks again for your efforts!

**Comment by RickStrahl** [comment]
i'm going to leave this open for a little while, in case somebody has any other ideas, but I think this is not going to be a fixable issue.

**Comment by RickStrahl** [comment]
Closing since I don't think there's a fix for this from this end. This will need to be fixed in wkhtmltopdf or Chromium and even then I'm not sure that would get fixed because it's meant for displaying properly, not necessarily for copying properly from PDF.
