### ISSUE TITLE
Preview is jittery while typing math

### ISSUE THREAD

**Issue by ChrisgammaDE** [RickStrahl/MarkdownMonster#612]
When updating anything in a markdown document with Math in it, the preview is constantly gittering while refreshing it.

![ezgif-3-caf751b842d0](https://user-images.githubusercontent.com/18314920/71563619-04f5d400-2a93-11ea-9dc3-cff0e31cf1c4.gif)

This is pretty annonying and ruining my attention.
Maybe a virtual dom rendering could help about this.

**Comment by RickStrahl** [comment]
Yeah anything that requires `<script>` tags (including implicitly embedded ones such as math or Mermaid charts) needs to refresh the entire page. DomDiffing would work with static HTML/Markdown but with this dynamic stuff if any of the dynamc elements change the script has to re-render the items. The way all of these work currently is that the page is re-rendered. What you're seeing is the math lib re-rendering the equations. IOW, the slowness is the math rendering.

I'm not sure there's a good way to make this generic so that only the current equation/graphic/gist etc. is updated. Most of these libraries work at the page level and have to re-render everything.

It's a great request, and it's something I've not spent a lot of time thinking about. Just not sure what the solution is offhand.

**Comment by RickStrahl** [comment]
So I looked into using a Virtual DOM, but unfortunately that isn't helping the preview rendering because the preview renders additional info like line numbers into the HTML output which cause the DOM to actually change for any changes following the current line. Also the two diffing libs I tried both had problems properly diffing very large documents resulting in invalid HTML where direct assignment worked without issue. This is likely due to running inside of the IE WebBrowser control rather than Chromium.

I don't have a good answer to this at the moment unfortunately.

**Comment by timunie** [comment]
hi @RickStrahl ,
is there a way to enable / disable the rendering of `Math` elements? If yes, the user could activate it to preview the result and deactivate it for a better typing experience.

Happy coding and a nice weekend,
Tim

**Comment by RickStrahl** [comment]
Yes there's a flag - MarkdownOptions.UseMathematics. But currently that only controls whether the Markdig math translations are loaded. 

I've added a tweak that if not enabled the `MathRenderExtension` also won't run and embed the `<script>` code. 

fccbf3c40ec757682ae63bbf83f62bef8f81e1d6

The script is what triggers the full page refresh and the flashing. It's sort of possible to toggle that at runtime by using a **Code Snippet** with the Snippets extension, but at that point the script has been embedded and it will continue to run and refresh the entire page until the preview is completely reloaded.

Hacky, but this works:

![image](https://user-images.githubusercontent.com/1374013/72226272-7cb40c00-3533-11ea-94fe-f56501e72111.png)

**Comment by timunie** [comment]
Hi Rick,

thank you for the explanation and the workaround. In my simple mind (note: I am an engineer and not a programmer, so sometimes my mind produces impossible stuff) there should be a simple `bool` which toggles to auto reload. This could be checked via a `ToggleButton` in the Toolbar. And next to this `ToggleButton` there is a Refresh-`Button` to reload the page whenever the user wants to. 

If you want me to I will try to make run and, if I was successful, make a PR. You can decide then if you want it or not.

Happy coding 
Tim

**Comment by RickStrahl** [comment]
Sure but there are a million settings and not all of them belong (and surely don't fit) in the toolbar and frankly this isn't a highly visible item.

**Comment by timunie** [comment]
Hi @RickStrahl ,
I tried a few things and one of my ideas I would like to show you. I will not make a PR of this because I think it would be easy for you to adopt it, if you find the idea good. 

I added a `bool` which indicates, whether to run the `previewUpdateEvent` in `JS`. This bool can be toggled in the Toolbar, so the user can decide if he wants the jittering preview but with the equations rendered or no jittering but the equations shown as plain text until he refreshes the browser. For  a more convenient refresh I added a global shortcut `Ctrl+R`.

https://github.com/timunie/MarkdownMonster/tree/NoScriptTest 

Here is a short gif:
![MM_AutoRefresh](https://user-images.githubusercontent.com/47110241/72433609-f9482400-3799-11ea-8f8c-c1c2416e5b5a.gif)

\cc @ChrisgammaDE 

Happy coding,
Tim

**Comment by RickStrahl** [comment]
@timunie, thanks for the example.

There's a better way most likely though by setting the **Allow Script Tags in Markdown** menu option (upated in latest preview builds). Now, previously this didn't work for immediately fixing the preview because it would still embed the script tag as part of Math RenderExtension which runs **after** the script filtering usually happens (that might require fixing as well). 

Anyway, in the latest update you can disable the **Allow Script Tags in Markdown** setting and it will now immediately refresh the preview and properly check in the MathRenderExtension to not expand any script. Additionally I added a shortcut key to the menu option so you should be able to access the option now with the `Alt-E-T` menu shortcut.

Here's what the updated menu looks like:
![image](https://user-images.githubusercontent.com/1374013/72868315-bdbfc500-3c85-11ea-8720-4c1db001b2f3.png)

The fix is here: 440553060d23e8b34db5e93ca6393929415dc3d7
