### ISSUE TITLE
Editor has an annoying delay when scrolling through large files

### ISSUE THREAD

**Issue by paulmrozowski** [RickStrahl/MarkdownMonster#614]
I have a file with around 3500 lines / 24K words / 161K characters. When scrolling up/down via the arrow keys there is a noticeable delay as you scroll. I thought it might be related to the render refresh, but the delay still appears when you shut off the editor sync (Preview sync mode: None) - although it is slightly faster.  The weird part is if you just hold down the up or down arrow, scrolling the text seems reasonable. But if you do something like hit the down arrow, stop for .5 second, then hit it again, you'll get this delay.

**Comment by RickStrahl** [comment]
Can you send me the file to look at? What happens when you turn off the preview altogether (F12)?

**Comment by RickStrahl** [comment]
So I created a huge file like this by copying a really long blog post like 10 times and I can see quite a few problems at that size **when the preview is set to two-way syncing**. If I switch to **preview to editor** then things are much better.

The problems I see are that the editor gets jumpy as it tries to refresh the preview in a timely fashion, causes a delayed scroll operation which in turn scrolls the editor because it's beyond hte scroll delay timeout that is supposed to prevent that. 

But that sounds like a different problem than what you're describing. The editor scrolls fine for me with the arrow keys as long as not in two-way sync mode.

**Comment by paulmrozowski** [comment]
Yeah, the delay goes away completely if I toggle off the preview. I normally run in one way sync (editor -> preview).

 I'll send you a sample file that reproduces the issue.

**Comment by RickStrahl** [comment]
Give 1.20.8.3 or later a try. For large files it suspends the refresh on up/down keys.

Looking into a different way to refresh the display on navigation only operations. Right now the code uses same codepath for updates and scroll to operations which in this case aren't necessary because the doc didn't change. 

Most of the overhead comes from the re-render of the large doc in the browser which has to run on the UI thread.

**Comment by RickStrahl** [comment]
Another update here:

I've completely refactored how non-edit navigation and click operations affect the preview, which has resulted in some drastic performance improvements - especially in large documents - for:

* keyboard navigation
* click selecting content in the editor
* document scroll via scrollbar or mousewheel

The editor now also checks for document size and expands the preview sync update timeout with larger documents which reduces preview induced delays. With your 3000 line doc you probably don't have that issue yet, but with larger docs (10k+ docs) the preview refresh cripples the editor. With the longer timeout the preview isn't triggered usually unless you explicitly stop typing for a couple of seconds. 

Give 1.20.8 a try and see how you fare with your large document. It should be much better.

**Comment by paulmrozowski** [comment]
Nice, much better. It seemed to make issue #615 better as well.

**Comment by RickStrahl** [comment]
#615 was fixed separately. If that's working for you now, please close that issue.
