### ISSUE TITLE
Right-clicking on text context menu flashes the first time you click

### ISSUE THREAD

**Issue by paulmrozowski** [RickStrahl/MarkdownMonster#615]
I've noticed that if you select some text to do something like format a table, right-click on it, the context menu appears then immediately disappears. If you right-click on it again it works. This feels like something is refreshing causing the focus to be shifted to something else (which causes the context menu to disappear), but who knows. 

This only seems to occur in larger files. 
![2020-01-03_11-30-25](https://user-images.githubusercontent.com/1640831/71735502-a1fe9700-2e1c-11ea-8d17-843d2756edba.gif)

**Comment by paulmrozowski** [comment]
This is definitely a timing/refresh issue. If I select the text, but then wait a second or so, then right-click it works as expected.

**Comment by RickStrahl** [comment]
There are other instances where this happens and I haven't been able to figure out where this issue originates from. I think it's happening because somehow the context click is actually fired multiple times. This causes the menu to be opened multiple times and the delayed close of the first is closing the context menu. I've added some logic that should prevent multiple context menu openings.

Adding this change I can no longer duplicate the closing failure reliably. I still see it if I try hard enough but it's now very rare (probably related to a slow doc refresh somewhere which shouldn't be a big issue).
