### ISSUE TITLE
Provide installation via Windows 10 Store

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#617]
Hey @RickStrahl ,

this is just an idea. Maybe you could get more customers when MM is available via Windows 10 Store. 

Happy coding and a nice weekend,
Tim

**Comment by RickStrahl** [comment]
Not going to happen unfortunately.

Looked into it a while back and while MM can run just fine in the crappy store model, there are things that we do that isn't allowed. Addin loading (dynamic loading of assemblies), scripting in Addins, executing shell commands (plus a few others) -  none of which is allowed in store apps.  When I submitted the app a while back it got shot down.

In addition the store model adds a huge burden for publishing - with the rapid release schedule of updates of MM the store would always be trailing behind because it's such a pain in the ass to publish to it.

Without these things, MM would be greatly diminished...

I suspect this might also be why apps like VS Code are not store apps.

**Comment by timunie** [comment]
Hi Rick,

many thanks to the lightning fast answer. I didn't knew that it is so hard to get access to the store. I thought it would be as easy as in Linux. Moreover I thought that the Store was opened to all Programs, but it seems this was a wrong information. 

Should I close this issue?
Tim

**Comment by RickStrahl** [comment]
What you're refrerring to is more like [Chocolatey ](https://chocolatey.org)which we do support and update frequently.
