### ISSUE TITLE
KeyBindings -- bugs and suggestions

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#618]
I see the KeyBindings.json file. Let me offer the following. Maybe of interest, maybe not.

1. There are no key bindings for turning selected text to upper or lower case, or for capitalizing it. I realize that MM isn't primarily a text editor, but this would be a useful addition to the list of key bindings.

2. I'd love a keybinding for making text both bold and italic at once. (Ctrl+Shift+B, maybe?) When you select text and then bold with Ctrl+B, you lose the selection and have to select again before using Ctrl+I to italicize. Would be nice to do that all in one go.

3. ZoomEditorUp happens consistently and immediately. ZoomEditorDown needs a few keystrokes each time before it takes. This feels like a bug.

4. ZoomEditorUp increases the width of the right-hand scrollbar, but ZoomEditorDown does not have the opposite effect. Alternating between them therefore results in an _enormous_ scrollbar. This definitely feels like a bug. I'm kinda thinking ZoomEditor shouldn't affect the scrollbar size at all, but if we're going to increase it, there should be some corresponding way to reduce it again.

5. If you ZoomEditorDown enough times, text disappears from the editor window completely, and I found no way to get it back. (ZoomEditorUp just made the scrollbars even more enormous, but didn't bring back the vanished editor text.) This also definitely feels like a bug. Also a suggestion: maybe there's value in a ZoomEditorRestoreDefault?

**Comment by RickStrahl** [comment]
Hmmm... yes I see this but only via the shortcut keys. 

FWIW you can use Ctrl-Mousewheel to change the size as well and that doesn't exhibit this behavior - which is weird because it should actually fire the same code (but I have to look). Also you can reset on the status bar where it shows the editor zoom level - but it won't fix the oversize scrollbar and overlays.

I'll take a look.

**Comment by RickStrahl** [comment]
As to keybindings you can more or less do this with additional keyboard commands. I just made an additional change that should make your scenario possible.

https://markdownmonster.west-wind.com/docs/_5im10bjpw.htm#template-content

The template syntax for:

```json
"AdditionalToolbarIcons": {
    "Bolt": "html|<b><i>{0}</i></b>"
}
```

will create the dual key. No hotkeys for that though.

**Comment by RickStrahl** [comment]
Did some fairly major refactoring of the key manager so that it can take advantage of generically accessing the editor 'commands' that drive the hot key selection operations.

Basically I've refactored all those commands into a single operation with a parameter now:

```json
{
    "Id": "EditorCommand_Bold",
    "Key": "Ctrl+B",
    "CommandName": "EditorCommand",
    "CommandParameter": "bold"
  },
  {
    "Id": "EditorCommand_Italic",
    "Key": "Ctrl+I",
    "CommandName": "EditorCommand",
    "CommandParameter": "italic"
  },
  {
    "Id": "EditorCommand_Href",
    "Key": "Ctrl+K",
    "CommandName": "EditorCommand",
    "CommandParameter": "href"
  },
...
```

This simplifies the code and removes a bunch of mappings that had to be done explicitly in code.

This also means that now **all** editor 'commands' can be accessed like this even if a mapping does not exist. This includes commands like `small`, `underline`, `bolditalic`, `uppercase`, `lowercase`, `mark` and so on. 

You can also create your own commands using `html|tag` or `html|<b><i>{0}</i></b>` templates.

More info here;
http://markdownmonster.west-wind.com/docs/_59l0izpoe.htm#editor-commands

**Comment by bcmadsen** [comment]
I have installed MM 1.20.15.6, and I see all of these changes. I am very, very happy with all of it. Thank you so very much!!

**Comment by RickStrahl** [comment]
Thanks for raising these issues - resulted in some nice improvements into how keybindings are handled.

This won't address all bindings, but it will open up a ton of functionality with additional editor commands/operations. The templating one especially might be very useful and doesn't rely on the Snippets addin for simple one line wrappers.
