### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by pmgeuze** [RickStrahl/MarkdownMonster#622]
I am getting this error when attempting to Save To-> HTML (embedded)

![image](https://user-images.githubusercontent.com/12847134/72924696-5f472500-3d1f-11ea-9a9a-3ff1ae175ec8.png)

I also get an error when attempting to Save To-> PDF

![image](https://user-images.githubusercontent.com/12847134/72925376-94a04280-3d20-11ea-941b-6e055d371556.png)

Is there a means that I can further access the the 128GB RAM on my machine to process these documents?

Is there another way that I can alter functions in MM to process these files?

**Comment by RickStrahl** [comment]
MM runs as a 32 bit process so it'll be limited to 2gb of RAM. If your documents are that large though they are unlikely to work at least with wkhtml2pdf.exe (which is what MM uses for PDF conversion). Not sure for HTML packaging, but the issue there likely is that the doc gets loaded into an internal DOM for processing. Even if this wouldn't crash for memory errors, I suspect it would a crushingly long time to run.

What exactly are you doing and how big are your documents?

FWIW, MM's source code is available and you can recompile it with a 64 bit target which will give you the extra memory support. It's a single flag change. MM runs in 32 bit mainly for better compatibility with the browser component for the preview.

**Comment by pmgeuze** [comment]
Mr. Strahl,

Thank you for the quick response. I am writing computer forensic reports on a child molestation case. The case involves about 20 devices which require chain of custody pictures, a number of tables and such.

My programming skill is generally at the Frankenstein (monster) level of hacking at other people's code. How would I be able to try to rebuild in a 64bit environment?

Pieter-Michiel

**Comment by RickStrahl** [comment]
Is it possible to send me that file or provide it somewhere so I can take a look?

I do know that wkhtml2pdf we use definitely has problems with massive files and I can't fix that. But I might be able to do something about the html packaging. I suspect not because my guess is the memory issue occurs when we load the final HTML document into the DOM for post processing but worth a look at least.

**Comment by RickStrahl** [comment]
Best suggestion I have for large file PDF printing is this:

* View in Web Browser
* Use Print to PDF (may work better)
* Use Print and print to a third part PDF Driver (Microsoft PDF)

I'm not sure if that will yield better results but 

More info in this documentation topic:
http://markdownmonster.west-wind.com/docs/_4u512gngv.htm#built-in-printing

**Comment by RickStrahl** [comment]
For the PDF printing I've updated wkhtmltopdf to use the 64 bit version which might work better for creating larger documents as it'll have access to more memory. Since you're getting an error this may not help, but it's worth a shot - I noticed with the updated version that it works on much larger documents than previously.

**Comment by pmgeuze** [comment]
Mr. Strahl,

I will go ahead and work on making smaller file chunks to ease the printing problem. I am making use of the Browser->View->Print, and I appreciate that the format is clean and prints well to PDF.

I cannot send you the file due to the nature of the material, but I appreciate your efforts very much. Thank you again for your prompt response.
