### ISSUE TITLE
The file has been deleted

### ISSUE THREAD

**Issue by asdeva** [RickStrahl/MarkdownMonster#623]
I have created an md file after a day of working. When I have tried to open it from windows explorer, monster launched and started with the demo file instead of my file. I have closed monster markdown and my file has been reduced to zero bytes, so all the work of one day has been destroyed.

**Comment by RickStrahl** [comment]
I have no idea how that could possibly happen and I've never heard of another report of this sort of thing happening either. Not saying that it's not possible, but without more information I find that hard to believe given the ~1000 or so users that use MM every day.

MM doesn't clear file content and never writes files unless you explicitly save or are prompted to save (unless you have AutoSave enabled, which is **not** on by default). If a save operation fails at that time it'll will warn you.

My guess for the Sample doc to show up is because your configuration has reset itself. Maybe you launched as another user? Changed permissions? Manually changed settings in the configuration and the configuration file was invalid? If the configuration file is missing, or you don't have permissions, or is invalid MM will re-write a new configuration file and load with default settings at which point it will re-open the sample document (ie. same as a first start of MM).
