### ISSUE TITLE
`AddMenuItem` either does not report failure or does not add correctly

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonster#636]
V 1.21.1

Attempting to perform the following
https://markdownmonster.west-wind.com/docs/_4zv0o3r46.htm#icon-info-circle-finding-menu-item-names

```C#
            var mitemOpen = new MenuItem()
            {
                Header = "Compile File",
                Name = "CompileFileMenu"
            };
            //mitemOpen.Click += (s, a) => OnExecuteLoadGist();
            if (!AddMenuItem(mitemOpen, menuItemTextForInsertionAfter: "Compile Snippets", mode: 0))
                mmApp.Log("Unable to add custom menu item in CompileFileMenu: " + mitemOpen.Name);
```
- Stick a breakpoint on the log line
- run code
- breakpoint not hit
- menu item not found in any dropdown

**Comment by Smurf-IV** [comment]
More Info:
I changed the line to 
```C#
if (!AddMenuItem(mitemOpen, menuItemTextForInsertionAfter: "Open From Html", mode: 0))
```
and the breakpoint is still not hit AND the menu is not visible
![image](https://user-images.githubusercontent.com/2418812/74244067-c3cf2180-4cd8-11ea-8a1e-b0f0a1738a39.png)

**Comment by Smurf-IV** [comment]
More Info:
Consider the following code:
```C#
MenuItem GetChildMenuItem1(
                ItemsControl mitem,
                string menuItemName = null,
                string menuItemText = null)
            {
                foreach (object obj in mitem.Items)
                {
                    if (obj is MenuItem menuItem)
                    {
                        if (!string.IsNullOrEmpty(menuItemName) && menuItemName == menuItem.Name || !string.IsNullOrEmpty(menuItemText) && menuItemName == menuItem.Header?.ToString())
                            return menuItem;
```

Now lets focus on the following line
if (!string.IsNullOrEmpty(*menuItemName*) && *menuItemName* == menuItem.Name 
|| !string.IsNullOrEmpty(**menuItemText**) && **menuItemName** == menuItem.Header?.ToString()
)

Changing the 2nd bold item to `menuItemText` make it find the correct menutItem
**BUT**
this still does not display the menu item in the plugin drop down menu

Also: When will the header be `null`? otherwise it would not be able to display a `clickable menu text` ?

**Comment by RickStrahl** [comment]
The problem is that the name has to **exactly** match the menu item name including in this case the mnemonics for the shortcut key. The best thing to do is look up the menu name (or header text) in the [source code](https://github.com/RickStrahl/MarkdownMonster/blob/master/MarkdownMonster/MainWindow.xaml#L224):

![image](https://user-images.githubusercontent.com/1374013/74576277-35ec7400-4f2e-11ea-829b-82845968141d.png)

Note the underscore!

If possible don't use the header text but the menu item name.

I've updated the help topic with some more information and also changed the signature with an overload that uses an enumeration.

https://markdownmonster.west-wind.com/docs/_4zv0o3r46.htm
