### ISSUE TITLE
do not mark html and all uppercase as spell checking errors

### ISSUE THREAD

**Issue by nicolgit** [RickStrahl/MarkdownMonster#640]
It could be useful do not mark tags like <br/> as spell checking errors.

Also words all UPPERCASE I think sholud be not evaluated by the spell-checker.

**Comment by RickStrahl** [comment]
Can you post an example for the html that you are talking about please? There are many ways you can write 'HTML' and I don't know which you might be referring to here.

**Comment by nicolgit** [comment]
sure, in attach

![Capture](https://user-images.githubusercontent.com/10533937/74832689-21d2b900-5318-11ea-8935-fb64b4a97621.PNG)

**Comment by nicolgit** [comment]
I'd also exclude from spell-checking **CamelCaseWords**

**Comment by RickStrahl** [comment]
The problem here is that the spellchecker doesn't have all the context it needs to figure things like inline HTML because tags can start way back and can be inline. It's possible to track but would add a lot of overhead which we're trying to avoid.  In order to keep performance up MM uses hard code exclusion lists for HTML tags.

Currently the way things get excluded is via hard coded tags. I've added `br` and `nbsp`  to the exclusion list which will take care of the ones above but there are likely additional others that can pop up.

I've also added logic to exclude UPPER and MixedCase - not sure yet if I want MixedCase excluded or not, but will give it a try. FWIW, Chromium's Html editor spell checking doesn't exclude Upper or Mixed case words...

Anyway here's what it looks like with the updates:

![image](https://user-images.githubusercontent.com/1374013/74898228-5b69eb00-533d-11ea-86f1-fa10f61b0efe.png)

de777d86

**Comment by Smurf-IV** [comment]
Don't forget the html correct closure of br as well; i.e.
`<br />`
or
`<br/>`

**Comment by RickStrahl** [comment]
Those are handled by virtue of the word breaks - symbols are ignored so it works regardless of what the surrounding characters are.

**Comment by nicolgit** [comment]
Thank you Rick!

about the CamelCase, my suggest comes from how Microsoft Word manage them
![word](https://user-images.githubusercontent.com/10533937/75239190-8d0e0680-57c2-11ea-9eee-3d564856d0d8.PNG)
