### ISSUE TITLE
Emoji not rendered in PDF output

### ISSUE THREAD

**Issue by dpr20** [RickStrahl/MarkdownMonster#641]
Repro:
Create a doc containing emoji such as :warning:
Select Save To... and Save To PDF
Open PDF using Adobe Acrobat Reader
Emoji are rendered as 􀀀􀀀 (two squares) in document

**Comment by RickStrahl** [comment]
Unfortunately that's appears to be an issue in the PDF generation engine (Chromium/wkhtmltopdf) that we're using. I played around a bit with making sure that the right fonts are referenced and setting the encoding of the document, but none of that seems to help in the PDF output generation.

if you're interested there's a long discussion of 'options' on this thread here:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2913

**Comment by dpr20** [comment]
Many thanks for this explanation!

**Comment by RickStrahl** [comment]
Ok so after playing around with this some more I think I found a way to make this work after all.

* Open a document
* Go to the Preview Window
* Right click Edit Preview Theme
* Open Theme.css in your favorite editor
* Change the "Segoe UI" to "Segoe UI Emoji"
* Remove the "Segoe UI Emoji" from the end of the string (if there)
* Save and exit
* Reload page

The full recommended line will look something like this:

```css
html, body {
  color: #333;
  font-family: -apple-system, BlinkMacSystemFont,"Segoe UI Emoji", "Apple Color Emoji", "Segoe UI", Helvetica, Helvetica, Arial, sans-serif;
 ...
}
```

This appears to work both for regular output and PDF generation. The issue here is that those Emojii fonts take over all font processing. I think Segoe UI Emoji is just the regular Segoe plus the emoji fonts so that's probably OK for windows, but not sure what will happen on the Mac with those `Apple Color Emoji` fonts.

I'm making the above change for any themes that are using Segoe UI as their main font (which is most of them).

However, I'm not sure how well this will

**Comment by dpr20** [comment]
Many thanks. Your proposed fix works for me on Windows at least.
