### ISSUE TITLE
Won't stay registered

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#642]
I have a Mac with Parallels installed. I am running Windows 10  Pro.
MM does not retain my registration code.  Every time I start it says not registered

**Comment by RickStrahl** [comment]
Most likely that's permissions. Are you running Portable mode? If so make sure you have your settings folder set to writable. The folder will be `.\PortableSettings` in the MM install folder. If you didn't have permissions to create the folder/config file, then it might not exist and settings are not saved between restarts.

**Comment by HowardEdidin** [comment]
I am storing configuration in Dropbox

**Comment by HowardEdidin** [comment]
Any chance of porting to the Mac.  From what I have seen, there isn't a Mac app that does not even get close to providing what you have.

**Comment by RickStrahl** [comment]
You're not really providing much information here, so I have to guess as to what you're doing. If you provide feedback please be more descriptive.

That said - I tried this out and that registering locally when the configuration is moved to dropbox works fine if you shut down and restart. 

However, I think the issue you're seeing is this:

* You change your config folder to DropBox
* You register
* You shutdown
* You start MM on another machine via DropBox config
* MM is unregistered

The reason for this is that the registration file is stored in this common folder and **it's machine specific** - it's encrypted with a machine encryption key, so if you open on another machine it won't recognize the key and is not registered. 

This is by design to keep the registrations tied to a specific machine. I can see how this is not ideal, but offhand I don't see a good way around this - basically what needs to happen is to have the registered.txt file **not synced** across machines. Storing it elsewhere would work, but other locations have potential issues with file write/read security which is required to update the file.

**Comment by RickStrahl** [comment]
In the meantime looks like DropBox is adding a feature to ignore files:

https://help.dropbox.com/files-folders/restore-delete/ignored-files

that might work... I think this will have to happen on each machine.

**Comment by RickStrahl** [comment]
Ok, so gave this some more thought. Rather than by default storing `registed.key` in the common folder, I've changed behavior so that it first checks and writes the key into the installation folder. If permissions allow the file is written there which is a machine local location that isn't shared. 

If that location can't be written to due to permissions, then the common folder is used. Reading the key first looks in the local install folder then in the common folder if that's not found.

This will let you isolate each machine with its own registration. Given that MM by default installs in `%LocalAppData% which by default **is writable** or using a portable install which very likely is also installed to a writable location this should work well.

43c55fe9
