### ISSUE TITLE
Possible to map H1-H5 as format shortcuts?

### ISSUE THREAD

**Issue by nonplayer** [RickStrahl/MarkdownMonster#648]
I'm looking to create an easy shortcut to automatically format a line as H1 through H5. Something like Ctrl+Shift+1 through 5. I'm not having any luck with this. It's really the one final set of keyboard usability that has kept me from uninstalling Atom and switching to MM entirely for my writing. I just need to be able to easily use the same H functions on the top toolbar, but via the keyboard.

Are these commands mappable? If so, what is the proper CommandParameter to use in the keymap?

**Comment by RickStrahl** [comment]
There's no shortcut for these at the moment so they can't be mapped directly from the commands. The reason is mainly key availability.

What you can try is using the Commander C# Addin and write a custom snippet like this:

```cs
var selection = Model.ActiveEditor.GetSelection();
selection = "### " + selection.Trim();
Model.ActiveEditor.SetSelection(selection);
```

![image](https://user-images.githubusercontent.com/1374013/76569008-2fcab400-6456-11ea-9ba5-721bb7baf31e.png)

You can assign that to a hotkey like `Ctrl-Shift-3` and that'll work. You'd create entries for the other Hx values too.

**Comment by nonplayer** [comment]
Hm ok. I'll see if I can work with this. Not ideal, but I can tweak it. Thanks.
