### ISSUE TITLE
Suggestions for the Embed Link Dialog

### ISSUE THREAD

**Issue by RealDotNetDave** [RickStrahl/MarkdownMonster#649]
I have a few suggestions for the Embed Link dialog box:

1. Remember if I chose "Open link in new window" or "Link as a reference".
2. Remember the last folder I navigated to.
3. Move buttons to the right side of the dialog.

**Comment by RickStrahl** [comment]
1. done

2. I'm not sure if this should happen or not - I've been back and forth on this frankly. The logic to save the last value is there already and was taken out because this is pretty personal.

I've reset it to remember the last path - let's see how it goes. One change I made that I created a new saved path config property `LastLinkPath` specifically for links, rather than sharing that path with the global lastfolder which stores the location of documents opened (and a few other thing). So this might make this more useful than the old setting that saved the path.

3. Ok done. I have to adjust all the dialogs that have bottom buttons though :-)
