### ISSUE TITLE
Math expressions not rendered

### ISSUE THREAD

**Issue by gasilva** [RickStrahl/MarkdownMonster#656]
I can see the equations in the preview, save the file, but when visualized in github it simply does not work and the expressions are not rendered.

If you see your example here in github, it does not render also.

MarkdownMonster/SampleDocuments/MathJax.md

no math expressions are shown in the sample.

![image](https://user-images.githubusercontent.com/477692/79019222-41ce6e00-7b4c-11ea-9085-1af4e2b592b3.png)

I am trying to put equation here in my README.md

https://github.com/gasilva/dataAndModelsCovid19

https://github.com/gasilva/dataAndModelsCovid19/blob/master/README.md

**Comment by RickStrahl** [comment]
Github is not going to render this because they're not loading the libraries required to run the math rendering. You need to use HTML that has the required HTML associated with it working. This means you need to export the HTML then run the HTML standalone, or on a Web site that has the appropriate libraries running on the active page.

More info on Math rendering is here:

[Rendering Mathematics Expressions in Markdown Monster](https://markdownmonster.west-wind.com/docs/_59l0mv2uw.htm)

Specifically look at the section at the bottom that describes what's required to render the math equations in HTML pages.
