### ISSUE TITLE
(numbered) table headers would be quite essential for me

### ISSUE THREAD

**Issue by sreyem** [RickStrahl/MarkdownMonster#657]
Hi,

thanks for your amazing tool!!!
Is there a possibility to have tables and figures with a name, so that I can use them in the text like
'as you can see in table 5.1' or 'please refer to "Summary of results"'as a link 

Thanks a lot in advance

**Comment by RickStrahl** [comment]
Not that I know of. The problem is that Markdown has no way to express these things natively.

There is an **Extra Attributes** extension that supports some naming of elements via a custom Markdown extension. This works for output generation in MM, but may not work everywhere. Not sure offhand if Github supports it (I don't think so).

Here are a couple of examples that do work:

```markdown
# Extra Attibutes

* [Image 1.1](#image1_1)
* [Table 1.1](#Table1_1)


### Image with Id

![](images/MarkdownMonsterLogo.png){#image1_1}

### Table with ID? No, but you can use a wrapper

<div id="Table1_1">

| Header 1 | Header 2 |
|----------|----------|
| Column 1 | Column 2 |

</div>
```

Note using raw HTML tags to force IDs as wrappers should work with anything. It's ugly but it works.

**Comment by RickStrahl** [comment]
Trying this out by pasting the text from above. See if Github can render it here:

----

# Extra Attibutes

**Links:**

* [Image 1.1](#image1_1)
* [Table 1.1](#Table1_1)

### Image with Id

![](images/MarkdownMonsterLogo.png){#image1_1}

### Table with ID? No, but you can use a wrapper

<div id="Table1_1">

| Header 1 | Header 2 |
|----------|----------|
| Column 1 | Column 2 |

</div>

---

Yup - as suspected GitHub doesn't support **Extra Attributes**, but the `<div id="Table1_1">` wrapper works.

**Comment by sreyem** [comment]
Hi,

Thanks a lot for your quick answer and for your time!
I'll see  how I can circumvict this problem.


Rick Strahl <notifications@github.com> schrieb am Mo. 27. Apr. 2020 um
21:16:
