### ISSUE TITLE
Editor code syntax not following markdown selection

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#658]
Fresh install so all default settings. However just for clarity:

```
"MarkdownSymbolsConfiguration": {
      "Italic": "*",
      "SoftReturn": "  "
    }
```

Within the editor, no differentiation is made between * and _ yet clearly the underscore should not have any affect within the editor:

[![Bug.png](https://i.postimg.cc/431GBmQf/Bug.png)](https://postimg.cc/CZd9KM2X)

**Comment by RickStrahl** [comment]
Both are supported by Markdown and that configuration setting has no effect on that. 

The setting is for **markdown insertion/generation** for example when you use `Ctrl-I` or the toolbar shortcut.

**Comment by SMTStuck** [comment]
Thanks for the quick reply. There _is_ a bug somewhere here and if it's not classed as a bug it's certainly coming across as something too unexpected. Consider this:

`Test_Test Test_Test`

This is not rendered in italics in either the preview pane or the saved HTML file, however it is rendered in italics within the editor. Whereas the following:

`Test _Test Test_ Test`

Is rendered correctly as italics within both the editor and preview pane (and so the HTML file). 

As nice as this is, perhaps there is a setting to turn off the editor attempting to render itself as per the markdown?

**Comment by RickStrahl** [comment]
Yes this has come up before, but not something I will fix here because it's a relatively minor editor rendering issue and because the raw editor is a plugged in component.

MM uses [Ace Editor](https://ace.c9.io/) for the text editor implementation and MM picks up the latest releases of ACE for integration.

If this issue is of concern to you can try filing an issue on the Ace Editor Github site as they maintain the editor and Markdown syntax. 

https://github.com/ajaxorg/ace/issues

**Comment by SMTStuck** [comment]
Well, it's your project so it's your choice, but 'it's a relatively minor editor rendering issue' is a point that is dependent on how you use the editor. For me, it is a relatively major issue, and as a workaround I enclose all text that requires an underline with the code tags. I shall not be chasing different projects to report bugs for sub-components used in this project.

**Comment by RickStrahl** [comment]
Well I get the issue and the problem, but I've looked into fixing a few of the issues related to the Markdown rendering in the editor and it's crazy complex to affect the behavior of the editor. While it's doable, diverging the code base so it's no longer in sync with the ACE support Markdown editing support is not something that I really want to trade off. The risk vs. reward is too high there. The Markdown support in ACE is excellent overall and giving that base support of a widely used component up for a few small customizations that may fix a small bug are not worth the risk in this case.

So if this really bugs you I do want to encourage you to forward the request to the ACE repo because that will actually benefit a much larger community than just the MM community here.

I know it sounds like passing the buck :smile: up the line, but that's really the way this should work - if it gets fixed here not only does it not help the entire ACE community, but it also breaks the connection to that community and the enhancements down the line being integrated back into MM in the future.

**Comment by SMTStuck** [comment]
I can appreciate you not wanting to diverge the code base, and it is a rather sensible option.

I shall consider posting on the ACE repo regarding this bug then.
