### ISSUE TITLE
Dragging multiple files from explorer onto editor opens only the first file.

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#661]
1) Have multiple files selected in explorer.
2) Drag into editor window.
3) An icon appears saying "Move" with the correct number of files shown.
4) However releasing the button will only open the first file in the selection.
5) If the file is already loaded it moves that open tab to the beginning rather than just showning it.

**Comment by RickStrahl** [comment]
Unfortunately there are some problems with this if you drop the files directly into the editor area. I've looked into this a few times but there's no way to capture multiple files dropped into that control unfortunately. Only a single file is returned.

However, there's a is a workaround:  You can drop the files into the header area of the window (or anywhere else but the sidebar) and it will correctly open multiple files.

The problem is that the browser control is not surfacing the drop operation, but treats the drop operation like a document navigation. The navigation only reports a single file. I don't know of a way around this limitation unfortunately, so this won't get fixed unless somebody has an idea how to get at the actual drop list. The drop events are not firing on the document - as it is all the drop operations (like dropping images or text drag and drop) are all handled by  inferring the selection points and then getting the targets from the host. But without the full drop file list the list of files is simply not accessible.
