### ISSUE TITLE
Publish to Jekyll tooling/add-in

### ISSUE THREAD

**Issue by rockfordlhotka** [RickStrahl/MarkdownMonster#663]
I have traded some emails with @RickStrahl about this, and based on his suggestion wanted to do an issue to see if anyone else has found a solution to my challenge.

I use a GitHub-hosted static Jekyll blog. The blog has a prescriptive way of formatting post md file names and related image assets. Also the URL in the md file referencing image asset files is ... odd.

The Jekyll format is that there are `/_posts` and `/assets` directories at the root level. Inside `_posts` are your posts

```
/_posts/yyyy-mm-dd-my-blog-post-title.md
```

Inside `assets` are your images

```text
/assets/yyyy-mm-dd-my-blog-post-title/myimage1.png
/assets/yyyy-mm-dd-my-blog-post-title/myimage2.jpg
```

The link from a `.md` file to an image is like this:

```
![]({{ site.url }}/assets/2020-03-30-Choosing-Client-UI-Tech-in-Early-2020/flowchart.png)
```

And the `.md` file must have a yaml header something like this:

```
---
title: Choosing Client UI Tech in Early 2020
weblogName: Rockford Lhotka
postDate: 2020-03-30
---
```

I've built a [simple CLI publish tool](https://github.com/rockfordlhotka/publish) to publish my markdown files and assets into the right filename and directory structure. My CLI tool doesn’t address the yaml header (yet). It

* Adds the `yyyy-mm-dd` prefix and replaces “ “ with “-“ in the filename
* Fixes the image names
* Fixes the image paths
* Copies images into the `/assets` subdirectory correctly

This can be done by hand in MDM, but it is tedious to say the least.

Do others have this issue? What other solutions exist?

I'm proposing that I take my CLI code and convert it to be a MDM add-in.

**Comment by steveoh** [comment]
We made a little js app to create the front matter yaml bits and name the file. Then we just copy paste the md into the template.

You could build that with your cli and look at prior work also

https://www.npmjs.com/package/jekyll-utils could help generate the jekyll specific markdown items. 

If you are using jekyll 4, you should switch to the [link tag](https://jekyllrb.com/docs/liquid/tags/#links)

**Comment by RickStrahl** [comment]
My first reaction to this was: It's a static blog so why do you need any automation here :-)

After discussion with Rocky it turns out it's not quite that simple because of the (frankly) silly folder layout  in Jekyll that separates post data and resources into separate folders. If the post 'name' changes everything has to be fixed up so a static solution may be too inflexible.

Here are a couple of thoughts:

### Re-Packaging existing MDM WebLog Post layout
Rocky's approach is to basically publish what MDM natively produces for folder content which is a self-contained folder that holds both the post and related resources and then uses a script to create and move them into the right Jekyll folder. In a way this is another way of 'publishing'.

This should work pretty good for making sure that resources get into the right place. Would require that the default YAML header is re-parsed and then rewritten into the format that Jekyll requires plus the post and images would be copied into another folder.

The options here are to create a new Addin with a toolbar button (and perhaps a few other helper options on the menu like opening the posts folder and image folder in the folder browser).

Or - it could be integrated  integrated into the existing WebLog Addin as another 'publish' option - which in this case would actually publish into the Jekyll folder and potentially also commit and push as an option. One advantage to this would be that the existing Weblog addin already knows about all the post meta data and it would be pretty easy to rewrite a new header into the Jekyll output folder with the existing functionality.

### New Post Template
Another option that may be simpler is a post template. The idea with this is that you give a title and publish date and the template in the Weblog addin (or a custom addin) would then create the relevant folders and put the new post into it. The document could also get the image folder pre-assigned so that any images that are pasted or embedded will automatically go to the right assests folder that was created.

### Leave me Alone
Yeah right? Just write the post and manage everything manually. Don't let MDM help you in any way. Create an MD document, create folders by hand and put images manually into the right folder.

This is an option and I do wonder if that's how people that work with Jekyll do this and are OK with this?

### What are common Jekyll Writing Workflows?
Any thoughts on what workflow people that have been using Jekyll for a while are using?  If you're using Jekyll I would love to hear what you're doing to create posts and manage resources efficiently.

Whatever the solution I think this would be a useful feature to add especially if we could figure out a semi generic way to create a `local file publisher` that could turn the standard MDM WebLog posts into posts for various static generators easily (which would allow going to multiples too).

Personally I'm leaning towards reviewing what it takes to integrate into the existing WebLog Publish approach.

**Comment by RickStrahl** [comment]
@rockfordlhotka  I'm going to take a look at integrating your script as a WebLog publish type. Maybe think about how refactor the 'publish' interface into something that can be extended with an Addin which would be cool (extending the addin with an addin 😄).

**Comment by RickStrahl** [comment]
@rockfordlhotka So I took a swing at this using your script as the basis. I think you did things a little bit different, but here's the work flow I'm shooting for:

![image](https://user-images.githubusercontent.com/1374013/82317732-77941d00-996a-11ea-8c38-e89c7f198379.png)

The idea is this:

* You create a Markdown Monster Blog Post
* Single folder hierarchy - post and images go into the same folder typically
* When done you publish your blog post to **Local Jekyll Project**
* Pushes Markdown document into the Jekyll `_posts` folder.
* Copies MM folder images into Jekyll `assets/<post-tag>/image.png`
* Updates the Markdown to reflect the new image paths
* You explicitly publish to Jekyll when you're ready (this can be integrated later too but needs a bunch more options for which there's no current settings in the Weblog Config)

If you need to update the post:

* Open the Markdown Monster Blog Post
* Make your edits
* Publish again
* Re-publish nukes all existing images for the post, and copies only the new ones

The updated (very rough) code is here:

https://github.com/RickStrahl/MarkdownMonster/blob/master/AddIns/WebLogAddin/LocalJekyll/LocalJekyllPublisher.cs

https://github.com/RickStrahl/MarkdownMonster/blob/master/Tests/WeblogAddin.Test/JekyllPublisherTest.cs

and an integration test to go with it. The test needs to point at an MM Markdown file and the Jekyll project.

This code is a little different than yours's in that it uses the MM Weblog Meta data to hold the post info. Only when the post is published is the data then converted to the Jekyll format. Same info is available but the Yaml is different.

Right now this is only hooked up via code/test but it's using all the same objects that the other providers are using so from here plugging this in shouldn't be very difficult.
 I'll take a look at the integration into the Weblog publishing dialog adding Local Jekyll as another provider. I'm using the ApiUrl for the project path which is really the only major requirement for the Jekyll provider.

**Comment by jguadagno** [comment]
I've been using Jekyll on my blog for a while. I like keeping the images in a separate folder from the page. For newer posts, non-legacy, I generally name the images close to the name of the post with a description of the image.  Looking at [https://github.com/jguadagno/jguadagno.github.io/tree/master/assets/images/posts](https://github.com/jguadagno/jguadagno.github.io/tree/master/assets/images/posts), you see images like `build-` or `code-signing-`.  These "help" know what posts they go to.  I also don't include the `site.siteUrl` in the links. I tend to use a helper feature of my theme to provide alt text and figure captions.

```markdown
{% include figure image_path="/assets/images/posts/build-sign-create-pipeline.png" alt="Build and Sign - Create Pipeline" caption="Build and Sign - Create Pipeline" %}
```

You can see the structure of my blog at [https://github.com/jguadagno/jguadagno.github.io](https://github.com/jguadagno/jguadagno.github.io).

**Comment by CalvinAllen** [comment]
Coming here from Twitter as I also use Jekyll.

I put all of my posts in a folder with the same name as the post.  

I.e. _posts/2020/2020-05-01-whatever/2020-05-01-whatever.md

In the same folder as the markdown, I put any assets I need for the post.

On build, I have a custom Jekyll plugin that copies those assets to the proper output folder, and rewrites the embedded relative URL into an absolute path.  This allows me to keep everything together, and include relative paths in my post, which lets the preview features work.

The downside is that it requires a custom plugin. 

You can see this in my repo, https://github.com/CalvinAllen/calvinallen.net

Not sure its any help or not, but thought I'd toss it in.

**Comment by RickStrahl** [comment]
@jguadagno,

To me the problem with images in external folders is that it becomes very difficult to manage as you end up with tons of images. I have posts with 20 images and the approach you're using would have me end with a folder with thousands of images :smile: which is clearly not what you want. 

I realize it's easy to organize into folders manually, but still not sure **why** you'd want to do that as it adds mental overhead in your writing process,  as you have to change folder at least once to go save your image and figure out what to name the folder or file to make it obvious which post it belongs to. Although MM is smart about image save locations, as it remembers last location, but still at least the first save you have to hunt down the folder and then use an appropriate file name. That's all just busy work for no apparent benefit unless I'm missing something here.

IAC - the idea of the publish process described above is that, that  the actual layout what goes into the Jekyll repository will be separated out whether I like it or not because that's what Jekyll requires :smile:. So the tooling does this for you. 

The scenario I'm addressing with this publishing mechanism is that you basically manage the raw editing content as a folder of files, and then publish to Jekyll as output. Jekyll in that scenario isn't the actual content repository. 

For a clue of what that looks like you can see my Weblog repo here:
https://github.com/RickStrahl/BlogPosts

There's a lot of content there, but it's fairly organized and I can find stuff by editor or Explorer search and then simply re-publish. I frequently make changes to even my pre-Markdown posts from 13 years ago :smile:

FWIW this isn't MM specific although MM helps set this up when do 'New Weblog Post' - a post is just a folder with a markdown file and all it's dependencies in one place. 

The other nice thing about this is that I can take a post and re-publish it easily on multiple platforms - or if in the future I do something different it can easily be re-purposed for something else. IOW, it's not tied to the publishing platform in any way. I have the **raw content Posts** repo for the posts and if I publish to something to a generator that is separate and basically there for the CI/Build process, not to manage the content.

Maybe I'm making this too simple, but this has worked well for me for the last 5 years or so.







Personally I don't understand what problem separation solves in this case. Anybody looking at your posts in your repo now also has to  go hunting for images.

**Comment by RickStrahl** [comment]
@CalvinAllen The publish addin described abovve basically does exactly what you're doing manually. 

The main difference is that your actual content is stored outside of the Jekyll folders and the publish operation then pushes the content into Jekyll with the appropriate post tag and image folder name.

The only downside to this is that you end up having another repo for the actual content you keep and treat the Jekyll repo as an application/build/ci process separately.

**Comment by jguadagno** [comment]
@RickStrahl From an organizational standpoint, your way wins hands down.  I went with this approach because of the limitations of Jekyll and I did not want to add a separate build system or plugin to take from a format like you have to what is required for Jekyll.  I used the naming *standard* as a way to folderize the images.  I would much rather have each post be in the own folder with all of the images and have a tool break them out according to the requirements of the engine. 

I believe BlogEngine.Net stored them in that fashion.

**Comment by RickStrahl** [comment]
I've posted an updated preview version (1.22.5.5) of MM that has an initial implementation of the Jekyll publishing described built into it:

[Download Markdown Monster] (https://markdownmonster.west-wind.com/download.aspx)

It's a preview release.

I've also added documentation here:

[Local Jekyll Publishing](https://markdownmonster.west-wind.com/docs/_5rv00rx4i.htm)

Here's what is provided. 

First thing is to set up Weblog configuration for a Jekyll site:

![image](https://user-images.githubusercontent.com/1374013/82705508-789ba780-9c13-11ea-9abf-a9ed091e8562.png)

You basically point at the local Jekyll project root folder and optionally provide a Jekyll build server launch command line and preview URL. The latter two can be left out and you can alternately manually build Jekyll. This feature does not push to Git at this point.

To publish a post - you start by creating a new weblog post in MM writing the text and keeping images in a local folder with relative (or same folder) paths. 

When it's time to publish you use the Weblog publishing dialog:

![image](https://user-images.githubusercontent.com/1374013/82705782-04153880-9c14-11ea-8bc5-84a6dcf4ed95.png)

The publish process performs the following tasks:

* Copies the Markdown File to the Jekyll `_posts` folder
* Fixes up the YAML header for Jekyll's format
* Copies any local relative Images into the Jekyll `assets` folder
* The `assets` folder has the same slug name as the post
* Fixes up the image in the Markdown for the `assets` folder location
* Optionally launches the Jekyll build server
* Optionally opens a browser on the new post

When it's all said and done you end up with what this screen shot encapsulates:

![image](https://user-images.githubusercontent.com/1374013/82705872-2c9d3280-9c14-11ea-9147-d538cef7f24b.png)

Let me know what you find.
