### ISSUE TITLE
Snagit 2020

### ISSUE THREAD

**Issue by dirkduplooy** [RickStrahl/MarkdownMonster#669]
Hi there,

Is there an issue with Markdown Monster and Snagit 2020.1.2?

I click the Screen Capture Button > The timer starts > I do the capture > Snagit Editor comes up > I click finish and Markdown Monster does nothing.

I tried to save the image and click finish as well and not result either.

Thanks for your help

**Comment by RickStrahl** [comment]
Unfortunately that's a bug in SnagIt 2020. The Finish button is supposed to show a file open dialog box from within SnagIt, but that doesn't happen in this version - instead SnagIt just hangs.

I have a ticket open with Techsmith to investigate as this has to be fixed on their end - there's no other way I know of get the image directly so we have to wait for this to get fixed by Techsmith.

This same issue happened a few years back with SnagIt 2018. It took several point releases before they ended up fixing this. Unfortunately the interop bits in SnagIt are not well supported by the SnagIt time. I've provided a number of issues over the years that would make the interop behavior much nicer, but they pretty much ignore all requests. Heck they didn't even acknowledge the bug report I made 2 years ago or when it was fixed. It just started working without the ticket being updated at the time.

**Comment by RickStrahl** [comment]
The problem with SnagIt apparently is the Preview Window and Finish button. if you **turn off the preview window** then SnagIt works. Unfortunately the current version doesn't respect the `ShowPreviewWindow` setting, but that at least will be fixed in the next update. Without the preview window the file save dialog pops open and you can select a filename and get it embedded.

**Comment by dirkduplooy** [comment]
Thanks @RickStrahl at least we know it is their problem, I will use the copy and paste for the moment, it works as advertised. Thanks for the effort and time you put into the issue

**Comment by SyntaxDreamer** [comment]
Is this still an issue? Running Snagit 2024 latest build and after clicking Finish it crashes Snagit.
