### ISSUE TITLE
Embed images as inline images in document

### ISSUE THREAD

**Issue by weggetor** [RickStrahl/MarkdownMonster#67]
Hi Rick,

before I found Markdown Monster I used another Markdown tool to create my posts. But this one does not have the ability to upload the images to the blog so I wrote a little tool to embed the images as inline data (base64 encoded) directly in the html document. It is a very simple Winforms program, that opens an Html or MD file, parses for all images and changes the image tags. Maybe this could be an interesting option for Markdown Monster ?

It uses HtmlAgilityPack library to find all images with linq query in the html document and changes the attributes. Feel free to add it to Markdown Monster as an option or not - as you like.

Best, Torsten

[Html_Embed.zip](https://github.com/RickStrahl/MarkdownMonster/files/629133/Html_Embed.zip)

**Comment by RickStrahl** [comment]
Thanks Torsten, but I'm not sure if that's such a good idea.

Personally I don't really think this is such a good idea as you can't cache images, or offload them to another server. If you embed it's also difficult to optimize images because optimization is slow.

For example, I upload images to my server and on the server I post process the images by optimizing them (in the background). The original images are posted and available immediately, and the updated images get plunked in when the optimization is complete. If images are inline you can't really do that. Likewise, if you

I mean it wouldn't be hard to integrate even now - I'm already parsing the generated HTML for images and then replacing the images URLs that come back from media post using HtmlAgility pack. So embedding the base64 images wouldn't be a stretch to add.

But just not sure if this would be such a good idea especially since images can be potentially large and slow down document loading.

**Comment by weggetor** [comment]
Hi Rick, 
you're totally right with your arguments and I would never make this the default! But sometimes it is a very handy solution when you do not have the right to upload images. 

Think of answering a forum post. You have to upload images on their site to integrate the image in your post or upload them to your own website and link it from there. All in all not very handy. In this case you can write your answer with MM including images. Then select "copy HTML with embedded images" and paste it to the forum post and you are done!

**Comment by RickStrahl** [comment]
Yeah I guess i can see that, but you're going to end up with massive HTML documents to paste in that case.  

I'll put that on my ToDo list but not a priority item. Closing.

**Comment by RickStrahl** [comment]
As a late follow up - this feature has been added as part of 1.2.14 and later. There's a base64 checkbox in the Image dialog to embed image content as ref links into the page now.

**Comment by eselje** [comment]
Base64 embedded images don't seem to appear on GitHub's rendering of the Markdown pages?
