### ISSUE TITLE
infinite loop opening ext other than .md

### ISSUE THREAD

**Issue by adamfoneil** [RickStrahl/MarkdownMonster#670]
Hi there, I noticed some odd behavior this morning in which opening a file with an extension ".rzm" causes an infinite loop. I have a little repro video here: https://1drv.ms/v/s!AvguHRnyJtWMlvp9V6IRUA2bIMFGDA?e=UpZKiH

"rzm" in my case stands for "roslyn markdown" -- this is something I use to build markdown content that converts C# identifiers to GitHub line number links. It's regular markdown in every respect except for having # signs in links. Some background on this is [here](https://github.com/adamfoneil/RoslynMarkdowner/issues/29), and [here](https://github.com/adamfoneil/RoslynMarkdowner/blob/master/RoslynDoc.Library/Services/WikiBuilder.cs) is my `WikiBuilder` class that uses this, incidentally.

Anyway, expected behavior is to open .rzm file normally and not go into loop.

**Comment by RickStrahl** [comment]
Thanks for the video - that's helpful. 

Not quite sure what's happening there. How is the extension registered? Did you just register in Windows only? Or also add the mapping in the configuration file? If not mapped the file wont be treated as Markdown in the editor.

You'll want to map the extension in Markdown Monster's extensions in the configuration file:

![image](https://user-images.githubusercontent.com/1374013/83992753-0a323700-a8ed-11ea-8b25-f0247b6fd7c2.png)

(**Tools->Settings->Edit Json**)

Still doesn't account for the looped loading - i'll take a look.

**Comment by RickStrahl** [comment]
Ok so took a quick look and I can duplicate what you see.

The quick fix here is to register the extension in the settings and that make the file open properly.

But there's definitely a bug here for the unmapped extension endlessly looping making it hard to shut down MM even. That's messed up :smile:

Will have to dig in to see why that's happening...

**Comment by adamfoneil** [comment]
Thank you @RickStrahl . I registered the .rzm extension in Windows only. I will apply the easy fix you mention!

**Comment by RickStrahl** [comment]
So I took a look and this is a catch-22 problem and not quite sure how to fix this...

The reason this fails is this:

* File Association in Windows starts MM for the file
* MM doesn't know the file type so it, defers opening the file and
* Ends up using `ShellExecute()` on the file
* Windows tries to route the file to MM again

I've changed the behavior to open only tabs for files referenced which is probably cleaner anyway. Also fixed a related issue that left files that weren't mapped without any sytnax. Files mapped now default to `markdown` syntax.

Fixes here: d976a392

**Comment by adamfoneil** [comment]
Interesting! Glad you identified the underlying issue. My naive question is would a program ever need to call `ShellExecute` on filename args passed to it? It seems like that's asking for an infinite loop

**Comment by RickStrahl** [comment]
Yeah in hindsight that's obvious :smile: 

The reason for this is that `OpenFile()` is used in other places where `ShellExec()` does make sense - like double clicking on documents in the file browser for example. From there any unmapped extensions will open via ShellExec and that actually makes sense. In that case it would even work because it would then try to open the document in MM 'externally'.

This operation handles a number of different file types and folders, project files, images urls etc. - all the stuff that MM can open. The ones that fall through are shell executed - all that functionality is desired for command line args **except** for the shell exec fall through.

I ended up adding a flag to the `OpenFile()` function that will not fall through but rather try to open any files it doesn't know about. This might be a problem for binary files passed, but then at least that should be soemthing that only happens by accident.
