### ISSUE TITLE
[Feature Request] Enhance Caption Of MarkdownMonster

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#671]
So I have two Jekyll blogs, and after much angst, I discovered the setting that I can change to have multiple instances of MarkdowMonster.

My challenge now is it is difficult to tell which blog is open in which instance.

Suggestion: Is it possible to prepend the parent folder (Just the name, or alternatively the path) to the document?

So for example instead of

Window 1: **2020-01-01-frying-bananas.md**
Window 2: **2020-01-10-async-await.md**

You can have this

Window 1: **FoodBlog/2020-01-01-frying-bananas.md**
Window 2: **TechBlog/2020-01-10-async-await.md**

or

Window 1: **C:\Blogs\FoodBlog\2020-01-01-frying-bananas.md**
Window 2: **C:\Blogs\TechBlog\2020-01-10-async-await.md**

That way I can tell from the taskbar which instance to switch to.

**Comment by RickStrahl** [comment]
As to different blogs you can set up multiple profiles for each blog that you are publishing too (assuming you're using the Markdown Monster Jekyll publishing functionality).

As to the title - full pathing in the title is already supported via a switch:

![image](https://user-images.githubusercontent.com/1374013/84578258-77b3ec80-ad5f-11ea-9b1c-b83f36b08438.png)

That tends to get messy though because the path can be rather lengthy.

If you want the parent path then tabs do that already if you have multiple instances of a file with the same name but in different folders:

![image](https://user-images.githubusercontent.com/1374013/84578320-e1cc9180-ad5f-11ea-8c01-f08fcadb9cec.png)

I don't think I'm going to be changing the way that any of this works because it does provide what you're asking for even if it's not exactly what you want.

**Comment by conradakunga** [comment]
Thanks for your response.

I'm surprised I missed that setting.

That does exactly what I want.

You're right about the paths

Will probably solve that by either moving the blogs closer to the root or using a trick like Subst to mask the actual location.

But the setting works for my current predicament.

The challenge is I often work on the two blogs concurrently so it is simpler to leave two instances open all the time so when I need to work on either I can quickly switch from the other work I am doing to the blog I want to post to.

This setting is exactly what I needed.

![image](https://user-images.githubusercontent.com/1281845/84654753-682bd380-af18-11ea-81fe-154be59eff8e.png)

**Comment by RickStrahl** [comment]
I've added a new configuration that replaces the old setting with an enum of choices:

![image](https://user-images.githubusercontent.com/1374013/84967809-a22fdd80-b0b0-11ea-9158-1bb9884747e9.png)

So now you get exactly what you're looking for...
