### ISSUE TITLE
Language Support for Chinese

### ISSUE THREAD

**Issue by anson2416** [RickStrahl/MarkdownMonster#673]
Hi team,

Thanks for making MarkdownMonster. Do you know if we can add Chinese support? If yes, I think I could help as a Chinese. Thank you.

**Comment by RickStrahl** [comment]
If you're talking about localization - then no. Currently there are no translated versions of MM at all - there's no localization support. It's something I'm looking into for a future version but it's not high priority at the moment.

If you're talking about spell checking - the problem is that there aren't any dictionaries available that I could dig up and AFAIK the reason for this is this issue:

https://github.com/hunspell/hunspell/issues/502
