### ISSUE TITLE
character encoding issue

### ISSUE THREAD

**Issue by fschwiet** [RickStrahl/MarkdownMonster#677]
Attached file contains text:

- ?Qué estarán mirando? - What are they look at?
- !Serás hipócrita! - What a hypocrite!

When I open it, the extended characters show as question marks.  If I make changes and save, the extended characters are overwritten.

[extended-characters.md.txt](https://github.com/RickStrahl/MarkdownMonster/files/4991838/extended-characters.md.txt)
.

**Comment by RickStrahl** [comment]
The problem is that file is encoded with ANSI encoding. If you open this file in another editor (I used VS Code) you'll see the same thing. Now in VS Code you can switch to Windows 1252 and that will make it work, but when you open it it doesn't know what encoding the file has - so it assumes UTF-8.

So my question is: How did this file get written to be non-UTF8 since just about everything these days writes out in some UTF-8 or Unicode flavor which are supported by Markdown Monster?

It's been awhile since I added encoding in MM, but I made a concious decision not to add hundreds of ANSI encodings that can't be detected when the file is opened which brings me back to the question whether this is something that is needed by anything but a very rare edge case?

**Comment by RickStrahl** [comment]
So I'm taking a look at how to work with this. Running into some issues however with the fact that the editor itself can only handle UTF-8 or Unicode text, but not ANSI formatted characters. So there's some multi-way conversion required which is going to require some special handling.

This still not sure if this is really worth it, but giving it a look anyway.

**Comment by fschwiet** [comment]
This particular file I created by copying the text into notepad and saving from there.  But it was taken from a markdown file I had created in Visual Studio by adding a txt solution file.  Let me create such a file in visual studio again and send it to you (as that is the format I'm more concerned with, not sure it'd be the same, I don't want to send the full original file).

**Comment by fschwiet** [comment]
I'm kind of curious if the file is getting modified somehow in the process of uploading to github and downloading, so let me give some repro steps:

- Open a solution in Visual Studio (I have 2019 community edition)
- create the text file
  - right click on solution items folder, 
  - "Add" => "new item"
  - "Text file" => whatever filename (I later renamed it to an .md file)
- copy'n'paste the two lines from the issue into the text file and save
- open in markdown and observe the formatting, the special characters are corrupted

**Comment by fschwiet** [comment]
Attaching a file created via those steps: 
[repo.md.txt](https://github.com/RickStrahl/MarkdownMonster/files/5018169/repo.md.txt)

**Comment by RickStrahl** [comment]
AFAIK, most Windows text editors use either Unicode or UTF-8 for file formats **unless you explicitly choose to use a different encoding**. Using an Ansi (pre-Unicode) Encoding should be very rare these days, unless you're opening old files.

But... all that said after playing around with this MM still has a problem in that if a file is opened with the wrong encoding it'll display wrong and there's no way to reload with the correct encoding right now.

So I'm changing the way the encoding drop down works:

* Clickable button instead of a drop down list
* Opens a form with all encodings (current encoding preselected)
* Allows for: Reopen with Encoding
* Set Encoding for File

This isolates the bulk of this logic away from the main form and - as a side effect - you will be able to load files even with those ancient encodings.

This will take a bit to get right though. Lots of little side effects with all this.

**Comment by RickStrahl** [comment]
if your file is in a Unicode format (UTF-8 or Unicode (UTF-16/UTF-32)) then the special characters should 'just' work. But if the file not encoded and was originally saved with some Ansi encoding then those characters will not work. With UTF-8 formatting those characters should not be in the raw binary output - instead there would be UTF-8 escape sequences.

The 64k question then is - how is the file not getting saved as Utf-8 by Visual Studio? Pretty sure the default is UTF-8 unless VS does something different with `.txt` files.

Can you try the above sequence again and **explicitly save with encoding** and use UTF-8 or Unicode? Then open in MM. Wonder what that gives you... That should work. Also if VS can open it

**Comment by fschwiet** [comment]
Yeah this encoding stuff can be a mess and it would be reasonable to look at the situation and say "not supported".  I am really surprised that Visual Studio is creating a file that Visual Studio Code doesn't know how to read.  I didn't realize Code wouldn't open it, I did just confirm that Code doesn't know how to display it.  Being able to edit files from Code is important to me, so I would need to UTF8 them anyhow.  I garden path'd my way through all of this without selecting encodings for anything.

**Comment by fschwiet** [comment]
> Can you try the above sequence again and explicitly save with encoding and use UTF-8 or Unicode? Then open in MM. Wonder what that gives you... That should work. Also if VS can open it

I tried saving with encoding UTF8 without signature and Code and Markdown Monster were able to open it fine.  Choosing the encoding was only an option after I created the file and used the "save as" option to save it.

**Comment by RickStrahl** [comment]
VS Code can read it but you have to change the Encoding to Western European (or one of the other Ansi encodings appropriate for your region). 

I can validate your experience - see the same thing here when creating a text file. Apparently text files are created with default Ansi encoding which is pretty lame.

If you do the same thing in VS Code though the file is created with UTF-8 encoding and that will work just fine.

The only reason I'm going ahead and working with this is because in a way MM needs to be able to 'Re-open file with Encoding' after changing the encoding.

Maybe the solution to keep this simple is to just provide a handful of common encodings - then the old logic can stay intact as is with a slight modification for showing the extra encodings and a reopen option.

Most of the Unicode encodings by default have file pre-ambles that identify the encoding in the first few bytes so that makes identification much easier. But without the BOM there an application can only guess at the file format. I'll keep noodling with this and I'm sure I'll find something that'll work. Just not quite sure what that will look like exactly. I think VS Code experience is really nice for this by way of the Command Palette.

**Comment by fschwiet** [comment]
I did just confirmed that .cs files I created in the same solution with special characters are opened correctly by markdown monster, so yeah it does look like something particular to how visual studio treats text files.

**Comment by fschwiet** [comment]
Thank you for looking into this.

**Comment by RickStrahl** [comment]
Just to confirm: Visual Studio indeed creates text files with Windows-1252 (or whatever your default ANSI code page is). If I do new text file then Save As Save with Encoding I get:

![image](https://user-images.githubusercontent.com/1374013/89224569-62478b80-d574-11ea-85f8-d09e016a9b86.png)

which is the current encoding.

Bah!

**Comment by RickStrahl** [comment]
Ok, so added it as follows:

![FileEncodings](https://user-images.githubusercontent.com/1374013/89230564-40073b00-d57f-11ea-88ee-86cea735b545.gif)

In the screen shot the content hasn't been changed so the document is automatically reloaded. If the content **has been changed** a dialog pops up and prompts on whether to proceeds and allows aborting the encoding change.

We can't automatically save or ask to save because of the lack of proper encoding the file may be completely hosed, so the only option here is to abort or overwrite changes.

Note: If you close MM and reopen the file, it once again will come up with the wrong encoding because as metnioend above there's no way to actually detect the encoding correctly. This is the same behavior as VS Code which also can't detect ANSI code pages and will also default to UTF-8 as does MM.

The biggest problem with all of this is that it's non-obvious what's wrong. If you don't know the problem is Encodings you're unlikely to find and change the encodings.

**Comment by fschwiet** [comment]
Seems reasonable... I didn't realize the existing formatting option box was there (selecting UTF-8 by default).  Thats me being lazy though.  When I eventually do notice it, I would be more like to try an "ANSI" option then "Western Europe", though I suppose WU being the at the top I may have found it.  Consider hard-coding a custom label/postfix so it shows as "Western Europe (ANSI)"

**Comment by RickStrahl** [comment]
Those names are the actual names from Windows. I'm not going to go through and assign custom names especially given that this is such an edge case as is. If you don't know what those encodings are or mean, then you probably wouldn't know what a codepage is and how it works anyway :smile:
