### ISSUE TITLE
Syntax highlighting and rendering not consistent for intra-word italic

### ISSUE THREAD

**Issue by Myvh** [RickStrahl/MarkdownMonster#680]
The syntax highlighting and the rendering are not the same for intra-word italic with underscores:
![image](https://user-images.githubusercontent.com/68384832/90008905-632b9c00-dc9d-11ea-8951-980e7dfb942f.png)
I think that the syntax highlighting is wrong. GitHub renders `One_Two_Three` as One_Two_Three.
I'm using Markdown Monster 1.23.15.

**Comment by RickStrahl** [comment]
The rendered output looks right to me: The above text shouldn't be italic because it's basically one word. If I add a leading `_`  it goes italic. So the rendered output is OK.

The editor is not displaying this correctly I agree. 

But is this really an issue? Typically when you use words like this it's Variables which you are very likely to put inside of inline code block.

```markdown
The variable name is `SYNTAX_HIGHLIGHTING_ERROR` and it renders correctly.
```

![image](https://user-images.githubusercontent.com/1374013/90076066-886adb00-dc9a-11ea-8941-2abc2e569021.png)

I've filed an issue with ACE Editor which controls the markdown syntax used in Markdown Monster

**Comment by RickStrahl** [comment]
So, I added a PR to the ACE Editor repo to address this issue. It's pending but don't see any reason why it wouldn't go through. This should fix this issue in future updates to ACE when they get merged into MM.
