### ISSUE TITLE
Pandoc Parser addin minimises MM

### ISSUE THREAD

**Issue by marcusyoung** [RickStrahl/MarkdownMonster#689]
A little annoying behaviour. I run a configuration using the Pandoc Parser  addin. After it has successfully completed I then close the addin. MM is then minimised.

**Comment by RickStrahl** [comment]
Hmmm... I don't see minimization, but in some instances I see that MM doesn't get focus back. Part of the reason for that is if you opened another doc (Word or PDF viewer perhaps?) I think the Windows window stack changes that the focus goes back to that window rather than MM.

I'll see that the focus is explicitly set when the window's closed.

In the future, please post any issues related to the PanDoc addin in the repository for the addin here:

https://github.com/RickStrahl/Pandoc-MarkdownMonster-Addin

**Comment by marcusyoung** [comment]
Yes, you're right. It's a loss of focus rather than the window being minimized.

**Comment by RickStrahl** [comment]
Fixed in 714cd5fc (Pandoc Repo)
