### ISSUE TITLE
addin configuration files prevent markdown preview

### ISSUE THREAD

**Issue by marcusyoung** [RickStrahl/MarkdownMonster#691]
If you open the JSON configuration file from the plugin dropdown menu while you have a markdown document open, if you then close the configuration file (or go back to the tab for the markdown file) the preview is lost. It is also then not possible to toggle it back on.

The issue seems to be that the code syntax is changed to JSON for all open documents. If I manually put it back to markdown I get the preview back. 

On further testing, this seems to be a general problem of the editor not supporting files of different types across tabs? As if I open a JSON document, and then a markdown document, the code syntax setting for the JSON document changes to markdown.

**Comment by RickStrahl** [comment]
I've been trying to track this down for some time but haven't found a reliable repro scenario to make this happen. The syntax display is relatively new so I haven't even noticed that the doc type of the old document changed.

Will take a look.

**Comment by RickStrahl** [comment]
Fixed by moving the editor syntax association down to the Markdown Document rather than the editor. It was on editor because of old design decisions. This change touches a lot of code but by the looks of it it is safe because it always happens in the context of an editor instance. The syntax is now loaded and assigned when the document loads and always assigned.
