### ISSUE TITLE
[Feature Request] Add snagit screen capture to clipboard to enable Azure blob integration

### ISSUE THREAD

**Issue by marcusyoung** [RickStrahl/MarkdownMonster#693]
I'm not sure if this is possible for me to do myself - are the snagit presets saved somewhere so they can be edited?

It would be good to improve the screen capture to azure blob process. 

At the moment it is only possible to *save* the file after snagit edit. This means it's not usable with the Azure blob addin. I have to delete the inserted file link and start over again with the blob addin. If I could add the snagit edit to clipboard at the end rather than save, I could go straight to saving it in blob storage. Could there be an option for this?

Note: there is an issue with pasting images copied from snagit in the azure blob addin see: 

https://github.com/RickStrahl/SaveToAzureBlob-MarkdownMonster-Addin/issues/11

**Comment by RickStrahl** [comment]
SnagIt integration relies on SnagIt settings. So you can set up SnagIt the way you want it or save a profile there.

As to Azure integration you can use the Save To Azure addin for that. With that though you have to use the clipboard which is easy enough to do.

This is personal preference but I'd thought I'd mention it here:

Frankly - the integrated SnagIt screen capture process is not what I use these days anyways for screen captures, although I use SnagIt extensively. Rather I rely on the clipboard for getting images into MM which is more consistent with the way I use SnagIt for everything else.

I do:

* Bring up SnagIt with the SnagIt global hotkey (or the taskbar icon)
* Do my capture and editing
* Ctrl-A, Ctrl-C to copy to clipboard
* Then paste the image into Markdown monster as needed

If you're using the Azure Blob addin you can just paste the image into the Addin form (or it will pick it up if you foucs to it).

Why this when there's an addin? For me oddly this is quicker and more natural than the addin. I built the addin because I have that functionality in a few other tools, but with the way the SnagIt Windows UI has evolved using SnagIt directly just feels more natural than going through MM to me most likely because I use the screen capture for so many non MM things too (email, message boards, Github etc.) 

One of the problems with the SnagIt's automation is that **you can't set the output folder where the image is saved** initially. SnagIt will always use the last remembered folder which usually means the first capture you have to navigate to some funky location that doesn't match the document.

Using the clipboard approach also does away with MM being locked up in the background while I'm capturing. I often capture a whole bunch of pictures and leave them in SnagIt's image history then go back and push them into the clipboard one at a time when I'm ready to get them into MM. 

Just something to think about.

**Comment by marcusyoung** [comment]
Thanks for the info on your approach. There is a problem with copying screenshots from snagit and pasting them into the blob addin. It doesn't work for me. No image appears or is uploaded. Open image file works fine.

**Comment by RickStrahl** [comment]
Yes I'm on it. It looks like there's some sort of WPF bug that has been introduced in WPF itself that is causing the clipboard image capture to not display in the editor.

Fixing this now (by using the WinForms clipboard instead which seems to work correctly) - there will be an update shortly.

**Comment by marcusyoung** [comment]
> SnagIt integration relies on SnagIt settings. So you can set up SnagIt the way you want it or save a profile there.

I not clear how to control this. The snagit addin seems to be using a preset that requires you to click "Finish" at the end, at which point you get a save dialogue. None of my snagit presets are defined in this way.

**Comment by RickStrahl** [comment]
The finish button is part of the integration features that SnagIt provides. I can't control what that does, but that's part of the problem with this thing. Techsmith doesn't give a shit about this SnagIt addin. I have several bugs pending that haven't been addressed for several major versions. The folder configuration in particular sucks because it breaks a smooth workflow of saving in a more appropriate place to start with.

You can configure custom settings in SnagIt for capture options etc. and save htem as a profile, but they won't work with the addin. The addin has fixed behavior which is what SnagIt provides. This is one of the reasons why I don't actually use the SnagIt addin anymore. It works and is great to get started with but if you're serious about image capture and customization I think using SnagIt directly and copying from clipboard into MM directly is the more efficient way to go. So instead of using MM to launch SnagIt  you use the SnagIt hotkey (or taskbar icon). Capture, and edit if you need to, Ctrl-A, Ctrl-c, then paste into MM where needed (or at current cursor). This will prompt you for a filename to save using MM's pathing options which are per document or per project, current doc folder etc.

**Comment by RickStrahl** [comment]
Going to close this because there's really nothing else I can do here effectively.

**Comment by RickStrahl** [comment]
Ok so I was able to actually make this work, although I'm not sure if that will make any sort of difference to your scenario. 

But it does fix the bug in SnagIt2020 that wouldn't save files when clicking the Finish button, which now works because I'm no longer using SnagIt to capture the file but rather place the image onto the clipboard and then save to disk explicitly. This gives back control over the output filename.

Seems to work and the process is much smoother overall.
