### ISSUE TITLE
Multi monitor doesn't show icon on the task bar

### ISSUE THREAD

**Issue by woanware** [RickStrahl/MarkdownMonster#697]
Working with a multi-monitor setup, and Windows configured to only show the icon on the taskbar for the desktop/monitor it's open on, then the icon doesn't show e.g. I have MM open on my right monitor, but the icon doesn't appear on the right monitors task bar, just on the left one

**Comment by Smurf-IV** [comment]
It's annoying yes, But I just use the  Holding (Windows Key + Shift) then press the right arrow twice, gets the icon the correct screen.

Having a guess, I think it is to do with the "Splash / Loading" form loading on the default monitor, and then the actual app realising that it was last loaded on the other screen.

**Comment by RickStrahl** [comment]
I'm not sure I can duplicate this.

I have this configured:

![image](https://user-images.githubusercontent.com/1374013/92572431-244b2080-f220-11ea-9503-5d388c16c523.png)

If I start MM on the second (non-primary) monitor I see the icon on the second screen.

If I move MM from one window to the other, I see the icon on the correct screen.

What am I doing differently than you here?

**Comment by woanware** [comment]
I tend to always have MM on my right monitor, so it's in that position when closing e.g. it will load back by default onto that monitor perhaps?

It doesn't matter which Start Menu I use to start MM, the splash screen shows on the left monitor, and then MM loads onto my right monitor, but not showing in the task bar.

The screenshot below shows my task bar and MM loaded on that monitor

![image](https://user-images.githubusercontent.com/1075956/92584907-264ac900-f28c-11ea-81e2-49cc6cae40d2.png)

**Comment by RickStrahl** [comment]
As I said I'm not sure what your setup is - please double check. I don't think you have the same settings as I have - because it sure sounds like you have your taskbar set to show icons only on your main window. 

For me moving the window or starting on the second screen with the settings I show above works as expected.

The splash screen will always come up on the main screen because it's not directly controlled by the application (it's the WPF splashscreen bit that pops a bitmap on startup before any forms load so it's fast). I can't control where that goes because the application has no control at that point. The main window uses the last used position to open the main window and if that was on another monitor it will go back to that other monitor. If the location is off screen (ie. a second screen is no longer available) MM will try to reposition itself back on the main monitor.

**Comment by woanware** [comment]
These are my task bar settings :-)

![image](https://user-images.githubusercontent.com/1075956/92693218-379fde00-f33d-11ea-9114-9fbe5c4303d9.png)

The person above who commented, also has this issue, it's not major but it is a bug, so thought I would mention it

**Comment by RickStrahl** [comment]
I'm not sure then. 

But regardless, Windows controls the behavior of the taskbar buttons, so the application can't really control this. Once the app is open on a given monitor Windows either displays the icon or not if the window is set to display an icon. So my guess is there's something interfering on your setup that affects the taskbar display. Perhaps some utility or tweak?

FWIW when I move my window to the bottom of the window like in your screen shot I also get no icon - presumably because the majority of the window is not actually in the active screen. But if I move the window up and make it fit (or mostly fit) onto the screen, the icon shows up. Which again...  is **Windows** behavior, not MM.

**Comment by Smurf-IV** [comment]
This is a real issue (Not high, but real) FYI:
- I have no "Tweaks" set.
- The window is not "Offscreen"
- My main monitor is the left one
- Both monitors are the same resolution and size 
- Resolution is not the problem (As before I upgraded to higher, it used to happen)
- Splash opens on left, MM opens on right as expected
- Task Icon remains on the left
![image](https://user-images.githubusercontent.com/2418812/92873496-fc65e380-f3fe-11ea-90e6-06fd6f9673e5.png)

**Comment by RickStrahl** [comment]
@Smurf-IV I'm not saying there isn't an issue, I saying I  can't duplicate it. There's something else happening here that may or may not be unrelated to MM's behavior.

What version are you using? Latest versions (as of 1.23) use a new version of MahApps which changes general Window management  logic. Can't say what happened before that version, but I've never in all the years of using MM seen the behavior that is described in this post. Then again I most of the time run with all icons on all taskbars... but right now I'm running with it using the settings above to test and I can't duplicate the behavior you describe.

What I see is this:

* Run MM, move to secondary monitor and  close MM on the secondary (my right) monitor.
* Start MM
* Splash screen shows on main screen which is expected
* MM icon briefly flashes on the main screen
* When the window actually opens the MM icon moves to the secondary screen

v1.24.1

This is the expected behavior. The short flash of the icon on the main screen occurs because MM has to read the startup location as part of the startup code and only after that moves the screen to its last location. So the brief flash is the time when the form is not yet visible but loading into the default Windows location before getting moved. Don't think there's a way around that because taskbar options have to be set on launch of the form.

So even assuming there's a reproducible bug here, I don't think this can be fixed because it's basically Windows that's controlling the icon placement. It might be timing that's causing this issue, but then again I can't see how slower (or faster) operation would change the window taskbar location display given that the window is displaying correctly on the new monitor.

**Comment by RickStrahl** [comment]
Ok so I think I found the failure in this specific scenario:

* Works fine when using my secondary monitor as the main monitor 
* Fails as described in this bug when using the Laptop as the main screen

I played around a bit with the startup processing and it turns out you can change the `ShowInTaskbar` setting after the window is initially loaded, so this value is now set **after the Window position has been adjusted**. This should fix the issue you're seeing.

Please take a look in 1.24.2 or later.

**Comment by woanware** [comment]
Have just updated, and it appears to be fixed, thanks!
