### ISSUE TITLE
[Feature Request] - Resizing images

### ISSUE THREAD

**Issue by stefanstranger** [RickStrahl/MarkdownMonster#698]
I often need to resize images in the Markdown documents I create.

Until now I used html to resize an image if it needed to be resized .

e.g.

```html
<img src="foo.png" alt="Image to be resized" width="460" height="422"/>
```

Would be great to have an interactive option to resize the image in the preview pane and select a corner of the image and drag the image to the correct size.

No idea if this is possible in the preview pane but it would be great extra feature.

Regards,
Stefan Stranger

**Comment by RickStrahl** [comment]
I don't think that's too difficult, but not sure if that's really very useful? You can already resize explicitly by setting the image size values in the image preview. I'd argue seeing the resized image without the context of a page it's displayed in is not all that useful.

Furthermore, wouldn't you almost always let the image resize itself by using CSS styling to `img { max-width: 100% }`? It seems like a bad idea to resize the image for fitting into the document unless it's huge (in which case resizing isn't really an option since it's probably not fitting into the image viewer anyway.

**Comment by RickStrahl** [comment]
FWIW, the image resizing on that form for clipboard images was broken, so I've fixed that. When you paste an image it now properly shows the image size which you can change manually and the image resizes with it. It also better preserves transparency in most cases (depends on the exact image format).
