### ISSUE TITLE
Suggestion: Update links after file rename in folder browser

### ISSUE THREAD

**Issue by riskcon** [RickStrahl/MarkdownMonster#700]
I am looking for an editor to work an a whole set of markdown files placed in a folder structure and linking each other. If a file is renamed all the links pointing to it need to be updated, otherwise I cannot "refactor" the growing documentation. Does no one else need this I wonder?

**Comment by RickStrahl** [comment]
Interesting thought. Agree that would be useful but it shouldn't be the default behavior - too much potential for messing up file links by accident in this.

But some sort of refactor feature that would allow link and file refactoring sounds useful.

I have to think about how this should work. It's almost like we could use a Refactoring addin that could take over some custom refactoring tasks.

**Comment by riskcon** [comment]
Yes, it would suffice to have it as a special renaming that you deliberately choose when links need to be updated. Does the addin API have all the necessary hooks/entry points to build something like that?

**Comment by RickStrahl** [comment]
The Addin API is pretty flexible and functionality wise it's possible. The UI part is the harder issue - getting a menu option into the folder browser would require some tweaking I think. I have to take a look.

The way I see how this should work:

* Menu option like Rename with Link Refactoring (or something like that)
* Pop up a dialog
* Show base path(editable): Dialog tries to guess based on MM's project discovery what the base path is
* Show old file name
* Show editable new file name

You'd then click a button to find all the matching files which get displayed in a list with a checkbox next to them (all checked by default). Clicking would open them in the editor on first matching line.

Another button and it would then rename the file and all the links in the checked file.

---

The basics of this are not too complicated. If it's really just the filename then it's fairly straight forward to make those changes as you can basically do the equivalent of a replace in files (with some extra checks).

But the next issue then becomes that you likely also need this same behavior when moving a file to a new location. This is considerably more tricky because in that case the path has to be updated which is much harder because paths come in some many different variations (relative, rooted, full path, web path, OS path etc.). That part I'm not so sure about - it would have to be handled differently probably through the drag and drop API, but eventually somehting similar is required for that.

**Comment by RickStrahl** [comment]
I've added static eventhandlers to all the dynamically, runtime generated context menus including the FolderBrowser menu that allows the ability to add custom menu items to these context menus.  

8f953507

This should allow adding a custom menu option  to after the rename for example. 

Should be useful for all sorts of other stuff too especially for addin authors.

**Comment by riskcon** [comment]
Thank you for looking into this so fast and thoroughly! I wonder if handling paths becomes easier considering that the whole file movement will always take place inside a root folder? So no movement between different drives or network shares.

**Comment by RickStrahl** [comment]
Won't be implementing this. There's too much margin of error and incorrectly marking up wrong links. Modifying documents of existing content is always tricky and validating those changes goes somewhat beyond the scope of a text editor.

It's something that can potentially be addressed in a custom addin that specifically performs this task with offloading the risks from the main MM application.
