### ISSUE TITLE
Focus the editing area when opening a file from outside of MM

### ISSUE THREAD

**Issue by marin-bratanov** [RickStrahl/MarkdownMonster#705]
When I open a `.md` file, I expect to be able to start editing it - for example MS Word puts the cursor at the beginning of the first line, just like most notepad-type apps. I use double-click or Enter from Windows Explorer to open the file.

The problem is that MM does not take the focus, so the focus remains in my folder even though MM is at the front of my monitor.

This causes the following issues:

* I cannot start typing, scrolling and so on with the keyboard, I need to reach for my mouse to click the correct area
* I cannot search for content (`Ctrl+F` does not trigger the search box)
* It is extremely easy to close what you don't mean to by pressing `Ctrl+W` expecting to close the file you just skimmed and decided you don't need - it will actually close the folder you still have focused

**Comment by RickStrahl** [comment]
How are you opening a new file?

Ctrl-n or File | New all should give you a new doc with the cursor in it ready to type.

If you use the folder browser, it only creates the file it doesn't open the file - you can press Enter on the file to open it and that is the expected behavior in that context so that you can create multiple files quickly.

**Comment by marin-bratanov** [comment]
I usually have the `.md` file in the folder which I have opened in Windows Explorer (Windows 10 user), so I press `Enter` when I get to the file I want. I don't create new files through MM.

The cursor blinks in the first row at position 0, but the focus isn't there - `Ctrl+W` will close the Windows Explorer folder, typing types...somewhere, but not in MM. `Ctrl+F` does not open the Find dialog in MM.

This does not happen all the time, and I think having MM maximized makes it happen more often.

**Comment by RickStrahl** [comment]
Can you give me exact steps please? I'm not sure from your description what you're doing.

**Comment by marin-bratanov** [comment]
1. Open a folder with some .md files
1. Use `Up` and `Down` arrows to select the one I want to open
1. Press `Enter` to open it in MM
1. Repeat 1-3 for another file so you now have two tabs open (the issue reproduces much more rarely if you only have one)
1. Press `Ctrl+W` to close it - closes the Windows Explorer folder instead of the MM tab

If you use a `double click` instead of `Enter` you can often see how the Windows Explorer folder remains on the foreground and focused, instead of MM.

Unfortunately, when trying to record my screen the behavior goes away, screen capturing often seems to do things like that because it seems to tie to the cursor somehow and alters that type of behaviors. Nevertheless, below is avideo that's as close as I can get.

In the video:

1. I first have MM open with one document
1. I double click another - you can see MM blinking in orange in the taskbar - inactive window that has an event
1. I try press `Ctrl+W` to clsoe the file I just opened and the folder closes instead
1. I re-open my folder, select a file and press Enter on the keyboard - MM again flashes in the taskbar as a background application with an event
1. Pressing `Ctrl+F` or `Ctrl+W` this time do nothing, but it would usually close the folder (screen recording alters the behavior here)
1. I then bring up the on-screen keyboard to show how the focus is not in MM and it does not respond to the key combinations above - it keeps blinking in orange in the taskbar as an inactive app. Without screen recording it closes the folder, the on-screen keyboard is just an attempt to show my keypresses

[closest-to-repro-I-can-record.zip](https://github.com/RickStrahl/MarkdownMonster/files/5346537/closest-to-repro-I-can-record.zip)

**Comment by RickStrahl** [comment]
So I took a closer look and this is a lot more difficult than I thought it would be. It turns out the editor is properly getting focus, however, there's some sort of Windows focus issue that doesn't transfer the focus from Explorer (or another external app) into the WPF. 

Tried a bunch of different approaches but nothing seems to really work to force the Window focus into MM. Doing a bit more research to other approaches.

**Comment by RickStrahl** [comment]
I'm coming to the conclusion that this functionality may not be possible **due to Windows restrictions that don't allow applications to force themselves into focus** arbitrarily except by direct activation or via Shell Loading.

The following demonstrates this behavior as I can't activate a non-active MM instance when running externally even with Windows API calls:

![image](https://user-images.githubusercontent.com/1374013/95533506-07b91a00-097f-11eb-93bb-960fb4aaada3.png)


The behavior you describe works fine when MM is not running yet. In that case the  Exe is launched and MM is allowed to focus because it goes through the standard Shell APIs. So that's the correct behavior and it works.

However **if MM is already running**, launching from Explorer causes a new EXE instance to launch, which checks for an already running instance. If there is one it forwards the command line to the already running instance which then opens the document and shows the editor, while the new EXE just exits. The opening logic works fine: The editor is loaded and the cursor shows as active, but the application focus stays inside of Explorer - any keystrokes go into Explorer rather than into the MM Editor tab.

The problem here seems to be that the already running instance can't set focus to itself. Everything I've tried here including form focusing, using an explicit text control to focus, setting Topmost to true, using PInvoke calls - they all fail to actually set the focus for the form which all seems to point at the Windows limitation that doesn't allow application to steal focus unless they are properly activated.

**Comment by RickStrahl** [comment]
So I found a way to make this work after using the `SetForegroundWindow` Win API. WPF based activation, nor `SetActiveWindow` were working but `SetForegroundWindow()` seems to work reliably to activate the MM window and set focus into the editor (which worked before but the Window wasn't focused).

**Comment by marin-bratanov** [comment]
Thank you for your time, efforts and the free lesson, I do appreciate it, and the whole MM, it's been my md editor of choice since I found it (I especially love the ToC generation of the headings).

**Comment by RickStrahl** [comment]
Updated in 1.24.10

**Comment by marin-bratanov** [comment]
Thanks! I've installed and, unfortunately, it does not seem to help. There is a new issue, however - until I close it, 
MM now remains the topmost window and I can't show another window above it (like the folder with my md files).

[video-mm-always-on-top.zip](https://github.com/RickStrahl/MarkdownMonster/files/5354503/video-mm-always-on-top.zip)

**Comment by Lakritzator** [comment]
Hi Rick,

I wanted to add some background information, and maybe a solution.

Since Windows XP Microsoft decided to change some behaviors to prevent applications from stealing focus. In general this is a good thing, who wants that suddenly the focus is gone. But this also adds some challenges to the applications. In Windows 7 it got a bit stricter, and in following Windows releases even more.

Here in the remarks are the details about why changing the focus doesn't work:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow

And some more information can be found here, note the "alt" key remark: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-locksetforegroundwindow

In general starting a new application because the user did something will give your application focus, but if I understood your case you start an exe to handover information to the running instance. A running application **generally** cannot steal focus.

Generally... what does this mean? Well if you look at the second link there is something about the "alt" key.
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-locksetforegroundwindow

So I needed to add a very hacky solution to make this possible... You can see the code for this here, in my open source code (MIT License) for doing stuff that Greenshot needs:
https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows/Desktop/InteropWindowExtensions.cs#L594

**The trick is besides doing the PInvoke, also to generate the ALT-key presses.** You will be able to find all the code in the repo, I don't mind if you use any of it if that hacky way is the way you are going for.

You could use my project via nuget, but you might not want due to the additional bloating...

Btw. there are some very interesting functions in that repository, like using the clipboard via IObservable so you can de/register a clipboard observer which gets all clipboard changes, with only knowing System.reactive. It should also help with delayed rendering, or access in general. Example here: https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Tests/ClipboardTests.cs#L157
There is a lot more in there, global hotkeys, getting window title information etc.. more to come too. I still need to change my pinvoke usage to https://github.com/dotnet/pinvoke, but most the functionality will stay as is.

Let me know if I can help you more!

P.S.
If you are debugging with Visual Studio 201x you might not always get what you want when you do stuff like this. It's a weird world...

Best wishes,
Robin

**Comment by RickStrahl** [comment]
@marin-bratanov Hmmm... I can't duplicate that behavior. Can you give me steps? FWIW, the top level window - if that is happening is not supposed to be happening. It's possible that a new bug has crept in because this does affect the top level flag I use to force the window to top but it should unset before loading is done.

I just went through your previous steps and I see:

* Open MM
* Go into Explorer
* Navigate to an .md file and press enter
* MM opens doc and cursor is there
* go back to Explorer - Explorer becomes topmost window (ie. MM is not topmost)

I also can't get MM to be top most in these scenarios:

* Opening MM for first time
* Openiong MM from Explorer on .md file

So, if you're seeing that - what are you doing to get MM to be stuck topmost?

**Comment by RickStrahl** [comment]
@Lakritzator Thanks for the info. It looks like PInvoke (with SetForegroundWindow) works without any additional settings, so not sure if anything else is needed at least in the MM activation scenario.

**Comment by RickStrahl** [comment]
@marin-bratanov Give it another try with 1.24.10.1 - that fixes the .md launch topmost issue.

**Comment by marin-bratanov** [comment]
@RickStrahl On the upside - 1.24.10.1 fixes the issue where MM was always topmost which lets me keep using the other programs.  It does not give me the focus from the original issue, though, `Ctrl+W` still closes the windows explorer folder like in the first video ([post link](https://github.com/RickStrahl/MarkdownMonster/issues/705#issuecomment-705432760)). 1.24.10 didn't solve it for me either.

**Comment by RickStrahl** [comment]
That is strange. 

Here's what I see:

* Open MM
* Go into Explorer
* Navigate to an .md file and press enter or double click
* MM opens doc and cursor is there and I can start typing into the document

![MM_Focus](https://user-images.githubusercontent.com/1374013/95607855-07a93080-09f8-11eb-8eb6-4d0bb7a84b8f.gif)

You're not seeing this?

**Comment by RickStrahl** [comment]
Alright. I was able to duplicate the problem you described previously on another machine. out of 3 machines 1 didn't work, while the other 2 did.

Anyway, I think I have a solution now that handles this - at least it works on the machine that previously didn't work.

Give a try with 1.24.12

**Comment by marin-bratanov** [comment]
Looks good to me! Thank you for the amazing work and ultra-fast responses!

**Comment by RickStrahl** [comment]
Thanks for bringing this up. I totally would have missed this since it's apparently just outside of my own usage where I usually mouse into MM and didn't notice. Definitely needed fixing. Aloha!

**Comment by marin-bratanov** [comment]
I am willing to bet there are so many more usage patterns, but I think things mostly work fine in MM, especially if you are a casual user. I tend to write a lot of documentation in md and it is not uncommon for me to have 10+ documents open at any time, and I still haven't hit major ones. So, if you want me to report similar findings I can keep opening issues (e.g., about how closing one document/tab does not focus the next).
