### ISSUE TITLE
Insert Link action uses %2F for encoding slash or backslash character

### ISSUE THREAD

**Issue by mattslay** [RickStrahl/MarkdownMonster#712]
If I use the Insert Link action in the toolbar to link to another md file **in a different folder**, Monster is encoding what should be a slash or backslash a with "%2F" instead of "/".

![image](https://user-images.githubusercontent.com/309016/96914429-9b541580-146a-11eb-9f5a-dfe2dc0b3b16.png)

Is should be:

`Computers/Computers.md`

**Comment by RickStrahl** [comment]
This should be fixed in the latest update (per your other bug).

Technically speaking the above syntax is most correct as URLs should be URL encoded, but it's not necessary and the latest fix only fixes up the spaces that break Markdown rendering due to the space being interpreted to terminate the URL in the markup.
