### ISSUE TITLE
reStructuredText support

### ISSUE THREAD

**Issue by Philippe91** [RickStrahl/MarkdownMonster#715]
reStructuredText is supported by GitHub (https://gist.github.com/dupuy/1855764)
and is gaining popularity IMHO, because it can be used to create better documentation
(https://www.sphinx-doc.org)

Therefore, I call for reStructuredText support...

**Comment by RickStrahl** [comment]
This has come up before and it's been put aside because this isn't Restructured Monster :-)

It's possible to do this with an Addin that uses a custom parser to generate the HTML output. The problem is that things are different enough with RS that it would produce inconsistent behavior for the editor surface. That might be OK for  a custom plug-in, but not so much for the main product.

Long story short I can't see this ending up as a native built-in feature...
