### ISSUE TITLE
Resizing splitpane moves the markdown view out of the boundaries

### ISSUE THREAD

**Issue by me-kell** [RickStrahl/MarkdownMonster#716]
When the splitpane divider (between text and markdown view) is dragged to the left until its maximum and the mouse continues to drag to the left the following happens:

1. the content of the markdown preview moves to the right and the left margin in the markdown preview increases

1. the size of the markdown preview pane slightly increases on the right side moving the scroll bar to the right and disapearing

1. the increase (1 or 2 pixel) on the right side makes impossible to resize the window from the right side. Resizing is only possible on the right side either up in the menu/icon bar or down in the status bar

Furthermore, when the window has three panes (sidebar, editor, and preview) and you drag the divider between sidebar and editor to the right until its maximum the same behavior is observed.

Observed in Version 1.24.12 32 bit .NET 4.8 Portable mode

**Comment by RickStrahl** [comment]
Whoa that's a weird one. It looks like the pane keeps expanding into negative space, while the browser control won't go into the negative space so the overflow is stretching beyond the window (invisibly I suppose).

Not sure if I'll be able to fix this - the overflow behavior is the WB control, so if something funky is happening with airspace that's not going to be fixable. But I can possibly fix the reszing of the splitter perhaps so it won't expand beyond the zero bound.

**Comment by RickStrahl** [comment]
So I think I fixed this issue by explicitly checking the preview pane size and ensure it doesn't get larger than the EditorPreviewPane container. 

WPF * sizing causes the Window to overflow and that's what's breaking the border. If it wasn't for the Web Browser controls that are used this wouldn't be an issue, but due to the airspace issues with the WB control it'll overlay the border and that's what caused the border to become unavailable in the EditorPreviewContent area.

**Comment by RickStrahl** [comment]
Ok the issue described here is mostly resolved, but there's still a problem if the form is resized and the preview pane overfills the editor. The same fix that works for the preview doesn't appear to work for the window resize.

TODO: Fix for Window Resizing

**Comment by tjrobinson** [comment]
I think this is a variation of the same problem, so I'm mentioning it here rather than a new issue. If I am using the preview pane with MM maximized, and then resize the window to only use part of the screen, the preview window is the only thing I see, the editor is not visible until I maximize again.

Maximized:

![image](https://user-images.githubusercontent.com/925311/99881835-f157dc80-2c13-11eb-8703-de758d31646f.png)

Not maximized:

![image](https://user-images.githubusercontent.com/925311/99881841-f9178100-2c13-11eb-8346-8e153898c57c.png)

Markdown Monster Version 1.25.5, Windows 10

**Comment by RickStrahl** [comment]
@tjrobinson No that behavior is actually expected (the overflow may not be, but the maximized view is). The reason for the sizing issues is that the preview pane stays fixed in size to whatever you size it to - the editor is adjusted to match. When maximized and then reducing chances are very likely that the preview will be larger than the editor pane and so obscures it. 

The bug here is the overflow is somehow wiping out the window borders and unfortunately I've not been able to reliably detect when the editor pane goes below zero. There are events and bindings but they are not respected properly and not reporting the right values in this scenario - or worse resulting in a recursive loop when resizing explicitly. I'll keep looking but I'm starting to think I can't fix this edge case.

**Comment by RickStrahl** [comment]
I haven't been able to track this down but I won't fix this given that it's a relatively minor annoyance. It's all the time I'm willing to spend on this. Will review when the time comes to update the browser controls to the WebView which most likely will resolve this as the airspace issues will change.
