### ISSUE TITLE
Header ending in \ causes problem with TOC

### ISSUE THREAD

**Issue by djfm501** [RickStrahl/MarkdownMonster#717]
I have the following header:
```
### Jump to bracket: ctrl+shift+\
```
The TOC entry is generated as:
```
* [Jump to bracket: ctrl+shift+\](#jump-to-bracket-ctrlshift)
```
I believe that the \ escapes the ]

I tried
```
### Jump to bracket: ctrl+shift+\\
```
But the TOC entry was the same

**Comment by RickStrahl** [comment]
TOC as in the generated TOC that goes into the document, or TOC as in the bookmark sidebar? (assume generated TOC).

**Comment by djfm501** [comment]
The generated TOC in the markdown file:

### Jump to bracket: ctrl+shift+\
generates the TOC entry
* [Jump to bracket: ctrl+shift+\](#jump-to-bracket-ctrlshift)
which displays as:

[image: image.png]

**Comment by RickStrahl** [comment]
Hmmm... so I think what's happening here is that the single slash is escaping the `]` which causes the 

So this fails:

```markdown
* [Jump to bracket: ctrl+shift+\](#jump-to-bracket-ctrlshift)
```

but this works:

```markdown
* [Jump to bracket: ctrl+shift+\\](#jump-to-bracket-ctrlshift)
```

The problem is that the way the document is parsed is via HTML which unescapes the actual header tags. There's no real way to encode that string because on its own it's actually valid:

```markdown
Jump to bracket: ctrl+shift+\ is valid text.
```

I think the issue is simply that the \ is escapign the `]` and so I think the only thing that needs to get fixed here (thankfully) is the trailing slash which has to be double slashed.


So I can fix this I think by explicitly converting a **trailing** `\` or `\\` into `\\`.

```csharp
// handle trailing backslash which escapes the bracket  `\]` and turn into `\\]`
if (!string.IsNullOrEmpty(text) && text.EndsWith("\\"))
    text = text.TrimEnd('\\') + "\\\\";
```

Looks like that works, but I'm not 100% convinced this fixes all the scenarios where escaped chars can be a problem. But it does solve the immediate bug.

**Comment by djfm501** [comment]
Thanks for looking into this.  For now I will simply change the header into:

### Jump to bracket: ctrl+shift+backslash

**Comment by RickStrahl** [comment]
Well this is fixed for this particular use case now. You can grab the latest preview version with the fix.
