### ISSUE TITLE
mermaid class diagram displayed incorectly

### ISSUE THREAD

**Issue by kashiash** [RickStrahl/MarkdownMonster#720]
im trying to build diagram using mermaid markdown:

```mermaid 
classDiagram
    Organizacja <|-- Organizacja
    Organizacja <|-- PodmiotLeczniczy
    PodmiotLeczniczy <-- JednostkaLecznicza : jednostki w podmiocie
    Organizacja <|-- JednostkaLecznicza
    Organizacja <|-- Komorka
    JednostkaLecznicza o-- Komorka
    JednostkaLecznicza *-- JednostkaZP
    Komorka *-- KomorkaZP
    KomorkaZP o-- JednostkaZP
    Organizacja : run()
    class Organizacja{
      +String nazwa
      +String regon
      +String nip
    }
    class PodmiotLeczniczy{
       +String regon14
        +String kodResertowy
    }
    class Komorka{
      +String kodResertowy VII
      +String kodResertowy VIII
    }
```

but this is not displayed with class details

**Comment by RickStrahl** [comment]
Looks like that requires a newer version of Mermaid than what we've been using. MM internally uses v7.1.2 because that's the last version that apparently supports Internet Explorer 11. Anything post 8.0 doesn't work in IE 11.

if a newer version of Mermaid is used your mermaid code works:

https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

With that I correctly get:

![image](https://user-images.githubusercontent.com/1374013/99119359-2ec9c380-259d-11eb-8473-28f049712e6f.png)

But with that the Web browser control no longer renders.

So I think in order to make this work better we need to do a few things which are not great:

* Give up on Preview Browser Previewing
* Use the latest version of Mermaid.js
* Rely on external preview to show the diagrams (Shift-f12)
* Figure out some way to render graphs in preview and maybe provide a link that lets you see the graph
     * Just show the code 
     * Show some custom UI that allows to click to view diagram

FWIW - we're looking into ditching the Web Browser control in the not so distant future. Currently waiting for the Microsoft WebView2 control to be production ready but unfortunately there are still a bunch of major issues open in that control which is still in preview.

**Comment by RickStrahl** [comment]
So I've implemented some scripting features in `preview.js` that will no longer try to display Mermaid content inside of the Web Browser control but rather display a placeholder, that holds a link you can click on to view the diagram.

![Mermaid](https://user-images.githubusercontent.com/1374013/99575803-357d7f80-297d-11eb-9cc9-119d5d8cd571.gif)

Until the time that we replace the old IE based browser with the new WebView2 this will have to do.
