### ISSUE TITLE
when add 2 or more mermaid graph only first is displayed corecctly (almost)

### ISSUE THREAD

**Issue by kashiash** [RickStrahl/MarkdownMonster#721]
when write two mermaids , the second is displayed incorectly:

```mermaid 
classDiagram
    Organizacja <|-- Organizacja
    Organizacja <|-- PodmiotLeczniczy
    PodmiotLeczniczy <-- JednostkaLecznicza : jednostki w podmiocie
    Organizacja <|-- JednostkaLecznicza
    Organizacja <|-- Komorka
    JednostkaLecznicza o-- Komorka
    JednostkaLecznicza *-- JednostkaZP
    Komorka *-- KomorkaZP
    KomorkaZP o-- JednostkaZP
    Organizacja : run()
```

```mermaid 
classDiagram
    Organizacja <|-- Organizacja
    Organizacja <|-- PodmiotLeczniczy
    PodmiotLeczniczy <-- JednostkaLecznicza : jednostki w podmiocie
    Organizacja <|-- JednostkaLecznicza
    Organizacja <|-- Komorka
    JednostkaLecznicza o-- Komorka
    JednostkaLecznicza *-- JednostkaZP
    Komorka *-- KomorkaZP
    KomorkaZP o-- JednostkaZP
    Organizacja : run()
```

![image](https://user-images.githubusercontent.com/10448372/99078878-69445800-25bf-11eb-9320-f112f934c6d3.png)

**Comment by RickStrahl** [comment]
So I've removed preview support for Mermaid in the native previewer since recent versions of Mermaid don't work at all with Mermaid any longer (no more IE 11 support). So now there will be a placeholder with a link you can click that will open the document in your external browser and navigates the document to the diagram (if supported - file URLs with hashes).

![Mermaid](https://user-images.githubusercontent.com/1374013/99619529-bf523a80-29c7-11eb-85e0-
aba19b82e1c4.gif)

Until we replace the IE Web Browser control with WebView2 (which has other problems that prevent us from doing this now) this is as good as Mermaid support can be at this time.
