### ISSUE TITLE
[Bug] Search field losing focus.

### ISSUE THREAD

**Issue by jovibor** [RickStrahl/MarkdownMonster#726]
The hard part of this bug is that i could not catch exact circumstances it triggers under.

But the gist is very simple:
1. Open any document.
2. Press Ctrl+F (search box opens).
3. Start typing some character sequence that exists for sure in the document.
4. Editor starts to highlight found sequences in the document. It can even scroll sometimes to the matched sequence.

**[Bug]** Not always but sometimes, in the process of writing characters into the search box, the focus suddenly jumps into the document, and all the subsequent input goes to the document itself, not into the search box.

The good news (for tracking that bug down) it happens not that rare.

**Comment by RickStrahl** [comment]
I played around with this a bit, but I can't duplicate this behavior. I see the search box staying focused.

One thing that I think might be happening is that if you scroll the doc due to search the preview will updated and perhaps a secondary scroll from the preview to the editor might be having some sort of effect on the search box. I don't see that but I can see how that might have an effect.

Can you try turning off two-way scrolling (on the statusbar rightmost icon) and set it to **Preview to Editor** and see if you get better results? That would confirm that it's a scrolling feedback issue if that removes the problem completely.

**Comment by jovibor** [comment]
1. I don't use *two-way* scrolling, only *Editor to Preview*.
2. I set it to *Preview to Editor* and still could catch that bug just trying **Ctrl-F->typing** within the 3-5 minutes frame.
3. One thing to mention: even when in *Preview to Editor*, scrolling the editor still scrolls the preview, certainly a bug as well  (1.25.6).
4. When search box loses the focus the input goes to the editor view exactly at the place where highlight from the search was taking place.

> I played around with this a bit, but I can't duplicate this behavior.

It's the hardest. I could not catch exact reproducible sequence, cuz it's definitely related to some internals.

**Comment by RickStrahl** [comment]
Still can't duplicate this behavior.

#3 in your list was recentfly fixed along with various other scroll updates.
