### ISSUE TITLE
Some Elements are hidden if the window is too small

### ISSUE THREAD

**Issue by timunie** [RickStrahl/MarkdownMonster#727]
## The issue
I found that some items get clipped if the window is too small. Unfortuantally I often don't know that there is hidden stuff. 

## Screenshot
Here is an example screenshot of the settings window. The same can be found in many other windows. For now I didn't test all windows, 

This is what I see first:
![image](https://user-images.githubusercontent.com/47110241/100785276-b40ffd80-3410-11eb-87cc-342e8a8be27c.png)

And this is the view after resizing. Notice the additional content:
![image](https://user-images.githubusercontent.com/47110241/100785374-d6a21680-3410-11eb-9022-fb27ffab65e3.png)

## Possible solutions: 
- Make the XAML more flexible. The `Toolbar` should show an overflow if it has hidden items. (my favorite)
- Adjust the `MinWidth` of the window to ensure everyting is visible
- Hide the buttons texts if there is too less space

## Environment
![image](https://user-images.githubusercontent.com/47110241/100785870-90998280-3411-11eb-9b04-cd7cbbc4d319.png)

## Additional content
If you want I can see if I can manage to fix this and provide a PR. Maybe one window after the other to not mess up too much. 

Happy coding
Tim

**Comment by RickStrahl** [comment]
So, we're talking about the toolbar here right? I don't see other things getting clipped (in this particular window). I bumped the min-width a little to ensure the settings panel fits and the scrollbar is there.

The other part is the toolbar. 

I've been using a `ToolbarPanel` and a `StackPanel` containing the Toolbars rather than using a `ToolbarTray`. The main reason I chosethat is because I **hate** movable toolbars and I've not been able to figure out a way to keep toolbars in their fixed position in the toolbar tray. But that also loses the overflow which is useful.

So I did some experimenting and maybe the way to do this is to use:

* ToolbarTray
* Toolbar with `ToolbarTray.IsLocked="true"`
* Use a `<Separator />` to separate the toolbar groups

This looks like this:

![image](https://user-images.githubusercontent.com/1374013/100805724-4db8ba00-33d3-11eb-90ee-4b3eceeb0dc5.png)

I think I like that. Note the overflow is still there at the end of the toolbar and the toolbars are fixed and we have separation which actually looks cleaner than the toolbar drag handles that otherwise would be confusing because they don't actually work as expected.

**Comment by timunie** [comment]
Hey @RickStrahl 

I would do it in a similar way if I was you. 👍. IMO the new design looks nicer and cleaner. I provided a draft PR of some additional changes / ideas which makes the UI even more resize-able. It is completely up to you if you want to take these ideas or not. 

Happy coding
Tim

**Comment by RickStrahl** [comment]
So I ended up waffling on this and going back to unlocked Toolbars, but instead resizing and fixing min-width sizing on a bunch of the forms. After experimenting I tend to think that the movable toolbars look more consistent and also work if content is obstructed as they can be moved  around if necessary.
