### ISSUE TITLE
Detecting if another application changes a loaded file

### ISSUE THREAD

**Issue by itimpi** [RickStrahl/MarkdownMonster#734]
I am frequently editing a markdown document that is stored in a shared Dropbox folder.    This means that someone else with access to that shared folder may make their own edits to a file I am working on (or at least have loaded). It would be nice if Markdown Monster could detect this had happened and give me the chance to load the updated document.    This would help with collaborative working.   An example of the behaviour I am thinking of is that shown by the TextPad editor.

**Comment by RickStrahl** [comment]
Hmmmm.... MM already detects changes from other documents, but I think it requires a context switch if both docs have been changed.

If your document is unchanged when a change occurs (in Dropbox), then the document will just update with the change. 

If your document has been changed and has pending changes, then you'll get a dialog that says so when you re-activate the editor (ie. tab away and come back). I don't think that happens if you are still active in the editor because that would be pretty disruptive.

I have to look and see how that works exactly and maybe think about what happens in your use case with Drop Box. My original use case was that you tab off change the doc somewhere else, then come back to MM which works well. But what would we want to have happen if the doc changes while we're actively changing it?

**Comment by RickStrahl** [comment]
To Summarize

* If MM has no pending changes in the document, remote updates just update the active doc
* If MM has pending changes nothing happens in the editor when remote updates are made
*  ^ unless you tab away and come back to MM - then you get a dialog that says file has changed
* Currently your changes will overwrite other changes (not good)

So I think the way this needs to be addressed in MM is:

* Add check for changed file when saving (we already save a CRC so this should be relatively easy)
* Prompt whether to overwrite or compare changes
* Compare changes if comparison editor (or GIT) is configured
* Reload file content in editor  (but don't save)
* Resave if necessary to ensure any interim changes are detected
* At this point we should probably remove the dialog that pops up when remote   
is updated and just rely on the Save behavior as that's more reliable

**Comment by itimpi** [comment]
Sounds like a plan.    The main thing is to know that there might be a potential problem so at the least one can take some manual action to avoid losing any changes that another player might have made without you being aware of it.   I must admit I was not aware of the current behaviour you mention as I have never to my knowledge received a prompt that the file might have changed behind the scenes.

I actually have Beyond Compare installed as standard on my system so being able to trigger that in some way to show the changes and allow them to be merged into one of the copies and then reloading the merged document would be the perfect solution.   Not quite sure if the steps you are suggesting cater for that but it sounds like they might.

if you want me to check out any specific scenarios let me know what they are and I will endeavour to try them out and report back the results.

**Comment by RickStrahl** [comment]
MM has GIT support and it will try to find various compare tools that are installed - it'll find BYC and use that (Git should already use that when double click in the commit dialog) - it's a configuration setting. So that is the plan to show the files.

Like I said currently changes that happen while you're editing won't be notified **unless you navigate away and come back from MM** which pops up the dialog. In the above I'm saying that we should get rid of the dialog and only when saving notify. This will ensure that when you save the file change is noticed and **then you can compare** changes or overwrite.

**Comment by itimpi** [comment]
I assume that the MM setting I need to change is the one for the Git Diff Executable?   If so this was not the obvious setting (at least to me) that I would need to change to bring up comparisons.   I also noticed that this was preset to kdiff.exe (which I do not have).  I thought you said that BYC might be auto-detected (I have BYC 4 installed) or was that me mis-interpreting what you said.

**Comment by RickStrahl** [comment]
Ok so I've started adding support for file comparison and also updated the way the change handling works.

* [File Change Detection](https://markdownmonster.west-wind.com/docs/_5xx0nr61g.htm)

Here's what that looks like:

![FileChangeDetection](https://user-images.githubusercontent.com/1374013/103160326-a6cc0180-4777-11eb-984f-7f83a5049d6c.gif)

In short if you have no pending changes in your document, the document is updated automatically. If there are pending changes, the document is not updated immediately, but you'll be prompted to pick a file or compare (if a Diff tool is configured).

**Comment by itimpi** [comment]
Looks good - I look forward to trying it out :)
