### ISSUE TITLE
Custom Addin from Template not showing up in MM UI

### ISSUE THREAD

**Issue by GraniteStateHacker** [RickStrahl/MarkdownMonster#735]
I’m trying to create a custom addin for Markdown Monster.  I’ve got MM 1.12.25.2, 32-bit, registered.
 
I’ve got the addin project extension 1.23 in Visual Studio 2019 (preview version, fwiw)
 
When I spin up a new addin project and build it (defaults to AnyCPU), it drops the dll in **%appdata%**\MarkdownMonster\Addins\{projectname}.
 
It looks like my other installed MM addins are in **%localappdata%**\... 
 
I don’t see my addin in the MM ui.  
 
What’s the best way to troubleshoot?

**Comment by GraniteStateHacker** [comment]
(My need for the addin is to compose md files that represent chapters into a book md file, so I can generate a PDF of the whole work, not sure this is the best way to do it.)

**Comment by RickStrahl** [comment]
The `%appdata%` location is correct for a user addin. The built-in addins go to a different location because they are updated with the application. Realistically addins work from either location, but `%appdata%` is the right place in your case.

If the addin doesn't work look for errors in the status bar or an error dialog popping up. If that's the case there's likely a problem loading the addin. 

Ideally after you run the new template before you add any code to it, you should run the Addin to ensure everything works correctly.

***IMPORTANT: ** the addin's binary file **must end in *Addin.dll*. Otherwise it's not found and won't load.  

![image](https://user-images.githubusercontent.com/1374013/102938982-71f73c00-4451-11eb-9f80-d66f3fd93207.png)

_The reason for the naming is that without that there would be a ton of extra load time overhead scanning all the DLLs for types (which has other problems too) when an addin has lots of related dependencies._

**Comment by GraniteStateHacker** [comment]
Confirmed, after making sure the custom addin matches the *AddIn.dll name mask, it loads up and runs as expected.  Sorry for the miss!
