### ISSUE TITLE
Add more PDF Generation Page Sizes

### ISSUE THREAD

**Issue by GraniteStateHacker** [RickStrahl/MarkdownMonster#736]
I'd like to add A5, B5 & B6 page sizes to PdfPageSizes enum in HtmlToPdfGeneration.cs. 

They appear to be supported by wkhtmltopdf

I can submit a PR for it if it helps.

**Comment by RickStrahl** [comment]
Some time ago I asked around what commonly used page types were in countries that use these page sizes and the common consensus was that those weren't used very much.

I can't recall exactly why I didn't add all supported formats - presumably due to too much noise in the dialog. I have to look at it again. Maybe the solution is to add them all but then have a list of 'common' formats that bubble to the top.

**Comment by GraniteStateHacker** [comment]
I forked the repo and added what I wanted... Works like a charm, but maybe an "advanced" mode?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
