### ISSUE TITLE
[bug] Drag and drop selected text

### ISSUE THREAD

**Issue by IgorBuchelnikov** [RickStrahl/MarkdownMonster#737]
The mouse cursor is followed by all text (not just selected text)

**Comment by RickStrahl** [comment]
Unfortunately this has to do with the host control and Internet Explorer. The host container is tracking the selection and that's what's providing the image to the editor.

For now I won't fix this - because this is platform dependent. If and when I finally switch to Chromium based rendering this likely will be fixed or we'll revisit then.
