### ISSUE TITLE
Not Stealth - Writes an empty folder in AppData

### ISSUE THREAD

**Issue by skarsgal** [RickStrahl/MarkdownMonster#749]
Markdown Monster Portable rel. 1.25.15.2:
Not Stealth - Writes an empty folder in: AppData/Roaming/Markdown Monster/

**Comment by RickStrahl** [comment]
Thanks - this was caused by the default configuration which assigns the common folder before the check for the `_portable` install is made. 

Fixed. Updated the code to always use the `FindCommonFolder()` to make the initial assignment. Fixed race condition for load order.

Give this another try in 1.26.3 or later. 

Note: This will still happen if MM is lauched without a `_portable` file in the launch folder as the folder is created on startup if it doesn't exist. If `_portable` is added later, or the `mmcli -setportable` is used it will not clean up the old folder although it offers to copy files from the appdata folder to the local settings store.
