### ISSUE TITLE
<br> tags 'kill' some functionality

### ISSUE THREAD

**Issue by kpeters58** [RickStrahl/MarkdownMonster#751]
I often insert break tags tags for vertical spacing in other MD editors and never had a problem.

In Monster, things work fine if I insert break tags after I have all markups already done.

However, if I insert a break first and then, say, try to apply bold to a word in the line below it fails and the '**' bold tags are shown verbatim.

**Comment by RickStrahl** [comment]
You're going have to post an example and step by step because I can't duplicate this.

Also it's better to use two spaces or `\` for line breaks at the end of a line. `<br>` should also work, but it certainly is more obtrusive in the text.

Either way I can't reproduce what you're describing based on your very limited description.

**Comment by kpeters58** [comment]
There's probably even simpler ways:
1) New file (with preview on)
2) enter something on line1 and mark as H1
3) enter \<br\> on line 2
4) enter something on line 3 and try to mark it bold
Presto - preview shows bold 'verbatim'

**Comment by RickStrahl** [comment]
Oh I see,

Technically that's invalid Markdown. Any HTML tag that is used as a block statement has to be separated by blank lines. The reason for this is that the tag otherwise is treated as an opening tag and treats everything in between as an HTML block.

IOW:

```markdown
# This is a header
<br>
This is some **bold** text
```

doesn't work.

But this does:

```markdown
# This is a header

<br>

This is some **bold** text
```

As does this:

```markdown
# This is a header

This is some text<br>
This is some **bold** text
```

Note that both the editor and the render treat this the same way and they are both separate tools that interpret Markdown. So this **is the correct behavior**.

Note apparently there's some mixed behavior for this functionality as BabelMark shows:

https://babelmark.github.io/?text=%23+This+is+some+text%0A%3Cbr%3E%0AThis+**is+some+text**.%0A

About half of the implementations do what MM does, the other half does it the other way. I think the MM interpretation makes sense and IAC I can't change that since this is built in behavior in the Editor and Render components.

All that said, your scenario doesn't make any sense anyway as a header followed by a BR will ignore the BR since the header it automatically adds the break. It does work if you have two regular text lines:

```markdown
this is some text
<br>
this is more text
```

and that works fine and is a more likely scenario where you actually need the line breaks.

Also if you're doing Markdown it's recommended you the double-space at the end of the previous or `\` to represent breaks rather than `<br>`. When there are alternatives to HTML tags you should take advantage of them.
