### ISSUE TITLE
Auto Updates

### ISSUE THREAD

**Issue by RealDotNetDave** [RickStrahl/MarkdownMonster#753]
It would be nice if MarkdownMonster updated itself when there are new versions. :-)

**Comment by RickStrahl** [comment]
No - too intrusive. You get notified and it's pretty quick to update from the download link it takes you to. 

I originally had auto-update built in but there are lots of issues with permissions etc. At the time the problem was that the some AV software would trigger on that. 

So short answer: Not going to do it.

If you have chocolatey set to auto-update packages that's one way you can automatically update.
