### ISSUE TITLE
Drag & Drop Link Location

### ISSUE THREAD

**Issue by RealDotNetDave** [RickStrahl/MarkdownMonster#755]
It could be useful if I could drag and drop a file name from the File Explorer into the link location for a link.

**Comment by RickStrahl** [comment]
Unfortunately that's problematic as its ambiguous. Should it open the file or use the link.

Also due to the HTML nature of the editor there are complications getting the proper editor drop location. I can't remember the details - it works with images out of the file browser, but not with arbitrary files as links.

**Comment by RickStrahl** [comment]
I'll take another look. There's already some logic there that deals with the image file drop and it looks to me that the drop behavior is triggering in the editor where it needs to now. So might be possible to make this work.

**Comment by RickStrahl** [comment]
So I've added the logic to drag files from explorer and also from the File Browser into the editor and have those files linked instead of opening the editor file.

![FlieDragAndDrop](https://user-images.githubusercontent.com/1374013/109232393-5e779280-776c-11eb-9917-287283647577.gif)

A few caveats (similar to the way images are handled): 

* The mouse position when dragging into the editor from Explorer doesn't track so the caret position is used for insert location
* Relative paths that are not in the current hierarchy are pretty ugly
