### ISSUE TITLE
Spell check feature is not working as expected

### ISSUE THREAD

**Issue by dealproc** [RickStrahl/MarkdownMonster#759]
I am evaluating MM right now to determine if I should have a client adopt the software.  One of their biggest needs is to have a decent spell-check.

As a method to test this... I entered the word `someting` into the editor and it a space.  

Upon doing so, the editor highlights the word with the read squiggly thing under it.  If I use the mouse to right-click the word, I lose the squiggle and the context menu does not come up with spelling correction suggestions.  If I use the keyboard and move the cursor to the word, then use the context key on the keyboard, I can get the expected spell check context menu.

Fair warning, and unsure if this has something to do with the issue or not... I am using the tool on a Virtual Machine hosted within VirtualBox.
HTH

**Comment by RickStrahl** [comment]
Yeah I suspect that's due to some virtual machine funkiness. The right click behavior is a little fiddly in the editor mainly due to the host behavior. I've found using the Chromium addin (the Blue Chromium icon in the toolbar) does better than the default IE based editor. Maybe try one or the other and see if the behavior is better. I believe this has to do with the Windows right click trigger speed and and if too slow or too fast the the context double pops and then loses focus and goes away immediately. 

This problem is exacerbated  by virtual machines lagginess which may very well be the problem. I run MM on several machines, one of them a very underpowered machine with a laggy mousepad and on that machine I often see misclicks for the context menu. Not just for spell check but for all ops in the editor. Usually re-right-clicking works. 

I've known about this and have looked at it a few times, but there's not much I can do here as this behavior is based on the internal browser and editor component behavior. There have been improvements in the timing management so it is much better than it used to be, but still not perfect. OTOH, I also see problems in other apps with context menus with that slow machine so I think this is definitely a machine/hardware timing issue.

You can also try and tweaking the mouse settings. I believe the double click speed has some bearance on mouse timings.

**Comment by dealproc** [comment]
Sorry for the delay.. personal issues... I have no straight windows boxes.  Trying to figure out how to best test this theory.  When I was "testing" this using VirtualBox, I assigned 4 processors to the machine and the physical hardware is a rather beefy system running at 3+gHz... so i am unsure.

**Comment by RickStrahl** [comment]
The issue usually isn't necessarily of performance, but rather the hardware devices used and how they respond to clicks.

Either way there's not much I can do about this because this is caused by hardware timing issues in how the clicks are forwarded to the application. Making any changes in the way it is supposed to work (as it does native hardware) might make the behavior fail for the way it's meant to work so I would be very hesitant to make changes there even if there was a way to do it easily (which there's not because it's basically context menu pops that are forwarded into MM from WPF/Windows).
