### ISSUE TITLE
Are you planning a portable chocolatey package?

### ISSUE THREAD

**Issue by gep13** [RickStrahl/MarkdownMonster#76]
Was just curious if you had plans to do this?  Can help you through the process if you are unsure.

**Comment by RickStrahl** [comment]
Perhaps later. Need to see what issues we run into with this. 

Frankly I'm not sure what the benefit of this is if you're already running through a Choco install? Other than not requiring Admin rights to install.

**Comment by shawnwildermuth** [comment]
The not requiring admin is important (especially for corporate dev's who need permission)

**Comment by RickStrahl** [comment]
Looking at the installer the only thing that uses admin is the installation of the file association (.md and .markdown). Everything else in the installer can actually run under non-admin account at this point (I've spent some time dialing things back).

I think that's a nice feature to have though - and worth having an admin installer for. Otherwise you have to manually attach the association.

I'm going to play around with the installer and see if it can be set up to run without admin by default and not install the association, and if run with admin do install the association.

**Comment by RickStrahl** [comment]
Ok so if you want to install into Program Files **you have to run as admin**. Otherwise no rights there. So pretty much ANY installed application that goes into Programs and Features requires admin rights. Only apps that don't tend to be OneClick or other AppData installed apps may not require. 

That would work for Markdown Monster, but frankly that's not really a goal for the main install. I rather have MM go into a predictable folder where you'd expect it to go and behave like other installed applications.

So the the portable install is an xCopy install out of the zip file and does what's needed.

Gary - I'm not sure how that works with a Portable install in chocolatey. If somebody wants to take a crack at getting that started I can probably automate it into the rest of the build process in place so it's somewhat automatic. The portable .zip is auto-created every time the deployment project builds so what's missing is the Choco wrapper for it.

**Comment by shawnwildermuth** [comment]
If Gary's not up to it, i'll look at the portable install. I'm thinking about installing it in user folder instead of ProgramFiles (like portable Chrome does). Doesn't solve the file association, but love to have the option.

**Comment by gep13** [comment]
>@RickStrahl said...
Gary - I'm not sure how that works with a Portable install in chocolatey. If somebody wants to take a crack at getting that started I can probably automate it into the rest of the build process in place so it's somewhat automatic. The portable .zip is auto-created every time the deployment project builds so what's missing is the Choco wrapper for it.

Since you are the creator of the Application, the best advice would be for you to embed the Markdown Monster executable, and any dependent assemblies directly into the Chocolatey Package.  That way, Chocolatey will automagically extract the files, and automatically make them available on the path.  i.e. if you have an executable called `MarkdownMonster.exe` in the package, Chocolatey will create a `shim` executable, and it will be callable from the command line.

If you wanted to create an additional shortcut, perhaps `mm`, then you can use the `Generate-BinFile` helper method, as shown in this package:

https://chocolatey.org/packages/GitVersion.Portable/3.6.4#files

Let me know if you have any questions.  Not sure I will have the cycles to do the work just now, but if @shawnwildermuth wants to pick it up, happy to provide input.

**Comment by RickStrahl** [comment]
So MM already builds a Distribution folder which current gets Zipped up for the portable install. So there's a Zip file that has everything that's needed. If memory serves Chocolatey can work off a zip file, right? In the zip there are MarkdownMonster.exe and mm.bat (the shortcuts). There shouldn't be anything else needed for the portable install in terms of running.

**Comment by gep13** [comment]
@RickStrahl yes, Chocolatey certainly can work with zip files.  Your chocolatey package would need to include the use of this helper function: https://chocolatey.org/docs/helpers-install-chocolatey-zip-package, which would need you to include checksums for the zip file that is being downloaded as well.

If you were to embed the files directly into the chocolatey package as part of your build, you wouldn't need to include the checksums, and chocolatey would take care of placing the files onto the file system, something which you would have to take care of it you are extracting the zip file.

**Comment by RickStrahl** [comment]
I could definitely do that. I suppose that would make packaging easier too as we wouldn't need to upload the portable package anywhere permanently. Can you point at docs for doing this. I still have a heck of a time dealing with the verbose Choco docs and finding what I need.

**Comment by RickStrahl** [comment]
So I'm trying to embed the zip file where the zip file is in the tools

```powershell
$toolsDir = (Split-Path -parent $MyInvocation.MyCommand.Definition)
# Install-ChocolateyZipPackage "$packageName" "$url" "$toolsDir" 
Get-ChocolateyUnzip -FileFullPath "MarkdownMonsterSetup.zip" -Destination $toolsDir
```

I get errors from this that the file can't found.

BTW:  Navigating the Choco docs is extremely frustrating. I don't find any sort of reference to how to do an embedded install. I know I've been through this before when I initially  with the main package but I can't remember for the life of me. I can't find any docs that describe how to do an embedded install. Like where does the embedded file go? Into the Tools folder? Content? No idea.

If I wanted to embed the actual distribution files instead of the zip what command would I use?

**Comment by RickStrahl** [comment]
Ok... so I figured out that this works:

```
$toolsDir = (Split-Path -parent $MyInvocation.MyCommand.Definition)
Get-ChocolateyUnzip -FileFullPath "$toolsDir\MarkdownMonsterPortable.zip" -Destination $toolsDir
```

Might be nice to add this to the documentation because that would seem to be the most common use case.

**Comment by RickStrahl** [comment]
More info - opted to build another version that just embeds all the files - no zipping no nothing as is and it just goes into the Chocolatey lib folder. 

Also added mm.exe to replace mm.bat to allow the exe linking to work with both.

**Comment by gep13** [comment]
>@RickStrahl said...
More info - opted to build another version that just embeds all the files

This is definitely the ideal situation, and one in which Chocolatey will actually do most of the work for you.

>@RickStrahl said...
Also added mm.exe

Chocolatey can actually do this for you, if you wanted to maintain the name of the original executable.

>@RickStrahl said...
Might be nice to add this to the documentation because that would seem to be the most common use case.

Embedding applications is actually not the norm.  Most packages draw directly from a download location, since we don't normally have distribution rights for the binaries.  Your case is actually the edge case, hence why there isn't much documentation around it.  Seems like something we need to fix though.  We are starting to encourage more embedding of the packages where possible.

**Comment by RickStrahl** [comment]
> This is definitely the ideal situation, and one in which Chocolatey will actually do most of the work for you.

Yeah it is nice. Thanks to your feedback I was able to remove all the Chocolatey files except `license.txt` which is sweet.

> mm.exe

Previously that was mm.bat. The exe should get auto-shimmed according to the docs and it actually makes it more consistent to launch. I can also sign it and have the MM icon. So it's a good thing to add anyway.

> docs

I might write this up for a quick blog post. May be able to reuse some of that for the docs.

**Comment by gep13** [comment]
>@RickStrahl said...
I might write this up for a quick blog post. May be able to reuse some of that for the docs.

Perfect!

**Comment by RickStrahl** [comment]
For anybody interested the Portable package is up, but still under review at Chocolatey.

```powershell
choco install MarkdownMonster.Portable
```

**Comment by gep13** [comment]
**NOTE:** While in the moderation phase, it is necessary to use:

```
choco install MarkdownMonster.portable --version 1.1.15
```

to get it installed.  However, this is *NOT* recommended, as a package may need to be changed during the moderation phase.

**Comment by RickStrahl** [comment]
I think you can also get it to run with the -f switch. Yeah - this is meant more for people to see if that will work for them or not and potentially to check for problems. I'm not announcing this publically outside of here.

Per conversation with Rob I'm not really sure what this buys us, since Chocolatey still needs to run as admin in order for this to work... <shrug>

**Comment by RickStrahl** [comment]
Well, we're sitting in the endless Chocolatey Queue waiting for approval with this which always makes me sad :-)

**Comment by RickStrahl** [comment]
Uh huh.... :-)

**Comment by RickStrahl** [comment]
The portable Chocolatey package is now live:

```
choco install MarkdownMonster.portable
```
