### ISSUE TITLE
Question: what does "---" at the start of the file accomplish?

### ISSUE THREAD

**Issue by bcmadsen** [RickStrahl/MarkdownMonster#763]
I understand why this gives the results it does:

```text
asdf
===
qwer

---
zxcv
---
```

I notice that inserting "---" at the top causes everything up to the next "---" (in this case, everything above "zxcv") to disappear:

```text
---
asdf
===
qwer

---
zxcv
---
```

Is that supposed to happen? If so, why?

**Comment by RickStrahl** [comment]
Yes - that's because there's Frontmatter support which uses 

For example:

```markdown
---
title: LiveReloadServer - A .NET Core Based Generic Static Web Server with Live Reload
weblogName: West Wind Web Log
postDate: 2020-11-11T20:33:50.3496543-10:00
---
# LiveReloadServer - A .NET Core Based Generic Static Web Server with Live Reload

```

The `---` block is meta data for the document and it's quite common for Markdown documents.

You can turn off FrontMatter parsing in the Markdown parser:

![image](https://user-images.githubusercontent.com/1374013/111247248-b9eab280-85ab-11eb-9f1c-e1a4c5d154b8.png)

**Comment by bcmadsen** [comment]
Thank you!

I knew it was going to be something like this, but I didn't know what to call it. Now I do.
