### ISSUE TITLE
Problem with Preview to Editor in IE Mode

### ISSUE THREAD

**Issue by JoeC4281** [RickStrahl/MarkdownMonster#769]
The cursor jumps home after every keypress with Preview to Editor in IE Mode.

@RickStrahl has been able to duplicate the problem, and asked me to post the issue here.

For more info about the issue see https://support.west-wind.com/Thread60E0E0BMR.wwt#60E1F5HIG

--- 
_Adding more info_

* Works fine in Chromium Mode
* Fails only in Preview to Editor mode
* Works in Editor **and** Preview mode

**Comment by RickStrahl** [comment]
Finally was able to track this down - certainly an odd bug, still not sure why it occurred only in IE mode. Essentially this was caused by a race condition due to a dual preview request. Removed the implicit preview request and that makes the behavior work. As a bonus this also provides slightly faster preview performance and less jitter.
