### ISSUE TITLE
Fails to load images whose filenames contain white spaces

### ISSUE THREAD

**Issue by liugaocn** [RickStrahl/MarkdownMonster#771]

**Comment by liugaocn** [comment]
I have to use %20, instead of white space to load an image whose name contains a white space.
```
![TCP Firewall](img/TCP%20firewall.png)
```

**Comment by RickStrahl** [comment]
This is by design as it's required by most Markdown Parsers to work properly. You do want this to work when you publish this somewhere don't you?

Take a look here:

https://babelmark.github.io/?text=!%5BTCP+Firewall%5D(img%2FTCP%2520firewall.png)%0A%0A!%5BTCP+Firewall%5D(img%2FTCP+firewall.png)

and you can see that without the encoding many parsers (including Markdig which is what MM uses) fail.

Using `%20` is the proper way and the only way to be sure that it renders.
