### ISSUE TITLE
Confirmations for file moves and deletes please!

### ISSUE THREAD

**Issue by dainsburg** [RickStrahl/MarkdownMonster#783]
Great tool, I love it so much over Visual Studio Code. But like Windows file browser, MM doesn't have automatic confirmation dialogs for drag-and-drop or delete operations.

This is very dangerous with any network file/folder browser (it's a well-known issue with local file storage). But it can be catastrophic when working with repositories and posting to public distro centers. 

So please help us out with that? Thanks!

**Comment by RickStrahl** [comment]
Hmmm...  MM confirms deletions of files in the folder browser:

![image](https://user-images.githubusercontent.com/1374013/115972028-c84fb680-a4e7-11eb-8233-7817e7d61297.png)

and files deleted are sent to the Recyle Bin for potential recovery:

![image](https://user-images.githubusercontent.com/1374013/115972118-54fa7480-a4e8-11eb-8d5c-7e682f41890e.png)

As to drag and drop - well dialogs or popups for drag operations are a pain in the ass - that's why most tools don't have them. The whole point of drag and drop is that it's interactive and you can always press ESC to exit the drag operation. It's not exactly easy to drag files by accident in MM.
