### ISSUE TITLE
Make the highlighted file match the selected Editor pane for the file?

### ISSUE THREAD

**Issue by dainsburg** [RickStrahl/MarkdownMonster#785]
When you have multiple files open, you can change Editor tabs, but the highlighted file in the browser pane stays the same. This is confusing as we are trained to think the highlighted file is always the one we're working on. 
Thanks!

**Comment by RickStrahl** [comment]
Not going to happen.

This is not common behavior and if you work on 'projects' where you work with many open files the last thing you want is have your folder view keep bouncing around to different locations all the time.

**Comment by RickStrahl** [comment]
So I gave this a little more thought. It wouldn't be too difficult to add a flag that shows on the folder browser that lets you keep the folder browser in sync as an option (off by default).

But - there are a problems with this approach. The Folder browser when it opens folder or document in the folder browser makes that folder the root folder for the view. Meaning that you loose your file hierarchy up stream. This is the reason I've turned this down in the past - for me that simply wouldn't work as I need to see my root folder and then open subfolders as I go. I usually work in projects where there are many related files open and having the 'top level' project view is much more useful than seeing the folder the file is open. Take an example if you are in a subfolder of a project and you have an image folder off the root of the project - you then no longer see the root or the images folder to drag and drop images into the document for example. It just breaks the entire navigation chain.

You can use the navigation icon (`alt-v-f`) to quickly open the folder browser in the active document's folder.

**Comment by RickStrahl** [comment]
So I added support for this and it looks like it works reasonably well:

![TrackDocumentInFolderBrowser](https://user-images.githubusercontent.com/1374013/116333167-b9c70080-a76e-11eb-9edd-d4bc145e38bc.gif)

The feature is optional via a small button in the Folder Browser to toggle the mode, or via the `FolderBrowser.TrackDocumentInFolderBrowser` configuration setting.

Still not a fan of this feature, but it is optional so to each his own. It looks like it's not as noisy as I thought it would be as the code tries to find documents in the current active tree rather than always resetting the root folder to the target file - if possible.

**Comment by dainsburg** [comment]
Awesome! Sorry I didn't chime in earlier, work work. I didn't consider documents in different places, all of mine are in the same source location. But I've got 9 READMEs in that folder tree, use similar boilerplate text, and have the same foldernames in different distros even. 
So clicking a different tab and not being able to use the folder browser to confirm what file I was working on, even when I could see them all at once, was a big problem. I'll download this version and check it out.
Thanks for helping with this!
