### ISSUE TITLE
Suggestion: Update markdown generated by image paste to use paths relative to "PreviewWebRootPath"

### ISSUE THREAD

**Issue by LeeHolmes** [RickStrahl/MarkdownMonster#795]
Today, when you paste in an image to a Markdown document, MarkdownMonster does a great job of saving the image where you tell it, and then inserting the appropriate Markdown.

Currently, it uses a path relative to the open document (i.e.: ../../images/my_image.png). This breaks when the document has a different PreviewWebRootPath enabled, where the URL should really be "/images/my_image.png".

It would be great if MarkdownMonster automatically canonicalized image paths during the Image Paste operation so they were relative to PreviewWebRootPath.

**Comment by RickStrahl** [comment]
Hmmm... yes that sounds like a good idea.  Gets a little complicated though:

* Check for PreviewWebRootPath
* Check path and see if it's relative and in hierarchy
* If path is below the PreviewWebRootPath, or back to PVWRP and then up another tree use /
* If no PreviewWebRootPath or straight relative path use hardcoded path

Resolving these paths and matching them is tricky though because there are so many combinations because now MM has to basically walk the hierarchy explicitly to check the folders at each level.

**Comment by LeeHolmes** [comment]
If it helps, here's the code that PowerShell uses to resolve a relative path: https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L5077

![image](https://user-images.githubusercontent.com/11475352/118302950-b84d4600-b499-11eb-9a4e-21ba2942bf53.png)
