### ISSUE TITLE
Is it possible for the Markdown transformation to be async?

### ISSUE THREAD

**Issue by deanebarker** [RickStrahl/MarkdownMonster#798]
I built a custom Markdown parser that calls a web service to do the transform.

(Why? There's a lot of custom stuff going on, and I have a central "templating service" that exists for this reason. Also, the transform is in .NET Core, so I can't make it local to MM.)

This actually works great, except that it slows MM way, way down, obviously. The app locks and pauses all the time while it waits for the response. I put a five-second cache on it, so it only makes the web service call once every five seconds at most (otherwise, it just returns the result of the last call), and this has helped quite a bit.

However, I was wondering if it's possible to make the Markdown parsing async, so the app doesn't block and wait for it to return? I don't need instantaneous updating of the preview -- "eventual updating" is fine.

**Comment by RickStrahl** [comment]
Are you doing this with an Addin and a custom Markdown parser?

At this point and even if it was I don't think that would work with the way MM currently works. It's heavily dependent on a quick response to rendering the output and knowing when it's ready to update the preview. With Async this would become much more difficult to ensure that there are no overlapped results trying to push content into the previewer. 

You couldn't wait for overlapping results to come back to you because the updates happen frequently for rendering.


FWIW, I'm looking into a bunch of async changes in MM as I'm trying to migrate the editor code to the WebView2 control which doesn't allow for sync interaction with the JavaScript code. So even something as basic as retrieving the Markdown from the editor requires an async request. Which in turn is necessitating async for almost the entire set of interactions with the editor which is huge change.  Still experimenting with this (may have to abort though due to sheer volume of code that is touched by this - we'll see).

**Comment by deanebarker** [comment]
>Are you doing this with an Addin and a custom Markdown parser?

Correct. So, the Markdown "parser" doesn't actually parse anything -- it just makes an HTTP call out and returns the result.

Honestly, it's tolerable. It only makes the call once every five seconds, and I could probably even rig it up to do it on demand (like, when I hit a key combination, or something). I don't have eyes on the previewer all the time, so I really don't need it to be updating while I'm typing.

In fact, I might be able to change it so it only updated when I paused typing. I could kick off a timer in the handler, then keep resetting it, so it only fires when the parser _hasn't_ been called for five seconds or something.

It's a weird use case, I know. But it works for me.

**Comment by RickStrahl** [comment]
So in the next **major update** to Markdown Monster a lot of the internals will switch to run asynchronously because Interop with the editor actually requires async opernati

**Comment by deanebarker** [comment]
Fair enough. Looking forward to it.

**Comment by deanebarker** [comment]
@RickStrahl Has this changed at all?  I would still like to render with a web service, but I need to do it async, because the natural network latency is too great for the app to block while it waits for the response.
