### ISSUE TITLE
Add support for Azure Markdown image resizing

### ISSUE THREAD

**Issue by midoriha-senpai** [RickStrahl/MarkdownMonster#810]
Okay, I think I botched the title here, haha. What I'm looking for is for images to render properly when I code Markdown that uses the resize denotation in an image's URL. It renders properly in my README in Azure Repos once I've pushed the code, but the Markdown Monster editor does not render the image, it just doesn't render the Markdown at all. Here is where Microsoft talks about the resize denotation: [https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#images](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#images).

Here's some example Markdown: `![Logo of License Manager](../assets/images/LicenseManagerLogo_v10071.png =100x)`

The part that breaks the Markdown is the portion after the URL: `IMAGE_URL =WIDTHxHEIGHT`

Thanks!

**Comment by RickStrahl** [comment]
You can't have spaces in the URL - it has to be escaped with %20.  I doubt the space in the URL you have is correct anyway?

**Comment by midoriha-senpai** [comment]
> 
> 
> You can't have spaces in the URL - it has to be escaped with %20. I doubt the space in the URL you have is correct anyway?
> 
> If it is then the embedded URL should be:
> 
> ```gfm
> ![Logo of License Manager](../assets/images/LicenseManagerLogo_v10071.png%20=100x)
> ```

@RickStrahl Just tried and it doesn't work. Here it is with the space:

<img width="536" alt="Screenshot 2021-06-28 091306" src="https://user-images.githubusercontent.com/2936762/123669492-fe176100-d7f0-11eb-8720-58a54c8dfc47.png">

Here it is with your suggestion:

<img width="170" alt="Screenshot 2021-06-28 091411" src="https://user-images.githubusercontent.com/2936762/123669613-21daa700-d7f1-11eb-80b9-b558f09fe847.png">

Here it is with the space, but on Azure Repos after I've pushed it up:

<img width="155" alt="Screenshot 2021-06-28 091538" src="https://user-images.githubusercontent.com/2936762/123669789-53537280-d7f1-11eb-9a45-bffe66c049c7.png">

**Comment by RickStrahl** [comment]
I guess I'm not sure what you're trying to do here. 

This looks to me like it's a dynamic URL on Azure (or whereever) and that's not going to execute on your local preview. There's no server so it can't possibly do this.

You can set the base URL for your 'site' and that might be what you're looking for to reference back to your server.

[Setting up Site Relative Base Paths](https://markdownmonster.west-wind.com/docs/_5fz0ozkln.htm)

This bascially lets you configure what `/` or `~/` references in the context of your site. It won't work with file relative links (like `../`) though because that's still going to be relative to your local file. So if a link is dynamic and executes on the server you need to provide a root relative path or a fully qualified Web Url (`https://site.com/folder/link`).
