### ISSUE TITLE
[MM2 Preview] WebView Error

### ISSUE THREAD

**Issue by Randy-Buchholz** [RickStrahl/MarkdownMonster#815]
I'm getting this error on load. I'm on previews for most things (MM, win11, etc.), so this is maybe just an FYI. 

7/6/2021 7:05:47 PM - Unable to load addin WebViewPreviewerAddin
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Markdown Monster v2.0.0.4
10.0.22000.1.amd64fre.co_release.210604-1628 - en-US - NET 4.8 - 64 bit
en-US - en-US    
---
mscorlib
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MarkdownMonster.AddIns.AddinManager.LoadAddinClasses(String assemblyFile, String addinId) in C:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\AddInInterfaces\AddinManager.cs:line 436
System.Reflection.ReflectionTypeLoadException
---------------------------

**Comment by RickStrahl** [comment]
Is the application starting though or is it crashing? Addin loads should log and put up a notice, but should continue to load the application.

It's due to the old WebView addin that is no longer used.  You need to remove the Addin explicitly for now from `%localappdata%\Markdown Monster\Addins\WebViewPreview` by removing that folder.

Need to add code to remove the addin when running v2, although when you do a proper install it should uninstall that folder when v1 gets uninstalled.

**Comment by Randy-Buchholz** [comment]
It just shows a notice, logs what I posted, and loads fine.

Don't know what you mean by "proper install". I installed from the link on the page that came up when doing the update for V1.

**Comment by RickStrahl** [comment]
A full install. There's a portable install which will not remove old code, since there's no installer/uninstaller.

Not sure why the uninstaller (which runs when the installer runs and find a previous version) would not remove the PreviewAddin. IAC, I've added code to the latest update that will remove the built-in WebView Previewer addin so that one won't be a problem.

Other old 3rd party addins however may still be an issue.
