### ISSUE TITLE
File browser sidebar does not work, program hangs when clicking on a folder

### ISSUE THREAD

**Issue by Sab73** [RickStrahl/MarkdownMonster#818]
When clicking on a folder on the left sidebar filebrowser panel, it says 'Cant' open file... , File doesn't exist.'

And then the program hangs for a few seconds. While in that state wherever I click with the mouse it keeps unfolding and folding the folder on the sidebar panel (I tried to open).

A few seconds later The "Ready" message appears with the green dot on the bottom status panel, but the selected folder on the sidebar is not opened.

Version 2.0.0.15

**Comment by RickStrahl** [comment]
Thanks @Sab73.

Made a bunch of changes for better click handling in the last update, apparently the folder handling didn't get handled right. Taking a look. Should have an update in a bit.

**Comment by Sab73** [comment]
Thanks you!
It might help you that I have tried and installed a previous version of your nevertheless great editor, too (the one before the current public version), and the problem is present there, too. I wondered if there was a problem maybe locally on my computer (file access rights or something) but this sort of symptoms do not appear in any other apps on my Windows install.

**Comment by RickStrahl** [comment]
I think this problem got introduced in one of the recent updates. I've changed the way the way the event handlers are invoked (PreviewMouseDown/Up instead of MouseDown/MouseUp plus the async updates) that have an effect on how the click handling works. Behavior is subtly different for some things the same for others. 

IAC, I've just updated 2.0.0.16 which reverts back to the original events  for mouse intercepts and that seems to have sorted it.

**Comment by Sab73** [comment]
Thank you!

Seems like it works now. Testing on :) Great editor, planning to buy it because of its Wordpress  capabilities (also, its handling of custom fields is a very nice feature, I like it very much), but I have just one other issue. Opening up a new thread for it.
