### ISSUE TITLE
100% font size on high DPI display is... monstrous?

### ISSUE THREAD

**Issue by bleroy** [RickStrahl/MarkdownMonster#822]
![image](https://user-images.githubusercontent.com/1165609/126720817-f068409b-fc39-4fd6-a7af-a716496e89e1.png)

**Comment by RickStrahl** [comment]
What resolution are you running at?  The default is 17px which isn't particularly large (I think standard is 16px for browsers for medium). I went with the slightly larger size due to large displays that most of us are using.

IAC, you can change the default in the Settings (or in the JSON config)

![image](https://user-images.githubusercontent.com/1374013/126725742-e5a6cdd6-f7e4-45f9-bf7b-ce417fe3881a.png)

FWIW that doesn't look monstrous in this screen shot :smile:

or you can just Ctrl-Scrollwheel to reduce the zoom level, but it's probably better to set the base size.

if the font-size is too big you probably want to tweak the line height too.

**Comment by bleroy** [comment]
3240x2160 at 200%

I resized it to 55% and that's fine, I just thought the default was about 2x too big, but that's clearly a matter of opinions.

**Comment by RickStrahl** [comment]
I think a lot of that depends on the size of your display. If I ran my 40" screen at 200% everything would be the size of a car :smile:

But at 100% 17px is pretty close to right. 16px is the default pixel size for most browsers so 17px is only slightly larger. I err on the larger size for those with hi res displays which I think most devs are running.

IAC, it's customizable. I'd recommend setting the font size rather than zooming down, just to get the best font fidelity at the size you want to use.
