### ISSUE TITLE
ERR_ACCESS_DENIED: _MarkdownMonster_Preview.html not readable

### ISSUE THREAD

**Issue by Hannes-Ole** [RickStrahl/MarkdownMonster#823]
Hello there, first of all thanks for providing such a promising software. I'd like to try it out, however a problem turned me down from the start: The preview isn't working. I consistently get the error `ERR_ACCESS_DENIED: _MarkdownMonster_Preview.html not readable` (see screenshot). 

**What I've tried so far:**
Reinstalling in different places didn't work. I also checked the Settings and the config json file for any possibility to change the location or file name - without finding an option to do so. However this probably isn't the problem, as the file itself is there (see second screenshot), hence the Temp folder is writable and MarkdownMonster creates the file itself. When checking the file, I get a suspicious error: "The permissions of _MarkdownMonster_Preview.html are ordered incorrectly ...".
I'm pretty sure it's connected. Opening the file with other programs (firefox, Chrome) doesn't work either.

**What solved the issue**
While writing this, I simply deleted the file and created an empty `_MarkdownMonster_Preview.html` myself. That actually solved the problem: Preview is now working fine now, and does so for arbitrary files and after restarting MarkdownMonster.

**Further thoughts**
Before the current version `2.0.2.3` I freshly installed MM with an installer from 13.04.2021 (not sure which version). That gave me different errors, showing the preview but not the text editor. I therefore uninstalled and reinstalled the newest version. Maybe the uninstall didn't purge the `_MarkdownMonster_Preview.html` and left it with inconsistent rights? Just a vague theory. 

Sharing this here so maybe it helps someone. The issue may be marked solved and can be archived.

![grafik](https://user-images.githubusercontent.com/72789281/126755910-eda26cbd-34a3-434f-bd80-33c0ff7f2e92.png)

![grafik](https://user-images.githubusercontent.com/72789281/126755730-d94569df-7739-40fd-81cb-67e51a450ac2.png)

**Comment by RickStrahl** [comment]
Thanks for the report.

This is security issue that we can't really do anything about. It looks to me it's likely anti-virus that's interfering here and it's complaining about a file getting written into a temp folder. MM writes that file without any specific permissions, so if the permissions are screwed up something (anti-virus most likely) is getting in between the write operation and changing the security attributes. 

To see if that's the issue maybe at a temporary exclusion for the temp folder in your AV and see if that fixes.

I can't think of anything that MM does we could change to make this behave differently since MM doesn't write out any permissions - its a simple file write operation.

**Comment by Hannes-Ole** [comment]
Dear Rick,
thanks for your answer and your assessment. The problem occurs on a business laptop where we have corporate admins taking care of (a complex) security and network system, so it is likely that some specific security configuration messes with the program. Wouldn't be the first time/case where this happened. Got lucky that it could be fixed that easily and that I could try out MarkdownMonster. I definitely like it so far 👍 great work.
