### ISSUE TITLE
Async methods in addin templates

### ISSUE THREAD

**Issue by joemclain** [RickStrahl/MarkdownMonster#825]
I'm sure you're aware of this and haven't had time to fix the issues.

I don't know when you changed the addin api to use async, I would guess version 2 since 1.28 is still not async.

In any case, the addin examples using the dotnet template, and the the code in MarkdownMosterProjectTemplate still use non async code. In addition there is no 'maxVersion' in the versions.json file which keeps the addin from loading.

Another gotcha for anyone trying to develop an addin targeting MM 2.0. If you have an earlier version installed in the default location the addin project will import from this directory location which will not provide the correct imports. This is only an issue if your developing the MM 2.0 source and have a 1.xx version installed in AppData/Local/MarkdownMonster.

**Comment by RickStrahl** [comment]
Yes the docs have not been updated. Most of the addin methods are now async. 

I need to update the template project, forgot about it until recently and haven't had time to update it yet. It'll be a while longer.

In the meantime you can use the old templates (or an old addin) and change the main entry methods to `async Task` or `Task`  to get the addin to work with 2.0. Functionally not much needs to change except editor access functions many of which now are async, which is why the signatures have changed.

I was able to update all of my addins mostly with search and replace.

**Comment by RickStrahl** [comment]
Docs and templates have been updated, although some of the examples may not yet use the async calls. Should be easy to detect though. It's on my internal list for updating.
