### ISSUE TITLE
Preview Sync Mode

### ISSUE THREAD

**Issue by Snemelc** [RickStrahl/MarkdownMonster#827]
When I use Preview Sync Mode **"Editor and Preview"** and then preview in **full-screen** mode (F11), the view sometimes jumps back to the starting position. It seems as if the Editor is still syncing the view even if not visible. This doesn't always happen, but I can trigger it by scrolling.

When I choose one of the "one-way" sync modes, everything is fine.

**Comment by Snemelc** [comment]
Sorry, I forgot: version is 2.0.2.3

**Comment by RickStrahl** [comment]
Well the preview and editor are linked, even if you are in View only mode, so the editor is always there even if invisible (you can drag it open if you use the splitter bar on the left). So the syncing is going to happen no matter what.

However, it **the preview shouldn't jump if you're not doing anything to the editor**, so there's an issue there.

That said I've seen this myself on some occasions, although rare (in two-way sync mode) and it has to do with a situation where the preview scrolls and can't find anything to match back to the editor. This can happen with long multi-page code blocks, large images, large tables (none of which have back-link markers). There are checks for that but in some situations apparently these get bypassed and it jumps to the top or bottom.

I'll take another look and see if some additional checks can be put in. It's a pain though because I don't have a repeatable repro scenario.

**Comment by Snemelc** [comment]
Here is an example file that almost always reproduces the behavior on my computer:
[JumpingPreview.md](https://github.com/RickStrahl/MarkdownMonster/files/6876116/JumpingPreview.md)

(I'm on a 1080p resolution, maybe the lists have to be larger for bigger screens?)

**Comment by RickStrahl** [comment]
I can't duplicate this with your sample file even at minimum window size for MM. What version are you using? 

The problem usually occurs when MM can't find an ID to match editor to preview items. Recent versions of MarkDig add pragma line numbers for list items so list are not the problem they used to be. The big issues are large `<pre>` blocks  or large images that span over a single display page/view especially right at the top and end of the document. Not much I can do about this unfortunately, but you can turn off two-way sync and just use editor->preview syncing on problem  documents.

**Comment by Snemelc** [comment]
The version is still 2.0.2.3 (Jul 21, 2021; 64 bit; .Net 4.8)
Not a big deal, I will use one-way sync then.
