### ISSUE TITLE
Paragraph spacing lost after roundtrip to Wordpress

### ISSUE THREAD

**Issue by r2musings** [RickStrahl/MarkdownMonster#828]
I created my MD document using internal preview and all of my paragraph spacing was fine.  I pushed to Wordpress and it shows the document fine as a preview and as a published blog post, but when I pull the document back into MM, all of the paragraph spacing is gone.  

I read the MM docs about Chromium Preview thinking that might help, but I can't find an icon or any mention of that functionality in the program...is it still there?  Do I need to add an add-in?  (No add-in matching that name in my list of Add-ins).  
Would this help and if so, how do I get the icon to show?

This is my live post:  https://www.wintellect.com/moving-to-asp-net-core-replacing-html-helpers-that-have-dependencies/
You can see the spacing I am expecting in both Chrome/Edge.  

This is image has it side-by-side in Chrome and in MM preview:
<img width="1808" alt="MissingParagraphBreaks" src="https://user-images.githubusercontent.com/2158785/126915777-c1047576-b6a2-4137-a06b-f6e6455fc09a.png">

Thanks in advance for any help you can offer.

**Comment by RickStrahl** [comment]
I can't really duplicate that. I just tried this on my sample Wordpress site (on Wordpress.com) and here's what I get:

![image](https://user-images.githubusercontent.com/1374013/126929965-1261f2cf-d7f8-4487-a75e-381889c3aed9.png)

Browser on the right is the site with the post loaded, and MM on the left is the imported blog entry. As you can see it's picking up the paragraph breaks.

MM sends up raw HTML to WordPress sites and if the site renders that correctly (as it should) then you should also get that HTML back. We use a reverse markdown parser that takes HTML and converts it back to Markdown as best as it can. If you're not getting linebreaks then it looks like the `<p>` `</p>` breaks are not there when WP returns it. Is it possible you have the site set to return markdown?

-- later ---

I spent a bit more time experimenting and I'm seeing some really weird behavior from Wordpress. Sometimes it returns the proper HTML, at other times it returns some sort of pseudo HTML that removes all the `<p>` breaks. I'm not sure what the difference is. The post above works just fine. Another post I made has the `<p>` stripped. Not sure what to make of that.


FWIW, if you need to repost it's better to republish posts rather than downloading and then re-uploading as there's bound to be some fidelity loss in the HTML -> Markdown conversion. It's better to store the Markdown locally (or in a central place like DropBox) and then re-publish.

It looks like there's a problem with Wordpress republish - checking that out now.

It looks like Wordpress has silently changed their API not too long ago to break a whole bunch of functionality that was working just fine a few months ago when I last checked.

**Comment by r2musings** [comment]
Thanks, Rick.  Glad you were eventually able to repro and sorry to hear about the API change from WP.  Thanks for the tip on the re-publish.  I was only pulling it back in because our Marketing Director does a few additions for SEO/etc before we go live on posts.  I do keep my markdown in GitHub, so I can certainly adapt to the flow you recommend.  Let me know if you need anything else from me.
