### ISSUE TITLE
Scripts run when in an iframe even with setting to disallow scripts

### ISSUE THREAD

**Issue by bleroy** [RickStrahl/MarkdownMonster#831]
MM has a setting to disallow scripts in the preview. It may be unexpected or dangerous that even with that setting, an iframe in the markdown is able to include scripts that will be run in the preview. Maybe iframes should be disallowed by default like scripts are.

**Comment by RickStrahl** [comment]
Hmmm... this actually looks like a different bug - the allow script setting is not setting correctly.

The Allow Script Tags setting should filter iframes out when not set, but it looks like the setting toggle on the menu is not working and the value is not making it into the Markdown parsing code.

Checking now.

**Comment by RickStrahl** [comment]
So yes - the problem was that a recent change broke the bindings for the actual setting so the setting wasn't being applied properly and with the fix I just applied this should now work. In addition, some time ago the script setting was applied to the active document and that setting wasn't forwarded, so you actually would have had to close down the document to see the change take.

Updated the bindings (the real bug) and also added updating of setting on all open documents when the setting is changed (at least on the menu).

![AllowScriptingIFrame](https://user-images.githubusercontent.com/1374013/127419610-b21d9da9-b1c1-4dda-af8e-10c01432f647.gif)
