### ISSUE TITLE
Copying and pasting from preview window doesn't retain images

### ISSUE THREAD

**Issue by teemoon** [RickStrahl/MarkdownMonster#843]
When copying from the preview window and pasting to an external app like Word, Outlook, etc. images get lost.

**Comment by RickStrahl** [comment]
Yeah that's not going to work because the clipboard takes the HTML verbatim and pushes that into Word (or whatever clipboard target). 

The problem is that the images are local images on disk with a relative path. The Clipboard can't resolve that, so that's just not going to work. 

You can see this same behavior in browsers if "Open in Web Browser" (from the preview) and then copy from there. 

The only way this can work is if you

* use Web links for images
* use embedded inline images

For the first http links work because they are globally accessible. Likewise for embedded resources because they are part of the document.

If you really need to do this you can do the following:

* Export to HTML - Self Contained
* Open document in Web Browser
* Copy from there
* Paste into Word

![CopyToWordWithImages](https://user-images.githubusercontent.com/1374013/130492152-752a8b5b-ea71-48ce-a140-4a28f41987cf.gif)


Export to HTML/Self Contained will package up the document and embed all resources inside of the document and that will then work.

**Comment by RickStrahl** [comment]
Added a FAQ topic in the help file:

[Missing Images when copying from HTML Preview](https://markdownmonster.west-wind.com/docs/_64m0mxxl7.htm)

**Comment by teemoon** [comment]
Yeah, but why did it work before the recent major update (in versions 1.*)? Used it on a daily basis.

**Comment by RickStrahl** [comment]
It didn't. I checked in 1.28.

It worked perhaps because you had images hard linked to a Web url.
