### ISSUE TITLE
[Feature Request] Add ability to choose the default table mode.

### ISSUE THREAD

**Issue by JimBobSquarePants** [RickStrahl/MarkdownMonster#849]
If this already exists and I've missed it, sorry!

I've been using Markdown Monster in an unconventional way recently to annotate some code I've been writing to parse open type font files. The table editor feature is glorious and lets me format HTML tables from the spec docs into a manner I can supplement my code documentation with.  

![image](https://user-images.githubusercontent.com/385879/132146938-177c4ba4-71a6-4bda-bfc1-38904cac071f.png)

As you can see I use the grid table format because, well, it's prettier than the pipe one but I have to specifically choose to do so each time. It would be amazing if I could set a default for that decision and have my preferred type each time.

Thanks!

**Comment by RickStrahl** [comment]
Yup, that's actually been on my list of things to do. I've pulled this to the top of the list as I'm doing a few things around the table editor today.

It'll end up being a flag in the Editor Configuration Settings that tracks your last choice rather than a default (similar to the way Commit and Commit and Push is handled in the Git component).

**Comment by RickStrahl** [comment]
Added in 2.0.12.3 and later.

**Comment by JimBobSquarePants** [comment]
Hero!
