### ISSUE TITLE
Window is off-screen, no right-click / alt-space taskbar icon menu to move it

### ISSUE THREAD

**Issue by CADbloke** [RickStrahl/MarkdownMonster#852]
Multiple monitors, I must have moved screens around since the last time I opened MarkdownMonster. MM is off-screen, outside the boundaries of the current window arrangement. 

Msft has some hints about fixing this: https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4 pretty URL, eh.

Cascading the windows worked (eventually) but it broke my OCD about where all my apps were. 

Method 2: "Right-click the program on the taskbar, and then click Move....arrow keys" doesn't work, there is no right-click menu for the MM taskbar icon as there is on most apps. Alt-space didn't work either, for the same reason.

Yeah, that's all - everything else in MM is **awesome**.

Cheers
Ewen

**Comment by RickStrahl** [comment]
When exactly does this happen?

MM has logic in it on startup to re-position windows if they are not visible. But I think there's no logic at this point that detects resolution changes when they happen in real time.

**Comment by RickStrahl** [comment]
So can you provide your exact scenario that's failing here?

Just double checked and MM definitely handles desktop resizes for:

* Restarts
* Resolution Changes

I'm testing these particular scenarios on a single screen since that's all I have access to at the moment. Scenarios are:

* 4k res - move MM window into lower right
* reset res to 1080p

Window auto-resizes to fit into 1080p

* 4k res - move MM window into lower right
* shut down MM
* reset res to 1080p

Window opens properly in ViewPort.


* Move MM to 1080p laptop screen
* Disable 1080p laptop screen to 4k Monitor

MM moves to the 4k screen.

* Move MM to 4k monitor
* Disable 4k Monitor to 1080p monitor

MM moves to 1080p display and resizes itself to fit on screen (although some of MM's screen is bleeding off screen).


These seem to be all the scenarios that I would expect commonly to happen and it seems that MM handles them all as expected.

**Comment by CADbloke** [comment]
Hi @RickStrahl I'm really sorry I missed this. I haven't seen the problem again so sorry I can't help diagnose what went wrong. 

I believe it was on startup. This is my screen layout if that helps, all 4k but the laptop screen # 1 is set to 150% dpi, which breaks an enormous number of apps, and Windows things...

<img width="291" alt="2021-11-24 08_58_00-Settings" src="https://user-images.githubusercontent.com/147329/143135839-80b1df51-6cea-4fd0-80b3-a185d9f9b2b8.png">

In any case, I haven't seen it again. Also, the right-click menu on the task bar popup works now. Maybe it was (yet another) Windows 10 glitch. 

Sorry again for missing this and thanks for looking into it.

**Comment by RickStrahl** [comment]
I think if you have asymmetrical stacked window layouts like what you show in your 4 monitor setup it's possible that the window ends up in a 'dead spot' of the screens where it thinks it's visible when it's actually not. 

The way the realignment algo works is that it uses a virtual canvas square and if the screen layouts aren't square some of the holes may not make the app visible. That should be rare though, especially if your layout is the same in which case it'll just go back to where you left it next time you start.

As to the 'move' missing on the taskbar context menu - I'm aware of it and I think that started with Windows 11. This is related to the custom window library MM uses and I suspect this will resolve in updates of this library as it adjusts for Windows 11.
