### ISSUE TITLE
Bug - insertion point changes when typing in link part of a []() when in editor and preview sync mode

### ISSUE THREAD

**Issue by DangerMouseB** [RickStrahl/MarkdownMonster#857]
e.g. I want to add a `resources/` subdirectory to 
```
[Diagram Case 1](case_1.png)
```

but when I start typing the cursor jumps to a couple of lines before (doesn't happen in other sync modes)

**Comment by RickStrahl** [comment]
Can't duplicate, but there are a few scenarios where there's some cursor jumpiness due to feedback between the editor and the preview since both can be scrolled and adjust each other. Usually has to do with long tables, large images or codeblocks that span more than an editor page.

I can't dupe this even in those scenarios on demand but it does happen occasionally. The workaround is to use editor->preview syncing.
