### ISSUE TITLE
New Markdown Monster Plugin

### ISSUE THREAD

**Issue by joemclain** [RickStrahl/MarkdownMonster#866]
I submitted a pull request to the MarkdownMonsterAddinsRegistry back in early September, don't know if you've had a chance to look at it yet.

Additionally, I was wondering if you were going to comment on the other issues I've posted here?

FYI, I'm back in work mode and finally registered for MM 2.0 the other day.

Thanks,

-joe-mclain-

**Comment by RickStrahl** [comment]
Finally added... sorry for the delay on all of these addin related issues. I've been putting off dealing with anything related to addins until today when I was ready to finalize the addin interface changes etc.

The addin is approved, but you'll need to recompile it - it fails to load due to signature changes since last summer. Make sure to set the min-version to 2.3+ or higher.

I was going to update it for you but since you have hard coded paths in the project I didn't want to make those changes and check them back in.

**Comment by joemclain** [comment]
I've put this on my list of things to do.

**Comment by joemclain** [comment]
Rebuilt, pushed, and works (for me at least) with the current MM release.

**Comment by RickStrahl** [comment]
Yup works for me too. 

Do you see a need for this often though I wonder - I don't see a lot of use cases for this in Markdown in particular, but it will be handy for other things (genereating place holder text for Web pages).
