### ISSUE TITLE
Error while export to html or pdf

### ISSUE THREAD

**Issue by kashiash** [RickStrahl/MarkdownMonster#879]
Unable to render Markdown Document
An error occurred trying to parse the Markdown document to HTML.

Error
Nie można załadować typu 'Markdig.Parsers.Inlines.AutolineInlineParser' z zestawu 'Markdig, Version=0.26.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by RickStrahl** [comment]
More info please. What version? What are you doing exactly?

Markdown you're rendering?

**Comment by RickStrahl** [comment]
Taking a closer look it looks like this is due to an incompatibility with the DocFx parser. Essentially that parser is using an old version of MarkDig that can't interact with the more recent version that Markdown Monster uses. For the time being this means that the DocFx parser no longer works until this can be resolved at the DocFx library level to use a more recent version of MarkDig.

You can switch to the default MarkDig parser, which has some but much more limited DocFx feature support.
