### ISSUE TITLE
Slash/BackSlash Issue for Snippets

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#880]
Hi Rick, 
In the Snippet manager, when I am using the {{Model.ActiveDocument.Filename}} expression the result comes with Backslashes "\\" . For Linux and Max this might be ok, but under Windows this gives me headaches. 
Can we have an option to toggle to Forward-Slash "/" instead (the same way you did already when dragging files into the document to create a link/path to the dragged document).

**Comment by RickStrahl** [comment]
Not sure I understand what you're asking. How would this be OK under Linux and Mac, and not on Windows?

IAC, the filename is what it is on Windows, so it'll come as whatever the OS filename is. If you need to change the slashes it's easy enough to do with:

```cs
{{Model.ActiveDocument.Replace("\\","/")}}`
```

Still not sure how this would help on non-Windows OSs since the filename includes a drive letter and the full Windows path.

**Comment by realB12** [comment]
To make relative hyperlinks work for internal navigation in the Monster-Editor AND Monster-Preview I have to use Slashes "/" such as [myLink](../mylink.md) - backslashes do not work. 

So, when {{Model.ActiveDocument.Filename}} generates backslashes  it is somehow inconsistent with hyperlinks in my documents. I can live with that. 

However, what really bothers me is the case (often),  when using this generated path as a hyperlink in other documents (copy/pasting this generated path into other *.md files, so that they refer to the document for which this path has been generated. And Navigating in the Monster-Browser Panel and drag/dropping the file (which generates Slashes!!)  is not an option,  because my structures are very complex. 

{{Model.ActiveDocument.Replace("\\","/")}}` will not work because I have some documents where backslashes are required and must not be replaced. 

Does this help?

**Comment by RickStrahl** [comment]
No not really. 

FWIW, in the last release there have been some updates to the pathing of dropped files so that may address some of the backslahs issues you mention in document.

I don't see how this can be resolved in an addin or snippet using the ActiveDocument's filename. As said, the file name is a physical OS filename so that's what the path is. It's trivial to fix up the slashes if that's a problem. Fixing up the path for a base path is more difficult but there are no easy solutions for that. 

Markdown monster does have a way to retrieve a 'root' path based on things described here:

[Configuring Site Relative Base Paths](https://markdownmonster.west-wind.com/docs/_5fz0ozkln.htm)

and there are  helper functions in `mmFileUtils` that let you normalize a path based on that base path.

First you need to get the base path for the a document:

```cs
// on MarkdownDocument
public string GetWebRootPathFromMarkerFiles(string basePath)
````

Then you can normalize a given path to that base path:

```cs
// on mmFileUtils
public static string NormalizeFilenameWithBasePath(string file, string basePath)
```

This allows you to normalize paths for embedding. Internally that's what MM does when content is embedded (or is supposed to - there are quite a few places where embedding happens and there might still be one or two that don't do this correctly but I think as of 2.1.8 all of them do.

**Comment by realB12** [comment]
You lost me. I am not into coding :-) - not even sure whether we are on the saem page. 
Trying again to explain my case: 

## Setup
1. I have created a "xpath" named Snipped that simply puts` {{Model.ActiveDocument.Filename}}`
2. When I execute this xpath-Snippet in an link01.md document I am getting
`C:\...\RelearnThemeExplore_a\content\linktests\link01.md` with backslashes
3. Then I am opening a test.md file in the `C:\...\RelearnThemeExplore_a `folder. 

## Issue
a) When I am referring back from test.md to link01.md I copy paste part of the xpath genrated path so that the hyperlink looks like `[link01](content\linktests\link01.md)  ` (with BACK-slashes)

b) when I am drag dropping test01.md into test.md from the NavigationTree I am getting  `[link01](content\linktests\link01.md)  ` (with backslaches) [content/linktests/link01.md](/content/linktests/link01.md) with FORWARD-slashes. 

With the new release this issues is only for cosmetic reasons as the Backslahes navigate within the MM-Editor as well (which they didn't with previous release). 

So, as the issue has only a "cosmetic" nature - for me this issue can be closed.
