### ISSUE TITLE
MM 2.1.6.2 fails when common folder is "%appdata%\Markdown Monster" and is not writable

### ISSUE THREAD

**Issue by BGood375** [RickStrahl/MarkdownMonster#881]
Installed Markdown Monster 2.1.5.5 to "C:\Program Files\Markdown Monster" as admin user.
Changed Common folder to "C:\ProgramData\Markdown Monster".
Added shortcut to MM from non-admin user.
Markdown Monster appeared to be working, but didn't do much with it.
A couple of days later, installed update to MM 2.1.6.2 as admin user.
Started MM as non-admin user.
Opened file - no content showed.
MM displayed error information, but since MarkdownMonsterErrors.txt wasn't writable, no error information was saved.
Added permission for non-admin user to write to "C:\ProgramData\Markdown Monster"
MM started and displayed content and preview of same worked.

**Comment by RickStrahl** [comment]
Well this is to be expected, if you use a non-writable folder explicitly.  Foot: meet gun :smile:

By default Markdown Monster installs to `%localappData%\Markdown Monster` and uses  `%appdata%\Markdown Monster` for common files both of which are writable. The install folder doesn't need to be writable, but the common folder most definitely does as configuration information is stored there - including the Web Browser environment (which is why the browser fails with the error page).

 If you choose a non-writable folder there's nothing we can do about that and you're out of luck.

You found your solution which is really the only one if you're not going into a location on your user profile that's writable, which is explicitly set permissions. We won't do that for you (security issue obviously).

This makes sense only if you use the machine routinely with different user accounts or explicitly run MM under an admin account as that would use a different user profile.
