### ISSUE TITLE
.gitignore files open double when double-clicked in the SideNavBar

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#886]
Hi Rick, 
I am on Windows 10 Pro with newest MM. 

When I doubleclick an .gitignore file in MM-Editor's side-navigation-bar this opens notepad.exe TWICE ??

**Comment by RickStrahl** [comment]
Hmmm... that's not what I'm seeing. Double click on .gitignore opens VS Code for me and only once.  But VS Code actually uses a single instance so probably wouldn't notice double open. Not sure how to test for that though since any editor association pretty much goes into VS Code due to the many associations it sets up including .gitignore.

But checking some other types of files - like images, I only see them open once, so something seems screwy about the double open. What happens for you when you double click on an image? (Should open in Windows Photo Viewer if default) - does whatever opens, open twice there two?

**Comment by RickStrahl** [comment]
Also as a side  note you can right click -> Open -> Open With Shell. What happens when you do that? Uses the same code path, but avoids the potential of double clicking causing more than one actual activation...
