### ISSUE TITLE
SampleMarkdown.md error in Fontawsome Icons demo

### ISSUE THREAD

**Issue by MarshP** [RickStrahl/MarkdownMonster#888]
The examples as given
@ icon-gear
@ icon-
doesn't work in MM. Needs the space removed.

**Comment by RickStrahl** [comment]
Yeah unfortunately that's because the renderer will render it if you don't have the spaces in the display values. 

After playing around with this some more I figured out that I can perhaps use an EM Dash in the examples.

```markdown
@icon—gear Configuration
```

which looks correct, but won't work if you try to use it. 

It's the only work around I have for this...
