### ISSUE TITLE
App often crashes when clicking on a file result after searching subfolders

### ISSUE THREAD

**Issue by deanebarker** [RickStrahl/MarkdownMonster#893]
I've refrained from posting this, because I was trying to find a pattern, but I can't (sorry).

The app often crashes when you

1. Search files names with the subfolder option checked
2. Attempt to open a result

The app will hang for a second, never open the file, then just closes.

Here is a video:

https://www.loom.com/share/bdd6ce734c3141ffa769e02175fb2f57

Towards the end (it's 0:37), I click on "coordinated-disclosure.md." It never opens, the app hangs for a second, then just goes away.

But after the app crashes, and I re-open, I can search for that same file, and it works fine. So it's nothing in the file that's causing it.

I'm surprised it took that long for the video. Honestly, it's about 50% of the time. And, again, it seems to only happen when the "search subfolders" box is checked.

There is nothing in the error log.

I'm sorry, I tried to find a pattern or other clues, but I can't. But know that it's very consistent, to the point where I avoid using the "search subfolders" feature.

**Comment by RickStrahl** [comment]
Without looking closer I think I know what this is - still an artificat of the 2.0 conversion to async code. Anytime there's a 'hang' where the app appears to lock up it's usually associated with an async lock where non-async code waits.

I'll take a look but almost certain it'll be code that fails to properly handle an async call. Hopefully an easy and quick fix. 

Thanks.

**Comment by RickStrahl** [comment]
Give version `2.2.2.2` or later a try. 

Turned out to be a bigger issue than just the async problem that had to do with the way the item selection is taking place. Issue was occurring when the item was click-moved (even very small distances).

This fix ended up fixing several other related issues:

* Fix accidental drag and drop starting on clicks
* Fix potential lockups when turning preview document to editable document (double click)
* Fix title bar display when converting to editable document (no path if not same name docs in list)
* Fix odd Document open lockups through folder browser

**Comment by deanebarker** [comment]
>Issue was occurring when the item was click-moved (even very small distances).

Confirmed. That is exactly what causes it.

**Comment by deanebarker** [comment]
Installed 2.2.2.2. I can no longer replicate bug.

Great fix, Rick. I appreciate it.
