### ISSUE TITLE
Centering mermaid diagrams

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#894]
I notice that when there is a mermaid diagram the SVG within the div of the `mermaid` class has an inline style that has a max-width. Could something be implemented to either remove the inline style or have a setting such that the mermaid diagram can be centred?

I.e:

```
<svg id="mermaid-1640242331086" width="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="168" viewBox="0 0 520.36669921875 168" style="max-width: 520.36669921875px;">
```

When replaced with the following will centre the mermaid diagram:

```
<svg id="mermaid-1640242331086" width="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="168" viewBox="0 0 520.36669921875 168">
```

Thanks!

**Comment by RickStrahl** [comment]
The layout doesn't come from MM but from the Mermaid renderer. IOW, MM doesn't render that SVG tag - it gets rendered by the Mermaid renderer.

Also remember - what you see in MM is just **a preview**. If you use Mermaid diagrams, you'll need some way to publish that Markdown so that you can actually share the content on some platform that supports Mermaid for it to be viewable outside for MM. MM just provides the editing and preview side of it, not what gets published.

**Comment by SMTStuck** [comment]
Yes I'm aware that MM is just a preview, I'm actually using an external web browser for the preview.

I appreciate MM does not render the SVG, but MM does control the location of the SVG element. Also, when saving to a HTML file, is there any option to have MM include mermaid so that mermaid diagrams within the HTML files may be rendered?

**Comment by RickStrahl** [comment]
I don't think you quite understand how Mermaid rendering works. It requires a library to render so the target output mechanism has to provide the rendering.

if you want to capture the output in MM including the Mermaid library you can:

* Export to HTML (self-contained or with loose dependencies)
* Print to PDF

![Print to PDF](https://user-images.githubusercontent.com/1374013/147610206-d4f7efbb-4d9b-43e6-9030-f4c09966cc36.png)

The PDF export (only from Print to PDF - not from PDF output that won't do it) will be self-contained and small. But the HTML export will be huge due to the library size of the Mermaid library.
