### ISSUE TITLE
Editor changing caret location

### ISSUE THREAD

**Issue by SMTStuck** [RickStrahl/MarkdownMonster#897]
Struggling to find the steps that replicate this problem, shall keep the topic updated as I do. It is a very regular occurence (at least once every 10 minutes), so have managed to capture the event. Essentially, left clicking within the document and then moving the scroll wheel once, forces the caret to the first visible line. This has never been seen before and have checked with a previous version of MM which showed no issues after many hours of use. Perhaps this is related to the changes with the editor now being asynchronous?

![Animation](https://user-images.githubusercontent.com/28392792/147584422-094f6c2e-a569-4dd1-a969-28a071f9afaa.gif)

**Comment by RickStrahl** [comment]
If you have problems with this start by setting the preview to update one way from editor to preview instead of two-way.  This is almost always called by a recursive update loop where the previewer scroll reflects back into the editor. It's rare, but it can happen more frequently if you have large block elements at the end of your document (images/code snippets/script rendered elements). It's worse if the rendering is slow due to script running in the page (ie. Mermaid/MathML rendering).

In most cases disabling two-way doc syncing and using either one-way from editor to preview or none solves this.
