### ISSUE TITLE
Minor issues with Grid Tables in MM v2.3.5

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#905]
1. When you edit a Grid Table then the table editor offers the command `Align Column` although the alignment cannot be changed, unlike in Pipe Tables. Grid Tables are always left-aligned. Unapplicable commands are usually ghosted or hidden.
2. When you create a new Grid Table then the table editor shows the second column as right-aligned although again Grid Tables are always left-aligned.
![image](https://user-images.githubusercontent.com/98041047/150703535-a9b9cd86-000f-4d1c-8cae-fcdc56cf97aa.png)

**Comment by RickStrahl** [comment]
That's not going to change because you can select a different type of table at any time and in fact most people won't set that value until they're ready to embed (or have already embedded) the table. 

Both Pipe and Html tables do support the alignment. The selection isn't set in stone and the assignment of the alignment is the state needed to preserve that state. 

It doesn't break anything and while I get your point in this scenario it doesn't make sense to disable it and UI complexity in dealing with alignment.

**Comment by jbridgy** [comment]
Of course these are minor issues as I stated in the title. I would initialize a new table always with left-aligned columns (which does not add UI complexity) and put the rest (ghosting the alignment command for Grid Tables) into the backlog.

**Comment by RickStrahl** [comment]
Sorry missed 2.) (right aligned second column)- that was fixed for the next update.  This was a hold over for the original table editor which didn't have the ability via menus to changing the alignment. It was meant as a hint that you can use Markdown formatting in the headers. Less needed now although I still kind of think that that's appropriate as you will be changing the header text on both columns.
