### ISSUE TITLE
<img> not rendering in live preview for .html files

### ISSUE THREAD

**Issue by ncfreedman** [RickStrahl/MarkdownMonster#907]
While working on .html files, <img> elements using relative links are not rendered in the live preview and instead yield the broken image icon (&lt;img src="image.png"&gt;   yeilds   <img src="image.png">) Any ideas for why this is? It would be such a great help if there was any way of fixing this.

**Comment by RickStrahl** [comment]
The problem is that the previewer previews from a temporary file location and not in the folder that the actual file lives. So images aren't found unless there's a `<base>` reference back to the page:

For example, the Markdown Previews render into `<tempPath>\_MarkdownMonster_Preview.html`. It then sets the `<base>` back to the original document's folder:

```html
<html lang="en">
<head>
    <base href="file:///C:/projects/MarkdownMonster/"/>
```

This is also true for HTML files because it's not just previewed but basically 'rendered' (copied in this case) and then previewed using the standard editor/Markdown preview. At the time I probably didn't think about this much, just kind of as a bonus that it worked out of box.

Agree with you though - MM should just open the file from the actual location.


There are two ways this could be fixed:

1. Don't copy the HTML file, open from source
2. Inject `<base>` ref back to the original path to the doc header


2. is probably easier as everything will just work the way it does now. The problem with 1. is that it requires lots of special checks for html files where the preview is specifically set up to render a single preview document.

**Comment by RickStrahl** [comment]
I've added the `<base>` injection code into rendering for HTML documents and this seems to work really well - I'm now able to properly preview most documents with their related resources:

![image](https://user-images.githubusercontent.com/1374013/151677353-7962a846-0090-4b51-b7f9-e7777385dfc1.png)

But this will not work, if the document already has a base tag and the base tag is not a fully qualified path. 

It's a nice enhancements for the most common use case even if it has limitations compared to the much more full featured preview features of Markdown.

Thanks - this is a great addition!

**Comment by ncfreedman** [comment]
Thanks for this!!

**Comment by RickStrahl** [comment]
Updated in 2.3.7
