### ISSUE TITLE
Multiple "Mermaid"s in one Document

### ISSUE THREAD

**Issue by hesspet** [RickStrahl/MarkdownMonster#913]
I evaluate MM for the use in our company. I've a sample file which displays correct in other editors like Joplin or Mermaid VisualCode Plugin.

MM shows only one graph. I've attached a the md file. 
[test_md_monster_with_mermaid.md](https://github.com/RickStrahl/MarkdownMonster/files/8089457/test_md_monster_with_mermaid.md)

And a result pdf created by joplin with this file:

[test_md_monster_with_mermaid.pdf](https://github.com/RickStrahl/MarkdownMonster/files/8089486/test_md_monster_with_mermaid.pdf)

to show the expected result.

Looks that MM run into problems with multible graphs.

**Comment by RickStrahl** [comment]
As to PDF printing, because Mermaid uses script code to render, which isn't support by the MM PDF output engine, the only way you can print pages with embedded Mermaid is by using the print function from the Preview and the Save as PDF:

![image](https://user-images.githubusercontent.com/1374013/154760557-497fcdfe-6139-45bb-83be-386929024e42.png)

This will capture the Mermaid graphs in the output.
