### ISSUE TITLE
MM 2.3.17 version doesn't take in registration key

### ISSUE THREAD

**Issue by sonokamome** [RickStrahl/MarkdownMonster#915]
In the most recent version 2.3.17 I put in my registration key and email and I get the following prompt:
![MarkdownMonster_GGbJkmgT1H](https://user-images.githubusercontent.com/13297452/155298401-d5fc75ae-a066-4ca4-9a9d-b1eefb520e5d.png).

Should I just downgrade to an older version or wait for a fix? Love the editor. Good work.

**Comment by RickStrahl** [comment]
That should work. Can you please try again?

Also make sure that you are not blocking applications from Web access via Anti-Virus or Firewall. For Firewall you can add the Markdown Monster exe to the rules exception list.

**Comment by RickStrahl** [comment]
Any update on this?

**Comment by sonokamome** [comment]
Still nothing. I've updated to the most recent version. put a whitelist rule for `licensing.west-wind.com`, and have put an exemption for `MonsterMarkdown.exe` (Windows 10) and still the same prompt. Will try and update you later.

**Comment by RickStrahl** [comment]
are you using some sort of proxy server?

**Comment by sonokamome** [comment]
No. Just Pi-Hole.

**Comment by RickStrahl** [comment]
Sure send an email since this is semi security related.

Is there some way to check what Pi Hole is blocking? MM makes a straight Http connection to the server - single server, nothing tricky there so this should work unless it's getting blocked either by Pi Hole, a firewall or perhaps Anti-Virus.

This is the first report that I've had with a registration not working.
