### ISSUE TITLE
State of button `Save active document` is not reliable in MM v2.3.18 (and before)

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#918]
**Sometimes** (quite often) the button `Save active document` is not updated when the document is changed by typing or by dragging&dropping text within the document, but only when you click on the toolbar or come back from another app. This has the following negative consequences:
1. If you edit a file quasi-simultaneously with MM and a general editor then it is crucial that the file is not modified when you switch to the other tool. So an unreliable save-state causes **needless work** or even **data loss**.
2. To make sure that the last changes made by MM are saved you have to click **twice** on the button `Save active document` because the first click just updates the save-state.

Unfortunately I could not find an example that **always** leads to the bad behavior.

**Comment by RickStrahl** [comment]
This is a binding artifact in the UI. The file is saved, but the UI is not immediately reflecting the updated status in the toolbar. You can verify by opening the menu where you can see the Save option enabled/disabled based on the current status and that should reflect the actual state. Opening the menu also refreshes the status on the toolbar and title correctly. It's a bug but I've not been able to track this one down.

I've known about this and have been trying to track down why the status isn't updating. I'll take another look.

**Comment by RickStrahl** [comment]
So I think I fixed this sort of by accident :smile: Turns out there's a WPF bug with initial `IsEnabled=True` which doesn't properly apply until the WPF chrome is activated. By removing the setting, the control now correctly displays the IsEnabled default state. Weird bug, but the state was actually correctly set and updating. I initially thought the state was not set correctly but it was the enabled state that was not working. Fixed now in 2.4.4+.

Also please note that the more visible file save status is shown in the filename on the Tab and in the Title of MM which had always displayed the state correctly.
