### ISSUE TITLE
Drag&Drop text ending with a file extension does not work in MM v2.3.18 (and before)

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#919]
Moving and copying a selected text within a document by Drag&Drop and Ctrl+Drag&Drop respectively fails if the text ends with a file extension, that is, the text is not inserted at the drop location (although it is deleted at the drag location in case of moving). For example `.md`, `ReleaseNotes.md` or `[](../a/b/ReleaseNotes.md` **cannot** be copied by Ctrl+Drag&Drop, **unlike**  `ReleaseNotes` or `[](../a/b/ReleaseNotes.md)`.

**Comment by RickStrahl** [comment]
Hmmm... yes, see that too now. This is happening because MM intercepts dropped content and looks for file names that it can embed. It looks like the behavior of how this works has changed when we switched to the WebView control. I'll take a look.

**Comment by RickStrahl** [comment]
Ok now fixed: (among other things related to drag and drop):

![DragTextAndFiles](https://user-images.githubusercontent.com/1374013/157364413-7faf17d5-0c80-4fa0-9bfe-dfd0355da77b.gif)

The problem was as suspected that MM was looking for a file extension and if it found one passed the file for the host to process. If the file is an image it embeds, but if not then it would basically remove the selection. Code now explicitly checks for files attaches for drop operations for several methods (in doc, from folder browser and from browsers) which fixes this problem. 

This is a change from the old WebBrowser control which didn't provide this functionality - in the past I couldn't differentiate between a dropped file as only the text was provided. The WebView2 provides the full data object and files collection that provides more context.

As a side affect I've reworked some of the D&D operations for files dropped into the document. You can now drag images from the browser to link, or ctrl-drag to save and link the local copied  file.
