### ISSUE TITLE
[Feature Request] Option `PrintTheme` as companion of `PreviewTheme`

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#925]
The option "Print Theme" (default: "Pdf Output") of command "Save Current Document as a PDF File" is not saved in the configuration file MarkdownMonster.json. At least it would be nice if there was a option (as companion of `PreviewTheme`) that could be set manually. The new option may be named `PrintTheme` or `PdfTheme`.

BTW: I don't use "Pdf Output" because it uses too much background color (especially for table headers) leading to ugly blackness and waste of ink.

**Comment by RickStrahl** [comment]
That seems like a bug - all the settings on that screen should be saved. 

As to the black background - I see that but lots of people don't print PDF output and expect something similar to what they see in the preview. You can [create your own themes](https://markdownmonster.west-wind.com/docs/_4nn17bfic.htm#theme-customization) and the use that. I'm hesitant to add too many themes because it's a real pain to keep them all in sync.

**Comment by jbridgy** [comment]
> That seems like a bug - all the settings on that screen should be saved.

Thank you for adding option `PdfPreviewTheme`.

MM 2.4.5.2 uses the value of `PdfPreviewTheme` as default value in the following dialog but still does not save it when changed in this dialog:

![image](https://user-images.githubusercontent.com/98041047/159064867-9dc764b8-7de9-44c5-b41f-c61701ea76d2.png)

**Comment by RickStrahl** [comment]
Fixed in 2.4.5.4
