### ISSUE TITLE
Single-clicking then double-click on a file in the folder explorer opens it twice

### ISSUE THREAD

**Issue by deanebarker** [RickStrahl/MarkdownMonster#926]
Sometimes I end up with the same document open twice, once empty, and once with content.

I've figured out that it has something to do with single-clicking in the tree, then double-clicking. Here's a video:

https://www.loom.com/share/7ecba3920dfd4ba3a474899702001471

You can't see the mouse point there, but the first thing I do is single-click the file name. This opens the document (with the title italicized for some reason). Then I double-click the document, and it opens again. Neither title is italicized now, but the second once has "- blog" at the end of the title (it's in a folder called "blog"), and the first document is now empty.

**Comment by RickStrahl** [comment]
That's by design because the two behaviors actually do different things. 

* Single Click - opens document in Preview mode (until you type into it)
* Double Click - opens document like normal

Preview mode is transitory. As you open the document it shows in the editor but if you then click on another document it's removed and the new document is opened.  A preview document in the editor switches to 'normal' document that stays open once you make a change.

Normal mode (double click) opens the document and keeps it open regardless of whether a change was made.

I imagine most people will single click through documents to find what they want, then start editing and that's the path of least resistance. There's really rarely a reason to double click and when you do you get the permanently open document.

This is similar to the way VS Code handles documents.

I think what your complaint (and mine too BTW) might be is that the document flashes a bit before opening because in fact it's opening twice - first in Preview Mode on the first click and then again in full mode. I don't know of a way to make this work any other way short of delaying opening by a bit to detect the double click before opening for preview. But that IMHO would be worse as it would delay the UI.

**Comment by RickStrahl** [comment]
Ok so I guess I should have watched the video first 😄 

Not sure what is actually happening in that video though but clearly you end with two documents of the same file which is not correct.

I've seen this behavior as well, but I don't have a repro for it and it's really, really rare that it happens for me.

I suspect the issue is related to the above described functionality if the timing is just so that the first document isn't open yet when the double click starts processing the second click.

**Comment by deanebarker** [comment]
So, when the title is italicized, the document is in preview mode, is that right?  I opened a document like that, then started typing in it, and it converted to a non-italicized title. Is that when it converts from preview to "normal" mode?

And what is the purpose of preview mode? How does a document in preview mode differ from a document in "normal" mode?

**Comment by RickStrahl** [comment]
It goes away if you click on another document while in preview mode.

It's a way that you can browse documents without having a million documents opening and cluttering the editor.

**Comment by deanebarker** [comment]
I will keep looking for a common thread that I can reproduce, but this happens to me with some regularity. Leave this issue open, and I'll update when/if I figure something out.

**Comment by realB12** [comment]
Hi Rick, 
For me this problem is getting really serious and is happening all the time: 
- Single Click: sometimes it works and opens in Preview, sometimes nothing is happening
- Double Click: opens files several time - most of the time twice, but it happens that the same file opens even 3 times.
- Clicking a folder icon sometimes produces Windows Popup telling me that "target and source-folders are the same" ??
<img width="335" alt="image" src="https://user-images.githubusercontent.com/3463881/158326977-21739a1c-3fc1-43b1-a27f-fd2a0991d967.png">

Neiter restarting MM nor rebooting the PC make a difference (does not seem to be a cache problem). 

All three issues were happening with all 2.3 versions and persists with 2.4. 
I am working on an updated Windows Pro 64Bit version.

**Comment by realB12** [comment]
> common thread

I have the slight  impression that it is getting worse with every new installation (no my files are tripling after installation of version 2.4): Can it be that every new installation is adding eventhandlers, somewhere? 
Complete uninstalling and reinstalling did not solve the problem but I had the feeling, that it got even worse afterwards. 
I am only guessing in the wild.

**Comment by RickStrahl** [comment]
@realB12 The way this works for a single click is as follows: 

* Click a not already open file link
* If a Preview Tab is open that tab is closed  
followed by opening the updated file you just clicked
* If no Preview Tab is open a new Tab is opened in Preview Mode (italic header)

There is some overhead in this process and yes some flickering that occurs as the old tab is closed and the new one opened. On a slow machine I imagine that this can be very visual - on a reasonably fast machine it's a slight flicker (on my desktop I see a tiny flicker, on my slowest laptop it's definitely more noticable as you can see both the close and opening. 

Unfortunately due to the way the WebView2 control works and the way you have to interact with browser even to shut it down for a tab, it can't be just hidden cleanly as an invisible control won't release its resources properly. So to make this work I unfortunately have to wait for the shutdown before opening a new tab so it can be assigned to the preview tab reference. These are some known issues with the control that hopefully will improve in the future but for now it's as good as I can do for 'swapping' tabs in place.

**Comment by RickStrahl** [comment]
So after a bit of sleuthing around it looks like there's some odd behavior change where one of the events that was handling the single click operation was no longer firing. This screwed up the mouse position capture on click which in turn screwed up the drag behavior which was now firing way more than it is supposed to.  This has been fixed.

Additionally I've reviewed the double click behavior, and added some additional gates that prevent from double loading the document. I think the problem of the dupe doc occurs on large/slow loading documents where the document is inflight of rendering in preview, when the double click tries to open the document as a regular document. What happens there is that the preview doc is not found and so the doc opens twice.  

There's now an additional check that delays opening the preview slightly to detect potential double clicks before opening the preview. This fixes two issues:

* Fixes potential double opening of files as preview and 'normal'
* Fixes excessive flashing as the preview document is not opened as part of the preview

Give this a try in 2.4.2+

**Comment by RickStrahl** [comment]
I've also added an option for the folder browser to preview documents as rendered Html rather than in the editor. This is an option that disabled by default but it works something like this:

![PreviewAsHtml](https://user-images.githubusercontent.com/1374013/158508907-39418eeb-94ef-4a8a-999d-b9a7e6673eea.gif)

Double click in the browser then opens the file for editing.

I'm not sure what I think of this - on the one hand it's a nice preview of the document, but it's not immediately obvious what you need to do to edit the document. So this is more of an advanced feature.

**Comment by realB12** [comment]
Have installed 2.4.4: Situation got even worse: 
Single Click works as intended. 
However Doubleclick now is ALWAYS opening documents double or even three times !
I cannot make it open single time anymore.

**Comment by RickStrahl** [comment]
I'm not sure what could possibly cause that other than your mouse actually causing more clicks to fire than the double click. At most you could get the preview opening and the full doc opening so max that could happen in worst case is two windows open, because those are the only operations that fire. If you get more than that then there's something seriously wrong with the way you're clicking or the way the mouse is transmitting your clicks.

Do you have another mouse you can try this with just to determine if the driver/software you're using has something to do with it? I can't make this fail even with extremely slow or fast clicks with physical mouse or touchpads on two different machines. For me what I see is with regular double clicks I now see relatively smooth load where before it was jumpy as the doc tried to load twice. I can't see how it could be worse now than before because the only change is throttling the single click to detect the double click to avoid the first load if a double click is in process.

The only issue I see is occasionally the document not opening on very fast double clicks - highly inconsistent though (due to anpother known WebView issue).

**Comment by RickStrahl** [comment]
Also - I'm not quite clear why the double click is used so frequently. Single click opens the doc and as soon as change is made the preview is converted to a fully persistent doc. Not saying that double click shouldn't work, but it should be the exception not the rule in most use cases, no?

**Comment by realB12** [comment]
have changed my mouse (old 2014 model, logitech): same issues.

**Comment by realB12** [comment]
conc. doubleclick: 
For presentations, preparations or when working on documentation that is organized wiki-style I have to open 3-5 *.md files from different folders in parallel to work with. So for my workflows,  opening (highly hyperlinked) documents side by side is often. Single-clicking and modifying every single file to make it stick is not an option for me.

**Comment by realB12** [comment]
When Just clicking into  a preview-file would make it sticky (without a need to modify it) I could live with that (and most probable will never use double-click again). Can we do this?

**Comment by RickStrahl** [comment]
No that's not the idea. You're supposed to be able to navigate the file to preview it.

I've made some more changes that should help in 2.4.4.2. These issues are due to async loading of the WebView control and I'm struggling with getting consistent load behavior. I have set up a different way to verify the control is ready which involves less retries and should help with the potential double loads that I think are causing the failures you are seeing.

It should be better as-is for you I think for double clicking (and also single clicking).

I've also a added a configuration option for `FolderBrowser.DoubleClickDelay` which allows you to configure the time before single click navigation occurs to wait for the double click. The default is 300ms - if you still have problems try bumping this a lot to say 1000ms and see if that helps.

**Comment by RickStrahl** [comment]
So I spent a bit more time digging into the click pipeline in all the tracing I found that the tab loading code for double click opening caused tabs to fire load events twice. The click operation was fine, but one of the code paths that handles the file processing had a logic error that caused a condition to fall through resulting in the tab being opened twice. This is very likely what's been causing the problems with double tabs and also with the occasional blank document as the two documents essentially were loading at the same time, asynchronously into the same tab causing a race condition.

This appears to fix the double click jankiness and double opening issues - tabs now open much more cleanly also when going from preview tab to full tab as the tab actually doesn't have to be closed but just gets flagged for redisplay as a full tab.

These updates are in 2.4.5.

**Comment by realB12** [comment]
With 2.4.5.1 all issues seem to be solved. Life is back :-)
I have not even changed settings in the config and it runs with both mice new game-mouse and old office-mouse. 
Thank you so much for this.

**Comment by deanebarker** [comment]
I upgraded, and can no longer reproduce the issue. I didn't know what was causing it before, so I don't have any definitive test criteria, but I would usually stumble across the issue in the course of working, and I can't now, so that's good.

Plus, I learned about preview mode, which I was totally ignorant of before.

A win all-around, then.

**Comment by RickStrahl** [comment]
@realB12 Hopefully life is back - **better**. 

The fix caught a secondary bug which was probably the cause for much of the issues I was trying to work around initially in the first place, which was the incessant flicker for tab activation. The updates now avoid an extra tab load (which was the main bug) **and** also switch between preview mode and edit mode simply by changing state rather than reloading the entire tab. This means much cleaner loads all around from the folder browser and hopefully more more double loads or empty tabs.

Thank you both for your help and patience in seeing this through so many iterations.
