### ISSUE TITLE
Keyboard shortcuts collide with writing polish letters mechanism (Alt + letter)

### ISSUE THREAD

**Issue by revanmj** [RickStrahl/MarkdownMonster#93]
As title says, many shortcuts collide with the way polish letters (ą, ć, ę, ł, ó, ś, etc.) are entered via right **Alt + normal letter** keyboard shortcut. Every time I press this combinations, some kind of window open (Alt + O - open file for example) which is super annoying.

System: Windows 10 Pro x64 with polish regional settings (keyboard layout - Polish Programmer).

**Comment by RickStrahl** [comment]
Hmmm that's odd. Can you tell me what exact keyboard combos are causing problems? I'm guessing the windows pop up are based on browser key combinations triggering some interaction with the Web Browser. 

Alt-O doesn't do anything in the English version (ie. it's not getting triggered by the WebBrowser).

MM itself only maps a couple of Alt- key combinations. Most key maps are Ctrl- key mappings,  which you can find in the [editor.js]https://github.com/RickStrahl/MarkdownMonster/blob/master/MarkdownMonster/Editor/editor.js#L67) file. If there are key combos in there that interfere can modify these settings by commenting them, or by setting them to blank (like the F5 key which gets disabled). This isn't a permanent solution but might be interesting to try to see if we can isolate what's triggering the behavior you see.

There are also a few key mappings in the shell UI but those are more complex command chords rather than simple. I'll take a look and see if I can get the polish keyboard working on my install here.

Thanks for the feedback.

**Comment by revanmj** [comment]
I tested all combinations and problematic ones are right Alt+O (should enter "ó", loads "Open Markdown File" window) and right Alt+N (should enter "ń", creates new tab with empty file). Just like the right Alt (sometimes called AltGr in this case) presses were misinterpreted as Ctrl in those two cases.

What's interesting is that there is Alt+C in the file with key mappings you linked above and it works fine (with right Alt it enters "ć", with left one in opens "Embed Syntax Colored Code" window).

**Comment by RickStrahl** [comment]
So on the US-En keyboard those keys (right alt) don't behave any different than the left alt combos. I'm going to install the polish keyboard and see what happens.

From what you describe though I think this might be an issue with the Web Browser (IE) interpreting these keys differently. Can you try one more thing for me? Open up Explorer and go to the `Markdown Monster\Editor` folder and open Editor.html with Internet Explorer (Open with... -> pick IE). Do you see the same behavior there?

**Comment by RickStrahl** [comment]
So I installed Polish keys and sure enough I can sort of see the behavior you describe. Just to reiterate here's what I see.

Typing right-alt n **occasionally** opens a new window - I can really only duplicate this when I type multiple combos in a row never on single typing. Possible also when typing another right-alt key. Same behvavior with right-alt-o.

I played around with disabling the WPF keybindings (which intercept a bunch of ctrl/alt/shift key combinations) and that doesn't seem to make a difference. Unfortunately when running the full version of IE, the same behavior does not occur - it only happens when the document runs inside of the Web Browser control.

Not sure how to address this but I have a couple of ideas to try.

**Comment by RickStrahl** [comment]
Ok, so I found the problem - I had some code that was internally and manually tracking Ctrl-O and Ctrl-N and apparently the Modifiers that WPF receives are not accurate on those special key combinations. I removed that code and explicitly created proper command bindings and added forwarding to the editor for those key combos. 

bf65fd3ab6ec60dc2f37438c6fd1646ab0fc7a6c

It seems to be working properly now. This will go into post 1.1 updates probably later today.

**Comment by revanmj** [comment]
Sorry I was not responding, but it was nigt here in Poland :)

For me issue occured practically every time I pressed those combinations, maybe it is dependent on something else, like particular keyboard model, its drovers, etc.

I'm glad you've managed to fix this, thanks!

**Comment by RickStrahl** [comment]
The latest version 1.1.2 is up on the Web site (not on Chocolatey) if you want to try it out.

**Comment by revanmj** [comment]
Will do as soon as I get home after work (in about 9 hours).

**Comment by revanmj** [comment]
Yep, 1.1.2 fixes this problem, thanks!
