### ISSUE TITLE
Suggestion: Preview Menu Options are confusing

### ISSUE THREAD

**Issue by shawnwildermuth** [RickStrahl/MarkdownMonster#939]
The 'Toggle Preview' is an on-off switch, but the two below are a either-or:

![image](https://user-images.githubusercontent.com/568272/162654118-02ae1625-2bcc-4603-ba1d-775518cdef56.png)

Took me a while to figure out that had to switch to Internal to turn off External Preview. Should be merged into a single option that toggles IMO.

**Comment by RickStrahl** [comment]
Not much in the way of choices for the menu which only supports checkbox marking.

I'm also not sure how you would roll this into one option - they are two separate tasks:

* Toggle the preview on and off (both internal or external)
* Toggle where the preview display (internal or external window)

Maybe a better caption for the first option would make this a little clearer.

*Toggle Previewer On or Off*


Note that there are many ways to toggle the Previewer:

* F12
* The Menu option above
* The menu from the Previewer
* The Globe button in the Right Window Controls Menu

**Comment by shawnwildermuth** [comment]
I like the idea of there being a toggle (like the one above it) for "External" or "Internal" previewer. Maybe "Toggle Previer" but I think changing the menu text would be fine: "Show Previewer Externally" and then when they click it, change to Internally or something.

**Comment by RickStrahl** [comment]
I think the reason I did that originally is to make it clear what the options are - without that it's a little sketchy. A toggle would be weird - it would have to be one or the other. ie. External Previewer - checked means external, unchecked internal. Otherwise there could be no check as it would always be the same with a different caption.

I think I'm going to leave it as is... personally I don't see it as being confusing, but then I'm biased 😄

**Comment by shawnwildermuth** [comment]
Your call, it was only confusing because it got stuck externally to me and when I tried to 'uncheck' the option it would just re-open and not go internally.

**Comment by RickStrahl** [comment]
Ah I see - that could be fixed. So when you click and it's already checked it'll flip modes. Unchecks the current choice and checks the other.

Yeah I like that - Maybe that's what you were suggesting all along and I just didn't see it :smile:

**Comment by shawnwildermuth** [comment]
I wasn't sure, but didn't want to confuse new users ; )

**Comment by RickStrahl** [comment]
There seem to be some other issues here that need addressing including an intermittent crash scenario when activating the external window. Grrr...

**Comment by shawnwildermuth** [comment]
D'oh

**Comment by RickStrahl** [comment]
So updated the command behavior so that when toggling from External to Internal the previewer becomes active. previously the previewer did not display, even though *Internal Preview* was checked. Fixed so that now toggling between modes allways displays the new mode.

Issue was that PreviewWindow close operation happened out of band and would unset the `IsPreviewVisible` flag which effectively closes the internal preview. Fixed by first closing the external window **before** toggling flags that determine the new window and previewer active state.

2.4.9.1+

**Comment by shawnwildermuth** [comment]
Sweet!

**Comment by RickStrahl** [comment]
Thanks for finding this. This is one of those features that few people - including myself - use, so it's often overlooked. The way this worked was a plain behavior bug (caused by the explicit closing of the external window the behavior of which was driven by physically closing and disabling the preview).

Looks like whatever crash behavior there was has also resolved as part of these sequence updates.
