### ISSUE TITLE
Crash when drag/dropping a Favourite item into a *.md document

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#944]
Hi Rick, 

When Left-clicking an item in the Favorites-Sidebar and dragging it into a document (expecting the relative link to this file dropped into the document) the MM-Editor is crashing: sometimes with a Timeout/NoResponsive Windows message and sometimes telling me that the WebViewer was not able to load and crashing when confirming this message...

Happens in all documents, and all different Favourits-Icons I have tried -> currently the Drag/Drop from Favourites does not work for me. Not essential to my work, but annoying. 

Thank you for having a look at this. 

Me on updates Windows 10 and MM-version 2.4.10

**Comment by RickStrahl** [comment]
Definitely a bug here...

What's happening is that there's a timing issue - there are multiple events competing with each other - basically the default click navigation plus the drag operation which results in a hanging situation until you move the focus out of the editor. Then the event fires and in some instances it will navigate, in others it may insert the link, usually in the wrong position because the mouse has moved at this point).

Checking to see how to fix this - the issue has to do with the Async Event handling and the events stepping on each other. So some sort of event dispatching is likely to fix this.

**Comment by RickStrahl** [comment]
Ok was able to track this down in the Move handler for the item. Requires extra dispatcher call to make it fire immediately instead of waiting for the UI to be available on the main UI thread.

Check in 2.4.10.1+.

**Comment by realB12** [comment]
It works! Thank you for this.
