### ISSUE TITLE
Snippet Execution of Editor Access Methods broken due to Async Requirements

### ISSUE THREAD

**Issue by anders-eriksson** [RickStrahl/MarkdownMonster#950]
I want to use the selected text in a snippet, but I can't figure out how to access the selected text.

I have a snippet the inserts this html code

`<div style="color:red;">~</div>`

I would like to have the current selected text inserted instead of the cursor marker ~

How?

MarkdownMonster: 2.4.13.2
Windows 10 Pro: 21H1

**Comment by RickStrahl** [comment]
The `~`  sets the caret to that position.

Actually getting the text selection is broken (this is bug) because of the changes in 2.0 that make all the document operations that affect the document async. The way to get this is with:

```
{{Model.ActiveEditor.GetSelection()}}
```

but due to the fact that these calls are now async and the method is not this no longer works like it used to.

Unfortunately this also doesn't work - worse actually it hangs MM:

```
{{Model.ActiveEditor.GetSelection().Result}}
```

This is a bug and one that has been overlooked in the 2.0 migration. What needs to happen to support this is the change the scripting engine so that all the script execution methods support async operation.

Unfortunately this is a not a quick fix, so this might take a bit to get fixed and updated. The fact that nobody has reported this since the release of 2.0 makes this very lightly used feature...

**Comment by RickStrahl** [comment]
This is now fixed and you should be able to use async methods in the snippet editor:

```cs
<div class="error-text">{{await Model.ActiveEditor.GetSelection()}}</div>
```

**Comment by Andis59** [comment]
I get this error dialog when I run the snippet.

`---------------------------
Snippet Execution failed
---------------------------
2 Errors:

Line: 24 - The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task<object>'.

Line: 25 - Unreachable code detected
---------------------------
OK   
---------------------------
`
