### ISSUE TITLE
[Feature Request] Sidebar not synced when opening MM by clicking an *.md file in Explorer

### ISSUE THREAD

**Issue by realB12** [RickStrahl/MarkdownMonster#954]
When I doupleclick an *.md file in Explorer it will open in MM. 
However the sidebar displays the sidebar with the directories from the last MM session which might be totally different from the path of the currently opened file. 

Can we sync the Sidebar with the such opened file as this file will always be the only file in the MM-tab anyway.

**Comment by RickStrahl** [comment]
You can use sidebar sync to fix the sidebar to the active document. Otherwise the sidebar stays wherever it was which is by design.

Here's what this looks like with the sidebar tracking on and off:

![TrackDocumentInFolderBrowser](https://user-images.githubusercontent.com/1374013/167226570-aa3c73ee-fdd2-46f3-ba7f-376b6aa51a1e.gif)

When on, the document loads and the sidebar matches.

**Comment by realB12** [comment]
Hi Rick, 
Sorry for not making my point clear here: 
I was not talking about the general syncing when MM already open - this, I am aware off and 100% fine with it. 
What I was referring to is the MM is opened from scratch when an *.md file is clicked in WINDOWS explorer/file-manager. 
Where the only file opened this way is the file to open and when open there is nothing that is referring to this file.

**Comment by realB12** [comment]
btw.  Shouldn't it be me - the issue creator - closing the issue?

**Comment by RickStrahl** [comment]
The file manager is sticky by design for a number of reasons. If you want to have it follow your document set the sticky option in the folder browser toolbar. At that point it will follow on open or any other document access including tab switches.

**Comment by realB12** [comment]
Rick: I believe you still have not got what I am asking. Ok for me. I give up here.
