### ISSUE TITLE
Bug: Preview in Table Editor of mm v2.5.12 is filled with garbage

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#963]
![image](https://user-images.githubusercontent.com/98041047/171573442-40f04535-1c3c-4372-80c2-028d5f0b5d53.png)

**Comment by RickStrahl** [comment]
I can't duplicate this reliably - this is a caching issue in the browser since we're rendering the same page every single time with different content. What's odd is that this is intermittent. Sometimes it doesn't refresh most of the time it works just fine. 

Not sure how to fix this - once you edit the table and the preview is updated again it syncs.

If you run into this again it might be useful to recount what might be different when it occurs.
