### ISSUE TITLE
General question about embedded html

### ISSUE THREAD

**Issue by aldosa** [RickStrahl/MarkdownMonster#964]
I'm having trouble locating this issue in the docs or the issues, so I'd appreciate if you referred me to the appropriate docs if a solution exists.

I'm working with KaTeX, which is a css/javascript framework for rendering TeX in the html output. It currently works quite well in stackedit.io. That project appears not maintained so I'm considering Markdown Monster.

Here's something the stackedit will not do: render script fonts such as [Snell Roundhand](https://www.myfonts.com/collections/snell-roundhand-script-font-linotype). I'd like to be able to include the font somehow:

```css
<style>
      span { font-family: Snell Roundhand Script; }
</style>
```
and then in the MarkDown/KaTex something like this:

Currently:

```markdown
- ***Subset***: $A\sub B$. All elements of *A* are also elements of *B*.
```
To this:
```markdown
- ***Subset***: $<span>A</span>\sub <span>B</span>$. All elements of *<span>A</span>* are also elements of *<span>B</span>*.
```

Is there any way to accomplish the above?

Thanks,

Aldo

**Comment by RickStrahl** [comment]
I think you're asking about HTML rendering support in the editor?

You can embed HTML into Markdown and the default rendering in the editor will process it.

However, whether HTML is processed depends on the processor so when you publish this somewhere (say on GitHub) the behavior may be different. If I recall GitHub only supports some HTML tags, not everything in its rendering.

For example take this Markdown and paste it into your comment and preview:


```markdown
# Markdown HTML 

<style>
  small { color: red; font: bold }
</style>

<small>small</small> Normal <sub>sub</sub>
```

which results in:

---

# Markdown HTML 

<style>
  small { color: red; font: bold }
</style>

<small>small</small> Normal <sub>sub</sub>

---

As you can see it renders the tags but not the style.

MM's editor will render this correctly - but that's just because the editor's default handling allows for embedded HTML. 

Ultimately this is something you have to decide based on whether your final destination of your Markdown supports the HTML features...

**Comment by aldosa** [comment]
Thank you for that. I'll give the KaTeX $ and $$-delimited expressions a try and see if they'll pass through and get picked up by the JavaScript on the HTML page with MM.
