### ISSUE TITLE
MM loses registration info and several settings & no restore settings from backup option found

### ISSUE THREAD

**Issue by royog** [RickStrahl/MarkdownMonster#978]
On several occasions, when I start MM, it has lost its registration info, and several config settings are lost including last files edited. I see there's a backup MM settings options, but cannot find a restore MM settings.

Annoying that for paid registration, when this happens, I have to scroll through all the settings and reset them. One being "Git Client Executable" resets to default setting which is a pain to reset.

And it's a pain to re-register.

I have a 2nd copy on my laptop, and this issue occurs there as well on occasion. Can't predict when this happens.

This is a real PIA!

**Comment by RickStrahl** [comment]
Hi Roy - sorry to hear you have problems with configuration and registration.

These are two separate issues I think:

* Registration loss
* Configuration corrupted

The former can have a number of causes - which is can be running without an internet connection for  a long period of time (or not starting MM when no connection) which causes the registration to get removed. I hated implementing this but it was necessary due to the large number of fraudulent registrations being applied. There's more info here:

[Markdown Monster Registration / Registration Checks](https://markdownmonster.west-wind.com/docs/_5pl0rucqm.htm#registration-checks)

For the latter it sounds like your configuration file is getting corrupted or perhaps deleted. Is there anything you're doing special with your configuration? Shared file in DropBox/OneDrive etc. and one version overriding settings from another perhaps? Are you running a full install or a self-contained install? Manual changes in the configuration JSON file can also result in invalid keys which invalidates the entire file.

Could you check the error file for any crashes or other information that pertains perhaps to configuration settings? Help -> Error Log.

**Comment by royog** [comment]
Hi Rick. Thanks for you prompt response!

I have set a common settings folder on OneDrive; both my Desktop and my Surface reference that same location for settings. Perhaps this is causing issues? My intent is for settings I change in one instance (like theme, font-size, GIT Client, etc.) to reflect in the other instance on the other machine when changes are made in one.

Both are full installs of MM.

Below is pasted full contents of the log file.

Roy


9/16/2022 9:30:40 AM - Addin CodeProject Markdown Parser version failed
The remote server returned an error: (404) Not Found.
Markdown Monster v2.6.9.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-US - NET 4.8 - 64 bit
en-US - en-US
---
System
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Westwind.Utilities.HttpUtils.JsonRequest[TResultType](HttpRequestSettings settings) in C:\projects\Westwind.Utilities\Westwind.Utilities\Utilities\HttpUtils.cs:line 157
   at MarkdownMonster.AddIns.AddinManager.<>c__DisplayClass34_0.<GetAddinListAsync>b__0(AddinItem ai) in C:\projects\MarkdownMonsterCode\MarkdownMonster\_Classes\AddInInterfaces\AddinManager.cs:line 598
System.Net.WebException
---------------------------



9/16/2022 11:07:07 AM - Editor WebView Control Process Failed: RenderProcessUnresponsive Unresponsive



9/19/2022 7:26:04 AM - Unregistering license: Validating invalid product SKU.



9/19/2022 7:26:04 AM - License unregistered: 0FDAE-EF511-5F9B1-1CB0D



9/19/2022 10:05:27 AM - License unregistered:



9/19/2022 10:05:27 AM - License unregistered:



9/20/2022 10:11:21 AM - Unregistering license: Validating invalid product SKU.



9/20/2022 10:11:21 AM - License unregistered: 0FDAE-EF511-5F9B1-1CB0D



9/20/2022 11:25:20 AM - License unregistered:



9/20/2022 11:25:20 AM - License unregistered:



9/22/2022 8:31:24 PM - Unregistering license: Validating invalid product SKU.



9/22/2022 8:31:24 PM - License unregistered: 0FDAE-EF511-5F9B1-1CB0D



9/23/2022 6:30:14 AM - Unregistering license: Validating invalid product SKU.



9/23/2022 6:30:14 AM - License unregistered: 0FDAE-EF511-5F9B1-1CB0D



9/23/2022 6:31:02 AM - License unregistered:



9/23/2022 6:31:49 AM - License unregistered:



9/23/2022 6:31:49 AM - License unregistered:






________________________________

**Comment by royog** [comment]
Oh, and forgot to mention that I have not opened nor edited the JSON config file ever.

Roy
________________________________

**Comment by RickStrahl** [comment]
Hi Roy,

I've re-issued your license number since you just posted here in public :smile: 

While at it I also checked your license record and made sure everything is in order with it and it appears so. It doesn't show any activated machines.

If you are running the 'self-contained' install **make sure you run in a folder that has write access**. Otherwise the license file cannot be written out. This may also cause conifguration to not be saved since the self-contained installation tries to store configuration data in a local folder. 

If you have problems I suggest perhaps running the full install to ensure that everything works as expected. The self-contained install requires some extra management.

**Comment by royog** [comment]
Oh shoot, I replied to the email from GitHub, not realizing it got posted publicly (otherwise I would have obfuscated the license key in my reply).

Hi Public!  🙂 How are all of you today?

I'm not running the 'self-contained' version, it's installed on Windows 10 on both computers. And, when I checked yesterday under "Manage Licenses > Show Activations" , it did confirm that my license was activated on my two computers. So, strange that you were seeing no activations!

Thanks for regenerating my key. I'll be careful not to publish it ever again. Oops!

Roy
________________________________

**Comment by RickStrahl** [comment]
Double checked now and I see the 2 machine registrations now... 

You should see the registration file (registered.txt) in your **install folder** - each machine has a unique registration key and that key is checked occasionally against the online registration (once a week roughly - if it fails repeatedly to validate the license is unregistered on the local machine).

I do see an error in your traces there whcih is this:

```
9/20/2022 10:11:21 AM - Unregistering license: Validating invalid product SKU.
````

That seems to suggest either that you were offline or that the license server didn't respond with a valid response. While that can happen, it's unlikely to happen repeatedly so that the multiple registration validation requests fail.

**Comment by RickStrahl** [comment]
As to the configuration issue it sounds to me that perhaps changing the path (or some other setting) might have corrupted the configuration file. This nearly impossible from the configuration editor itself, but definitely possible if manually editing and missing

MM creates a backup and you can explicitly create a copy once you have everything setup. It basically makes a copy of your configuration folder which by default lives at `%appdata%\Markdown Monster` or whereever you redirected it to (like OneDrive). The backup can be used to replace (manually) the old files from the folder or you can individually pick files out of it - specifically `MarkdownMonster.json`.

**Comment by royog** [comment]
One problem (and perhaps my root cause of this experienced issue) is that the MM app's "common folder" I designated as a OneDrive folder has a very different path depending on which machine (of the two) I'm using the app on. So one instance of MM will then lose track of the common folder as not found ... since the path data of that common folder is itself stored in the common folder. But it's not a constant value in my environment ... the path is different depending on the machine MM is opened on.

Perhaps the common folder info should be stored in users AppData, and not the common folder itself (or it needs a unique key based on the machine name).

(On one machine my OneDrive is on physical drive D, where the other has it on drive C. And the windows ID (which is part of the OneDrive path) is also different between the two machines ... which is fine as far as OneDrive is concerned).

Roy
________________________________

**Comment by RickStrahl** [comment]
That's the way it's supposed to work, but I've actually just reviewed the code and it looks that there's been a problem with the `InternalCommonFolder` and the `assigned `CommonFolder` - which ended up pointing at the same redirected location. The `InternalCommonFolder` is supposed to point at `%appdata%\Markdown Monster` and hold the machine specific information. 

That's been fixed and a couple of things have been updated to reflect this - the `CommonFolderLocation.txt` which holds the path that is redirected to (ie. your OneDrive folder).

This is what this looks like for me (I use DropBox):

![image](https://user-images.githubusercontent.com/1374013/192126805-44b104d7-5b6b-48d9-8cf3-401e5ad5c3dc.png)

The fix for this is in 2.6.9.6 ([pre-release](https://markdownmonster.west-wind.com/download))

**Comment by royog** [comment]
Thanks for looking into this. The other setting that winds up being different depending on the end user's machine used is for the "Open Folder in Git Client". Perhaps MM already takes care of this, but if not, it's another one to consider for the InternalCommonFolder.

Roy
________________________________

**Comment by RickStrahl** [comment]
If you share settings the assumption is that it'll be set up the same on each machine. If that's not the case - don't share your settings and copy between them and adjust what you need to for each machine.

You can't have it both ways :smile:

The pathing was definitely a bug - the base folder has to be discoverable on a local machine and that should now be working again in the update.

**Comment by RickStrahl** [comment]
Going to close this since configuration issue has been solved. If the registration issue persists, please open a new issue with just that specific topic.

Thanks for your help!
