### ISSUE TITLE
Bold text is not rendered correctly in special case

### ISSUE THREAD

**Issue by jbridgy** [RickStrahl/MarkdownMonster#989]
Bold text ending with a slash followed by a non-blank is not rendered correctly in the preview window of MM v2.7.6.

Example:

```markdown
OK: **bold text** followed by blank

OK: **bold text**followed by non-blank

OK: **bold text ending with slash/** followed by blank

BAD: **bold text ending with slash/**followed by non-blank
```

Preview of MM v2.7.6:

![image](https://user-images.githubusercontent.com/98041047/206169239-8c1b3983-0052-46e1-bf99-1b2a97499d34.png)

The preview of GitHub, GitLab and Azure DevOps behaves equally. Why?

Is there a workaround?

**Comment by RickStrahl** [comment]
Hmmm... I'm not quite sure what the parsers are doing to not parse this. It looks like a lot of Markdown Parsers - including MarkDig which is what Markdown Monster uses - fail to render this correctly:

[Expression on Babelmark](https://babelmark.github.io/?text=BAD%3A+**bold+text+ending+with+slash%2F**followed+by+non-blank)

My first thought was that you can escape the character with `\/` but that also fails. In fact it looks like **any punctuation/bracket characters** have the same behavior:

This also fails:
```
BAD: **bold text ending with slash=**followed by non-blank
```

BAD: **bold text ending with slash=**followed by non-blank


The only way I can see working around this is via:

```
OK: <b>bold text ending with slash/</b>followed by non-blank
```

OK: <b>bold text ending with slash/</b>followed by non-blank

which works in the MM preview but GitHub doesn't like it because it doesn't allow raw HTML.

Spaces will fix this, but

**Comment by RickStrahl** [comment]
I put in an issue on the Markdig repo for a potential fix of this however, not sure if this should actually be fixed because GitHub too has the same failing behavior. Probably better markdig matches that than work locally but not when published to the repo.

[Markdig Issue #683](https://github.com/xoofx/markdig/issues/683)

**Comment by RickStrahl** [comment]
So it looks like the reason that this doesn't work is due to a spec issue in the Common Mark spec (more info in the MarkDig issue)

https://spec.commonmark.org/0.30/#right-flanking-delimiter-run

Unfortunately I don't see a workaround for this using Markdown text - only using the HTML escape route.

**Comment by jbridgy** [comment]
I think a Markdown specification should allow to render any sequence of printable characters as bold text.

The current CommonMark Spec fails in this respect according to [MihaZupan](https://github.com/xoofx/markdig/issues/683#issuecomment-1341804631) and [commonmark.js demo](https://spec.commonmark.org/dingus/?text=OK%3A%20**bold%20text**%20followed%20by%20blank%0A%0AOK%3A%20**bold%20text**followed%20by%20non-blank%0A%0AOK%3A%20**bold%20text%20ending%20with%20slash%2F**%20followed%20by%20blank%0A%0ABAD%3A%20**bold%20text%20ending%20with%20slash%2F**followed%20by%20non-blank).

Maybe Markdig, GitHub, ... will follow soon when this issue is fixed in the CommonMark Spec. However after skimming chapter '6.2 Emphasis and strong emphasis' of [CommonMark Spec v0.30](https://spec.commonmark.org/0.30/) including the 'right-flanking delimiter run' (as if introducing a fancy term would help) I fear that this specification is hopeless. Oddly enough pandoc does it right.

Anyway I thank you for looking into it. At least the HTML escape route helps sometimes.

**Comment by RickStrahl** [comment]
Yeah I agree - this is clearly a bug since there's no work around, but it's deep in the spec and - really - an edge case scenario. A change in this feature would likely have other side effects that might be more severe for more common scenarios.

Like you seeing the spec (thanks to @MihaZupan's response)   I don't see this getting fixed  in the spec or any of the tools. Even if it did I suspect it would take a long while before it shows up in production on Github (they are slow to change too).
