### ISSUE TITLE
Table Editor: Intermittent Crashes

### ISSUE THREAD

**Issue by bigonroad** [RickStrahl/MarkdownMonster#993]
Hi! 

I love this project but I'm not much of a coder so it's hard to contribute much. However, MM's table tools are the reason I use it over others so I'd love to see these improve a little more, so I did my best to solidly document some issues.

### Bug - Random Crashes
Using tables in MM commonly causes crashes like the one pictured below. Difficult to consistently reproduce, but if you make a new table and add and delete a load of rows and copy and paste you'll usually get it within 5 minutes. Have seen this also with MM open in the background with the Table editor open, but user focus and activity in a totally different app or piece of software. 

![image](https://user-images.githubusercontent.com/821716/209149328-1d143393-66c4-49c0-a834-5507a3f05e5f.png)

* Clicking "No" closes the program (without an autosave). _My expected behaviour was that this would close the Table window, not the whole program_. 

* Clicking "Yes" continues with apparently zero issues.

Error log reveals the following:

```
22/12/2022 13:58:52 - TaskExecution: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Markdown Monster v2.7.6.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-GB - NET 4.8 - 64 bit
en-GB - en-GB    
---
mscorlib
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MarkdownMonster.Windows.TableEditor.MoveRowDown() in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\TableEditor\TableEditor.xaml.cs:line 338
   at MarkdownMonster.Windows.TableEditorJavaScriptInterop.<KeyboardCommand>d__12.MoveNext() in C:\projects\MarkdownMonsterCode\MarkdownMonster\Windows\TableEditor\TableEditorJavaScriptInterop.cs:line 116
System.ArgumentOutOfRangeException
--------------------------- 
```

**Comment by RickStrahl** [comment]
Please break out the second issue into a separate issue and remove from here. Thanks.

**Comment by bigonroad** [comment]
> second issue into a separate issue
Sorry, do you mean move _bug 2 keyboard shortcuts_ into a separate issue or move _feature request better copy and paste_

**Comment by jbridgy** [comment]
I think you should do the following:
1. Keep "Bug 1 - Random Crashes"
2. Delete "Bug 2 - Keyboard Shortcuts for row creation" because #992 is already a very similar issue.
3. Move "Feature request - Better copy and paste from other spreadsheet apps" to a new issue.

**Comment by RickStrahl** [comment]
Hard to repro this since there's not enough information. 

What would be useful:
Information on when the errors occur
* Is it boundary scenarios
*  End or top of the list 

I see the crashes in my logs, but they are difficult to pin down without context. I know where they happen but these only fail in very specific situations that are currently not anticipated. The one above appears to be from `MoveRowDown()` and it's a range bound error, so likely end of list or blank line.

Some of these issues might also be improved now that empty 'blank' rows care handled less strictly  (#992) and behave more like all other rows . I believe the reason for some of these failures have to do with blank rows at the end that get removed throwing off the index. With the changes made in #992 this might alleviate some of those type of errors.

**Comment by RickStrahl** [comment]
I've also added some additional range changes in `MoveRowDown()` and `MoveRowUp()`  that also should prevent out of range index crashes. All the above updates are in `2.7.10.6` and later versions.
