### ISSUE TITLE
Feature Request - Better copy and paste from other spreadsheet apps.

### ISSUE THREAD

**Issue by bigonroad** [RickStrahl/MarkdownMonster#994]
### Feature request - Better copy and paste from other spreadsheet apps.
Excel and Google drive copy data with whitespace details, see example below:

Data in Google Sheets copied
![209151837-1c1a5a98-340f-4a5a-94c3-9daa73dca0c7](https://user-images.githubusercontent.com/821716/210273981-52c8fae2-e343-4dac-9a99-0f2610952005.png)

Copies to clipboard as raw input of:
![209154021-b4ce07f7-08d5-4130-a177-d5283da74f6b](https://user-images.githubusercontent.com/821716/210273992-df9f0c71-7d32-4068-815f-dc27893604cb.png)

Data pasted into Excel
![209152613-d811c457-0912-45ef-b9ff-6d4c2b674c3e](https://user-images.githubusercontent.com/821716/210274000-68511093-e1a9-4003-a3b0-0e0310f5dd5c.png)

Data pasted into MM
![209152818-41466b4c-2947-4b47-843e-296929550552](https://user-images.githubusercontent.com/821716/210274013-08ad0d10-70da-447b-867e-d9bd847ac401.png)

There is a "Paste" function on the top toolbar which sort of works for entire tables, but not for sections or single columns. Expected behaviour would be for Ctrl-V to paste below and to the right of selected cell, creating new rows/columns as required. It might seem minor, but when copying a complex table with 4 columns and 20 rows, it could take 20 minutes to cut and paste them correctly from the tabbed version

Thanks,
Chris

**Comment by RickStrahl** [comment]
I think you want **Load From**:

![CsvImportFromExcel](https://user-images.githubusercontent.com/1374013/211180583-64feec70-26fa-4faf-9fa9-b16f1716fb58.gif)

**Comment by RickStrahl** [comment]
The problem with generic Paste is that CSV is not obvious to detect since you can have any character as the separator. Even then it's not super obvious to detect CSV.

I created a routine for clipboard detection by looking for tabs or commas in every line of the incoming clipboard data, and if that's the case then converting based on that. Load From will still be more reliable as you can specify the separator. For now it looks like Paste will work:

![CsvPasteTableEditor](https://user-images.githubusercontent.com/1374013/211183499-ab9f4341-8cf0-470d-83eb-66cd0ca9f90e.gif)
